### ISSUE TITLE
proj4 projection EPSG:3395

### ISSUE THREAD

**Issue by echocompany** [ghettovoice/vuelayers#100]
Migrate code from native to vuelayers and have some question, this native code will work:

````
proj4.defs('EPSG:3395', '+proj=merc +lon_0=0 +k=1 +x_0=0 +y_0=0 +datum=WGS84 +units=m +no_defs');
var base_layer = new ol.layer.Tile({
            source: new ol.source.XYZ({
...
                projection: 'EPSG:3395',
            }),
            visible: false,
            is_base_layer: true
        });
````

but vue code:

in home.vue
````
<vl-layer-tile id="tile">
    <vl-source-xyz ... projection="EPSG:3395"></vl-source-xyz>
</vl-layer-tile>
````

in main.js
```
import VueLayers from 'vuelayers'
import 'vuelayers/lib/style.css' // needs css-loader

Vue.use(VueLayers);

import proj4 from 'proj4';
proj4.defs('EPSG:3395', '+proj=merc +lon_0=0 +k=1 +x_0=0 +y_0=0 +datum=WGS84 +units=m +no_defs');
```

tried to access openlayers api to register proj4 (https://openlayers.org/en/latest/examples/wms-image-custom-proj.html), but it not exist in ol-ext and this code https://jsfiddle.net/ghettovoice/b3t5s4ku/44/ will error: Uncaught ReferenceError: ol is not defined 

What could be the error?

**Comment by ghettovoice** [comment]
What version of the OpenLayers and VueLayers?   

Current VueLayers version v0.10.x uses OpenLayers v4.6.5. The code from jsfiddle uses umd builds of VueLayers and OpenLayers that provides global variables: `VueLayers` and `ol`.  I don't see any errors in browser console

With modules code should look like (using native openlayers api):

```js
import proj4 from 'proj4'
import olProj from 'ol/proj'

proj4.defs('EPSG:3395', '+proj=merc +lon_0=0 +k=1 +x_0=0 +y_0=0 +datum=WGS84 +units=m +no_defs');

let projection = new olProj.Projection({
  code: 'EPSG:3395',
})
olProj.addProjection(projection)

// now you can use projection code in component properties.
```

In the vuelayers demo you can see definition of the custom projection using `ol-ext` wrappers https://github.com/ghettovoice/vuelayers-demo/blob/vl-0.10.x/src/App.vue#L243.

**Comment by echocompany** [comment]
i use vuelayers@next

Thanks for the tip, the problem was solved by a separate installation of ol
