### ISSUE TITLE
Render a text inside `vl-geom-multi-point` > `vl-style-box`

### ISSUE THREAD

**Issue by bobrosset** [ghettovoice/vuelayers#101]
Hey mate, I was able to add a fix text using `<vl-style-text text="test!"></vl-style-text>`, but I was wondering if there's any chance to render numbers based on an index maybe, I just want to show a progression on the points. Thanks in advance.

**Comment by ghettovoice** [comment]
Hi @bobrosset!
If you render features with vl-feature component then you can use scoped slot. Here is an example:
```html
<vl-feature v-for="feature in features" :properties="feature.properties">
  <template slot-scope="feature">
    <vl-style-text :text="feature.properties.aProp"></vl-style-text>
  </template>
</vl-feature>
```

For more advanced styling, for example when render layers that loads features from remote backend, the best way is to apply styles on the layer level with vl-style-func. This component allows to define function that will be triggered for each feature. [Usage example](https://github.com/ghettovoice/vuelayers/issues/57#issuecomment-395537399)

**Comment by bobrosset** [comment]
Sorry, I was talking not about features per se, but `<vl-geom-multi-point>`. I would like to use a text above the circles.

```<vl-feature>
            <vl-geom-multi-point :coordinates="trace.coordinates" />
            <vl-style-box>
              <vl-style-text text="this is the text I want to replace with an autoincrement number"></vl-style-text>
              <vl-style-circle :radius="10">
                <vl-style-stroke :width="2"></vl-style-stroke>
                <vl-style-fill :color="[0, 0, 0, 0.5]"></vl-style-fill>
              </vl-style-circle>
            </vl-style-box>
          </vl-feature>

          <vl-feature>
            <vl-geom-line-string :coordinates="trace.coordinates" />
            <vl-style-box>
              <vl-style-stroke :width="2"></vl-style-stroke>
            </vl-style-box>
          </vl-feature>```

Thanks in advance!

**Comment by ghettovoice** [comment]
Styles can be applied only to feature or layer. In other words vl-style-box will influence the full muti point feature as one.  
May be you should split muti point feature to multiple point features

**Comment by ghettovoice** [comment]
With vl-style-func you can return array of styles that is dynamically generated. ol.Style constructor accepts geometry function that you can use to change styling geometry http://openlayers.org/en/latest/examples/polygon-styles.html?q=geometry+style

If I understand you right, you need create separate ol.Style instance for each point in multipoint geometry
