### ISSUE TITLE
MoveEnd event on vl-view

### ISSUE THREAD

**Issue by SamuelRiversMoore** [ghettovoice/vuelayers#103]
Hi, is it possible to add a `moveend` event on the `vl-view` component (like in [this example](https://openlayers.org/en/latest/examples/moveend.html)) ?

It would be very useful for linking the map state with a state manager without doing too many useless updates...

Thanks!

**Comment by ghettovoice** [comment]
Hi @SamuelRiversMoore ,
it already added, but to the `vl-map` component. And in example you mention `moveend` event also used on the map instance.

```html
<vl-map @movestart="..." @moveend="..."></vl-map>
```
