### ISSUE TITLE
VectorSource CORS problem on moving to v0.11.0-rc.4

### ISSUE THREAD

**Issue by PeterC66** [ghettovoice/vuelayers#105]
I have moved from v0.11.0-rc.3 to v0.11.0-rc.4. and get the following error when I try to load a VectorSource:
`Access to XMLHttpRequest at 'http://localhost:5000/featurelayers/HcN_Pubs' from origin 'http://localhost:8080' has been blocked by CORS policy: The value of the 'Access-Control-Allow-Origin' header in the response must not be the wildcard '*' when the request's credentials mode is 'include'. The credentials mode of requests initiated by the XMLHttpRequest is controlled by the withCredentials attribute.`

This did not happen in v0.11.0-rc.3 so do I need to do anything different now? Maybe it is related to the listed change `default loader for vl-source-vector `?

I am using a Node/Express backend to return data of various types. My calls to get data outside of vuelayers still work OK.

I do not understand much about Cors but looking in devtools I see that the only difference between those calls that work and those that do not seems to be that

- for the calls that work OK : `Request Header = Accept: application/json, text/plain, */*`
- and for those that get the error (eg HcN_Pubs above): `Request Header = Accept: */*`

For both types of call the `Response Header  = Access-Control-Allow-Origin: *`

**Comment by ghettovoice** [comment]
You are right, this is related to the new default loader.
I'll try fix fix this quickly

**Comment by ghettovoice** [comment]
Now should work as before

**Comment by PeterC66** [comment]
Seems OK now in v0.11.0-rc.5
