### ISSUE TITLE
draw

### ISSUE THREAD

**Issue by LoveCai970511** [ghettovoice/vuelayers#106]
how to start draw

**Comment by ghettovoice** [comment]
Hi @LoveCai970511 ,
have you look at the demo source code https://github.com/ghettovoice/vuelayers-demo/blob/master/src/App.vue#L150?  There is a good example how to use `vl-interaction-draw`, `vl-interaction-modify` component.

In short: you should add some vector layer as container for drawn features, and bind draw interaction to it

```html
...
<vl-layer-vector id="draw-pane">
        <vl-source-vector ident="draw-target" :features.sync="drawnFeatures"></vl-source-vector>
 </vl-layer-vector>

<vl-interaction-draw source="draw-target" type="Polygon"></vl-interaction-draw>
...
```

**Comment by LoveCai970511** [comment]
Thanks your reply a lot,but I still have a question that Isn't it integrated with the draw function vl-interaction-draw? Isn't it based on openlayer5.0?

**Comment by ghettovoice** [comment]
Currently there are two versions of VueLayers:
- vuelayers@latest - v0.10.x - it based on openlayers v4.x
- vuelayers@next - v0.11.x - it based on the openlayers v5.x 

In the near future v0.10.x will be fully replaced with v0.11.x that is based on ol v5

**Comment by ghettovoice** [comment]
`vl-interaction-draw` actually integrates openlayers ol.interaction.Draw component

**Comment by LoveCai970511** [comment]
So it just needs to pass in a parameter and style to draw the element type，That's what I thought before, but I tried several times and didn't figure it out，
