### ISSUE TITLE
ol.MapEvent 

### ISSUE THREAD

**Issue by julsbreakdown** [ghettovoice/vuelayers#107]
I am trying to use the events from http://openlayers.org/en/latest/apidoc/module-ol_MapEvent-MapEvent.html
But while the ol.MapBrowserEvent are working I have no luck with ol.MapEvent
`<vl-map @pointermove="onPointerMove" @render="loadGeometry" ref="map">`
=> onPointerMove works juste fine
=> not postrender
Anything obvious i am missing?

**Comment by ghettovoice** [comment]
Hi @julsbreakdown ,
there is no event with the name `render`, neither the OpenLayers nor the VueLayers.
All map related events n VueLayers basically are same as in the OpenLayers.

Try this
```
<vl-map @pointermove="onPointerMove" @postrender="loadGeometry" ref="map">
...
</vl-map>
```

**Comment by julsbreakdown** [comment]
@ghettovoice
Thanks should have checked before posting.

**Comment by ghettovoice** [comment]
Ok, it happens
