### ISSUE TITLE
Is there a way I can utilise the select-interaction to respond to hover?

### ISSUE THREAD

**Issue by PeterC66** [ghettovoice/vuelayers#108]
Based on the vuelayers demo I have the select-interaction working.  Now in response to a single click on a feature its properties are shown in an overlay popup.

I would like this exact same functionality to respond to mouse **hover** rather than to a click. (I implemented this using forEachFeatureAtPixel in my first plain js version of my system.)

Using the onMapPointerMove logic you show in #74 I have got the pointer to change on hover. But I do not see how I can easily link that into the select-interaction.

Before I embark on a special implementation I wondered if there were an easier way of using the vuelayers implementation of the interaction? For example can I link in to the events in the subscribeToInteractionChanges, so features are selected and unselected on hover?  Any suggestions welcome.

**Comment by ghettovoice** [comment]
Hi @PeterC66 ,
like with plain OpenLayers you can use event `condition` on the select interaction. Take a look here https://jsfiddle.net/sy13j2gc/8/

**Comment by PeterC66** [comment]
Thanks, it works in principle (I need to just change the display as otherwise it moves the map and the hover is lost).

I had not noticed that `condition` before in OpenLayers, but then OL keeps getting better!

Again thanks for a helpful, quick response.
