### ISSUE TITLE
Displaying selected feature details in a fixed panel

### ISSUE THREAD

**Issue by PeterC66** [ghettovoice/vuelayers#110]
Following on from the vuelayers demo and my #108, I have implemented the select interaction on hover (with multi=true, and using v0.11.1). Thus each feature gets its details shown in an overlay beside the feature OK.

However what I want is for the details of **all** the selected features to be shown in **a single panel** to the side, like I implemented in my existing js system.  I have now tried doing it in Vue.js within the vl-interaction-select (with a `v-for` and a simple div).

This works OK, but only if I remove the `display:none` from the vl-interaction-select container. I am struggling to work out how to get my panel to display without removing the `display:none`, presumably by creating the panel outside the container.

vl-overlay (using ol/Overlay) does create a div outside the container, but it requires a `position` in the view or data projection, and I want it positioned relative to the window not the map.

I note that for ol/Overlay the `position` is not required, and there is the possibility of specifying the HTML `element` itself, so maybe it can be positioned relative to the window not the map?

I have tried the Bulma panel element, but this is no better as it is still within the container with `display:none`.

In my researches I have come across portal-vue (for rendering DOM outside of a component, anywhere in the document) but this seems a bit over the top, and I have not tried it.

I am probably missing something simple, in which case my apologies, but what do you suggest?
Thanks again.

**Comment by ghettovoice** [comment]
Hello @PeterC66,
`vl-interaction-select` also has synchronizable `features` property that always contains all selected features as plain objects. So I think the easiest solution would be just render side panel somewhere outside of `vl-interaction-select` (actually I didn't suppose such use case) and iterate over `selectedFeatures` array to render information about each features.

This an example of what I propose https://jsfiddle.net/ghettovoice/g8L96efo/

**Comment by PeterC66** [comment]
Thanks. That works fine.
