### ISSUE TITLE
Can I get vl-interaction-select to use its updated condition property

### ISSUE THREAD

**Issue by PeterC66** [ghettovoice/vuelayers#111]
I am still working with vl-interaction-select, and have an issue.  Thanks for your help so far. I am not sure if this is about the vl-interaction-select component itself, or a Vue reactivity issue, or just my lack of understanding. 

I want to use data (actionOnClick) in a Vuex store to determine whether vl-interaction-select responds to a singleClick [actionOnClick==='select'], or pointerMove (ie hover)  [actionOnClick!=='select'].

I have:-
``` html
<vl-interaction-select
  v-if="drawType == null"
  :features.sync="selectedFeatures"
  :multi="true"
  :condition="wantHover ? pointerMove : singleClick"
>
```
Now in a simple test (ignoring actionOnClick) I have
```js
import { singleClick, pointerMove } from 'ol/events/condition';

computed: {
  singleClick() {
    return singleClick;
  },
  pointerMove() {
    return pointerMove;
  },
  wantHover() {
    return true;
  },
```
This works as I expect - the selection is by hover.

If I change it to
```js
  wantHover() {
    return false;
  },
```
again it works as I expect - the selection is by single click.

Now if I introduce 
```js
import { mapState } from 'vuex';

  computed: {
    ...mapState({
      actionOnClick: state => state.mapping.actionOnClick,
    }),
    wantHover() {
      return this.actionOnClick !== 'select';
    },
```
again it works as I expect - because the initial value of actionOnClick is NOT 'select', the selection is by hover.

However this is where it seems odd. I have a dropdown to change the value of actionOnClick to 'select' in Vuex. This all works, and in Vue devtools I see that the condition property of vl-interaction-select has changed from pointerMove to singleClick - again as I would expect. **However** the selection remains as by **hover** not by single click. It seems as though vl-interaction-select is still using its original property value.

Can I get vl-interaction-select to use its updated property? Or have I misunderstood something?

**Comment by ghettovoice** [comment]
Hello @PeterC66 , 
this is related to vl-interaction-select and public interface of the ol.interaction.Select .
ol.interaction.Select doesn't allow change of the condition at the runtime.  
The only way to change it is recreate interaction, I can implement this in the vl-interaction-select like it was done in the vl-style-* components.

I'll try to fix this soon

**Comment by PeterC66** [comment]
Thanks.  It is a relief to know I wasn't doing something wrong. No hurry for the fix, as I have plenty of other things to implement.

**Comment by ghettovoice** [comment]
I not immediately guessed how implement hidden recreation for openlayers components that doesn't provide setters for its properties. So now watching for all properties doesn't implemented everywhere in VueLayers components.

But now with the latest versions it can be added relatively easy.
I'll ping you here
