### ISSUE TITLE
Each position of geometry may include more than two elements

### ISSUE THREAD

**Issue by become-iron** [ghettovoice/vuelayers#112]
According to [The GeoJSON Format description (Paragraph 3.1.1. Position)](https://tools.ietf.org/html/rfc7946#section-3.1.1) each position of geometry may include more than two elements. So checks for only two coordinates in components could be wrong.
For example, in [point-geom](https://github.com/ghettovoice/vuelayers/blob/master/src/component/point-geom/geom.vue) `validator: value => value.length === 2` probably should be `validator: value => value.length >= 2`

**Comment by ghettovoice** [comment]
Thank! I'll merge it later

**Comment by ghettovoice** [comment]
Fixed by #114
