### ISSUE TITLE
vectorLayer.getSource() returns null after a vl-layer-vector component is mounted

### ISSUE THREAD

**Issue by PeterC66** [ghettovoice/vuelayers#116]
I am continuing to re-factor my existing js OpenLayers system using Vue.js and vuelayers. I am generating vl-layer-/ vl-source- elements from a "LayerDefinitions" array, using render functions - and this works well for both raster and vector layers.

For various reasons, once a vector layer has loaded **I wish to run a function (processFeatures) through all its features**.

In my old system I used

- let src = vectorLayer.getSource()
- then src.forEachFeature{}
- _If source.getFeatures() found no features (because of its async operation) I waited for a change in vectorLayer.getSource()_

To do something similar in the vuelayers context I have:
```
const onMounted = (thisLayer) => {
  thisLayer.$mountPromise.then(() => { // using your answer to #73
    processFeatures(thisLayer.$layer),
  );
});

createElement(
  'vl-layer-vector',
  { on: { mounted: onMounted } },
  [ vlSourceElementVector, vlLayerStyle ], // defined elsewhere
)
```
 
The processFeatures routine receives a parameter I call vectorLayer. The problem is that, although the layer displays OK, **vectorLayer.getSource() returns null**.

I am way beyond what I am familiar with. What am I doing wrong?
Thanks.

---------------
In case it is useful:
(looking at the parameter of processFeatures) console.log(vectorLayer) shows:
```
VectorLayer {
  declutter_: false
  dispatching_: {}
  disposed_: false
  listeners_: {...}
  mapPrecomposeKey_: null
  mapRenderKey_: null
  ol_lm: {...}
  ol_uid: "2728"
  pendingRemovals_: {}
  renderBuffer_: 100
  renderMode_: "vector"
  revision_: 220
  sourceChangeKey_: {...}
  state_: {...}
  styleFunction_: ƒ __styleTargetStyleFunc(feature, resolution)
  style_: ƒ __styleTargetStyleFunc(feature, resolution)
  type: "VECTOR"
  updateWhileAnimating_: false
  updateWhileInteracting_: false
  values_: {
    declutter: false
    extent: undefined
    id: "Census entries-2"
    maxResolution: Infinity
    minResolution: 0
    opacity: 1
    renderMode: "vector"
    renderOrder: undefined
    source: VectorSource {...}
    visible: true
    zIndex: 2
  }
  vm: [VueComponent]
  __proto__: Layer
}
```
Note that the values_ property has a source property that looks to me like the correct VectorSource. It also has a vm property.

The __proto__ property has several properties I would expect (eg getStyle and getStyleFunction) but no getSource.

I have also tried doing a similar thing but passing the source as a parameter to processFeatures instead of the layer. This time all worked OK except that getFeatures returned an array of length zero. This seems a similar issue to the one above.

**Comment by ghettovoice** [comment]
As you mention about your old system I suppose that you should listen for a change event on the source.
With vuelayers you can subscribe to the `update:features` event  that is triggered for each openlayers `addfeature` and `removefeature` event, so probably you should debounce handler execution to get only the last.

> The processFeatures routine receives a parameter I call vectorLayer. The problem is that, although the layer displays OK, vectorLayer.getSource() returns null.

Actually each vuelayers component creates underlying openlayers instance asynchronously, so when `thisLayer.$mountPromise` will be resolved there is no guarantee that inner `vl-source-*` component already mounted. The easiest way would be use `$mountPromise` on the source component.  
But note that `$mountPromise` of the source indicates only that underlying `ol.source.*` object had attached to the layer. At that moment, if source is remote,  there are no features at all.

**Comment by PeterC66** [comment]
Thanks for the help. I am nearly there, but I am having trouble using the update:features event. 

Remembering that I want to process all the features in the vector source once they are mounted:

In my original post I used the mounted event to call onMounted thus:
    const onMounted = (thisSource) => {  processFeatures(thisSource.$source)  etc}
but it had 0 features.

I am now trying to use the update:features event (debounced), but I cannot see how to define the function to access the source. The only solution I can see is use to give it a ref and use this.$refs[myRef], and ensure that my function is bound to 'this' correctly.

Any further guidance would be appreciated.

**Comment by ghettovoice** [comment]
> The only solution I can see is use to give it a ref

I think this would be the right solution. 
To hold correct event handler context I usually make it like this :

```html
<template>
  <vl-map ...>
   ...
    <vl-layer-vector>
      <vl-source-vector ref="vectorSource" :features.sync="vectorFeatures" @update:features="onFeaturesUpdate" ...></vl-source-vector>
    </vl-layer-vector>
  </vl-map>
</template>

<script>
  import debounce from 'lodash/debounce'

  export default {
    methods: {
      // lodash debounce returns function that saves current call context https://github.com/lodash/lodash/blob/4.17.11/lodash.js#L10402
      // i.e. this.debounced will be executed with correct this
      // so use "function() {}" expression to hold function context bound to current component
      onFeaturesUpdate: debounce(function() {
        this.$refs.vectorSource.getFeatures() // vl-source-vector component method returns ol.Feature[]
        this.$refs.vectorSource.$source.getFeatures() // ol.source.Vector method ol.Feature[]
      }),
    },
    ...
  }

</script>
```

**Comment by ghettovoice** [comment]
If you can show me your old application that is based on the openlayers,
may be I can help better to translate it to the vuelayers

**Comment by PeterC66** [comment]
Thanks again for your help. In my js/olv3 system I was using the layer as the way in, and using there being >0 features as a proxy for everything being loaded. (a bit crude  - but this worked for me). Maybe promises might have helped but I was not aware of them then.

Here's an extract of my code:
```
thismap.getLayers().insertAt(layerindex,...);
...
var newLayer = thismap.getLayers().getArray()[layerindex]; 
processFeatures(newLayer, options);

function processFeatures(vectorLayer, options) {
  // The purpose of this routine is just to make sure we have a valid source to operate on
	var source = vectorLayer.getSource();
	if (source) {
		var numFeatures = source.getFeatures().length;
		// Known problem that numFeatures may genuinely be zero
		if (numFeatures===0) {
			vectorLayer.getSource().once('change', function(event){
				source = event.target;
				if (source.getState() === 'ready') {
					return processFeaturesActions(vectorLayer, source, options);
				}
			});
		} else {
			if (source.getState() === 'ready') {
				return processFeaturesActions(vectorLayer, source, options);
			} else {
				consolelog("In processFeatures source found, but not ready", vectorLayer, options, source);
			}
		}
	} else {
		consolelog("In processFeatures no source found", vectorLayer, options);
	}
}

function processFeaturesActions(layer, src, options) {
  // 'options' guides what aspects of the processing are to be done in this call
	src.forEachFeature(function(feature) {...})
}
```

**Comment by ghettovoice** [comment]
As one-to-one translate to vuelayers should work:

```html
<template>
  <vl-map ...>
   ...
    <vl-layer-vector>
      <vl-source-vector ref="vectorSource" :features.sync="vectorFeatures" @mounted="onSourceMounted" ...></vl-source-vector>
    </vl-layer-vector>
  </vl-map>
</template>

<script>
  import debounce from 'lodash/debounce'

  export default {
    methods: {
      onSourceMounted (vm) {
        const source = vm.$source

        var numFeatures = source.getFeatures().length;
	// Known problem that numFeatures may genuinely be zero
	if (numFeatures===0) {
		vectorLayer.getSource().once('change', function(event){
			source = event.target;
			if (source.getState() === 'ready') {
				return processFeaturesActions(vectorLayer, source, options);
			}
		});
	} else {
		if (source.getState() === 'ready') {
			return processFeaturesActions(vectorLayer, source, options);
		} else {
			consolelog("In processFeatures source found, but not ready", vectorLayer, options, source);
		}
	}
      },
    },
    ...
  }

</script>
```

To simplify such use cases may be I need to introduce additional vl-source-* events, something like : `update:state`, ...

**Comment by PeterC66** [comment]
Thanks.
Although your one-to-one translation of my routine did not quite work (as `vectorLayer` is undefined) I did manage to get it working by using `vectorLayer =  vm.$parent.$layer`.

This is possibly not the best way, but it does seem to work and I will explore it's use more. 

To summarise where I have now got to with this particular issue:

I am:
- using the mounted event for the vl-source, and not for the vl-layer
- passing the Vue component (vl-source) as an argument to my processing routine, rather than the ol object (source)
- listening to the 'change' ol event, rather than the vl 'update:features event'

I am **not**:
- using any refs
- using $mountPromise (presumably using the mounted event means this is unnecessary)
- using debounce (although I can see some other places where I should be using it)

If there any other things you can do in vuelayers to make this sort of thing easier I would appreciate them. But for now I can get on, so I will close this issue.
Thanks

**Comment by ghettovoice** [comment]
Thanks @PeterC66 for sharing your solution :+1:
