### ISSUE TITLE
Documentation

### ISSUE THREAD

**Issue by mediavariance** [ghettovoice/vuelayers#12]
Do you need any help with documentation on this project? I love the structure of it, and would like to help any way possible.

**Comment by ghettovoice** [comment]
Hi!
Currently I work on jsdoc plugin and webpack loader to generate documentation from source code. Also I try to form some rules for documenting that would work with this plugins.
Now there are issues with events documenting and links processing between components.

**Comment by ghettovoice** [comment]
Moreover, there are a lot of code that should be covered with comment blocks

**Comment by mediavariance** [comment]
Okay! Thanks for the response.
