### ISSUE TITLE
geometry in style-box or other workround

### ISSUE THREAD

**Issue by dd-han** [ghettovoice/vuelayers#122]
Hi

I need custom vertices style for polygon and polyline on my project, and I found [OpenLayers Custom Polygon Styles Sample](https://openlayers.org/en/latest/examples/polygon-styles.html) is what I need.

But I have no idea how to implement following code on VueLayer

```JavaScript
          geometry: function(feature) {
            // return the coordinates of the first ring of the polygon
            var coordinates = feature.getGeometry().getCoordinates()[0];
            return new MultiPoint(coordinates);
          }
```
What's `geometry` implement in VueLayer or any workaround can implement that ?

Thanks

**Comment by ghettovoice** [comment]
Hi @dd-han ,
this use case is supported through the `vl-style-func` component.  Or for the simplest case
with `vl-geom-*` appended to `vl-style-box` (if geometry coordinates resolved from something else then current features set).  
Take a look here https://jsfiddle.net/ghettovoice/rc4u02na/, this example reproduces original OpenLayers example you menthion

**Comment by dd-han** [comment]
Hi @ghettovoice ,

Thank you for your assistance, your sample help a lot.
