### ISSUE TITLE
Popup that follows a feature thats changing position dynamicly

### ISSUE THREAD

**Issue by striker890** [ghettovoice/vuelayers#123]
Hi,
so I am wondering how to make a popup follow the changes to it's features coordinates.
Feature like:

                <vl-feature v-for="object in objectAsList" :key="object.id" :id="object.id">
                    <vl-geom-point :coordinates="[object.lon, object.lat]"></vl-geom-point>
                    <vl-style-box>
                        <vl-style-icon src="/img/marker.png" :scale="0.4" :anchor="[0.5, 1]"></vl-style-icon>
                    </vl-style-box>
                </vl-feature>

Where objectAsList is a computed function wich generates an array from a map (using a small workaround for maps not beeing observable in vue).
Interaction Select:

                <vl-interaction-select :features.sync="selectedFeatures" v-if="drawType == null">
                    <template slot-scope="select">
                        <vl-overlay class="feature-popup" v-for="feature in select.features" :key="feature.id" :id="feature.id"
                                    :position="pointOnSurface(feature.geometry)" :auto-pan="true" :auto-pan-animation="{ duration: 300 }">
                            <template slot-scope="popup">
                                       .... some content
                            </template>
                        </vl-overlay>
                    </template>
                </vl-interaction-select>

I used this from the example to try out some stuff.

**Comment by ghettovoice** [comment]
Hi @striker890 ,
currently there is a known bug with `vl-interaction-select` `features` property synchronization, 
i.e it doesn't react on deep feature changes.  

But you workaround it like in this example https://jsfiddle.net/ghettovoice/gamdbzsp/. Here I made a computed property from original `features` array (that react on coordinate changes) filtered by selected feature identifiers list. Try to click on the marker and you will see an overlay that will be always connected to feature coordinate
