### ISSUE TITLE
How to fit view from extents?

### ISSUE THREAD

**Issue by fnoop** [ghettovoice/vuelayers#126]
Hi, two stage problem.

1.  If I have working features and then try to wrap them in a vectorsource, the features disappear:
```
    // Add marker for vehicle
    vl-layer-vector
      vl-source-vector(ref="vmarkers")
        vl-feature(:id="'v_' + api" v-for="(data, api) in navSatFixData" :key="'v_' + api")
          vl-geom-point(v-if="data && 'longitude' in data" :coordinates="[data.longitude, data.latitude]")
          vl-style-box
            vl-style-circle(:radius="api == activeApi ? 6 : 4")
              vl-style-fill(:color="apis[api]['color-dark']")
              vl-style-stroke(color="#666666" :width="api == activeApi ? 2 : 1")
```

2. I would then like to use the vectorsource to determine the boundaries and zoom to autofit all the markers into view:
 - https://stackoverflow.com/a/37385069
But `this.$refs.vmarkers.getExtent()` doesn't exist?

**Comment by ghettovoice** [comment]
Hi @fnoop ,
as for the first problem I have no idea why features are disappear. Can you provide test app that reproduces this behavior?

The second issue: not all methods of the openlayers are implemented in vuelayers components, but you can use original methods from ol object instance.  
For `vl-source-*` components: 
```js
// this.$refs.mySource.$source - ol.source.Source
this.$refs.mySource.$source.getExtent()
``` 
Take a look for this fiddle https://jsfiddle.net/ghettovoice/br84dgq2/.

**Comment by fnoop** [comment]
Perfect, that solves the problem exactly.  Thank you :)

**Comment by fnoop** [comment]
Just as a followup for anyone who comes across this, the fiddle above uses a 1 second timeout to hopefully wait for the layer features to be fully created on mount but that's not always the case, and then you get an extents error from openlayers.  Instead I use a watcher on my coordinates variable, and also specifically test to make sure the extent is valid:
```
          // Fetch extents of the vector source layer
          this.viewExtents = this.$refs.vectorSource.$source.getExtent()
          // If there is a finite extent, then fit the view
          if (!this.viewExtents.includes(Infinity)) {
            this.$refs.mapView.$view.fit(this.viewExtents, {
              size: this.$refs.map.$map.getSize(),
              duration: 1000
            })
          }
```
There are probably lots of ways to do this though.

**Comment by DanRamage** [comment]
> Just as a followup for anyone who comes across this, the fiddle above uses a 1 second timeout to hopefully wait for the layer features to be fully created on mount but that's not always the case, and then you get an extents error from openlayers (https://openlayers.org/en/v5.3.0/doc/errors/#25). Instead I use a watcher on my coordinates variable, and also specifically test to make sure the extent is valid:
> 
> ```
>           // Fetch extents of the vector source layer
>           this.viewExtents = this.$refs.vectorSource.$source.getExtent()
>           // If there is a finite extent, then fit the view
>           if (!this.viewExtents.includes(Infinity)) {
>             this.$refs.mapView.$view.fit(this.viewExtents, {
>               size: this.$refs.map.$map.getSize(),
>               duration: 1000
>             })
>           }
> ```
> 
> There are probably lots of ways to do this though.

I know this is old, but any chance you could expand on this. I'm running into the same issue. I'm not quite following how you are using/iplemented the watch.

**Comment by ghettovoice** [comment]
Hi @DanRamage ,
I have made a demo with one of the way to achieve this, take a look here https://jsfiddle.net/ghettovoice/1qdh3cLa/

**Comment by DanRamage** [comment]
> Hi @DanRamage ,
> I have made a demo with one of the way to achieve this, take a look here https://jsfiddle.net/ghettovoice/1qdh3cLa/

Thanks for the example. Here's a followup, and if I need to open a new issue I will. Is there a way to have the vector layer notify(event) the parent container that it has rendered the features? What I see alot is when referencing: 
`vm.$refs.site_vector_layer.$source`
$source is undefined.
Periodically I also see the call to getExtent:
`vm.sitesLayerExtents = vm.$refs.site_vector_layer.$source.getExtent();`
return Infinity.

**Comment by ghettovoice** [comment]
In the current version there is no any special event for `load complete` state, neither in VueLayers nor OpenLayers. So watching with deferred handler call can signal for you that something changed in the vector source (zoom out -> new extent loaded -> new features appended).
 In `features` watcher I use reference to the `$source` without checking for `null` because if this array start changing and it only used as input for `vl-source-vector`, then at handler call time the underlying openlayers vector source `$source` already created. And after even one feature already in the source, then `getExtent` should return something else then Infinity.

You can try another approach using OpenLayers objects https://gis.stackexchange.com/questions/123149/using-layer-loadstart-loadend-events-in-openlayers-3
In that case you can subscribe in the `created` event handler.

```html
<template>
  <vl-source-vector @created="onSourceCreated"></vl-source-vector>
</template>

<script>
  export default {
    methods: {
       onSourceCreated (sourceVm) {
         // sourceVm - vl-source-vector instance
         // sourceVm.$source - ol/source/Vector instance
        // here you are secure to use $source, because event fired exactly after ol/source/Vector instance created
       },
    },
  }
</script>
```

**Comment by DanRamage** [comment]
Excellent. thanks! My workaround was to use a timeout, but I want something more deterministic.
