### ISSUE TITLE
vl-style-icon doesn't work with svg?

### ISSUE THREAD

**Issue by fnoop** [ghettovoice/vuelayers#128]
Hi,

This works:
` vl-style-icon(src="/img/icons/vehicleIcons/060-helicopter.png" :anchor="[0.5, 1]")`

This doesn't:
` vl-style-icon(src="/img/icons/vehicleIcons/060-helicopter.svg" :anchor="[0.5, 1]")`

Is this an inherent limitation in the component?

**Comment by ghettovoice** [comment]
Hi @fnoop ,
it should work with svg. 
There is example with latest vuelayers and openlayers https://jsfiddle.net/ghettovoice/cpmstv7w/.

Maybe svg is broken? Is it opens for view?

**Comment by fnoop** [comment]
OK so the svg didn't have specific height/width so wasn't displayed correctly.  With specifying the heigth/width in absolute units then the svg displays, but scale and opacity props don't work.

**Comment by fnoop** [comment]
Scale/opacity is working now, just needed a couple of restarts for some reason to take effect :)
