### ISSUE TITLE
Problem with openlayers master

### ISSUE THREAD

**Issue by fnoop** [ghettovoice/vuelayers#129]
Looks like the current openlayers master (>5.3.0) has moved files around, so vuelayers lib can't find them:
```
./node_modules/vuelayers/lib/graticule/index.js
Module not found: Error: Can't resolve 'ol/Graticule' in '/srv/maverick/code/maverick-web/node_modules/vuelayers/lib/graticule'
```

**Comment by ghettovoice** [comment]
Hi @fnoop ,
what is version of openlayers you using?
I don't see any changes here https://unpkg.com/ol@5.3.0/, `ol/Graticule` at the package root.  
May be `ol` package is broken?

**Comment by fnoop** [comment]
Hey @ghettovoice - this is using latest openlayers master.  There was a huge bug in ol 5.3.0 that got fixed:
github.com/openlayers/openlayers/pull/9036

This affects vl-interaction-modify almost every time in my app, so I need the fix.

**Comment by fnoop** [comment]
They've changed the location of files in the latest build, by the look of it:
```
[dev] [mav@goodrobots ~/code/openlayers]$ ls build/ol/layer
Base.js		  BaseTile.js	     Graticule.js      Heatmap.js      Layer.js		Tile.js		     Vector.js		 VectorTile.js
Base.js.map	  BaseTile.js.map    Graticule.js.map  Heatmap.js.map  Layer.js.map	Tile.js.map	     Vector.js.map	 VectorTile.js.map
BaseImage.js	  BaseVector.js      Group.js	       Image.js        Property.js	TileProperty.js      VectorImage.js	 VectorTileRenderType.js
BaseImage.js.map  BaseVector.js.map  Group.js.map      Image.js.map    Property.js.map	TileProperty.js.map  VectorImage.js.map  VectorTileRenderType.js.map
```

**Comment by ghettovoice** [comment]
Yes, I found this commit. But this changes not released yet, so I can't make public release of the vuelayers.  

I only can try to prepare something like dev build that will be compatible with openlayers `master` branch.  Then you will install it with special tag: `npm install vuelayers@dev`.

**Comment by ghettovoice** [comment]
There will be a lot of work.
Thanks for pointing me!

**Comment by ghettovoice** [comment]
Can you make pull request to `ol-next` branch?

**Comment by ghettovoice** [comment]
@fnoop please try to install `npm i vuelayers@alpha`
