### ISSUE TITLE
No Tiles

### ISSUE THREAD

**Issue by mediavariance** [ghettovoice/vuelayers#13]
I'm attempting to build VueLayers with Webpack for my web application, and I'm not seeing any tiles, yet no errors.

WEBPACK:
`require('openlayers');
window.Vue = require('vue');
import Map from 'vuelayers/lib/index.umd.js';
import 'vuelayers/lib/style.css'
Vue.use(Map)`

Vue Instance:
`var v = new Vue({
            el: '#test',
            data: {
                name: 'vld-demo-app',
                center: [-12459082.126126748, 3959846.702973134],
                zoom: 2,
                rotation: 0,
                clickCoordinate: undefined,
            },
            methods: {}
        });`

HTML:
`<div id="test">
                        <vl-map :load-tiles-while-animating="true" :load-tiles-while-interacting="true">
                            <vl-view :center="[0, 0]" :zoom="3" :rotation="0" />
                            <vl-layer-tile>
                                <vl-source-osm />
                            </vl-layer-tile>
                        </vl-map>
                    </div>`

Any ideas?

**Comment by ghettovoice** [comment]
I think it's all about self-closing tags inside template ,them work only in single-file Vue components, but it's invalid for common HTML.
I create jsfiddle from your code without self-closing tags [See here](https://jsfiddle.net/49xvqahq/2/)

**Comment by ghettovoice** [comment]
I'll fix all examples and remove using of self-closing tags that no one else was confused

**Comment by mediavariance** [comment]
That was the perfect solution! Thank you!

This isn't exactly related to the original topic, but is this the proper way to specify an alternative tile server?
https://jsfiddle.net/mediavariance/y5q5v3fy/1/

**Comment by mediavariance** [comment]
I should add that I'm using mapbox, and found your vue:
https://github.com/ghettovoice/vuelayers/blob/237679121f859ad6b768bf8d2b914c54968fffd2/src/components/mapbox-source/source.vue

Although, I can't seem to get it to work. No errors, and no map container.

**Comment by ghettovoice** [comment]
For alternative tile source there is generic source component `vl-source-xyz` that accepts url template as `url` prop, tokens inside template are  same as in OpenLayers ol.source.XYZ and ol-tilecache package.
[Corrected fiddle](https://jsfiddle.net/y5q5v3fy/3/).
Take a look at source component and it url prop, I define url prop without binding because its value is a raw string, not a component field

**Comment by ghettovoice** [comment]
About mapbox, show me how you use vl-source-mapbox.

**Comment by mediavariance** [comment]
That's exactly it, thank you so much!
