### ISSUE TITLE
Raster Image overlays?

### ISSUE THREAD

**Issue by avpavp** [ghettovoice/vuelayers#134]
I have a raster image I would like to overlay on the map.  This image would be dynamic.  ie I wouldn't have a static url to the image, more likely I would receive the image via websockets.  

Is there a way for me to overlay this image with transparency on the map, covering certain lat/lon area?

Almost like overlaying weather data (like cloud cover) on top of OSM, for example.

Any help greatly appreciated.

**Comment by ghettovoice** [comment]
Hi @avpavp ,
so you get image from websocket as byte buffer or something similar?
You can encode it to the data uri and set as url for `vl-source-image-static`.
There is an example https://jsfiddle.net/ghettovoice/Ludfq6ay/

**Comment by avpavp** [comment]
Thanks for the fiddle.

I could receive the data ad a PNG for example (as a byte stream)...  I have some flexibility here...

How about transparency?  If the data has an alpha channel will it be preserved and displayed?  Or do you have a suggestion to handle this?

I will try some things based on your example.  Thanks again...

**Comment by ghettovoice** [comment]
If the image data will have alpha channel there shouldn't be any problems on the map.
As you can see in fiddle, I add png with alpha encoded as base64.

**Comment by avpavp** [comment]
Sounds good.  

I'll give it a try and see what happens.

Thanks!
