### ISSUE TITLE
HeatmapLayer

### ISSUE THREAD

**Issue by espositofulvio** [ghettovoice/vuelayers#135]
Any chance the HeatmapLayer will be implemented soon?

**Comment by ghettovoice** [comment]
Hi @espositofulvio,
I can include it to the next release.
But I can't say when it will be ready, as soon as there is a little time for this.

Meanwhile you can try to implement own layer based on the VueLayers mixins, you can use 
generic `vector-source` mixin, take a look at the package distrib https://unpkg.com/vuelayers@0.11.1/lib/mixin/

**Comment by espositofulvio** [comment]
I guess much of it will be very similar to vector-layer, just a few more properties and a new HeatmapLayer instead of new VectorLayer. I'll give it a go directly in my project as I'm using typescript. Thanks anyway, you've done an amazing job!
