### ISSUE TITLE
[Nuxt] Unable to render map when wrapped in <no-ssr>

### ISSUE THREAD

**Issue by felixdenoix** [ghettovoice/vuelayers#136]
Hello !
When using the nuxt <no-ssr> components that delays the render of a component until the page is mounted (to ensure it's only rendered when the window is ready), I do not manage to render the component. To simplify the tests, i rewrote my component like so:

``` vue
<template>
	 <section class="page stores">
		<vl-map
			v-if="mounted"
			id="stores__container"
			ref="map"
			:controls="false"
			data-projection="EPSG:4326">
			<vl-view
				ref="view"
				:zoom.sync="zoom"
				:center.sync="center">
			</vl-view>

			<vl-layer-tile id="osm">
				<vl-source-osm></vl-source-osm>
			</vl-layer-tile>
		</vl-map>
	</section>
</template>

<script>
export default {
	name: 'Stores',
	data() {
		return {
			mounted: false
		}
	},
	mounted() {
		this.mounted = true
	}
}
</script>
```
When the component is mounted:
 - the reference exists in the context `this.$refs.map` but it seems that the vl-map component is not rendered
 - I can access the component map like so `this.$refs.map.$map` so it seems to be instantiated;
 - the `this.$refs.map.$map.isRendered()` method returns me false so it seems that it is not rendered yet but I can't find a way to trigger a re-render. 

Does anyone has an idea on how to trigger a re-render on the component ?
Thanks in advance for your replies (and thanks to the author for the supernice work!)

**Comment by ghettovoice** [comment]
Hi @felixdenoix ,
this is a known issue, thanks! 
Sometimes map is not visible when container initially have zero height/width or hidden .
To workaround you can manually re-render `vl-map` component like below:

```html
<template>
  ...
  <vl-map .... 
              @mounted="onMapMounted">
    ...
  </vl-map>
  ...
</template>

<script>

export default {
    methods: {
        onMapMounted (vlMap) {
            // vlMap here is an instance of vl-map component
            // here vlMap.$map - ol.Map instance - is ready to use
            vlMap.refresh()
        }
    },
}

</script>
```
Try this please

**Comment by felixdenoix** [comment]
Hi again @ghettovoice ! 
I tried without `vlMap.refresh()` && `vlMap.remount()` without success 
(I've also set the height of the parent div to 100vh and 100vw)

**Comment by felixdenoix** [comment]
For anyone passing by the working shape of the component is the following 
```vue 
    <template>
	 <section class="stores">
		<div class="stores__wrapper">
			<transition name="fade">
				<vl-map
					v-if="mounted"
					id="stores__container"
        ...
    </template>
```
and the style 
```scss
.stores {
	display: flex;
}
.stores__wrapper {
	height: 100vh;
	width: 100vw;
}
#stores__container {
	position: relative;
	width: 100vw;
	height: 100vh;

	canvas, .vl-map  {
		height: 100vh;
		width: 100vw;
	}
}
```

**Comment by ghettovoice** [comment]
Thanks for sharing!

**Comment by felixdenoix** [comment]
Np ! 
I could try to do a pr for the documentation for usage with nuxt in the next days if you like  !

**Comment by ghettovoice** [comment]
It would be nice!

**Comment by mgiraldo** [comment]
@felixdenoix how did you get vuelayers to work with no-ssr and nuxt? i'm getting `Unknown custom element: <vl-map>` errors

**Comment by felixdenoix** [comment]
Hey @mgiraldo !
for starters i created a plugin:
```
import Vue from 'vue'
import VueLayers from 'vuelayers'
import 'vuelayers/lib/style.css' // needs css-loader

Vue.use(VueLayers)
```
It allows me to load the component and the styles as demonstrated in the doc [here](https://nuxtjs.org/guide/plugins#client-side-only) and then I include it in the nuxt config with the `ssr: false` since the window object is required:
```
plugins: [{
		src: '@/plugins/vueLayers',
		ssr: false
	},...
```
Afterwards have a look to the previous responses, you should have all the informations needed !
