### ISSUE TITLE
vl-interaction help

### ISSUE THREAD

**Issue by rmiller335** [ghettovoice/vuelayers#141]
I have the following code, which displays a crosshair on a map after an address geocode, to show the property that was found:

```
<vl-feature class="crosshair" id="crosshair" v-show="showCrosshairs">
	<template>
		<vl-geom-point :coordinates="xPsn" />

		<vl-style-box>
			<vl-style-icon @click="console.log('xhair click')" src="/images/crosshair.png" :scale=".05" />
		</vl-style-box>
	</template>
</vl-feature>
```
Once the crosshair is displayed, I would like the user to be able to click & drag it in order to fine tune the search result.  I see from the demo that a point can be moved in tis way using interaction, but I can't see how to apply it in this case.  Would you mind giving me a little guidance?

Thanks,
Bob

**Comment by ghettovoice** [comment]
I prepare an example, take a look here https://jsfiddle.net/ghettovoice/ec97d0fy/.
The main idea is provide to `vl-interaction-modify` a vector source ident, where you place
features to modify. In this example I just bind `vl-interaction-modify` to `vl-source-vector#ident="featuresSource"`, but here can be another separate layer/source, like in the vuelayers-demo .
