### ISSUE TITLE
vl-source-xyz has url as a required prop, but ol has it as optional

### ISSUE THREAD

**Issue by PeterC66** [ghettovoice/vuelayers#142]
In ol/source/XYZ the string property 'url' is optional, and the array of strings property 'urls' is an alternate (which I want to use for eg openTopoMap).

vl-source-xyz seems to have url as a required prop, and not use urls if it is given as a prop.

**Comment by ghettovoice** [comment]
Which URL patterns you want to use with "openTopoMap"? Can you show me example please?
I'm ask you because usually there is no need for `urls`, `url` accepts url template covers subdomains and url tiling schema

**Comment by PeterC66** [comment]
The one I was copying was "OpenTopoMap", defined for me in ol by 
"sourcedef": {"urls":[
"https://a.tile.opentopomap.org/{z}/{x}/{y}.png",
"https://b.tile.opentopomap.org/{z}/{x}/{y}.png",
"https://c.tile.opentopomap.org/{z}/{x}/{y}.png"
]}
I have discovered that I can use just one of these, so maybe as you say I don't need urls?

**Comment by ghettovoice** [comment]
You can url for this: `https://{a-c}.tile.opentopomap.org/{z}/{x}/{y}.png`

**Comment by PeterC66** [comment]
Thanks.
