### ISSUE TITLE
Highlighting feature clicked as row in table 

### ISSUE THREAD

**Issue by mustafahamid** [ghettovoice/vuelayers#143]
Hi, 
  I am tring to  select feature by calling this.$refs.interaction.select(feature) where my feature is 
`<vl-interaction-select :features.sync="selectedFeatures" ref="interaction"></vl-interaction-select>  
    `

```
{  type: "Feature",
          id: 
          geometry: {
            coordinates: []
          },
          properties: {
          }
        }
}
```

But the function select is not adding this feature.
 I am doing this because i need that synchronize the click event on the map with a click on the table.

**Comment by ghettovoice** [comment]
Hello @mustafahamid ,
sorry for the late response.

> But the function select is not adding this feature.

Select interaction doesn't add new features, it selects features already rendered by another layers. So all you need it load features from backend or something else, provde to the `select` method `id` of the feature you want to hightlight.
Are you sure that selected feature already on the map?

**Comment by mustafahamid** [comment]
thank you, it works with id.

**Comment by ghettovoice** [comment]
Nice! so I close this
