### ISSUE TITLE
support props for tilePixelRatio and HiDPI

### ISSUE THREAD

**Issue by jorgejesus** [ghettovoice/vuelayers#144]
Tile layers have several properties related to retina display devices (mobile phones), these should be possible to set on the layer component (for what I know is not possible to set is on vuelayers)

e.g
https://openlayers.org/en/latest/examples/xyz-retina.html

When implementing tiling with geoserver's geowebcache it becomes a problem using the current layers that will send tile size requests that are not supported by geowebcache

**Comment by ghettovoice** [comment]
Hi @jorgejesus ,
this is already implemented, each tile `vl-source-*` component has `tile-pixel-ratio` property.
Take a look at the example https://jsfiddle.net/ghettovoice/jnexb3t6/

**Comment by jorgejesus** [comment]
Thank you for the information, I am closing the ticket since replay helped solve the problem
