### ISSUE TITLE
toSubscriber.js.map

### ISSUE THREAD

**Issue by marcuus** [ghettovoice/vuelayers#145]
Where can I find toSubscriber.js.map seems to be a prerequisite in order to render a map.

> Source map error: request failed with status 404
> Resource URL: http://localhost:8150/js/app_admin.js
> Source Map URL: toSubscriber.js.map

**Comment by ghettovoice** [comment]
Hi @marcuus ,
source map loading shouldn't break the application, browser loads them only when devtools panel is active. Seems like you have broken source map, may be incorrect webpack config or something else.

In any case this file from rxj package, see here https://unpkg.com/rxjs@6.4.0/_esm5/internal/util/
