### ISSUE TITLE
vl-interaction-select style - disable, style function

### ISSUE THREAD

**Issue by marena** [ghettovoice/vuelayers#146]
Hi,

I am looking for a solution how to style selected/hovered features. In general, I just want to zoom in, or little fade out feature on select and keep styles (mostly icons) unattached.

1. Is there any way how to disable changing style on select event? If I don't specify style, default style is used.

2. Can I use style function? I tried vl-style-func component, but it does not seem to work.
```
<vl-interaction-select :features.sync="selectedFeatures" :condition="pointerMoveCondition">
   <template slot-scope="select">
      <vl-style-func :factory="styleFunc"></vl-style-func>
   </template>
</vl-interaction-select>
```
Any advice?
Thanks

**Comment by ghettovoice** [comment]
Hi @marena ,
you can use one style function for layer and select interaction, and toggle only parts of style in it.
Take a look here https://jsfiddle.net/ghettovoice/wafq536x/.
As for your second question: `vl-style-func` accepts function that returns another function (so called style function). In any case see the jsfiddle below.

**Comment by marena** [comment]
Thanks for reply. Works great.

If anyone like me has many layers in separate files with different style functions. Use interaction-select filter function.

```
    <vl-interaction-select :features.sync="selectedFeatures" :filter="filterFunction" :condition="pointerMoveCondition">
      <vl-style-func :factory="styleFuncFactory"></vl-style-func>
    </vl-interaction-select>

...
        methods: {
            filter(vector, layer) {
                return layer.get('id') === 'my-layer-name';
            },
```
