### ISSUE TITLE
KML factory

### ISSUE THREAD

**Issue by Gaetanbrl** [ghettovoice/vuelayers#147]
Hi,
According to [this example](https://jsfiddle.net/ghettovoice/c8adLb64/8/) and vueLayers-demo, i can't create layer from KML, i get an error: 
> 
> ./src/assets/clients_4326.kml 1:0
> Module parse failed: Unexpected token (1:0)
> You may need an appropriate loader to handle this file type
> \<?xml version="1.0" encoding="utf-8" ?\>
>  \<kml xmlns="http://www.opengis.net/kml/2.2"\>
>  \<Document id="root_doc"\>
> 

Here is my code.
```
<script>

export default {
 data () {
   layer : [
      { ...      
      source: [
              cmp: 'vl-source-vector',              
              formatFactory: kmlFormatFactory, 
              url:'https://openlayers.org/en/latest/examples/data/kml/2012-02-10.kml'
      ] ...
```
For methods :
```
  const methods = {
    kmlFormatFactory () {
      return new ol.format.KML()
    }, ...
```
Please, what's wrong ?
Thank  you.

**Comment by Gaetanbrl** [comment]
How can i import ol component ? I have one message as "ol.format.KML()" is undefined.

**Comment by ghettovoice** [comment]
Hi @Gaetanbrl ,
I'm not a big KML format expert, vuelayers just reuse format readers from openlayers lib.
Probably you should check openlayers documentation and examples to get some 
https://openlayers.org/en/latest/apidoc/module-ol_format_KML-KML.html
https://openlayers.org/en/latest/examples/?q=kml

In your examples I see the only problem: if you are using any bundler then you should import 
format constructor manually:

```html
<script>
  import KML from 'ol/format/KML'

  const methods = {
    kmlFormatFactory () {
      return new KML()
    }, 
    ...
  }
</script>
```

**Comment by Gaetanbrl** [comment]
So i could try this code.

```
import KML from 'ol/format/KML'
import data from './assets/data.kml'

const methods = {
    kmlFormatFactory() {
        return new KML()
    },
}

export default {
    methods,
    data() {
        return {
            layers: [{
                id: 'dataKml',
                title: 'Layer KML',
                cmp: 'vl-layer-vector',
                visible: false,
                renderMode: 'image',
                source: {
                    cmp: 'vl-source-vector',                    
                    formatFactory: new Kml(),
                  	// how link data.kml here ?
                  	url: './src/assets/data.kml
                }
            }, ]
        }
    }
}
```

Need i to insert url params to link import KML data with this layer ?

I come back with result. Thank you.

**Comment by ghettovoice** [comment]
If you are using `url` of the source, the source data should be available at this url. 
Then the lib automatically load it and use the provided format reader to parse features from it.
So you should statically host your kml files, and set `url` to something like `/path/to/data.kml` or with external host `http://example.com/path/to/data.kml`. 
If you are using webpack, so this plugin can help to add static files to the build https://github.com/webpack-contrib/copy-webpack-plugin

**Comment by Gaetanbrl** [comment]
I catch him !!
formatFactory: kmlFormatFactory is undefined , i don't know why because i have insert kmlFormatFactory  in methods.

Thiks code work :   
```

            source: {
              cmp: 'vl-source-vector',             
              url: './src/assets/data.kml',
              formatFactory: function(){return new KML()},
            },
```

**Comment by Gaetanbrl** [comment]
I have one more question with geojson style settings, but i prefer to try again and open new question if necessary.
Thank you again @ghettovoice for your response.
