### ISSUE TITLE
how to implement box-selection in vuelayers?

### ISSUE THREAD

**Issue by jerry1108** [ghettovoice/vuelayers#148]
I need to implement some funtions to select / unselect features by using vl-interaction-select. 
Thank you for your demo codes. It's very helpful.
However, I also need to provide users to select features by using Box Selection further.
How to implement box-selection in vuelayers? Here is an example in openlayers.org:
https://openlayers.org/en/latest/examples/box-selection.html?q=select
Use Ctrl+Drag to draw boxes to select multiple fearues...
Hope someone can give me an example or how to implement it and I will apppreciate it. :))

**Comment by ghettovoice** [comment]
Hi @jerry1108 ,
for now there is no any convinient wrapper component for DragBox interaction.
But there is exist a workaround to use any interaction/control from openlayers.
I made an example that is translation of the official example, take a look here https://jsfiddle.net/ghettovoice/v2s9drx4/

**Comment by jerry1108** [comment]
Hi @ghettovoice ,
Thank you so much for your example.
However, yesterday I found that this box-selection function is not suitable for mobile-users on RWD website. Because the mobile-users can't use Ctrl + Drag to draw boxes. 
But I learnt how to use official example in the vuelayers from your demo codes. Thank you.

So I want to use another method:
Suppose I implement it by using vl-interaction-draw to draw a polygon and important of all, the mobile-users also can draw polygons on their devices,
Then I tend to keep the coordinates of this polygon and send them back to server side to check if the polygon intersects with  those features (originally saved in database) or not by using STIntersects function. 
Finally I would write an API to provide the client side to get which features are selected and change their colors. 
(Is it efficient?)

However, in my first step:  I got a problem by using vl-interaction-draw plugin.
There is an error:
Uncaught (in promise) TypeError: this._olObject[VM_PROP].includes is not a function
at VueComponent._callee$ (index.umd.js:8690)
at tryCatch (index.umd.js:1058)
at Generator.invoke [as _invoke] (index.umd.js:1284)
..........
And I found vl-interaction-modify didn't work!! (can't modify polygon)
My included scripts are: (from official website quickstart~)
<script src="https://unpkg.com/openlayers/dist/ol.js"></script>
<script src="https://unpkg.com/vuelayers/lib/index.umd.js"></script>
And then I try it in your jsfiddle demo codes and it works !!!
It seems the draw plugin works well by including ol.js of v5.3.0 and index.umd.js of 0.11.1, right??

In a word, your demo codes is very helpful to me, thank you.

**Comment by ghettovoice** [comment]
There is a tiny changed previous example with selection by drawn polygon
https://jsfiddle.net/ghettovoice/nu13vkxe/
After polygon is drawn it can be modified, and when you click on the "Select intersected features" button at the top, all intersecting features are selected and drawn polygon will be removed.
So I think there is no need to calculate this on the server.

As for error with draw interaction:
`vl-itnteraction-draw` requires identifier of the target vector source to which new features will be added.
Take a look at the `ident` and `source` properties.

**Comment by jerry1108** [comment]
@ghettovoice ,
Thank you so so much and for your fast reply!!
Awesome!! You save my life and my time. I will try it later.

**Comment by jerry1108** [comment]
Hi~ @ghettovoice,
I got a problem by using your example.
My features are multiple points.
You use the extent of the drawSource to check if they are Intersecting.
However, some points are not intersecting with the drawn polygon and those points are intersecting with its extent range. So the selection result is not correct. 
How to exclude those points  that are not intersecting with the drawn polygon but intersecting with its extent ?
Thank you.

**Comment by ghettovoice** [comment]
Hello @jerry1108 ,
openlayers doesn't provide a lot of helpers for spatial operation, but there is another great tool for this
http://turfjs.org/.
Here is upgraded example that filters out non-intersecting features from selection. https://jsfiddle.net/ghettovoice/dpL9qneg/

Take a look to the turf.js documentation, there are a lot of other methods, that can help you to get best result

**Comment by jerry1108** [comment]
hi @ghettovoice :
I also used the the third party tool (turf) to achieve the goal earlier.  :))
But still wanna ask you whether the vuelayers has provided the same function or not.
I used the turf.inside funtion and returns false if it's intersecting. 

Thank you for the example to use booleanDisjoint function. You are great!!

**Comment by jerry1108** [comment]
It seems the result of using turf.inside is the same as using !turf.booleanDisjoint.
Maybe just intersecting with a tiny point is almost impossible...

**Comment by ghettovoice** [comment]
> But still wanna ask you whether the vuelayers has provided the same function or not.

VueLayers doesn't provide any special spatial functions. As for me I prefer to use turf for this.

> Maybe just intersecting with a tiny point is almost impossible...

Maybe adding a small buffer (about ~10-100 meters) around point before checking intersection

**Comment by ghettovoice** [comment]
> But still wanna ask you whether the vuelayers has provided the same function or not.

VueLayers doesn't provide any special spatial functions. As for me I prefer to use turf for this.

> Maybe just intersecting with a tiny point is almost impossible...

Maybe adding a small buffer (about ~10-100 meters) around point before checking intersection

**Comment by jerry1108** [comment]
Thank you for your suggestion.
