### ISSUE TITLE
Style KML

### ISSUE THREAD

**Issue by Gaetanbrl** [ghettovoice/vuelayers#149]
HI @ghettovoice,
I load KML file from file system and i need to style this layer.
But nothing happend, the KML layer already display the default style.

Here is my code:  

```
import KML from 'ol/format/KML'
import style from 'ol/style/Style'
import stroke from 'ol/style/Stroke'
import fill from 'ol/style/Fill'

export default {
    data() {
        layers: [

            {
                id: 'dataKml',
                title: 'Layer KML',
                cmp: 'vl-layer-vector',
                visible: false,
                renderMode: 'image',
                source: {
                    cmp: 'vl-source-vector',
                    url: './src/assets/data/kml/data.kml',
                    formatFactory: function() {
                        return new KML()
                    },
                },
                style: [{
                    cmp: 'vl-style-func',
                    factory: this.pointsStyleFunc,
                }, ],
            }
        ]
    }
}


const methods = {
    pointsStyleFunc() {
        const pStyle = [
            createStyle({
                strokeColor: '#de9147',
                strokeWidth: 3,
                fillColor: [222, 189, 36, 0.8],
            }),
        ]
        return function __pointsStyleFunc(feature) {
            return pStyle
        }
    },
}


```
So, sadly nothing change...
Thank you for help.

**Comment by ghettovoice** [comment]
Hi @Gaetanbrl ,
show me your component template please. 
Are you using code from `vuelayers-demo` repo? 
The layer contains only points?

**Comment by Gaetanbrl** [comment]
> show me your component template please.
[This is the test code.](https://github.com/Gaetanbrl/ddv-viewer/blob/master/src/App.vue#L109)

> Are you using code from `vuelayers-demo` repo?
Yes it's currently my base. For the style i'm inspired by pacman code style. Maybe i need to modify more or less...

> The layer contains only points?
Yes only points generated by Qgis (shape to KML to be sur).

**Comment by ghettovoice** [comment]
Ok I got it. Looks like you missed circle radius option.
Try to change your `pStyle` style to this:

```
const pStyle = [
    createStyle({
        // this is required to create ol.style.Circle with some radius
        imageRadius: 10,
        strokeColor: '#de9147', // or it can be imageStrokeColor to apply only to ol.style.Circle
        strokeWidth: 3, // or it can be imageStrokeWidth to apply only to ol.style.Circle
        fillColor: [222, 189, 36, 0.8], // or it can be imageFillColor to apply only to ol.style.Circle
    }),
]
```

**Comment by ghettovoice** [comment]
If you want to use some icon for points then instead of `imageRadius`
you should set `imageSrc` option. `imageSrc` accepts a url to icon.

There also a lot of other options for `createStyle` helper. Hint about point related style you can see here https://github.com/ghettovoice/vuelayers/blob/master/src/ol-ext/style.js#L206

**Comment by Gaetanbrl** [comment]
Ok my bad!
Kml style seem to be stubborn ^^ 

This code don't work with my **kml** data
   ```
 pointsStyleFunc () {
      const pStyle = [
        createStyle({
        // this is required to create ol.style.Circle with some radius
          imageRadius: 10,
          strokeColor: '#de9147', // or it can be imageStrokeColor to apply only to ol.style.Circle
          strokeWidth: 3, // or it can be imageStrokeWidth to apply only to ol.style.Circle
          fillColor: [222, 189, 36, 0.8], // or it can be imageFillColor to apply only to ol.style.Circl
        }),
      ]
      return function __pointsStyleFunc (feature) {
        return pStyle
      }
    },
```

I link style with layer already with this code : 
```
            style: [
              {
                cmp: 'vl-style-func',
                factory: this.pointsStyleFunc,
              },
            ]
```

**Comment by ghettovoice** [comment]
Are you sure that your layer is visible? 
In the demo all layers in the `layers` array are hidden by default. 
Check the `visible` key in the layer hash.

I can't add example with exactly your KML data, but I highly doubt that source data is the case.
I made example just with GeoJSON features and your style function, and set `visible` key to the `true` and all works as expected. https://jsfiddle.net/ghettovoice/7o1ry5h2/

**Comment by Gaetanbrl** [comment]
I got it !
By default the Kml style is defined by extraction from file.
If you want to create a new style, you need to deactivate the default style:

              formatFactory: function () {
                return new KML({
                  extractStyles: false
                  })
              }, 
For GeoJson and KML, it's work! 👍 
Thank you a lot.

Last question : How can i set img scale if my icon come from local png.
I use this : 
```
    pointsStyleFunc () {
      const pStyle = [
        createStyle({
        // this is required to create ol.style.Circle with some radius
          //imageRadius: 10,
          imageSrc:'./src/assets/img/star_orange.png',
          scale: 0.5,
          strokeColor: '#de9147', // or it can be imageStrokeColor to apply only to ol.style.Circle
          strokeWidth: 3, // or it can be imageStrokeWidth to apply only to ol.style.Circle
          fillColor: [222, 189, 36, 0.8], // or it can be imageFillColor to apply only to ol.style.Circl
        }),
      ]
      return function __pointsStyleFunc (feature) {
        return pStyle
      }
    },
```

**Comment by ghettovoice** [comment]
Nice!

> How can i set img scale if my icon come from local png.

`imageScale` should work for you. Also probably you should define `imageAnchor` and `imageOffset` to correctly place the marker. There is description for this  and other options on the openlayers docs https://openlayers.org/en/latest/apidoc/module-ol_style_Icon-Icon.html.
`createStyle` use this options too, but with prefix `image*`.

**Comment by Gaetanbrl** [comment]
Nice again ! 
I saw this doc and your code, but 
I have tried the wrong prefix `img*` instead of `image*` ... it's better now ! i was not so far :)

Thanks for your help @ghettovoice.
