### ISSUE TITLE
Draw Interaction

### ISSUE THREAD

**Issue by mediavariance** [ghettovoice/vuelayers#15]
Is there any work on a draw interaction? If not, I'll fork and begin working on one.

See:
https://openlayers.org/en/latest/examples/draw-features.html

**Comment by ghettovoice** [comment]
I plan to present draw/modify/rotate interactions and may be complex draw panel component in the next release

**Comment by ghettovoice** [comment]
Ok, thank you!

**Comment by aliciahogue** [comment]
Just curious if there is an eta on this or if you have had a chance to start working on it.

**Comment by ghettovoice** [comment]
Hi, @aliciahogue! Currently, I can't start working on it due to lack of free time. I still can not finish the long-suffering documentation :)
Contributing are welcome

**Comment by aliciahogue** [comment]
Thanks for the quick reply and thanks for the work!!   I may look at implementing something and if so I will post back with any updates.

**Comment by ghettovoice** [comment]
resolved at [v0.10.1](https://github.com/ghettovoice/vuelayers/releases/tag/v0.10.1)
