### ISSUE TITLE
How to add google maps as a basemap

### ISSUE THREAD

**Issue by boussadjra** [ghettovoice/vuelayers#152]
How can i add google maps as a basemap ? like it is did with ol :

`new ol.layer.Tile({
        'title': 'Google Maps Uydu',
        'type': 'base',
         visible: true,
        'opacity': 1.000000,
         source: new ol.source.XYZ({
         attributions: [new ol.Attribution({ html: '<a href=""></a>' })],
         url: 'http://mt0.google.com/vt/lyrs=y&hl=en&x={x}&y={y}&z={z}&s=Ga'
         })
})`

**Comment by ghettovoice** [comment]
Hi @boussadjra,
VueLayers provides two components for this: `vl-layer-tile` and `vl-source-xyz`. The properties of them are the same like in the openlayers.

```html
<vl-layer-tile>
  <vl-source-xyz url="url template" attributions="string or array" />
</vl-layer-tile>
```

**Comment by boussadjra** [comment]
@ghettovoice Thank you very much
