### ISSUE TITLE
Is there any way to move, scale and rotate a LineString?

### ISSUE THREAD

**Issue by kvaezo** [ghettovoice/vuelayers#153]
I'm planning to create a web app with ability to draw linear line strings (with only 2 coordinates), and after the drawing the user should be able to move, rotate and scale the lines by drag&drop. Transforming them with control buttons is not an option for me. I've been googleing for more than a week, but I didn't find any good solution for that with OpenLayers (I've found a solution with Leaflet, but it isn't suites me for other reasons). So my question is that is there any solution for that in VueLayers? Or is it planned to be implemented?

**Comment by ghettovoice** [comment]
Hello @kvaezo ,
for now only `vl-interaction-draw` and `vl-interaction-modify` is implemented in the vuelayers. But other interaction can be added to the OpenLayers map through native API.
With `vl-interaction-modify` you can modify the drawn features.
For moving feature there is `ol/interaction/Translate`. It doesn't have special wrapper in the vuelayers, but if you need it, you can use basic interaction mixin https://github.com/ghettovoice/vuelayers/blob/master/src/mixin/interaction.js and try to wrap it yourself.
For rotating features you can try to use https://github.com/ghettovoice/ol-rotate-feature.
For scaling I can't suggest nothing, probably I should implement it yourself. Maybe this lib can help http://viglino.github.io/ol-ext/.

Later I plan to wrap all available std interactions plus most popular and useful third party extensions, but it requires a lot of time to do this which for now I haven't enough.

**Comment by kvaezo** [comment]
Hello @ghettovoice ,

Thanks for the quick answer! I'll try out the things you've mentioned and will be back if those are solves my problem or not. What do you think, if I can implement any of these features, could I create a pull request to merge them into the code base? :)

**Comment by ghettovoice** [comment]
> could I create a pull request to merge them into the code base?

You are welcome!

**Comment by jhettler** [comment]
Hi @kvaezo,
please, have you solved the rotation somehow? 
Thanks for information!

**Comment by kvaezo** [comment]
> Hi @kvaezo,
> please, have you solved the rotation somehow?
> Thanks for information!

No, I messed up my things and it was easier to start it over by using the native OL and OLExt plugins

**Comment by jhettler** [comment]
Unfortunatelly, this is the point where I am standing at the moment. I am pretty new to Vue.js (I have always used jQuery with OL) and most of the time I spend on solving issue between Vue and OL (nothing bad to @ghettovoice, vuelayers are amazing!).

**Comment by ghettovoice** [comment]
There are third party implementations on translate and rotate interactions as Vue components for VueLayers. https://github.com/Cytomine-ULiege/cytomine-frontend/tree/master/src/apps/explorer
You can get them as an good example how to extend VueLayers with custom components. 
Later they will be included in the VueLayers core, but I'm still can't find enough time for this
