### ISSUE TITLE
How to get pixel from coordinate？

### ISSUE THREAD

**Issue by mingtianyihou33** [ghettovoice/vuelayers#157]
I used method 'map.getPixelFromCoordinate(Proj)',but the result is not my want.I need your help.

**Comment by ghettovoice** [comment]
Hi @mingtianyihou33 ,
can you clarify a bit: 
 - What is a `map`?  Is it OpenLayers map instance?
- Which projection is used by the map view?

**Comment by mingtianyihou33** [comment]
Sorry,map is OpenLayers map instance.I use Heatmap.js and need to calculate screen coordinates.But I used the OpenLayers map instance method 'getPixelFromCoordinate(coordinate)', the result is not my 
want.

**Comment by ghettovoice** [comment]
What you got from `getPixelFromCoordinate(coordinate)`?
Take a note that `coordinate` should be in the same projection like used in the map view.

If can provide code listing or fiddle I can understand better what going wrong

**Comment by mingtianyihou33** [comment]
For example ,coordinate is [110.75592041015622, 35.240571975147446] in EPSG:4326 correspond to 
screen pixel is  [215.15625, 269.5703125] .How can I get the screen pixel from coordinate?

**Comment by ghettovoice** [comment]
If map view works in the `EPSG:3857` (that is setup by default) you should transform coordinate projection
before calling map methods.

```js

import { fromLonLat } from 'ol/proj'

....

coord3857 = fromLonLat(coord4326, 'EPSG:3857')
map.getPixelFromCoordinate(coord3857)
```

**Comment by mingtianyihou33** [comment]
This method works. Thank you.
