### ISSUE TITLE
Icon marker not appearing when relative url

### ISSUE THREAD

**Issue by avpavp** [ghettovoice/vuelayers#158]
Seems to be same as:  

https://github.com/ghettovoice/vuelayers/issues/86

I seem to be experiencing the exact same issue. I'm using a style function, creating an Icon, and it works with the src set to and http://... address, but shows nothing when I use a relative url, './assets/imge.png', for example. So it sounds exactly like the problem described above, but I can't get it to work when I modify my vue.config.js as above.

The vue.config.js is in the root, same level as package.json.

I don't see any relevant errors in the console?

Any other ideas or suggestions as to how to debug this or track down the issue?

using vue 2.6.10

Thanks!

**Comment by ghettovoice** [comment]
Hi @avpavp ,
solution from #86 works only for vue templates, i.e when vue transforms html template to render function this fix allows it to correctly transform `src` attribute to something like this `const img = require(srvValue)`.

But in your case you should make import of the icon image yourself and then pass it the `src` option of the `ol/style/Icon`

**Comment by avpavp** [comment]
Not sure I understand?

I have a view template, 

```
<vl-layer-vector>
      <vl-source-vector :features.sync="features" />
      <vl-style-func :factory="styleFeature" />
</vl-layer-vector>

```

Then in my styleFeature() I have:

```
 new Style({
            image: new Icon(({
              anchor: [0.5, 100],
              anchorXUnits: 'fraction',
              anchorYUnits: 'pixels',
              scale: 0.1,
              src: './assets/oil_icon.png'
              //src: 'https://png.pngtree.com/svg/20160518/2b5cd1409c.svg'

```

but it only shows an icon when i use the "src: 'https://png..."

Isn't this the same as issue #86?

Thanks!

**Comment by ghettovoice** [comment]
> Isn't this the same as issue #86?

It the same, but solution a slightly different. 

Try to manually import image:

```js
<template>
 <vl-map ...>
    <vl-layer-vector>
        <vl-source-vector :features.sync="features" />
        <vl-style-func :factory="styleFeature" />
     </vl-layer-vector>
  </vl-map>
</template>

<script>
  import iconImg from './assets/oil_icon.png'

  export default {
    methods: {
      styleFeature () {
         return feature => {
           return [
             new Style({
                image: new Icon(({
                anchor: [0.5, 100],
                anchorXUnits: 'fraction',
                anchorYUnits: 'pixels',
                scale: 0.1,
                src: iconImg,
             }),
           ]
         }
      },
    },
  }

</script>

```

Also take a note that you need setup webpack file loader so webpack can handle
image imports

**Comment by avpavp** [comment]
Hi @ghettovoice 

Thanks for your patience and insights.  Based on your last comments, I have this working now!

**Comment by abdullateef97** [comment]
@avpavp how do you set up your webpack so as to handle image imports

**Comment by ghettovoice** [comment]
Hello @abdullateef97 ,
for image imports you should use `url-loader` and `file-loader` included into your webpack plugins set. Take a look here for options https://webpack.js.org/loaders/url-loader/

**Comment by empereira** [comment]
> > Isn't this the same as issue #86?
> 
> It the same, but solution a slightly different.
> 
> Try to manually import image:
> 
> ```js
> <template>
>  <vl-map ...>
>     <vl-layer-vector>
>         <vl-source-vector :features.sync="features" />
>         <vl-style-func :factory="styleFeature" />
>      </vl-layer-vector>
>   </vl-map>
> </template>
> 
> <script>
>   import iconImg from './assets/oil_icon.png'
> 
>   export default {
>     methods: {
>       styleFeature () {
>          return feature => {
>            return [
>              new Style({
>                 image: new Icon(({
>                 anchor: [0.5, 100],
>                 anchorXUnits: 'fraction',
>                 anchorYUnits: 'pixels',
>                 scale: 0.1,
>                 src: iconImg,
>              }),
>            ]
>          }
>       },
>     },
>   }
> 
> </script>
> ```
> 
> Also take a note that you need setup webpack file loader so webpack can handle
> image imports

Hello @ghettovoice ,

I get this error:
error  'feature' is defined but never used

I can remove this variable?

I'm using vl-style-func the way below:

```vue
layers: [
        {
          id: "circles",
          title: "stations",
          cmp: "vl-layer-vector",
          visible: false,
          source: {
            cmp: "vl-source-vector",
            staticFeatures: stations,
          },
          style: [
            {
              cmp: "vl-style-box",
              styles: {
                "vl-style-func": {
                  factory: this.styleFeature,
                },
```
Is it correct?
