### ISSUE TITLE
Will there be Google Maps Layer support?

### ISSUE THREAD

**Issue by ton212** [ghettovoice/vuelayers#16]
I would like to know if this library will have Google Maps Layer support?

**Comment by ghettovoice** [comment]
You can use `vl-source-xyz` with `url` prop pointed to Google tile server.
[Example](https://jsfiddle.net/xy88s2k1/2/)

If you mean full integration with Google Js Map Api, I don't plan to implement it cause there is no efficient way to do that without rendering two maps simultaneously

**Comment by ton212** [comment]
Thank you so much, I'll take a look at it.
