### ISSUE TITLE
Measure map rendering time

### ISSUE THREAD

**Issue by mustafahamid** [ghettovoice/vuelayers#163]
Hi, 
 Can you please tell me how to measure map rendering time in vuelayers ? 
Thank you,

**Comment by ghettovoice** [comment]
Hi @mustafahamid ,
vuelayers is strongly based on the openlayers as map engine, so I think this could help you https://stackoverflow.com/a/28727212.

You can get the underlying openlayers map instance through event handler

```html
<template>
  <vl-map @created="onMapCredented"></vl-map>
</template>

<script>
export default {
  methods: {
    onMapCredented (map) {
      // map - is the vl-map component instance
     // map.$map - is the ol/Map instance
    },
  },
}
</script>
```
