### ISSUE TITLE
Error: Unsupported GeoJSON type: Circle

### ISSUE THREAD

**Issue by mustafahamid** [ghettovoice/vuelayers#164]
I try to excute this code: 
```
 <vl-layer-vector render-mode="image">
          <vl-source-vector :features.sync="features"></vl-source-vector>
        </vl-layer-vector>
 
// where the features are 

  features: [
          {
            type: "Feature",
            id:" xxx",
            geometry: {
              type: 'Circle',
              coordinates: [9.708854737, 47.3817338348]
            },
          },]
```
So  i get this error:
Uncaught (in promise) Error: Unsupported GeoJSON type: Circle
    at readGeometry (GeoJSON.js?a2e1:295)
  
I know from here [https://stackoverflow.com/questions/16942697/geojson-circles-supported-or-not](url) that circles are not supported in the GeoJson spec.

 So how can i draw many circles using vl-layer-vector with high performance. If i use the circle as a feature, the performance is very bad.
 Thank you

**Comment by ghettovoice** [comment]
Hi @mustafahamid ,
the one workaround can be represent circles as circular polygons, but there can be issues with very large circles, especially that cross the axis.

Another workaround you can try: use vector layer with points and style it with style function. OpenLayers allows to style source feature with another geometry, see `ol/style/Geometry` documentation on the OpenLayers site. So you can replace source point geometry with circle geometry at the style function.
