### ISSUE TITLE
vector-source: incorrect creation of features loader

### ISSUE THREAD

**Issue by become-iron** [ghettovoice/vuelayers#167]
There is probably incorrect creation of features loader in `vl-vector-source` component. I believe if a custom loader was passed, there is no need to check whether a url was passed. It leads to the fact that the loader won't be created at all

https://github.com/ghettovoice/vuelayers/blob/73bf8aa6fb08c4a683324706d54177552808a32d/src/component/vector-source/source.vue#L104-L107

**Comment by ghettovoice** [comment]
Looks like you are right. I have re-cheked openlayers source: if custom loader is provided, it will be used in any case.

**Comment by become-iron** [comment]
Thank you!
