### ISSUE TITLE
How to make a nonselectable  static style  feature

### ISSUE THREAD

**Issue by mustafahamid** [ghettovoice/vuelayers#169]
I have the problem where when I select a polygon element in vue layer, the style of this polygon change like in the photo below: 

![image](https://user-images.githubusercontent.com/38086105/58255438-468c0700-7d6d-11e9-86bb-1871a22256c3.png)

How to tell vector layer that this is a nonselectable element with static style feature.

**Comment by ghettovoice** [comment]
Hi @mustafahamid ,
the layer isn't responsible for feature selection. I suppose you are using `vl-interaction-select` for that. So `vl-interaction-select` has `filter` property, it can be used to filter out some features before selection occurs.
Take a look here https://github.com/ghettovoice/vuelayers/blob/v0.11.x/src/component/select-interaction/interaction.vue#L31

```html
<template>
  <vl-map>
     <vl-interaction-select :filter="selectionFilter" />
  </vl-map>
</template>

<script>
  export default {
    methods: {
      /**
       * @param {ol/Feature} feature
       * @param {ol/Layer} layer
       * @return {bool}
       */
      selectionFilter (feature, layer) {
         let featureId = feature.getId()
         let layerId = layer.get('id')
         ....
      },
    },
  }
</script>
```

**Comment by mustafahamid** [comment]
@ghettovoice thank you.
