### ISSUE TITLE
How to interact with WMS layer served by GeoServer?

### ISSUE THREAD

**Issue by boussadjra** [ghettovoice/vuelayers#171]
I have the following code : 

       <component v-for="layer in layers" :ref="layer.id" overlay :is="layer.cmp" v-if="layer.visible" 
       :key="layer.id" v-bind="layer">
            <component :is="layer.source.cmp" v-bind="layer.source">
            </component>
        </component>

and 

          layers: [
               
                {
                    id: 'sections',
                    title: 'Sections',
                    cmp: 'vl-layer-tile',
                    visible: true,

                    source: {
                        cmp: 'vl-source-wms',
                        url: 'http://localhost:8080/geoserver/sager/wms',
                        layers: 'sections',
                        tiled: true,
                        format: 'image/png',
                        serverType: 'geoserver',
                    },
                },
         ....
        ]

i would like when i click on the layer which is of LINE type I get the layer properties, how can I do that ?

**Comment by ghettovoice** [comment]
Hello @boussadjra ,
you should listen click event on the `vl-map` component for this. This type of event provides click pixel. then in the handler you can filter out layer at the pixel.

i have prepared an example for use case https://jsfiddle.net/ghettovoice/g8hpxc04/36/

**Comment by Guito** [comment]
@ghettovoice Is it possible to identify features on a WMS service? I have tried the method getFeaturesAtPixel, but it returns null. It seems it invokes an empty method on Layer.js

**Comment by ghettovoice** [comment]
Hello @Guito ,
WMS/WMTST and other raster layers don't support feature related methods, because on the client there is no features, only raster data. But WMS service usually provide `getFeatureInfo` request, that you can use to find all features at some pixel

**Comment by boussadjra** [comment]
I tried the answer given to my [question](https://stackoverflow.com/questions/56318151/how-do-i-interact-with-wms-tile-layer-served-by-geoserver-using-vuelayers) on stackoverflow but no luck

**Comment by Guito** [comment]
hello @boussadjra 
To avoid the SecurityError: Failed to execute 'getImageData' on 'CanvasRenderingContext2D you just need to put this inside the source:

`crossOrigin: 'anonymous'`

@ghettovoice Ok, that's what I thought I needed to do. I will call the service with the coordinates (which I obtain from the pixel)

**Comment by ghettovoice** [comment]
@Guito  Exactly. 
The main thing is to correctly form a request, to help with this OpenLayers WMS source has a helper method https://openlayers.org/en/latest/apidoc/module-ol_source_TileWMS-TileWMS.html#getGetFeatureInfoUrl
You can use it with VueLayers through `this.$refs.youWmsSource.$source. getGetFeatureInfoUrl(...)` reference, if you add `ref="youWmsSource"` to the `vl-source-wms` tag.

**Comment by Guito** [comment]
That's great! thanks for the info :-)

**Comment by Guito** [comment]
I was testing this with version 0.11.4 with the non default projection and it was not working correctly. After using @next it works. It seems you have solved a problem with the projection of the map in a commit (basically the map was using a default View which used a default projection and it was never updated)

=)
