### ISSUE TITLE
Simple way to show polygons as icons when zoomed out?

### ISSUE THREAD

**Issue by avpavp** [ghettovoice/vuelayers#172]
I would like to show polygons as icons when the user has zoomed out far enough such that the polygons are too small.  This seems like it might be something provided by OpenLayers/VueLayers but I couldn't find anything.

Is there such a thing?

Or any hints on a simple way to handle this scenario?

**Comment by ghettovoice** [comment]
Hi @avpavp !
I usually make this through style function. With vuelayers you can use `vl-style-func` component for this.
From the style function you should return array of openlayers styles `ol/style/Style`. 
Check the documentation about styles here https://openlayers.org/en/latest/apidoc/module-ol_style_Style.html. You can set `geometry` option for the style, `geometry` from the style overrides rendered geometry on the map.

Something like this should work for you
```html
<template>
   <vl-map ...>
    <vl-layer-vector>
     <vl-source-vector ... />
     <vl-style-func :factory="styleFuncFactory" />
   </vl-layer-vector>
  </vl-map>
</template>

<script>
import Style from 'ol/style/Style'
import { findPointOnSurface, createPointGeom } from 'vuelayers/lib/ol-ext'

export default {
  ...
  methods: {
    styleFuncFactory () {
      const baseStyle = new Style({ ...  })
     const polygonAsIconStyle = new Style({
       ....
       geometry: feature => {
         // here I use vuelayers helper functions, but you can build any geometry with OpenLayers API
         return createPointGeom(findPointOnSurface(feature.getGeometry()))
       }
     })

      return (feature, resolution) => {
        /** @var {ol/Feature} feature */
        /** @var {number} resolution */

        if (resolution > 100000) { // replace with your resolution
          return [polygonAsIconStyle]
        }

        return [baseStyle]
      }
    },
  },
}
</script>
```

**Comment by avpavp** [comment]
Thanks for the input - as usual, you suggestions hit the nail on the head!

I have this working thanks to your help.

To help others in case anyone else finds this topic, the resolution parameter is in m/pixel, that combined with using getExtent on the geometry allowed me to get a basis for when to convert a polygon to an icon.

Thanks again!
