### ISSUE TITLE
Bug: when I draw polygon

### ISSUE THREAD

**Issue by mingtianyihou33** [ghettovoice/vuelayers#176]
![Uploading QQ20190619-220146@2x.png…]()
If I create two vuelayers component when I draw a polygon at one component but the other one showed the draw ？
Can you help me?, thank you!

**Comment by ghettovoice** [comment]
Hi @mingtianyihou33 ,
the link to the image is not working. 
Can you clarify what you want to implement? 
It would be very helpful if you add some code example here.
Thanks
