### ISSUE TITLE
Add to docs the module name of every component

### ISSUE THREAD

**Issue by categulario** [ghettovoice/vuelayers#178]
Hi @ghettovoice, I've been using this package for the last few months and I'm very happy with it. So happy that I'd like to contribute to the docs. I find myself trying to figure out the module name of the components and it turned out easier to just clone the project and browse the source, but I'd like to contribute and make the documentation better.

Looking at how it is organized today I see the following section:

![Captura de pantalla de 2019-06-19 20-52-53](https://user-images.githubusercontent.com/790756/59810636-45022000-92d4-11e9-8e77-cb6ea857f62f.png)

What I propose is to replace this with a section that would look like this:

![Captura de pantalla de 2019-06-19 20-53-00](https://user-images.githubusercontent.com/790756/59810657-5519ff80-92d4-11e9-8c39-afd9700ecdc9.png)

Which gives just the right answer to the question.

As simple as that. It would help me find the right module faster. If you agree or have a better idea I'm willing to make a pull-request adding at least that part of the docs to all of the components of this package including those that have no docs whatsoever at the moment.

**Comment by ghettovoice** [comment]
Hi @categulario ,
this would be great! Really very helpful
