### ISSUE TITLE
WMTS-source configuration from a GetCapabilities response

### ISSUE THREAD

**Issue by kremda** [ghettovoice/vuelayers#179]
Hello

I am using a TileLayer in the same way as in this example https://openlayers.org/en/latest/examples/wmts-layer-from-capabilities.html
and everything works, but I can't manage to get it to work in vuelayers.

code:
`<vl-layer-tile id="wmts">`
 `<vl-source-wmts :layerName="styleId" matrixSet="EPSG:3857" :url="url"></vl-source-wmts>`
 `</vl-layer-tile>`

layerName:
`cjd5uudve6jfe2tok41galwq0`

URL and also XML response:
https://api.mapbox.com/styles/v1/kucirektomas/cjd5uudve6jfe2tok41galwq0/wmts?access_token=pk.eyJ1Ijoia3VjaXJla3RvbWFzIiwiYSI6ImNqcnJ6a3g5ZTBmaXc0OXFzY2NjZ3BhdmkifQ.3tSWCx7WtjCetvuLCq7v-w

Am I doing something wrong or is it a bug? 
Thank you for any help

**Comment by ghettovoice** [comment]
Hello @kremda ,
you code snippet looks right. Can you check what values do you have in the `styleId` and `url` props?

**Comment by kremda** [comment]
Hello @ghettovoice 

`styleId = cjd5uudve6jfe2tok41galwq0`  
`url = https://api.mapbox.com/styles/v1/kucirektomas/cjd5uudve6jfe2tok41galwq0/wmts?access_token=pk.eyJ1Ijoia3VjaXJla3RvbWFzIiwiYSI6ImNqcnJ6a3g5ZTBmaXc0OXFzY2NjZ3BhdmkifQ.3tSWCx7WtjCetvuLCq7v-w`

If I switch parameters for the ones used in OpenLayers WMTS example (https://openlayers.org/en/latest/examples/wmts.html) everything works fine, so I guess the problem must be somewhere in the mapping of the URL. Maybe some missing properties? 

One thing I noticed is that `GetTile` from my URL works only with RESTful and not KVP as does the `GetTile` in the example.

Thank you

**Comment by ghettovoice** [comment]
I got it. Thank for clarification.

Current version of vuelayers doesn't support of url as function in the `vl-source-wmts`, only string template is supported. But with you use case there should be used openlayers extended url function that is built from Capabilities response. I'll try to include needed changes to the next version. For a while looks like you should go with manual source creating.

```html
<template>
  <vl-map>
    <vl-layer-tile id="wmts" ref="wmtsLayer" @mounted="onWmtsLayerMounted">
      <!-- source will be added manually from layer capabilities -->
    </vl-layer-tile>
  </vl-map>
</template>

<script>
  import WMTSCapabilities from 'ol/format/WMTSCapabilities'
  import WMTS, { optionsFromCapabilities } from 'ol/source/WMTS'

  export default {
    data () {
      return {
        zoom: 2,
        center: [0, 0],
        rotation: 0,
        wmtsOptions: null,
        styleId: 'cjd5uudve6jfe2tok41galwq0',
        mapboxToken: 'pk.eyJ1Ijoia3VjaXJla3RvbWFzIiwiYSI6ImNqcnJ6a3g5ZTBmaXc0OXFzY2NjZ3BhdmkifQ.3tSWCx7WtjCetvuLCq7v-w',
      }
    },
    computed: {
      wmtsCapabilitiesUrl () {
        return `https://api.mapbox.com/styles/v1/kucirektomas/${this.styleId}/wmts?access_token=${this.mapboxToken}`
      },
    },
    mounted () {
      const parser = new WMTSCapabilities()
      fetch(this.wmtsCapabilitiesUrl)
        .then(response => response.text())
        .then(text => {
          const options = optionsFromCapabilities(
            parser.read(text),
            {
              layer: this.styleId,
              matrixSet: 'EPSG:3857'
            }
          )
          this.wmtsOptions = options

          return options
        })
    },
    methods: {
      onWmtsLayerMounted (layer) {
        layer.$layer.setSource(new WMTS(this.wmtsOptions))
      },
    },
  }
</script>
```

There is exists another workaround for mapbox, it is more easy than described above. Looks like mapbox provides WMTS services as just a wrapper for simple XYZ tiled layers. So I think you can just use XYZ source here (https://stackoverflow.com/a/53566709)

**Comment by kremda** [comment]
Works great, thank you for help.
