### ISSUE TITLE
in vl-source-xyz  the tileUrlFunction can not be called

### ISSUE THREAD

**Issue by kmx2** [ghettovoice/vuelayers#18]
according to the openlayers documents, in ol.source.xyz,, if url is not available, the tileUrlFunction will be called, but in vl-source-xyz, the url option must be set.

**Comment by ghettovoice** [comment]
Hi! You are right, there is no support of custom tile url function, I plan to add it to the next release.
Now you can implement your own XYZ source component based on mixin [xyz-source](https://github.com/ghettovoice/vuelayers/blob/master/src/core/mixins/xyz-source.js).
[An example](https://jsfiddle.net/ghettovoice/p9on13mf/13/)

**Comment by kmx2** [comment]
thanks for you response, i'm try

**Comment by ghettovoice** [comment]
Close this, if have a questions, please, re-open
