### ISSUE TITLE
can one Feature have multiple geometries?

### ISSUE THREAD

**Issue by avpavp** [ghettovoice/vuelayers#181]
I have some feature data that has one Point Geometry per feature.  When I display this data, I would like to have a square (centered on the point), with an arrow inside the square, pointed in a direction specified by the feature attributes.  I could handle this by modifying the geometry of the orig feature from point to polygon, and creating a 2nd feature with a line geometry for the arrow.

It seems to me it would be better if I could have 2 geometries associated with the one feature - this seems it may be possible based on some OpenLayers research...  ?

Can you please advise if this should be possible with VueLayers?  Or if there is a better approach that you would suggest?

Thanks!

**Comment by ghettovoice** [comment]
Hello @avpavp ,
I think you should make custom style function. It allows you to make dynamic styles using any attribute from features, and override actual feature geometry.
There is a similar example https://jsfiddle.net/ghettovoice/wafq536x/. Look at the `verticiesStyle` where `geometry` option is used to override feature geometry at the render time. From the style function you should return an array of styles, this array is something like layers in the photoshop.
You can define first style with square geometry with center at the feature point and second style with line geometry (or maybe there simple icon would be easy).
