### ISSUE TITLE
Unknown custom element vl.geom-point

### ISSUE THREAD

**Issue by bluelemonade** [ghettovoice/vuelayers#182]
hi,

I tried to use a few point over the osm map. I used the code from the documentation in an vuejs/cli setup.

i got "[Vue warn]: Unknown custom element: <vl-geom-point> - did you register the component correctly? For recursive components, make sure to provide the "name" option."

```
<vl-feature id="point" :properties="{prop: 'value', prop2: 'value'}">
          <vl-geom-point :coordinates="[0,0]"></vl-geom-point>
      </vl-feature>
```

**Comment by bluelemonade** [comment]
ok, I did now a complete import VueLayers from 'vuelayers' and it works.

when I use 
```
import { Map, TileLayer, OsmSource, Geoloc, Feature, WmsSource } from 'vuelayers'
import 'vuelayers/lib/style.css' // needs css-loader
Vue.use(Map)
Vue.use(TileLayer)
Vue.use(OsmSource)
Vue.use(Geoloc)
Vue.use(WmsSource)
Vue.use(Feature)
```
I got the error. How should I use Feature?

**Comment by ghettovoice** [comment]
Hi @bluelemonade ,
what is the error text? 
You install code looks good, I don't see any errors with it.

**Comment by bluelemonade** [comment]
Unknown custom element vl.geom-point

**Comment by ghettovoice** [comment]
Looks like you have a typo somewhere in your template: instead of `vl.geom-point` the tag should be `vl-geom-point`

**Comment by bluelemonade** [comment]
sorry, in the console: [Vue warn]: Unknown custom element: <vl-geom-point> - did you register the component correctly? For recursive components, make sure to provide the "name" option.

**Comment by ghettovoice** [comment]
Can you dump here the template of component where this errors occurs?
