### ISSUE TITLE
Need an  example to calculate spherical lengths and areas for geometries

### ISSUE THREAD

**Issue by mustafahamid** [ghettovoice/vuelayers#183]
Hi, 
 I wonder if exist an example that can show how can we use vue layer to find the distance as shown here in open layer example
https://openlayers.org/en/latest/examples/measure.html

Thanks

**Comment by ghettovoice** [comment]
Hello @mustafahamid ,
currently I haven't such example. But I'll try to prepare something like this in coming days

**Comment by categulario** [comment]
@ghettovoice perhaps I can do that next in my documentation effort

**Comment by ghettovoice** [comment]
@categulario I think it will be a bit hackish to do this in the documentation.
I think that it would be more easy to implement as jsfiddle. 

As a future plan about documentation : add something like "How to" page where will be a list all interested issues with jsfiddle examples. I think this will be very helpful for others.

Do you have an account on the jsfiddle?

**Comment by Rih** [comment]
hello @ghettovoice thank you for your efforts in this repo!
I wonder if the issue can be done on the current version? Actually I need lengths & areas in irregular polygons or if is there a way to implement by myself with some guidelines ?. Regards

**Comment by categulario** [comment]
hi @Rih ,

I implemented measuring in one of my projects and it wasn't that difficult from the openlayers example and using `vl-interaction-draw`. Here I share the template part of the code:

```html
      <!-- draw line measures -->
      <vl-interaction-draw
        type="LineString"
        source="measures"
        :stop-click="true"
        :active="activeTool === 'measure:distance'"
        @drawstart="measureStart"
        @drawend="measureEnd"
      >
        <vl-style-box>
          <vl-style-stroke color="#20E02B" :line-dash="[10, 5]" :width="3"></vl-style-stroke>
          <vl-style-fill color="rgba(255,255,255,0.5)"></vl-style-fill>
        </vl-style-box>
      </vl-interaction-draw>

      <!-- draw area measures -->
      <vl-interaction-draw
        type="Polygon"
        source="measures"
        :stop-click="true"
        :active="activeTool === 'measure:area'"
        @drawstart="measureStart"
        @drawend="measureEnd"
      >
        <vl-style-box>
          <vl-style-stroke color="#20E02B" :line-dash="[10, 5]" :width="3"></vl-style-stroke>
          <vl-style-fill color="rgba(255, 255, 255, 0.5)"></vl-style-fill>
        </vl-style-box>
      </vl-interaction-draw>
```

**Comment by Rih** [comment]
thank you @categulario !

**Comment by ghansham** [comment]
A few doubts here..
How to apply getLength and getArea on the geometry on evt.feature.getGeometry(). Is it the same LineString (distance) or Polygon (area).
If we check instanceof LineString or Polygon on evt.feature.getGeometry(), it returns false. In the original example of openlayers, it checks before calculating length or area in the respective cases.
And even if we pass those values, for the projection 'EPSG:4326', we have to multiply the value returned by getLength with proj,metersperunit_. And for area, we have to multiply by square of that. I have not checked other projections. This is very wiered. Can someone see this? Or am I doing it in a wrong way?

Regards
Ghansham

**Comment by ghettovoice** [comment]
> If we check instanceof LineString or Polygon on evt.feature.getGeometry(), it returns false. In the original example of openlayers, it checks before calculating length or area in the respective cases.

@ghansham  I guess you have problem with dependencies installed. You probably install manually incompatible version of the `ol` package. So you have a situation when vuelayers uses it's own local openlayers lib, in your code you use another openlayers lib. 
To fix this you need to drop `node_modules/vuelayers` and `node_modules/ol` directories, check you package.json file to fix `ol` package version, then re-install dependencies with `npm install`.
`vuelayers@0.11.x` works with `ol@5.x`.
`vuelayers@0.12.x` (currently in RC state) works with `ol@6.x`.

> And even if we pass those values, for the projection 'EPSG:4326', we have to multiply the value returned by getLength with proj.metersperunit_. And for area, we have to multiply by square of that(proj.meterperunit_). I have not checked other projections. This is very wiered. Can someone see this? Or am I doing it in a wrong way?

Do you use `EPSG:4326` in `vl-view` `projection` property or in `vl-map` `data-projection` property?

1. `<vl-map :data-projection="EPSG:4326">` switches all in/out vuelayers plain coordinates in to the EPSG:4326.
Map view internally still uses default EPSG:3857 projection to render the map. So any openlayers objects with coordinates (like ol/geom/Point, LineString and so on) still have EPSG:3857 projection.

2. `<vl-view :projection="EPSG:4326" />` switches map view to EPSG:4326 projection. In this case map will be rendered in this projection and all openlayers objects with coordinates will have EPSG:4326 coordinates too.
In this case, if you need to calc geometry length/ area, you need to transform geometry to mercator projection to get result in meters. `const a = feature.getGeometry().clone().transform('EPSG:4326', 'EPSG:3857').getArea()`

**Comment by ghansham** [comment]
Ok. I will give a try for re-installing the vuelayers. and let you know.

. Regarding projection,
I am setting the data-projection in vl-map and projection in vl-view to
'EPSG:4326'.

**Comment by ghettovoice** [comment]
`data-projection` by default is same as `vl-view` projection. So if they are same, you can omit `data-projection` definition.
And go with second point above.

**Comment by ghansham** [comment]
Ok I will try.

**Comment by ghansham** [comment]
Could follow your advice of reinstalling the vue layers.I could not find
0.12 branch of vue layers.
Kindly let me know.

**Comment by ghettovoice** [comment]
> I could not find 0.12 branch of vue layers.

It is currently in RC state. Install with `npm vuelayers@next`.

**Comment by ghansham** [comment]
I could. Thanks
