### ISSUE TITLE
deactive the zoom control / style zoom control

### ISSUE THREAD

**Issue by bluelemonade** [ghettovoice/vuelayers#189]
hi,

how can I deactivate the zoom buttons?

and on the other hand, how can I style it?

regards

**Comment by ghettovoice** [comment]
Hi @bluelemonade ,
the default set of controls can be configured through `controls` property of the `vl-map` component.
So to disable only zoom control you can pass an object like that: `{attribution: true, rotate: true, zoom: false}`. To disable all std controls pass `false`.

Usually all std openlayers controls support adding of the custom class name through `className` option. https://openlayers.org/en/latest/apidoc/module-ol_control_Zoom.html#~Options.
This can be used to customize style of your special controls

**Comment by bluelemonade** [comment]
hmmm, I added this to the scoped style section. nothing...

```
ol-touch ol-control button {
    font-size: 3.5em;
}

.ol-control button {
    display: block;
    margin: 5px;
    padding: 0;
    color: white;
    font-size: 2.14em;
    font-weight: bold;
    text-decoration: none;
    text-align: center;
    height: 2.375em;
    width: 3.375em;
    line-height: .4em;
    background-color: rgba(0, 0, 0, 0.5) !important;
    border: none;
    border-radius: 2px;
}
```

**Comment by ghettovoice** [comment]
Inside scoped styles you should use so called deep selector https://vue-loader.vuejs.org/guide/scoped-css.html#deep-selectors.
Or move global style to separate non-scoped `style` tag.

**Comment by bluelemonade** [comment]
ooh, I never used them, good to know. thank you
