### ISSUE TITLE
label decluttering

### ISSUE THREAD

**Issue by chitombo** [ghettovoice/vuelayers#190]
Good day, 
I have a layer upon which I am showing labelled points, using  `vl-style-func` with a factory function to create the style per point to label each point with their name following what had been recommended in #57 
Unfortunately, when zoomed out the labels appear very cluttered and not readable, so I tried following the [Vector Label Decluttering](https://openlayers.org/en/latest/examples/vector-label-decluttering.html) from OpenLayers example using the `textOverflow: true` within the factory function.

This did not work for me, and I cannot figure out how to declutter the labels.
I would appreciate any advice on how to achieve this?
Thank you in advance,

samples from my code as follows
`<vl-layer-vector>
        <vl-source-vector :features="movingPoints"></vl-source-vector>
        <vl-style-func :factory="pointStyleFunc"></vl-style-func>
      </vl-layer-vector>`

Points are an array of 
`{
            type: "Feature",
            id: uuid,
            geometry: {
              type: "Point",
              coordinates: [longitude, latitude]
            },
            properties: {
              name: name,
              status: status
            }
          }`

Style is 
`let style = createStyle({
          imageSrc: "/img/moving.png",
          imageScale: 0.9,
          imageAnchor: [0.5, 0.5],
          text: feature.get("name"),
          textOverflow: true,
          textFillColor: "#fff",
          textStrokeColor: "#000",
          textStrokeWidth: 2,
          textFont: "bold 13px sans-serif",
          textOffsetY: -16
        });`

**Comment by chitombo** [comment]
I think I figured out my issue. I needed to add `<vl-layer-vector :declutter="true">` this seems to have cleared up the clutter by removing nearby points until you zoom in further.
This should work for me.

**Comment by ghettovoice** [comment]
Hello @chitombo ,
sorry for the late response. I'm glad you find a solution.
Almost all options of `vl-layer-vector` are the same as `ol/layer/Vector`.
