### ISSUE TITLE
Circle draw does not correspond to real word scale.

### ISSUE THREAD

**Issue by dalexhd** [ghettovoice/vuelayers#192]
Your documentation example:
https://vuelayers.github.io/#/docs/component/circle-geom?id=usage

Good calculated radius:
https://www.mapdevelopers.com/draw-circle-tool.php?circles=%5B%5B300%2C43.3163855%2C-1.9424133%2C%22%23AAAAAA%22%2C%22%23000000%22%2C0.4%5D%2C%5B100%2C41.8902102%2C12.4922309%2C%22%23AAAAAA%22%2C%22%23000000%22%2C0.4%5D%5D
![Captura](https://user-images.githubusercontent.com/30388428/60798349-41deaf00-a171-11e9-90b5-70f3717269bb.PNG)

I'm having a problem while developing my circle dynamic locations filter. Depending on the radius,  I search nearest business locations. 

![Captura](https://user-images.githubusercontent.com/30388428/60797681-05f71a00-a170-11e9-838b-cc6397cf2930.PNG)

In this photo, the distance from "Fibrodyne" to the center according to google api is: 1540m.
So the problem comes with the circle radius, not with my code.

PD: Im using the same system as your example, with the global projection "EPSG:4326". For now I'm multiplying by 1.37597279904 to the radius... I know that this is an ugly fix xd...

**Comment by ghettovoice** [comment]
Hello @dalexhd ,
thanks for report!
It is already known issue with circular polygons drawing and resolved by the #160 .
But currently released only as v0.11.5-beta.3 while several other issues isn't resolved.
Can try your app with vuelayers  beta version? Install it with `npm i vuelayers@next`.
Thanks!

**Comment by dalexhd** [comment]
Okay... I will tell you later ^^

**Comment by dalexhd** [comment]
Im using "import { getDistance } from "ol/sphere";" getDistance function from that file. Is it a good choice to calculate the distance from 2 coordinates?

**Comment by ghettovoice** [comment]
Yep, this function, as I know, calculates distance using WGS84 ellipsoid

**Comment by dalexhd** [comment]
Okay, so this update does not solve my problem. Basically it seems to be a scalar problem. While the radio gets bigger, the error is bigger.

**Comment by ghettovoice** [comment]
Do you make calculation of the distance with points in the EPSG:4326 projection?
In any case there always be an error with re-projection calculations.

**Comment by dalexhd** [comment]
My map data-projection prop is "EPSG:4326".
I'm using same projections for all my map stuff. The problem comes on the circle, I'm sure xd. 
Maybe, the problem comes from OL and not from your lib...

**Comment by dalexhd** [comment]
Any news from here?

**Comment by ghettovoice** [comment]
Currently not yet

**Comment by ghettovoice** [comment]
From here https://github.com/openlayers/openlayers/blob/v5.3.0/src/ol/sphere.js#L84
looks like coordinates for `getDistance` should be in `EPSG:3857`.
Can you make measure of the distance and compare with you previous measures here https://openlayers.org/en/latest/examples/measure.html?

**Comment by Razz21** [comment]
this is old thread, but i struggled with same problem to draw 'real scale' circle. AFAIK ol.geom.Circle does not support real measures, but Polygon class does, this is how i resolved this issue with vuelayers
```vue
<template>
<vl-layer-vector>
  <vl-source-vector>
    <vl-feature >
      <vl-geom-polygon :coordinates="polygonCoord"/>
    </vl-feature >
  </vl-source-vector>
</vl-layer-vector>
</template>
<script>
import { circular } from "ol/geom/Polygon"
export default {
  data() {
    return{
      polygonCoord: undefined,
   }
},
  methods:{
  // longlat center, radius in meters, 64=number of vertices
    createCircle(center, radius) {
      const circleGeometry = circular(center, radius, 64);
      this.polygonCoord = circleGeometry.getCoordinates();
    },
  }
};
</script>
```
this solution does not create real cirlce, but circular polygon you can control with number of vertices. 
[source](https://openlayers.org/en/latest/apidoc/module-ol_geom_Polygon.html)

**Comment by Nikitoring** [comment]
I need to use circle in my project. My solution https://codesandbox.io/s/objective-rgb-xfqln?file=/src/components/Map.vue
