### ISSUE TITLE
How to check if an extent intersects wtih a polygon?

### ISSUE THREAD

**Issue by jerry1108** [ghettovoice/vuelayers#193]
hi, @ghettovoice: 
I have set @moveend="onMoveend" on my vl-map.
When I drag my map, the  'moveend' event is triggerd and I get the extent: [13479899.249175688, 2821023.1844068575, 13626658.343483226, 2892644.679910068] from the frameState of the event.
Does that mean it's the extent of  the view of current map?

If the anwser is yes then I want to check if this extent is intersecting with a certain polygon (vl-layer-vector)  or not.
Is there any method to achieve this goal?  Thank you.

ps: Here is my polygon format and data source comes from geojson file~
```
<vl-layer-vector v-for="(feature, index) in overlays.Districts.features"
  <vl-source-vector ref="vectorSource">                                
    <vl-feature :id="'district_'+ index" v-if="zoom < 13">
      <vl-geom-multi-polygon :coordinates="feature.geometry.coordinates"></vl-geom-multi-polygon>
	<vl-style-box>
	  <vl-style-stroke :color="setStrokeColor(feature.properties.TOWN_)" :width="1"></vl-style-stroke>
	    <vl-style-fill :color="feature.properties.color"></vl-style-fill>
	</vl-style-box>
    </vl-feature>
  </vl-source-vector>                                         
</vl-layer-vector>

**Comment by ghettovoice** [comment]
Hi @jerry1108,
as I know, openlayers and therefore vuelayers doesn't provide any special helpers for intersection calc.

But there is another great tool for spatial calculations http://turfjs.org/. 
It usually works with GeoJSON encoded features in the EPSG:4326 projection. So before using extent from `frameState` (that is in the EPSG:3857 projection) you should transform it to EPSG:4326 with openlayers projection helpers  https://openlayers.org/en/latest/apidoc/module-ol_proj.html#.transformExtent

**Comment by jerry1108** [comment]
> Hi @jerry1108,
> as I know, openlayers and therefore vuelayers doesn't provide any special helpers for intersection calc.
> 
> But there is another great tool for spatial calculations http://turfjs.org/.
> It usually works with GeoJSON encoded features in the EPSG:4326 projection. So before using extent from `frameState` (that is in the EPSG:3857 projection) you should transform it to EPSG:4326 with openlayers projection helpers https://openlayers.org/en/latest/apidoc/module-ol_proj.html#.transformExtent

Thank you for your help. I achieve the goal. :))
