### ISSUE TITLE
vl-interaction-select not working when moving the map

### ISSUE THREAD

**Issue by bluelemonade** [ghettovoice/vuelayers#198]
when I touch a point on a touchscreen its normal that also the maps moves 1-2 pixel. when this occurs theres no selection click on my icons. How can I bubble the event...

```
 <vl-interaction-select :features.sync="selectedFeatures">   
       <vl-style-func :factory="styleFuncFactory"></vl-style-func>
</vl-interaction-select>
```

**Comment by ghettovoice** [comment]
Hi @bluelemonade ,
I think `hit-tolerance` property should help you on touch devices. It defines radius in pixels that will be check around feature in the select matching callback.

**Comment by bluelemonade** [comment]
ok, what's the difference to move-tolerance?

**Comment by ghettovoice** [comment]
I guess you talking about property from `vl-map`. So it can help tune up map for touch devices too.
From the OpenLayers documentation

> The minimum distance in pixels the cursor must move to be detected as a map move event instead of a click. Increasing this value can make it easier to click on the map.

**Comment by bluelemonade** [comment]
yes, I tried it and the behaviour is better.
