### ISSUE TITLE
disable pinchrotate 

### ISSUE THREAD

**Issue by bluelemonade** [ghettovoice/vuelayers#199]
I tried to deactivate the pinchrotate 

I can read the collection, avter the map is created:
let interactions = this.$refs.map.$map.getInteractions()

but I'm too stupid to disable that, 

`I tried this.$refs.map.$map.removeInteraction("PinchRotate");`

or 

```
 this.$refs.map.$map.getInteractions().extend([
        new PinchRotate({
          active: false
      
        }),
      ])

```

**Comment by bluelemonade** [comment]
ok, I found a way to setup the interactions from a cleared interaction set

```
let interactions = this.$refs.map.$map.getInteractions()
 interactions.clear() 

      let dragZoom = new DragZoom()
      let dragPan = new DragPan()
      let pinchZoom = new PinchZoom()
      let mouseWheelZoom = new MouseWheelZoom()

      this.$refs.map.$map.getInteractions().extend([
        dragZoom, mouseWheelZoom, dragPan, pinchZoom
      ])
```

**Comment by ghettovoice** [comment]
Also take a look here https://openlayers.org/en/latest/apidoc/module-ol_interaction.html#.defaults.
This helper allows enable/disable and configure default set of interactions.

```js
this.$refs.map.$map.getInteractions().clear().extend(
  ol.interaction.defaults({
    pinchRotate: false,
    // other options can be left as default
  }).getArray()
)
```
