### ISSUE TITLE
import TextStyle Cannot read property 'install' of undefined

### ISSUE THREAD

**Issue by rienk-git** [ghettovoice/vuelayers#20]
Hi,
When importing TextStyle I get a Cannot read property 'install' of undefined error. Is this a bug or some mistake? Other imports don't throw an error.

**Comment by ghettovoice** [comment]
Hi!
Can you show how you import and install text style component?

**Comment by ghettovoice** [comment]
And what version of VueLayers you use?

**Comment by rienk-git** [comment]
Wow fast response!!
This works:
`
import Vue from 'vue'
  import { Map, TileLayer, OsmSource, Geoloc, Feature, PointGeom, VectorLayer, StrokeStyle, FillStyle, VectorSource, StyleBox, core as vlCore, Overlay, IconStyle, ClusterSource, CircleStyle, StyleFunc } from 'vuelayers'

  Vue.use(Map)
  Vue.use(TileLayer)
  Vue.use(OsmSource)
  Vue.use(Geoloc)
  Vue.use(Feature)
  Vue.use(PointGeom)
  Vue.use(VectorLayer)
  Vue.use(StrokeStyle)
  Vue.use(FillStyle)
  Vue.use(VectorSource)
  Vue.use(StyleBox)
  Vue.use(Overlay)
  Vue.use(IconStyle)
  Vue.use(ClusterSource)
  Vue.use(CircleStyle)
  Vue.use(StyleFunc)
`

This does not work (throws the mentioned error)
`
import Vue from 'vue'
  import { Map, TileLayer, OsmSource, Geoloc, Feature, PointGeom, VectorLayer, StrokeStyle, FillStyle, VectorSource, StyleBox, core as vlCore, Overlay, IconStyle, ClusterSource, CircleStyle, StyleFunc, TextStyle } from 'vuelayers'

  Vue.use(Map)
  Vue.use(TileLayer)
  Vue.use(OsmSource)
  Vue.use(Geoloc)
  Vue.use(Feature)
  Vue.use(PointGeom)
  Vue.use(VectorLayer)
  Vue.use(StrokeStyle)
  Vue.use(FillStyle)
  Vue.use(VectorSource)
  Vue.use(StyleBox)
  Vue.use(Overlay)
  Vue.use(IconStyle)
  Vue.use(ClusterSource)
  Vue.use(CircleStyle)
  Vue.use(StyleFunc)
  // the only one added
  Vue.use(TextStyle)
`

with error:

> vue-router.esm.js?fe87:1905 TypeError: Cannot read property 'install' of undefined
    at Function.Vue.use (vue.esm.js?efeb:4613)
    at eval (fleet.page.vue?fb65:105)
    at Object.1482 (2.js:29)
    at __webpack_require__ (app.js:708)
    at fn (app.js:113)
    at eval (fleet.page.vue?5fa1:1)
    at Object.1462 (2.js:7)
    at __webpack_require__ (app.js:708)
    at fn (app.js:113)
    at <anonymous>

It's a vue/vuex/vue-router/webpack app.

**Comment by ghettovoice** [comment]
You are right. I checked lib entry file for ES and saw that I forgot to add named export for this component. Currently you can use full lib install or add temporary separate import `import TextStyle from 'vuelayers/lib/text-style`.

**Comment by ghettovoice** [comment]
Thank you for you time!

**Comment by rienk-git** [comment]
Thanks mate!
