### ISSUE TITLE
How to get the bounding box of the map viewport

### ISSUE THREAD

**Issue by ROTGP** [ghettovoice/vuelayers#200]
Is there any way to get the bounding box (coord at top-left and coord at bottom-right, for example) of the map's current viewport? I tried tracking the extent, but with no luck.

**Comment by ghettovoice** [comment]
Hello @ROTGP ,
for now you can calculate current view extent only with the OpenLayers API https://openlayers.org/en/latest/apidoc/module-ol_View-View.html#calculateExtent

```html
<template>
  <vl-map ref="map" ....>
    <vl-view ref="mapView" @created="onMapViewCreated" ... />
  </vl-map>
</template>

<script>
export default {
  ...
  methods: {
    onMapViewCreated (vm) {
      vm.$view. calculateExtent(this.$refs.map.$map.getSize())
    },
  },
}
</script>
```

**Comment by ROTGP** [comment]
@ghettovoice Great - thanks!

It took a little bit more to get the coordinates I was looking for...

`import { getTopLeft, getBottomRight } from 'ol/extent.js';
import { toLonLat } from 'ol/proj.js'

....

let extent = this.$refs.view.$view.calculateExtent(this.$refs.map.$map.getSize())
this.topLeft = toLonLat(getTopLeft(extent))
this.bottomRight = toLonLat(getBottomRight(extent))`

**Comment by ghettovoice** [comment]
Yeh, sorry. I forgot to write you about this
