### ISSUE TITLE
Vuelayers fills my console

### ISSUE THREAD

**Issue by JoakimBrandt** [ghettovoice/vuelayers#201]
Hi,

First off, thanks for this amazing package. It's super powerful and looking great. Good job!

When vuelayers is active and the map is being built, the console in the browser is getting filled up with messages from vuelayers, like so:

[VueLayers] created vl-view
[VueLayers] mounted vl-map
[VueLayers] mounted vl-view
[VueLayers] created vl-interaction-select c55f8ea6-dc2d-4878-a0be-edb291ee7397
[VueLayers] vl-style-box

Is there a way to disable the logging? It's a minor issue, but it would be nice to silence the application.

**Comment by ghettovoice** [comment]
Hello @JoakimBrandt ,
in the current version it can't be disabled.
I agree with you, this would be very convenient to have possibility to disable them fully.
I'll append this to the next release.
Thanks!
