### ISSUE TITLE
Is it possible to replace a point marker with a number?

### ISSUE THREAD

**Issue by JoakimBrandt** [ghettovoice/vuelayers#202]
Hi!

As the title says, is it possible for me to give each geom-point object an attribute which is a number, which the point fetches and gives itself that number as a marker instead of a circle? Or even better, a number inside a circle?

**Comment by ghettovoice** [comment]
Hi @JoakimBrandt ,
sure, this is possible. Take a look at this example https://jsfiddle.net/ghettovoice/wxf43djb/
For any dynamic (feature attribute based) styling the best choice is so called style function

**Comment by JoakimBrandt** [comment]
Thanks for the fast reply!

I pretty much copied the example into my project, I get this error:

Uncaught TypeError: imageStyle.getImageState is not a function
    at renderFeature (vector.js?30d1:103)
    at CanvasVectorLayerRenderer.renderFeature$1 [as renderFeature] (VectorLayer.js?da2f:400)
    at CanvasVectorLayerRenderer.eval (VectorLayer.js?da2f:351)
    at CanvasVectorLayerRenderer.prepareFrame (VectorLayer.js?da2f:368)
    at CanvasMapRenderer.renderFrame (Map.js?8eca:157)
    at Map.renderFrame_ (PluggableMap.js?fe37:1226)
    at Map.eval (PluggableMap.js?fe37:189)

4 times over, I have 4 features I want to render. It happens when I enable the style factory.
<vl-style-func :factory="pointsStyleFunc" />

pointsStyleFunc () {
        return feature => {
          let baseStyle = new ol.style.Style({
            image: new ol.style.Circle({
              radius: 10,
              fill: new ol.style.Fill({
                color: '#fff',
              }),
              stroke: new ol.style.Stroke({
                color: '#F44336',
              }),
            }),
            text: new ol.style.Text({
              text: "yeet", // get feature property
            }),
          })
          return [
            baseStyle,
          ]
        }
      },

Any idea what the error could be? Or do you need to see more of my code in case?

**Comment by ghettovoice** [comment]
Do you use webpack building? If so you should slightly change my example for ES module system (in example there is UMD build  used).

Firstly you should import style classes from `ol` package.
```js
import Style from 'ol/style/Style'
import Fill from 'ol/style/Fill'
import Stroke from 'ol/style/Stroke'
import Text from 'ol/style/Text'
import Circle from 'ol/style/Circle'
```

Then you should remove `ol.style.` prefixes from style function code.
i.e `new ol.style.Style(...)` -> `new Style(...)`, `new ol.style.Circle(...)` -> `new Circle(...)` and so on

**Comment by JoakimBrandt** [comment]
Works like a charm. Thanks a bunch for the help!
