### ISSUE TITLE
is there any possible to set stacked icon (font awesome) in vl-style-icon

### ISSUE THREAD

**Issue by ylzbachata** [ghettovoice/vuelayers#203]
I created a customized stacked icon.
`   <span class="fa-layers fa-fw fa-2x">
      <i class="fas fa-map-marker"></i>
      <i class="fas fa-industry" data-fa-transform="shrink-10 up-2" :style="{ color: 'white' }"></i>
    </span>`
or 
`<font-awesome-layers class="fa-fw fa-2x">
      <font-awesome-icon icon="map-marker" />
      <font-awesome-icon icon="industry" transform="shrink-10 up-2" :style="{ color: 'white' }" />
    </font-awesome-layers>`

Now I want to put into Vl-style-icon 
What should I put into src...
` <vl-feature id="marker" ref="marker">
        <vl-geom-point :coordinates="[-10, -10]"></vl-geom-point>
        <vl-style-box>
          <vl-style-icon
            :src="'data:image/svg+xml;charset=utf-8,' + encodeURIComponent(svgComment)"
            :scale="0.5"
            :anchor="[0.1, 0.95]"
            :size="[128, 128]"
          ></vl-style-icon>
        </vl-style-box>
      </vl-feature>`

**Comment by ghettovoice** [comment]
Hi @ylzbachata ,
you should provide for `vl-style-icon` an image URI or data url. So you can try to encode svg into data url format and put it into `src` field .
Something like this https://jsfiddle.net/ghettovoice/m3j0zydr/ 
or this  https://jsfiddle.net/ghettovoice/rofL2085/ 
or this https://jsfiddle.net/ghettovoice/cpmstv7w/
should help you

**Comment by ylzbachata** [comment]
Hi @ghettovoice 
Thank you for replying.  I followed [https://jsfiddle.net/ghettovoice/cpmstv7w/ ](url) It works well. but I can't use SVG file from the local computer. but using [http://simpleicon.com/wp-content/uploads/rocket.svg](url) works well... 
It should look like that.
<img width="685" alt="Screenshot 2019-07-26 at 16 12 58" src="https://user-images.githubusercontent.com/44340236/61957770-4ce26d80-afc0-11e9-9adf-e44fa8b1570e.png">
now it looks like that
<img width="258" alt="Screenshot 2019-07-26 at 16 12 38" src="https://user-images.githubusercontent.com/44340236/61957775-5075f480-afc0-11e9-9eaf-75764d83ab82.png">

**Comment by ghettovoice** [comment]
> but I can't use SVG file from the local computer. but using http://simpleicon.com/wp-content/uploads/rocket.svg works well...

Icon source obviously should be available through an URI, or you can try some of webpack loaders that transforms images into data url on import.

Anyway looks like your image is big, you should scale it. For this you can use `scale` property of the `vl-style-icon`/`ol/style/Icon` component. It defines relative scale of the original image through value between `[0, 1]`

**Comment by ylzbachata** [comment]
Thanks again for answering... 
I scaled it to 0.1, but it doesn't show full image.
<img width="289" alt="Screenshot 2019-07-27 at 16 22 27" src="https://user-images.githubusercontent.com/44340236/61995586-c34ba200-b08a-11e9-8be4-3fec26e32cec.png">

**Comment by ghettovoice** [comment]
Try to play with options `size`, `imgSize` from here https://openlayers.org/en/latest/apidoc/module-ol_style_Icon-Icon.html.
Or write here the full source code how you define icon style

**Comment by ylzbachata** [comment]
I found the problem. https://stackoverflow.com/questions/46401143/openlayers-4-shows-only-1-4-of-svg-image
As soon as I set height and width in SVG file. then It works fine. otherwise no ...
I used two different ways to set Icon
`  <vl-layer-vector>
      <vl-source-vector :features.sync="features" />
      <vl-style-box>
        <vl-style-icon :src="iconsvg" :scale="0.1" :anchor="[0.5, 1]"/>
      </vl-style-box>
    </vl-layer-vector>
    
      <vl-feature id="marker" ref="marker">
        <vl-geom-point :coordinates="[-10, -10]"></vl-geom-point>
        <vl-style-box>
          <vl-style-icon
            :src="iconsvg" 
            :scale="1"
            :anchor="[0, 0.95]"
          ></vl-style-icon>
        </vl-style-box>
      </vl-feature>`
set Iconsvg and put into data:
`iconsvg:require("./industry.svg"),`
Svg file:
`<svg xmlns="http://www.w3.org/2000/svg" viewBox="0 0 512 512" ><path d="M475.115 163.723L336 252.251v-68.28c0-18.916-20.931-30.399-36.885-20.248L160 252.251V56c0-13.255-10.745-24-24-24H24C10.745 32 0 42.745 0 56v400c0 13.255 10.745 24 24 24h464c13.255 0 24-10.745 24-24V183.971c0-18.917-20.931-30.399-36.885-20.248zM464 432H48V80h64v215.971c0 18.916 20.931 30.399 36.885 20.248L288 227.691v68.28c0 18.915 20.931 30.399 36.885 20.248L464 227.691V432z"/></svg>`

**Comment by ylzbachata** [comment]
The first way is 
`      <vl-layer-vector>
      <vl-source-vector :features.sync="features" />
      <vl-style-box>
        <vl-style-icon :src="iconsvg" :scale="0.1" :anchor="[0.5, 1]"/>
      </vl-style-box>
    </vl-layer-vector>`

**Comment by ghettovoice** [comment]
I can only add that the second ways is preferred for layers which are consists of a lot of features .
It uses less memory and doesn't depend on slow DOM operations for each `vl-feature`.

**Comment by ylzbachata** [comment]
I see. Because I saw in demo https://vuelayers.github.io/#/docs/demo. That is why I used the first way. 
BTW do u know anyway to change height and width in vuelayer instead of manually changing the icon height and width in SVG file.

**Comment by ghettovoice** [comment]
You can try to load svg into the `img` tag or `Image` object, set it's width and height and then append it to the `ol/style/Icon` through `img` property.

**Comment by ylzbachata** [comment]
![Screenshot 2019-07-29 at 10 32 26](https://user-images.githubusercontent.com/44340236/62033600-9e6f4000-b1ec-11e9-889b-b2134b8b77e0.png)

each time it shows error above 

But I already gave proper attributes.
![Screenshot 2019-07-29 at 10 32 12](https://user-images.githubusercontent.com/44340236/62033646-af1fb600-b1ec-11e9-8a5b-8c421c64e153.png)

`<vl-style-icon :img="myImage" :imgSize="[100, 200]"/>`

myImage is in data 
`myImage: new Image(100, 200),`
also in create function, i set URL:
`this.myImage.src = iconsvg;`
Iconsvg is set in data
`iconsvg:require("./industry.svg")`

**Comment by ghettovoice** [comment]
In the current vuelayers version `vl-style-icon` doesn't support providing image through `img` property, only through `src`.  As workaround try to replace `vl-style-*` tree with `vl-style-func` and define styles through the function.
