### ISSUE TITLE
refresh layer or map

### ISSUE THREAD

**Issue by jmpmcmanus** [ghettovoice/vuelayers#205]
I'm trying to refresh a map after changing the layers url:

this.layers[1].source.url = 'http://localhost:8000/api/testdata_Model/?format=json&timestamp__gte=' + this.starttimestamp + '&timestamp__lte=' + this.endtimestamp

I'm accessing a Django Rest Framework backend and want to update the map based on a time range.

I've tried various ways of refreshing the layer, such as this.layers[1].refresh(), as well as the map this.$refs.map.refresh(). However in all cases .refresh() is not recognized as a function. How do you refresh a map in Vuelayers on Openlayers 5?

Thanks
Jim

**Comment by ghettovoice** [comment]
Hello @jmpmcmanus ,
current version of vuelayers doesn't support `url` changes in sources, especially in the vector sources. For now `vl-source-vector` listens only for `features` changes.

If you need implement something like switching layers use case, I suggest just to make 2 layers for this, each with its own source. And then toggle them `visibility` property to show/hide the layer.

**Comment by jmpmcmanus** [comment]
I ended up getting a clue from this previous discussion:

https://github.com/openlayers/openlayers/issues/2683

but I used Axios to get the data:

                // the that is used to deal with this scope
                var that = this
                axios.get(url)
                  .then(function (response) {
                    that.layers.source.url = url
                    that.$refs.layerSource.removeFeatures(features)
                    that.$refs.layerSource.addFeatures(response.data.features)
                  })
                  .catch(function (error) {
                    console.log(error)
                  })

Thanks!
