### ISSUE TITLE
How to use ol-ext with nuxt?

### ISSUE THREAD

**Issue by Guito** [ghettovoice/vuelayers#207]
I'm trying to use vuelayers in a nuxt application. I have created a plugin like this:

```
import Vue from 'vue'
import VueLayers from 'vuelayers'

Vue.use(VueLayers)
```

Now, I want to use the strategy for loadingBBox
```
loadingStrategyFactory () {
        // VueLayers.olExt available only in UMD build
        // in ES build it should be imported explicitly from 'vuelayers/lib/ol-ext' 
        return loadingBBox
      },
```

But when I do this:
```
<script>
    import {loadingBBox} from 'vuelayers/lib/ol-ext'

    export default {
```
I get an error: 
Unexpected token export.

What's the correct way?

**Comment by ghettovoice** [comment]
Hi @Guito ,
looks like you should setup you webpack config to also include `vuelayers/lib/...` files to be included into the babel loader, so to correctly transform `import`/`export` expressions.
VueLayers modules from `vuelayers/lib/...` directory compiled as ES2015 modules .

**Comment by Guito** [comment]
hi @ghettovoice 

I'm a bit new to this, could you please explain a bit further how to do it? I have tried with transpile:
```
build: {
        transpile: ['vuelayers'],
}
```
But I get the same error

**Comment by ghettovoice** [comment]
You can dump here your config files from nuxt.config.js.
Maybe I can help you. Bu t I'm not so familiar  with nuxt too 😄

**Comment by Guito** [comment]
I'll create a project tonight and I will share it here :-)

**Comment by Guito** [comment]
Hello again @ghettovoice 

I created the project: https://github.com/Guito/vuelayers-nuxt-example

In /pages/index.vue you can see the commented out `import {loadingBBox} from 'vuelayers/lib/ol-ext'`

in nuxt.config.js you can see the transpile.

Also, what's the way to re-render the layer-vector? (I am changing it with the button)

**Comment by ghettovoice** [comment]
Hello @Guito !
Looks like you have made setup according to documentation. 
I re-checked it too and can't figure out why `nuxt` doesn't respect `build.transpile` option.  It seems that it tries to build server side without transpiling of ES6 modules.
The only working setup I got when change `mode` option to the `spa` https://github.com/Guito/vuelayers-nuxt-example/blob/master/nuxt.config.js#L2.

**Comment by Guito** [comment]
Hello @ghettovoice 

Thank you for your help! I made some changes and now it seems to work. However, I'm not sure what loadingBBox should be doing (I'm also a bit new to maps :-D)

You can check the changes here: https://github.com/Guito/vuelayers-nuxt-example/commit/273fd24781b06da30c27c4553bf3a77dcbb28d63

Regards,
Guito

**Comment by ghettovoice** [comment]
> You can check the changes here: Guito/vuelayers-nuxt-example@273fd24

Nice solution! I haven't think about this

As for loadingBBox, this is one of supported loading strategy when you use vector layer with url or custom xhr loader. By default vector source loads all features from the remote source - so called `all` loading strategy. If remote source supports filtering features by current map view bounding box then you can use `bbox` loading strategy, then source will load features only for visible part of the map.

**Comment by Guito** [comment]
Ahh! ok, so to test it I have to zoom and center in a place where not all the features are shown, correct?

**Comment by ghettovoice** [comment]
Yes, you are right. 
In that case you see you load only part of the layer. Then when you move the map, this will trigger new load with the new view bbox  and etc.

**Comment by niklashaa** [comment]
My solution to using ol-ext was to use `require` in the method where I needed it:
```
    styleFuncFactory() {
      var olStyle = require("vuelayers/lib/ol-ext/style.js");
      return function __styleFuncFactory(feature) {
        const size = feature.getProperties().size;
        return [
          olStyle.createStyle({
            imageRadius: size,
            strokeWidth: 1.25,
            strokeColor: "#3399cc",
            fillColor: [255, 255, 255, 0.4],
          }),
        ];
      };
    },
```
Don`t know if this is best practice or not but it works.
