### ISSUE TITLE
Error Uncaught (in promise) TypeError: this._olObject[VM_PROP].includes is not a function

### ISSUE THREAD

**Issue by TiepHoangDev** [ghettovoice/vuelayers#209]
- I built the application using js and encountered an error with `<vl-interaction-modify>`
- Expect my points to be displayed and can edit location, update colors, text according to changes of data.
Because the knowledge of openlayer and vuejs is still poor, please support me.
Thank you!
and this my code: [http://ideone.com/Os9K9S](http://ideone.com/Os9K9S)

> index.umd.js:8690 Uncaught (in promise) TypeError: this._olObject[VM_PROP].includes is not a function
    at VueComponent._callee$ (index.umd.js:8690)
    at tryCatch (index.umd.js:1058)
    at Generator.invoke [as _invoke] (index.umd.js:1284)
    at Generator.prototype.<computed> [as next] (index.umd.js:1110)
    at asyncGeneratorStep (index.umd.js:7897)
    at _next (index.umd.js:7919)

**i debug**
![image](https://user-images.githubusercontent.com/30700664/62837577-3bc17e00-bc9b-11e9-8472-23fa09ccd660.png)
**I noticed that `this._olObject [VM_PROP]` returns an array but only this returns funtion, and this causes an error!**

**Comment by ghettovoice** [comment]
Hello @TiepHoangDev ,
which vuelayers version do you use?

**Comment by TiepHoangDev** [comment]
**Thanks for replay!**
Sorry because the link source code does not show enough links.
All css links or js I get from your tutorial page [https://vuelayers.github.io/#/docs/quickstart](https://vuelayers.github.io/#/docs/quickstart) and it @version 0.11.4
my source code: [https://pastecode.xyz/view/2c898189](https://pastecode.xyz/view/2c898189)

**Comment by TiepHoangDev** [comment]
i try change version js from https://unpkg.com/vuelayers/lib/index.umd.js to
1. https://unpkg.com/vuelayers@0.11.5-beta.1/lib/index.umd.js
2. https://unpkg.com/vuelayers@0.12.0-alpha.1/lib/index.umd.js

but not work, and have same error!

**Comment by ghettovoice** [comment]
v0.11.4 is ok, this is the latest stable version for now.
I have reproduced your source in the jsfiddle with exactly the same vuelayers files https://jsfiddle.net/ghettovoice/mcno0976/. You check that here you can draw new points and then drag them (i.e. modify)
And I don't see any errors with `vl-interaction-modify`.

What browser do you use?

**Comment by TiepHoangDev** [comment]
_**thanks you help me!**_
I found the error. it is **version of ol.js**
My source use: https://unpkg.com/openlayers/dist/ol.js (Version: v4.6.5) (this link i copy from https://vuelayers.github.io/#/docs/quickstart)!
and need change to: https://cdn.jsdelivr.net/gh/openlayers/openlayers.github.io/en/v5.3.0/build/ol.js (v5.3.0)
and to reproduct the error, this is my source: https://jsfiddle.net/pvw3f0uo/3/. 
(use browser chrome )
`Mozilla/5.0 (Windows NT 10.0; Win64; x64) AppleWebKit/537.36 (KHTML, like Gecko) Chrome/76.0.3809.100 Safari/537.36`

_And I have a question_
Data of `features.properties` always has a change in value, is there any way to update the change to `<vl-style-box> <vl-style-text>` without using `<vl-feature>`?

**One again, thanks for your help and great project!!!**

**Comment by ghettovoice** [comment]
> My source use: https://unpkg.com/openlayers/dist/ol.js (Version: v4.6.5) (this link i copy from https://vuelayers.github.io/#/docs/quickstart)!

Sorry, this is my fault. I forget to update link here :man_facepalming:

> And I have a question
Data of features.properties always has a change in value, is there any way to update the change to <vl-style-box> <vl-style-text> without using <vl-feature>?

A better way is drop `vl-feature` components and use `:features="featuresArray"` on the `vl-source-vector`. As for styling, the most efficient way is to use style function. Look at the another 
example https://jsfiddle.net/ghettovoice/wxf43djb/

**Comment by TiepHoangDev** [comment]
Ok. i got it! Thanks you very much!
why you don't use `scope` to binding style for `vl-style-box`. I hope that :))
