### ISSUE TITLE
weird erro

### ISSUE THREAD

**Issue by sirb0rab0g1** [ghettovoice/vuelayers#21]
Uncaught TypeError: __WEBPACK_IMPORTED_MODULE_0_ol_source_osm__.a.ATTRIBUTION.getHTML is not a function

i dont know why i am getting this. i just follow the installation in npm but after this error prompts

**Comment by ghettovoice** [comment]
Hi, 
as I see from the latest release of OpenLayers, `ol.Attribution` was deprecated.
I will fix this soon.
Thank you!

**Comment by ghettovoice** [comment]
The new release v0.7.4 fixes this. Please try
