### ISSUE TITLE
Translate interaction

### ISSUE THREAD

**Issue by ghettovoice** [ghettovoice/vuelayers#210]
Implement wrapper component for https://openlayers.org/en/latest/apidoc/module-ol_interaction_Translate-Translate.html

**Comment by keeganwitt** [comment]
FYI, there is an implementation of this here: https://github.com/Cytomine-ULiege/cytomine-frontend/tree/master/src/apps/explorer/translate-interaction

**Comment by ghettovoice** [comment]
Thanks you for info!
