### ISSUE TITLE
Rotate interaction

### ISSUE THREAD

**Issue by ghettovoice** [ghettovoice/vuelayers#211]
Integrate rotate interaction https://github.com/ghettovoice/ol-rotate-feature

**Comment by keeganwitt** [comment]
I haven't looked to see what the differences are with your branch, but FYI there is an existing implementation of this: https://github.com/Cytomine-ULiege/cytomine-frontend/tree/master/src/apps/explorer/rotate-interaction

**Comment by ghettovoice** [comment]
Wow! This implementation is almost what I plan to add to the vuelayers. 
Thanks for info 👍
