### ISSUE TITLE
Modify Interaction with Style not work

### ISSUE THREAD

**Issue by dd-han** [ghettovoice/vuelayers#217]
Hi

I tried to change point style on modifiable vector object when cursor snap. And I have been successful on OpenLayers like sample below:
https://jsfiddle.net/dd_han/jh5x73dt/

According to some similar component [Issue discussion](https://github.com/ghettovoice/vuelayers/issues/106#issuecomment-439860854) and Demo code, I write them in VueLayers but not works:
https://jsfiddle.net/dd_han/0pvmuzow/

Maybe I wrote something wrong or this not implement ?

**Comment by ghettovoice** [comment]
Hello @dd-han ,
thanks for response!
Your example looks good and right. 
Obviously there is some bug with interaction component.

**Comment by dd-han** [comment]
Thanks. It works.
