### ISSUE TITLE
Doc about nuxtjs

### ISSUE THREAD

**Issue by RemiDesgrange** [ghettovoice/vuelayers#218]
Since #136 have a great response on how to setup vuelayers with nuxtjs. Can put this somewhere in the doc ? I can put up a PR if you want, can you points where this should take place.

Thanks

**Comment by ghettovoice** [comment]
Hello @RemiDesgrange,
if you have a lot of information about this, I think, I can add a new page here https://github.com/ghettovoice/vuelayers/tree/master/docs. It will be shown under left menu.
Or you can just add a new section to the [quickstart.md](https://github.com/ghettovoice/vuelayers/blob/master/docs/quickstart.md) page.
Thanks in advance!

**Comment by RemiDesgrange** [comment]
closing since #221 is merged
