### ISSUE TITLE
.d.ts files

### ISSUE THREAD

**Issue by frankhommers** [ghettovoice/vuelayers#219]
Hi,

I have read https://github.com/ghettovoice/vuelayers/issues/194 and that's great to hear that you'll be moving to TypeScript someday.

But would be an idea to supply this component with .d.ts files in advance (i.e. before you fully convert to typescript)?

Thx!

**Comment by ghettovoice** [comment]
Hello @frankhommers ,
it would be nice addition for current version. 
But I can't say when I have time for this right now.
If you can make this, you are welcome for pull request

**Comment by frankhommers** [comment]
Thanks! I have to investigate this. I am pretty new to vue and typescript so I am not sure if I am able to do this ;-)
