### ISSUE TITLE
Instructions to run demo

### ISSUE THREAD

**Issue by ludoo0d0a** [ghettovoice/vuelayers#22]
It would be great if we could get information to run easily a simple boilerplate (like vue-cli + webpack + vuelayers only).
the whole setup of webpack is not easy to understand; Thanks !

**Comment by ghettovoice** [comment]
Hi! 
I think about this, may be a fork of [vue-webpack template](https://github.com/vuejs-templates/webpack) with simple demo app.

**Comment by ghettovoice** [comment]
I had added demo repository https://github.com/ghettovoice/vuelayers-demo for easy start with vuelayers.
vue-cli template will come later.
If you have questions about demo, then re-open this issue

**Comment by ludoo0d0a** [comment]
Great. it works well with yarn too :)

The sample is huge. I have stuff to work on it !!
