### ISSUE TITLE
Multiple vl-interaction-selection

### ISSUE THREAD

**Issue by RemiDesgrange** [ghettovoice/vuelayers#222]
I would like to use two `vl-interaction-select` component. Api is not documented, but I looked at props [in the source file](https://github.com/ghettovoice/vuelayers/blob/master/src/component/select-interaction/interaction.vue)

it seems that we can filter the layer used with select interaction. I tried this with no luck :

```vue
<template>
  <vl-map
    id="map"
    ref="map"
    :load-tiles-while-animating="true"
    :load-tiles-while-interacting="true"
    data-projection="EPSG:4326"
  >
 <vl-view
      :zoom.sync="zoom"
      :center.sync="center"
      :rotation.sync="rotation"
    ></vl-view>
    <vl-layer-tile id="baseLayer">
      <vl-source-osm />
    </vl-layer-tile>

    <vl-layer-vector render-mode="image">
      <vl-source-vector :url="test1" ref="test1Layer">
      </vl-source-vector>
    </vl-layer-vector>
    <vl-interaction-select :features.sync="selectedtest1Feature" :layers="test1"/>
    <vl-overlay
      v-for="feature in selectedTest1Feature"
      :key="feature.properties.id"
      :id="'popup-' + feature.properties.id"
      :position="findPointOnSurface(feature)"
    >
      <div>
        propr test1 {{ feature.properties.name }}
      </div>
    </vl-overlay>

    <vl-layer-vector render-mode="image">
      <vl-source-vector :url="test2" ref="test2Layer">
      </vl-source-vector>
    </vl-layer-vector>
    <vl-interaction-select :features.sync="selectedtest2Feature" :layers="test2"/>
    <vl-overlay
      v-for="feature in selectedTest2Feature"
      :key="feature.properties.id"
      :id="'popup-' + feature.properties.id"
      :position="findPointOnSurface(feature)"
    >
      <div>
        propr test2 {{ feature.properties.name }}
      </div>
    </vl-overlay>

 </vl-map>
</template>

<script>
export default {
  data() {
    return {
      zoom: 5,
      center: [3.845, 45.506],
      rotation: 0,
      test1: "",
      test2: "",
      selectedTest1Feature: null,
      selectedTest2Feature: null,
      test1Layer: [],
      test2Layer: []
    }
  },
  method() {
    findPointOnSurface(feature) {
      const point = turf.pointOnFeature(feature)
      return point.geometry.coordinates
    }
  },
  mounted() {
    this.test1Layer.push(this.$refs.test1Layer)
    this.test2Layer.push(this.$refs.test2Layer)
  }
}
</script>
```

I cannot make it work with a filter function too.

**Comment by ghettovoice** [comment]
Hello @RemiDesgrange ,
which version do you use? 
The `layers` property available only in the beta version `v0.11.5-beta`.

Anyway multiple select interaction on the map is not the use case that is  supported by the OpenLayers and the therefore by the VueLayers. You can find discussion about this here https://github.com/openlayers/openlayers/issues/1988. You can find here some workarounds and than I can help translate them to the VueLayers. What is your use case?

As for `layers` filter, it's here for a bit another use case, skip selecting of some layers on the map.
Take a look here for example https://jsfiddle.net/ghettovoice/yh9fbcet/, where `points` layers is skipped from the select interaction, only polygons can be selected.

**Comment by RemiDesgrange** [comment]
I stumble upon this issue https://github.com/openlayers/openlayers/issues/1988. 

My use case is:
* I have a vector layer 1 (geojson), when I select one of the element of this layer, I'll mutate the store (and other component will do some work)
* I have a vector layer 2 (geojson), when I select one of the element of this layer, I want to show a overview (vl-overview component).

Maybe I'm using it wrongly ?

**Comment by ghettovoice** [comment]
Hmm, as one of solutions https://jsfiddle.net/ghettovoice/64d715ka/

**Comment by RemiDesgrange** [comment]
I'm not an expert in frontend dev, but watchers are expensive right ?

**Comment by RemiDesgrange** [comment]
> Hmm, as one of solutions https://jsfiddle.net/ghettovoice/64d715ka/.
> Also you can listen for `select`/`deselect` events instead of watchers on computed properties.

Ok dumb question: how am I supposed to listen to `select`/`deselect` I cannot found these event in openlayers doc :-/

**Comment by ghettovoice** [comment]
> Ok dumb question: how am I supposed to listen to select/deselect I cannot found these event in openlayers doc :-/

Just like any other event in the Vue. 
```
<vl-interaction-select @select="onSelect" @unselect="onUnselect">...</vl-interaction-select>

... 
// in component object
method: {
  onSelect (feature) {},
  onUnselect (feature) {},
},
```
Here you will get instance of the `ol/Feature` like with native OpenLayers.

> I'm not an expert in frontend dev, but watchers are expensive right ?

it depends on what they do. They triggers asynchronously, also you can debounce or throttle them (for example with lodash helpers). You can read about watchers here https://vuejs.org/v2/guide/computed.html#Watchers

**Comment by RemiDesgrange** [comment]
Ok thanks I'll try different approach and see what fits best with my use case.
