### ISSUE TITLE
Programmatic selection of a feature

### ISSUE THREAD

**Issue by panchofrank** [ghettovoice/vuelayers#224]
Hello,
I'm trying to select a feature when it matches a user search in a search box.  I've tried using the following method
`this.$refs.interaction.select(id)`
where interaction is the ref identifier of my vl-interaction-select and id is the id of the matching feature that I want selected.  
I can't get this to work and I was wondering if there is any working fiddle of this or example of code that does what I want?

Thanks!

**Comment by panchofrank** [comment]
This is what I've tried https://jsfiddle.net/Francoisgaudin/f2opaekt/ (forked from ghettovoice code)

**Comment by ghettovoice** [comment]
Hello @panchofrank ,
in your forked fiddle you forget remove `layers` filter from `vl-interaction-select` props.
Try to remove it and you see that selection of the point by its id now works.
Selection by GeoJSON object currently not implemented- this is missed feature that I'll add soon.
Thanks!

**Comment by panchofrank** [comment]
Yes it does, thank you!  I've also learned about the layers filter! :-)

**Comment by panchofrank** [comment]
Any idea why I can't get it to work in the demo app?

I've added ref="interaction" to the vl-interaction-select
I have a button which calls  this.$refs.interaction.select('marker')

**Comment by panchofrank** [comment]
So it's actually an issue in version 0.11.4 I think.
Here is the problem reproduced: https://jsfiddle.net/Francoisgaudin/f2opaekt/

(The original version of my jsfiddle used the latest beta version of beta layers)

**Comment by ghettovoice** [comment]
Yeh, v0.11.4 have an issue with `features` prop synchronization

**Comment by ghettovoice** [comment]
You can install beta version in your app with command: `npm install vuelayers@next`.
