### ISSUE TITLE
VectorSource: sync modifier doesn't work with features property in 0.11.5-beta.8

### ISSUE THREAD

**Issue by become-iron** [ghettovoice/vuelayers#225]
I expected the features being changed, because I used `sync` modifier and the vector layer was used as source of modify interaction. However, it doesn't work now. But it worked in 0.11.4, though. 
Example: https://jsfiddle.net/hjd94238/

**Comment by ghettovoice** [comment]
Hello @become-iron ,
thanks for response! 
I'll check this
