### ISSUE TITLE
How do I select a feature in a cluster

### ISSUE THREAD

**Issue by panchofrank** [ghettovoice/vuelayers#226]
Hello,

I'm trying to programmatically select a feature that is in a cluster: https://jsfiddle.net/Francoisgaudin/2bxdjuwg/

When I select the feature by clicking on it we see that the feature appears in an array as a field in another feature.  I guess that other feature represents the cluster and it has a generated id.  When we enter that ID in the jsfiddle text box and attempt to select by pressing the button  nothing happens.  
Also I can't find the cluster features using a getFeatures call on the source of the layer. 
What am I doing wrong?

**Comment by panchofrank** [comment]
So I manage to do the selection with the following call:

this.$refs.interaction.select(this.$refs.clusterLayer.getSourceTarget().values_.source.getFeatures()[0])

Is there a more concise way to the feature?

**Comment by ghettovoice** [comment]
Hello @panchofrank ,
your fiddle is how it should work, but for now vl-source-cluster a bit buggy. 
I see 3 problems with it:
- id dynamically generated 2 times for same cluster, so you can't get correct id
- vl-source-cluster doesn't allow generate cluster properties by some user defined handler
- vl-source-cluster doesn't emit `update:features` event like vl-source-vector, so you can't listen for clustered features changes

I'll try to release patch as soon as possible.
Thanks for pointing me to this problems!

**Comment by alejandrosuarez231** [comment]
@ghettovoice Hi! How are you?  I am working on a map which I need to show the elements grouped by cluster, but I must also show the lines that join the points (LineString) only when the points are visible and not grouped

**Comment by ghettovoice** [comment]
Hi @alejandrosuarez231 ,
I don't actually know what you want to implement. 
But I think this very basic example should show you an idea to use dynamic linestrings layer 
https://jsfiddle.net/ghettovoice/qa8p913o/231/.
