### ISSUE TITLE
listen rendercomplete event cause infinite loop

### ISSUE THREAD

**Issue by Razz21** [ghettovoice/vuelayers#228]
Hi, question from beginner. I am trying to implement loading state indicator for map. I am using `rendercomplete` event to catch signal on start-stop map rendering. It works fine until I want to add some custom layer-vector components. This event executes then in infinite loop and I am not able to catch end signal.
I was trying to use build-in vl-map `precompose` and `postcompose` events but I am not sure how to indicate last signal.

```javascript
// catch render event
mounted() {
    this.$refs.map.$on("rendercomplete", evt => {
      this.mapLoading =!this.mapLoading //works fine without vector layer
    });
  },

//template
<vl-map
      data-projection="EPSG:4326"
      :load-tiles-while-animating="true"
      :load-tiles-while-interacting="true"
      ref="map"

    >
      <vl-view
        :min-zoom="min_zoom"
        :zoom.sync="zoom"
        :center.sync="center"
        :rotation.sync="rotation"
      ></vl-view>

      <!-- map layer -->
      <vl-layer-tile id="osm">
        <vl-source-osm></vl-source-osm>
      </vl-layer-tile>
      <!-- map layer -->

      <!-- PROBLEM HERE -->
      <vl-layer-vector ref="featuresLayer">
        <vl-source-vector>
          <vl-feature ref="points" v-for="place in places" :key="place.id" :properties="place">
            <vl-geom-point :coordinates="[place.geodata._long, place.geodata._lat]"></vl-geom-point>
            <vl-style-box style="position:sticky">
              <vl-style-icon :src="place.icon" :scale="0.7" :anchor="[0.1, 0.95]"></vl-style-icon>


```

**Comment by ghettovoice** [comment]
Hello @Razz21 ,
sorry for the late response.
I re-checked the OpenLayers documentation and issues related to this event and it look like
the description of the event is not correct. Here is some more info about it's behaviour https://github.com/openlayers/openlayers/issues/8822

As a workaround I can suggest you debounce event handlers for those events, so they fires only once at one view change. Here is an example where I implemented this with the help of rxjs lib.
https://jsfiddle.net/ghettovoice/kxa8su47/ 
Maybe this is not the best solution or should be tuned up more accurately, but anyway I hope it give you the basic idea
