### ISSUE TITLE
点线面图形和图片在一定范围比例尺显示问题

### ISSUE THREAD

**Issue by jzyzxx** [ghettovoice/vuelayers#229]
目前组件有没有一个比例尺范围属性,只在一定范围的比例尺范围内显示?是不是需要自己监听比例尺变化?

**Comment by ghettovoice** [comment]
Hello @jzyzxx ,
can you repeat description in english please? I don't understand your issue

**Comment by dd-han** [comment]
@jzyzxx 我知道目前大部份元件(組件)都可以參考 OpenLayers 的 API 文件，要讓 Feature 只在特定比例尺下顯示，目前我看 [OpenLayers API](https://openlayers.org/en/latest/apidoc/module-ol_Feature-Feature.html) 並沒有相關屬性。

for @ghettovoice can't understand Mandarin, this issue translate by my poor english:

Title: Can point, polyline, polygon, shape and image show on only certain zoom level ?
Content: Is current component has zoom level range attribute, only show in certain zoom level ? Listen zoom change is require or not.

Then I reply the component can reference to OpenLayers API document, and I can't find related attributes.

**Comment by ghettovoice** [comment]
@dd-han thanks for the help!

On the `vl-layer-*` components you can define `minResolution` / `maxResolution` interval at which this layer will be visible. 
From vuelayers docs: https://vuelayers.github.io/#/docs/component/vector-layer?id=min-resolution
From openlayers docs: https://openlayers.org/en/latest/apidoc/module-ol_layer_Vector.html

Resolution values for any zoom you can take just from Vue devtool console

**Comment by ghettovoice** [comment]
@dd-han can you translate back this please?

**Comment by dd-han** [comment]
@jzyzxx <https://github.com/jzyzxx>

作者表示在 vl-layer-* 元件(組建)上你可以定義 minResolution / maxResolution 範圍作為是否顯示這個
Layer 的條件。
Vuelayers 文件：
https://vuelayers.github.io/#/docs/component/vector-layer?id=min-resolution
Openlayers 文件：
https://openlayers.org/en/latest/apidoc/module-ol_layer_Vector.html

各層 Zoom 的 Resolution 的數值可以從 Vue 開發工具的 Console 中找到。


@ghettovoice <https://github.com/ghettovoice>

Thanks infomation, maybe I will need that in soon future.



Vladimir Vershinin <notifications@github.com> 於 2019年9月26日 週四 02:10 寫道：

**Comment by jzyzxx** [comment]
With your help, my problem has been solved.
