### ISSUE TITLE
StrokeDashOffset does not work

### ISSUE THREAD

**Issue by VlaDi4eKK** [ghettovoice/vuelayers#230]
There is no prefix for LineDashOffset in the source code of the library. The new documentation mentions this style, but there is no implementation.

In general, I need to implement the direction of the route. Those. put arrows on the line so that you can understand the direction. The Dash mechanism suits me, but you cannot make your own drawing there for repetition. How to implement such a task?

**Comment by ghettovoice** [comment]
Hello @VlaDi4eKK ,
I guess you talk about this style implementation in the lib https://github.com/ghettovoice/vuelayers/blob/master/src/ol-ext/style.js#L325.
So this is actually just a convenient wrapper around OpenLayers style objects.
While I fix this in this lib you can use OpenLayers styles directly.
Take a look here https://openlayers.org/en/latest/apidoc/module-ol_style_Style.html

**Comment by VlaDi4eKK** [comment]
Thanks for the answer! I decided to do it differently. Since you cannot use your symbol for use in StrokeDash (for example, ↓), you had to rewrite the algorithm differently and just add a new layer with arrows on top of the path.
