### ISSUE TITLE
Migrating to openlayers 6

### ISSUE THREAD

**Issue by RemiDesgrange** [ghettovoice/vuelayers#232]
Hi,

I can put up a PR to try migrating to openlayers 6. 

According to OL dev, there shouldn't have any issue migrating. For me OL6 fix the "problem" where I cannot use interact/Select on multiple layers, which imply to create your own logic for selection on *each* layer.

**Comment by ghettovoice** [comment]
Hello @RemiDesgrange ,
it would be great! 
I'll try to find time for this upgrade too during this and next week.
I already made separate branch for this some time ago, but for now it should be upgraded from master.
It would be nice to include upgrade to ol v6 with the next v0.11.5 version

**Comment by RemiDesgrange** [comment]
See #233

**Comment by ghettovoice** [comment]
It's finally complete, you can try new build based on ol v6.
Install with `npm install vuelayers@next`
