### ISSUE TITLE
problem upgrading to 0.11.5

### ISSUE THREAD

**Issue by categulario** [ghettovoice/vuelayers#236]
I just upgraded to `0.11.5` as per d2abce19bcd2727e5d2672d9496363f7f20b5885, but after doing so I get

![Captura de pantalla de 2019-10-03 11-57-50](https://user-images.githubusercontent.com/790756/66147890-59dd9780-e5d5-11e9-8bb4-7e5349ea1360.png)

when I do `npm run serve`.

Am I missing something?

Thanks!

**Comment by ghettovoice** [comment]
@categulario  Yeh, I see. Thanks for response.
I'll make new release
