### ISSUE TITLE
WMTSTileGrid overwritten with TileGrid by mixin in vl-source-wmts

### ISSUE THREAD

**Issue by janlazo** [ghettovoice/vuelayers#239]
https://github.com/ghettovoice/vuelayers/commit/35191098e888258f36a44c9f7287a5ea768812cd#diff-37f72dd1b6349af667843b098801ed57R103 causes the problem. Bug happens since 0.11.5. Tested on 0.11.7.

**Comment by ghettovoice** [comment]
@janlazo good catch! 
Thanks

**Comment by ghettovoice** [comment]
Upgrade please up to v0.11.9
