### ISSUE TITLE
Events start and end adding features?

### ISSUE THREAD

**Issue by VlaDi4eKK** [ghettovoice/vuelayers#240]
Hello! I am using vuelayers v0.11.8 and I have a problem. There is a layer of points on the map that are added through the features field. This layer is shown by the event of clicking the on / off button. About 1000 points are drawn in the layer. Obviously, the drawing has been going on for some time. I need to make an animation of the expectation of this picture. How can I track the process of adding points to the map? Are there events for such situations?

**Comment by ghettovoice** [comment]
Hello @VlaDi4eKK ,
VueLayers provides two events for vector layers: `add:feature`, `remove:feature`.
You can try to debounce or throttle `add:feature` event handler, and also you can count added features in it. 
Debounce and throttle implementations you can find in `lodash` : 
https://lodash.com/docs/4.17.15#debounce
https://lodash.com/docs/4.17.15#throttle

**Comment by VlaDi4eKK** [comment]
Thank! This solves the problem!
