### ISSUE TITLE
postcompose event  "0x80004005 (NS_ERROR_FAILURE)" error

### ISSUE THREAD

**Issue by Razz21** [ghettovoice/vuelayers#241]
Hi there, i am stuck with  `0x80004005 (NS_ERROR_FAILURE)` error on postcompose event. 
Its strange, because in demo project it works fine, native ol in vue does not generate any problems too.

full error message:
```
[Vue warn]: Error in event handler for "postcompose": "[Exception... "Failure"  nsresult: "0x80004005 (NS_ERROR_FAILURE)"  location: "JS frame :: webpack-internal:///./node_modules/ol/style/RegularShape.js :: draw_ :: line 444"  data: no]"
```

edit: in project i was using vue-cli with default build settings.

**Comment by ghettovoice** [comment]
Hello @Razz21 ,
this error looks as browser error. I didn't get such errors before, so I could be wrong.
From the error text I see that a problem comes from `draw_` of the RegularShape class.
Maybe you missed some required options? And that lead to this error during canvas drawing.

**Comment by Razz21** [comment]
i have no idea, there is example [project](https://github.com/Razz21/vuelayer-error) where problem exists. 
There is only map instance with postcompose method.
This code is from vuelayers demo project.

**Comment by ghettovoice** [comment]
I tried your fiddle in Chrome and Safari (don't have other browsers right now) and didn't experience any errors with it. Even with uncommented `start = new Date().getTime()`  line.
I guess this issue is strongly related to some special browser versions.
Anyway your way to programmatic selection right.

**Comment by Razz21** [comment]
Thanks, need to find some workaround anyway.

**Comment by Razz21** [comment]
I left postcompose event and stay with programmatic styling, but i can't figure out why my select method does not replace feature style when used with vector cluster. Button select without cluster or mouse click select works fine. [jsfiddle](https://jsfiddle.net/k3phwqo1/1/)

**Comment by ghettovoice** [comment]
Seems like I don't get what is wrong with your example.
I made small tweaks to select style function to clearly highlight selection, it's works by the mouse click and by the button click in the same way. 
https://jsfiddle.net/ghettovoice/bo8fm4j2/

**Comment by Razz21** [comment]
well, if set style radius smaller than vector/feature style than it display on top of original style instead of replace it.

**Comment by ghettovoice** [comment]
Now I got it. 

You are using cluster source, so really on the map only clustered features are rendered, not your original feature. And  this is why  programmatic addition of origin feature to select collection don't replace the default vector source style, cause actually this is another feature.
When you click by the feature, the clustered feature appending to select interaction overlay, and this hides it from vector source.

So to programmatic select the clustered feature by the original feature, you should find the current cluster in which original feature added.

Take a look at the update example https://jsfiddle.net/ghettovoice/bo8fm4j2/
First of all I switch vuelayers to latest stable `v0.11.9` inside resources.
Then I add synchronization of clustered features to the data property.
And finally lookup the cluster by the included original feature.

**Comment by Razz21** [comment]
Very clever solution, thank you.
