### ISSUE TITLE
How get Intersected features?

### ISSUE THREAD

**Issue by jivalenzuela** [ghettovoice/vuelayers#242]
I'm trying to get the features that intersect with a drawn polygon

the features are in an array called "mapPoints"

```
<vl-feature v-for="point in mapPoints" v-bind:data="point" v-bind:key="point.id" :properties="{point: point}">
    <vl-geom-point :coordinates="[point.longitude, point.latitude]" @click="showPointDetails(point.id)"></vl-geom-point>
    <vl-style-box>
        <vl-style-icon v-bind:src="point.img" :scale="0.4" :anchor="[0.5, 1]" ></vl-style-icon>
    </vl-style-box>
</vl-feature>
```

and the polygons are in another array "drawFeatures"

```
<vl-layer-vector id="draw-panel">
    <vl-source-vector ident="draw-target" :features.sync="drawFeatures"></vl-source-vector>
</vl-layer-vector>
```

**Comment by become-iron** [comment]
OpenLayers' `Polygon` class has `intersectsCoordinate` method (https://openlayers.org/en/latest/apidoc/module-ol_geom_Polygon-Polygon.html#intersectsCoordinate) which receives coordinate. I think you could give it a try

**Comment by ghettovoice** [comment]
@jivalenzuela cause VueLayers exports features as GeoJSON objects, take a look also on this useful tool http://turfjs.org that can perform a lot of thing with GeoJSON data. And especially to this helper http://turfjs.org/docs/#pointsWithinPolygon

**Comment by jivalenzuela** [comment]
> @jivalenzuela cause VueLayers exports features as GeoJSON objects, take a look also on this useful tool http://turfjs.org that can perform a lot of thing with GeoJSON data. And especially to this helper http://turfjs.org/docs/#pointsWithinPolygon

I'm trying to implement turfjs but I don't have much experience on vue yet then I still couldn't

**Comment by jivalenzuela** [comment]
> OpenLayers' `Polygon` class has `intersectsCoordinate` method (https://openlayers.org/en/latest/apidoc/module-ol_geom_Polygon-Polygon.html#intersectsCoordinate) which receives coordinate. I think you could give it a try

im trying to use the openlayer's functions from vue, I still don't know how

**Comment by jivalenzuela** [comment]
> @jivalenzuela take a look at the example https://jsfiddle.net/ghettovoice/ztfbjkpd/.
> It shows you how to find intersection using ol native API.

amazing, it's just what I needed, thank you
