### ISSUE TITLE
In the createStyle method, the textAlign and textBaseline properties do not work.

### ISSUE THREAD

**Issue by VlaDi4eKK** [ghettovoice/vuelayers#243]
I am using VueLayers v0.11.18.
When applying a style to a feature, you need to align the label to the left or right. To do this, the textAlign and textBaseline properties must be used. But their use does not affect the display of text. The text is always displayed in the center. Perhaps there is a bug.

**Comment by become-iron** [comment]
Did you mean v.0.11.8? The last version is v.0.11.9 however
The bug replication demo would be useful I think

**Comment by ghettovoice** [comment]
@VlaDi4eKK can you dump code where you build a style object?

**Comment by VlaDi4eKK** [comment]
This is part of the code, all styles work, the text is displayed, but the textAlign property does not work.

`
style = [this.createStyle({
          textScale: 1.4,
          text: 'My text string',
          textAlign: 'left',
          textFillColor: '#fff'
})]
`

**Comment by ghettovoice** [comment]
Try with `v0.11.12` please
