### ISSUE TITLE
InteractionDraw: interaction preserves drawn features even if map has been destroyed

### ISSUE THREAD

**Issue by become-iron** [ghettovoice/vuelayers#244]
vuelayers version: 0.11.9
Demo: https://jsfiddle.net/j8uwyx1p/6/

1. Hide map
2. Show map
3. Draw something
4. Hide map
5. Show map
6. Previously drawn features are present

Passing the features array to the draw target source is not required, the drawn features will be preserved anyway

**Comment by ghettovoice** [comment]
@become-iron thanks for response!
Will be fixed soon

**Comment by ghettovoice** [comment]
Should be resolved by v0.11.10. Please upgrade.

**Comment by become-iron** [comment]
@ghettovoice 
When I try to use the new version, I get an error in console. At least, it's what I see in demo: https://jsfiddle.net/Lzdyjn80/1/

**Comment by ghettovoice** [comment]
Ahh, looks like several OpenLayers types was included into UMD version and now instanceOf assertion fails. ES version don't affected by this.

**Comment by become-iron** [comment]
And new version didn't work in my project code. I'll try to reproduce this later. Probably, in the demo repository

**Comment by ghettovoice** [comment]
Your example with v0.11.11 https://jsfiddle.net/ghettovoice/g6f01oks/

**Comment by ghettovoice** [comment]
Ok, I got it.  Let me some time to resolve it.
Thanks for reply!

**Comment by ghettovoice** [comment]
Done in v0.11.13. https://jsfiddle.net/ghettovoice/42sgkeoh/

**Comment by become-iron** [comment]
@ghettovoice 
I've prepared another demo: https://jsfiddle.net/ag5jr13b/1/. There are two problems:

* the modify interaction doesn't work for some reason before the features wouldn't be reset;
* the drawing interaction is still enabled after the features resetting, although it shouldn't be. It could be some issue of the race condition, which I created, adding `await this.$nextTick()` to the reset function

**Comment by ghettovoice** [comment]
@become-iron good catch! 
Here is the new demo with v0.11.14 https://jsfiddle.net/ghettovoice/jumr7sz8/
As for not working modify interaction: in browser you should always use explicit closing tag because this custom tags and by specification only several html tags are defined as self-closed . In `*.vue` files you can use any tags style

**Comment by become-iron** [comment]
You're awesome! Thanks a lot
