### ISSUE TITLE
Drag and drop item into the map

### ISSUE THREAD

**Issue by episanchez** [ghettovoice/vuelayers#245]
Hello,

I would like to drag and drop item from outside component into the map but the last one inhibit all  drag events like *pointerup* (openLayers event) or *drop* . I can only save the last position before the dragging with *pointermove* but i can't capture coordinate during the dragging.

It-is an expected behaviour to inhibit drag events ? What is the best way to resolve my issue ?

**Comment by ghettovoice** [comment]
Hello @episanchez ,
as I know OpenLayers drag/pan interactions intercepts native drag/pointer events, so you listeners can't catch them.
But for your use case OpenLayers offers special interaction [ol/interaction/DragAndDrop](https://openlayers.org/en/v5.3.0/apidoc/module-ol_interaction_DragAndDrop-DragAndDrop.html) that you can use for adding features by the drag-n-drop motion. This interaction for now don't have any wrapper in the VueLayers lib, but it can be easily included with native OpenLayers API. Here is the example how to implement this https://jsfiddle.net/ghettovoice/bc82p4yu/

**Comment by episanchez** [comment]
Hello @ghettovoice ,

i already checked the DragAndDrop interaction of OpenLayer, i can drag and drop a geojson file but i would like to capture the pointer position at the *dragend* and i did not succeed to do it.

I will try again with your example, maybe i forgot a step,

**Comment by ghettovoice** [comment]
Take a look at the updated version https://jsfiddle.net/ghettovoice/bc82p4yu/

**Comment by ghettovoice** [comment]
Yeh, that can be a good solution 👍

**Comment by ntraykov** [comment]
Actually it is very easy to implement this:

```HTML
<vl-map>
...
   <vl-feature @mounted="featureMounted">
      <vl-geom-point :coordinates="center" />
      <vl-style-box>
        <vl-style-icon src="icons/marker.png" :scale="0.04" />
      </vl-style-box>
    </vl-feature>
...
</vl-map>
```

```Javascript
export default {
    ...
    data: () => ({
        center: [0, 0]
    }),
    methods: {
        featureMounted(vm) {
            const translate = new Translate({
              features: new Collection([vm.$feature]),
            })
    
            translate.on('translateend', e => {
              let lonLat = toLonLat(e.coordinate)
              this.center = lonLat
            })
    
          vm.$map.addInteraction(translate)
      },
}
...
```
