### ISSUE TITLE
Tilting the map

### ISSUE THREAD

**Issue by ROTGP** [ghettovoice/vuelayers#246]
Is there any option (hacky or otherwise) to tilt the map (in 3D)? And if not, might there be plans? I've seen [this](https://openlayers.org/ol-cesium/) but integrating cesium into my project has proved to be extremely complicated (if not impossible).

**Comment by ghettovoice** [comment]
Hello @ROTGP ,
the only 3D tool for OpenLayers I know is ol-cesium, that you mention. And I have plans to  integrate it to the VueLayers. But I don't think I'll be able to do it anytime soon.
Maybe for now there are exist other solutions, I don't know... I haven't been interested in this question for a long time

**Comment by ROTGP** [comment]
Ok, thanks for clarifying
