### ISSUE TITLE
View rotation and style function

### ISSUE THREAD

**Issue by panchofrank** [ghettovoice/vuelayers#247]
Hello,

I am using a style function for clusters, just as in the demo application.  When the map view is rotated, the text in the cluster style also gets rotated.  
This can be reproduced in the demo app by setting 'rotation' to 1 and viewing the cluster layer.

Is there a way to prevent this text from being rotated?

Thanks!

**Comment by ghettovoice** [comment]
Hello @panchofrank ,
try to use boolean `textRotateWithView ` property in the style constructor

**Comment by indoor-onyourmap** [comment]
Hi @ghettovoice,

Thanks for the reply.  I tried that and it is correctly passing the boolean value to the ol Text constructor but for some reason it makes no difference whether it's true or false.  In both cases the text is rotated with the view.

**Comment by panchofrank** [comment]
Hi @ghettovoice,

Thanks for the reply. I tried that and it is correctly passing the boolean value to the ol Text constructor but for some reason it makes no difference whether it's true or false. In both cases the text is rotated with the view.

**Comment by ghettovoice** [comment]
Hmm, that now really interesting... I'll check on some test app
