### ISSUE TITLE
Crash in VlSourceXyz when url changes

### ISSUE THREAD

**Issue by ROTGP** [ghettovoice/vuelayers#248]
The following code produces an error when the value of `tileUrl` changes 

`<vl-source-xyz :url='tileUrl' />`

`Error in callback for watcher "url": "TypeError: this.createUrlFunc is not a function"`

**Comment by ghettovoice** [comment]
@ROTGP  thanks for response. I'll fix it soon.

**Comment by ghettovoice** [comment]
Fixed in the v0.11.15. Upgrade please
