### ISSUE TITLE
View is not yet initialized on map mount

### ISSUE THREAD

**Issue by become-iron** [ghettovoice/vuelayers#249]
v.0.11.15
Demo: https://jsfiddle.net/opsb3nhw/3/
I'm not sure whether it's VueLayers' problem. But it didn't appear on v.0.11.4, for example

In demo I try to get current map extent: on map and view mounts, respectively. Please, pay attention that I await VlView's `$mountPromise` in both cases. But it's not fruitful on map mount: I get extent only on view mount. And it's strange, because I thought that `mounted` hook is being emitted only when this promise is resolved
So it seems to me that view is not yet initialized with parameters which leads to the error: `{code: 1, name: "AssertionError", message: "Assertion failed. See https://openlayers.org/en/v5.3.0/doc/errors/#1 for details."}`

**Comment by become-iron** [comment]
Updated demo: https://jsfiddle.net/upv2f94e/

Well, I moved awaiting higher and now it works. But is it expected behavior anyway that view is not ready on map mount?

**Comment by ghettovoice** [comment]
Looks like I forgot to initialized default view with required props. In the first demo, when you get view from `olMap`, before awaiting for the `vl-view` component promises, you actually get default map view, not this one that will be initialized by the `vl-view` cmp.  I hope I describe it clear 😄

So to get correct view, that is initialized by `vl-view` component, you should call `olMap.getView()`  after `await this.$refs.view.$mountPromise` line. But I agree,  `olView` instance, even the default, should be alway prepared for work.

Thanks for response!

**Comment by ghettovoice** [comment]
Resolved in v0.11.16
https://jsfiddle.net/ghettovoice/gfmuwbpa/

**Comment by become-iron** [comment]
Yeah, I got it. Thank you

**Comment by hadalin** [comment]
I added `:projection` and it seems it stopped working https://jsfiddle.net/ukmyq2f6/

**Comment by ghettovoice** [comment]
@hadalin by default only 'EPSG:4326' and 'EPSG:3857' projections are supported.
To work with any other projections you should firstly register them before using.
Here is your updated example https://jsfiddle.net/ghettovoice/3metdkc7/
