### ISSUE TITLE
vl-interaction-select without changing the style

### ISSUE THREAD

**Issue by boardend** [ghettovoice/vuelayers#251]
It seems that it is not possible to reuse the styling of a feature once it gets selected/hovered.

If no `<vl-style-box>` is provided, a default style will be used. If an empty `<vl-style-box>` is provided, also a default style will be used. (So the icons from the original layer will disappear)

Do I really need to duplicate the style inside the `<vl-interaction-select>` or is there a nicer solution if I just want to sync the selected/hovered features to an array but don't change their style?

**Comment by ghettovoice** [comment]
Hello @boardend ,
this is expected behaviour. Select interaction internally add selected features to its internal overlay layer and hide original from the layer. So it should alway has some styling or null style.

To avoid style duplication you can define them through style functions and re-use layer style function in the select style function. Take a look at the demo: https://jsfiddle.net/ghettovoice/e51btof3/

**Comment by boardend** [comment]
Hi @ghettovoice 

I was thinking about a `<vl-style-func>` too, so that the same style function can be reused inside the layer and the `<vl-interaction-select>`. The problem with this approach is, that I have multiple layers with different stylings, but only wanted one `<vl-interaction-select>` for all the layers. It seems that the style function only gets the feature, but without a reference to the layer. So I cannot provide different stylings for the different layers when they are all bound to one `<vl-interaction-select>`?

**Comment by ghettovoice** [comment]
Do you store layer features in the some data properties? If so you match feature by this arrays.

Another way is to add `layer_id` property to each feature, so in style function you just match related style set by this id.

Anyway you can check for which layer feature belongs with method `getFeatureById`  of the vector source. You need to add `ref="..."` to each layer or get layers collection from the map, filter out only vector layers and filter that is contain current feature.

Something like this could be used:

```js
...
styleFuncFactory () {
  let layerStylesMap = {
    layer_id_1: ....,
    layer_id_2: ...,
    ...,
  }  

  return feature => {
    // if feature has layer_id prop
   let layerStyle = layerStylesMap[feature.get('layer_id')]
   ....

   // searching in layer collection
   let layer = this.$refs.map.$map.getLayers().getArray().find(layer => {
     return layer instanceof VectorLayer && 
                 layer.getSource(). getFeatureById(feature.getId()) 
   })
   if (layer) {
     let layerStyle = layer.getStyle()
     return typeof layerStyle === 'function' ? layerStyle(feature) : layerStyle
   }

   ....
  
   return defaultStyle
  }
},
...
```

**Comment by boardend** [comment]
I've used the second solution to resolve the layer style and reuse it accordingly. Works like a charm. Thank you for your help! 👍
