### ISSUE TITLE
Q: Get visible area

### ISSUE THREAD

**Issue by vikiival** [ghettovoice/vuelayers#252]
Hello,

I have a question about getting a visible area on the map.
Let's say I would like to show all the points on visible area.
I was trying to get the size of the map using ref on <vl-map> tag and then calculate it by some ratio but without any success.
<img width="1541" alt="Screen Shot 2019-11-10 at 20 53 47" src="https://user-images.githubusercontent.com/22471030/68549996-e9f5d480-03fe-11ea-869f-8de66bb1678a.png">

**Comment by ghettovoice** [comment]
Hello @vikiival ,
OpenLayers provides special types and methods to get current view state. Take a look at the examples how to use them with VueLayers: https://jsfiddle.net/ghettovoice/nLmq5vux/

For more info about `ol/View` and its methods: https://openlayers.org/en/v5.3.0/apidoc/module-ol_View-View.html

**Comment by vikiival** [comment]
Cool,
thanks so much I think it will be helpful for more people 💯 ✨ ^-^
