### ISSUE TITLE
Memory leak with Vue Devtools

### ISSUE THREAD

**Issue by VRuzhentsov** [ghettovoice/vuelayers#253]
Found a leak, with simple map dragging. There are a lot of `pointmove` events are emited with huge payload.

all of them are passed to the devtools object/array observer in unreal amounts

1 GB of ram increasing in 30 sec

![image](https://user-images.githubusercontent.com/4579833/68603070-45cc6600-04b0-11ea-9deb-68247e7621c7.png)

![image](https://user-images.githubusercontent.com/4579833/68603089-4bc24700-04b0-11ea-9ed7-ecf0fb84bd3f.png)

**Comment by ghettovoice** [comment]
Hello @VRuzhentsov ,
yeh, this is known issue. There is another same issue #45.

Strictly speaking this issue can't be resolved from the VueLayers side. Map always emits a lot of events `pointermove`, `pointerdrag`, `click` and so on. But the Vue Devtools is made in such a way that it subscribes to all events from all mounted components. And  of course this blows your RAM.

Also as I remember in other Web Map libs for Vue there is same issue too. (See vuejs/vue-devtools#449)

The only workaround I usually use is disable event catching in the Devtool, cause this is not so useful like for example components tree inspection.

**Comment by VRuzhentsov** [comment]
@ghettovoice Yea, thats helps. Also helps with the same problems with `Cesium` 3d lib
Thanks for the idea to help.
Better to close ticket with a refer links 
#45 
[ vuejs/vue-devtools#449](https://github.com/vuejs/vue-devtools/issues/449)
