### ISSUE TITLE
vl-interaction-select does not work

### ISSUE THREAD

**Issue by LucUrlings** [ghettovoice/vuelayers#254]
I have a problem with selecting points on the map, for some reason, it won't select the point whenever I click on it. I've been looking all over the internet for a solution but I can't find a comparable result.

I think it has something to do with the delay that follows from the data being received via an API, then I make a GeoJSON from the data that I receive from the API and then it is applied on the map as follows:

<vl-map ref="map" :load-tiles-while-animating="true" :load-tiles-while-interacting="true" style="height: 800px"
                    data-projection="EPSG:4326">
                

                <vl-view ref="view" :zoom.sync="zoom" :center.sync="center" :rotation.sync="rotation"></vl-view>

                <vl-interaction-select :features.sync="selectedFeatures">
                    <vl-style-box>
                        <vl-style-icon src="https://img.icons8.com/ultraviolet/50/000000/place-marker.png" :anchor="[0.5, 1]"></vl-style-icon>
                    </vl-style-box>
                </vl-interaction-select>

                
                <component v-for="layer in layers" :is="layer.cmp" v-if="layer.visible" :key="layer.id" v-bind="layer">
                    
                    <component :is="layer.source.cmp" v-bind="layer.source">
                    </component>
                </component>

                <vl-layer-vector id="features">
                    <vl-source-vector :features="processedApiData.features">
                        <vl-style-box>
                            <vl-style-icon src="https://img.icons8.com/office/50/000000/place-marker.png" :anchor="[0.5, 1]"></vl-style-icon>
                        </vl-style-box>
                    </vl-source-vector>
                </vl-layer-vector>
            </vl-map>

And

            async initMapData() {
                await this.$axios.get(process.env.VUE_APP_BASEURL + "address")
                    .then(response => {
                        // console.log(response);
                        this.rawApiData = response;

                        this.processedApiData.features = _.range(0, this.rawApiData.data.length).map(i => {
                            return {
                                id: 'marker-' + i,
                                type: 'Feature',
                                mapCursor: 'default',
                                properties: {},
                                geometry: {
                                    type: 'Point',
                                    coordinates: [
                                        this.rawApiData.data[i].lattitude,
                                        this.rawApiData.data[i].longitude
                                    ],
                                },
                            }
                        })
                    })
                    .catch(error => {
                        //TODO EXCEPTION HANDLING
                        console.log(error);
                    });
            }

I think this is the problem because whenever I use a file in the project as input the selecting works fine. 

Am I missing something here?

Regards

**Comment by ghettovoice** [comment]
Hello @LucUrlings ,
do you try load the file with the same features that you load from API? Can you dump part of your api response?

Anyway your example should work. Take a look at the demo: https://jsfiddle.net/ghettovoice/m8y7swcg/

**Comment by LucUrlings** [comment]
This is an example of the API response:
[
    {
        "id": 2,
        "street": "Somestreet",
        "number": 123,
        "addition": "E",
        "zipcode": "1234AA",
        "city": "Amsterdam",
        "longitude": 52.3644893748349,
        "lattitude": 364.89852905273426,
        "sales": []
            }
        ]
    }
]
Then I change this into the geojson format using the code I posted before already.

Note: First I copied your code from the jsfiddle. That worked perfectly fine with the delay of points. But once I added in the API it started not working again. The console prints: "loaded `undefined`" and the feature is not clickable.

**Comment by ghettovoice** [comment]
Ok, I re-checked your example once again.
That should not affect selection, but here : 
```
coordinates: [
  this.rawApiData.data[i].lattitude,
  this.rawApiData.data[i].longitude
],
```
the `longitude ` should be alway the first, then `lattitude`. In other words as `[x, y]`.

As for selection problem, can you provide the full component  source? Or maybe I can see it somewhere published

**Comment by LucUrlings** [comment]
Well, I am happy to say that it did affect selection. I checked it on all places that I used it and I deleted all the occurrences of me defining the projection and now I can select features. Do I have any reason to use the ESPG:4326 over the standard ESPG:3857? Because if not then I am not going to change it.
Then I have another question, once I select a feature there is a slight delay. Is there any way to remove this delay? Or will it be added in the foreseeable future?
Thank you very much for helping me out.

**Comment by ghettovoice** [comment]
> Do I have any reason to use the ESPG:4326 over the standard ESPG:3857?  
EPSG:4326 is widely used in other GIS tools (geography field in PostGIS for example), and also this is the default projection for GeoJSON format. So you can use any projection as `data-projection` that is convenient for you, map view in this case will always be in ePSG:3857. 

>  Is there any way to remove this delay? Or will it be added in the foreseeable future?
Take a look at the updated example: https://jsfiddle.net/ghettovoice/m8y7swcg/. Note `:condition="..."` attribute of the `vl-interaction-select`. This is select condition callback, you can find more info about it here: https://openlayers.org/en/v5.3.0/apidoc/module-ol_interaction_Select-Select.html
