### ISSUE TITLE
How to disable double click zoom?

### ISSUE THREAD

**Issue by funnyconteo** [ghettovoice/vuelayers#255]

**Comment by ghettovoice** [comment]
Hi @funnyconteo ,
do find a solution?

Double click zoom is included in the default interactions set of the map. You can override this collection through `defaultInteractions` property of the `vl-map` component. It accepts the object value with properties from here: https://openlayers.org/en/v5.3.0/apidoc/module-ol_interaction.html#.defaults. Or a collection of `ol/interaction/Interaction` instances.
