### ISSUE TITLE
Illegal interaction argument exception

### ISSUE THREAD

**Issue by spaasis** [ghettovoice/vuelayers#257]
Hi,
vuelayers version 0.11.17

I hit a strange bug:
When running `npm run serve` in development mode, everything works okay.
However, when changing to production (for example deploying after `npm run build`), vuelayers throws this exception: https://github.com/ghettovoice/vuelayers/blob/acbfd14701c1579119d586a51d4b89646ed8fde6/src/ol-ext/interaction.js#L16 

The error goes away if I remove this from my vl-map:
`<vl-interaction-select ref="selectInteraction" :features.sync="selectedFeatures"></vl-interaction-select>`

Another error in production that doesn't happen in development mode:
`TypeError: this.map_.getCoordinateFromPixelInternal is not a function`

**Comment by spaasis** [comment]
Easy way to reproduce, at least on my end, is to change package.json so:
```
"scripts": {
    "serve": "vue-cli-service serve --mode production",
    "build": "vue-cli-service build",
    "lint": "vue-cli-service lint"
  },
```

**Comment by ghettovoice** [comment]
This looks like you got on the page two OpenLayers libs. Can you check what is the version do you use?

**Comment by spaasis** [comment]
package-lock.json:
```
    "ol": {
      "version": "6.1.1",
      "resolved": "https://registry.npmjs.org/ol/-/ol-6.1.1.tgz",
      "integrity": "sha512-0dL3i3eJqgOpqIjDKEY3grkeQnjAYfV5L/JCxhOu4SxiaizRwFrFgeas6LILRoxKa03jhQFbut2r2bbgcLGQeA==",
      "requires": {
        "@openlayers/pepjs": "^0.5.3",
        "pbf": "3.2.1",
        "pixelworks": "1.1.0",
        "rbush": "^3.0.1"
      }
    },
    "ol-tilecache": {
      "version": "3.0.2",
      "resolved": "https://registry.npmjs.org/ol-tilecache/-/ol-tilecache-3.0.2.tgz",
      "integrity": "sha512-oA+UM8juw775gVm0ZgH5WIV9DnDhfLYWnY7zxkpIR8FDZaoFiPa0idG+GFRdRokeCqMoeoNMSD8aRguFbDE9XA=="
    },
```

**Comment by spaasis** [comment]
Oh damn, missed the ol ^5.0 in the requirements. I'll try to update vuelayers to latest and see if this disappears..

**Comment by spaasis** [comment]
Tried downgrading ol to 5.3.3, deleted node_modules and installed all again, but still gives the same error. On the plus side, now the error happens in development mode as well, so that at least clarifies things.

```
    "ol": {
      "version": "5.3.3",
      "resolved": "https://registry.npmjs.org/ol/-/ol-5.3.3.tgz",
      "integrity": "sha512-7eU4x8YMduNcED1D5wI+AMWDRe7/1HmGfsbV+kFFROI9RNABU/6n4osj6Q3trZbxxKnK2DSRIjIRGwRHT/Z+Ww==",
      "requires": {
        "pbf": "3.1.0",
        "pixelworks": "1.1.0",
        "rbush": "2.0.2"
      }
    },
```
Any other versions I should check?

**Comment by spaasis** [comment]
And the interaction causing the error is defined like this:

```
import { DragBox } from 'ol/interaction';
import { platformModifierKeyOnly } from 'ol/events/condition';
import * as olExt from 'vuelayers/lib/ol-ext';
...

public mapCreated(map: any) {
    // a DragBox interaction used to select features by drawing boxes
    const dragBox = new DragBox({
      condition: platformModifierKeyOnly,
      onBoxEnd: () => {
...
      },
    });

    map.$map.addInteraction(dragBox); //this line triggers the error
  }
```

**Comment by ghettovoice** [comment]
I have made test demo, but don't see any problems with your client code. Take a look here : https://codesandbox.io/embed/vuelayers-select-by-dragbox-w3wp7?fontsize=14&hidenavigation=1&theme=dark

I guess you have some mess problems with `node_modules` folder, try to drop it and re-install from the scratch with `ol` package version v5.

**Comment by spaasis** [comment]
Hmm, the test seems to work fine indeed. Where exactly do you import the ol library in that demo? It's not in the package.json nor included as a CDN in the html code..

And btw a separate issue: at least on Firefox, most of the time if you select multiple features, their style doesn't change. That seems to happen in that demo as well.

**Comment by spaasis** [comment]
Okay, finally got it working.
For those who might be hitting the same error:
`npm uninstall ol`
`npm uninstall vuelayers`
`npm install vuelayers`

This removed any version duplicates of ol (which seemed to be caused by ol-tilecache), and now everything works again :)

Thanks for the assist!

**Comment by ghettovoice** [comment]
Thats right! `ol` and `ol-tilecache` packages are included as dependencies in the `vuelayers`  self package.json
