### ISSUE TITLE
programmatic unselection does not update map

### ISSUE THREAD

**Issue by spaasis** [ghettovoice/vuelayers#258]
Hi,

When I have a 
```
      <vl-interaction-select
        ref="selectInteraction"
        :features.sync="selectedFeatures"
      ></vl-interaction-select>
```

and remove a feature from `selectedFeatures` programmatically:
```
  public removeSelection(id: number) {
    const mapFeatureIndex = this.selectedFeatures.findIndex((f) => f.id === id);
    this.selectedFeatures.splice(mapFeatureIndex, 1);
  }
```

The map still has the selected style for the unselected feature.
If I add `$refs.selectInteraction.clearFeatures();` into `removeSelection`, the map reflects the unselection as expected.

**Comment by ghettovoice** [comment]
Hello @spaasis ,
good catch! Thanks for report!

**Comment by ghettovoice** [comment]
See v0.11.18
