### ISSUE TITLE
How to visualize pure geojson file using Vuelayers?

### ISSUE THREAD

**Issue by Munyvorn** [ghettovoice/vuelayers#259]
Hello guys, I am really new to vuelayers. My purpose is to visualize a **geojson** file using this **vuelayers** library, but there seems to be no easy-to-understand **example** of which component to be used in order to do this visualization. Could you please kindly guide me through any sort of example code?
That would be really helpful for me in my project.
Thank you in advance!

**Comment by Munyvorn** [comment]
@ghettovoice could you please give me some help? That would mean a lot to me!

**Comment by jerry1108** [comment]
@Munyvorn : 
Here is an example @ghettovoice  gave me before. Take a look at it~
https://jsfiddle.net/ghettovoice/nu13vkxe/

**Comment by Munyvorn** [comment]
@jerry1108  thank you very much, however, I still do not know how to use the example to apply in my case. All I want is to make my geojson file that I store in my project or read from API to be displayed on the web page. I do not know which component that I can use to do so in vuejs. There is only geojson display example with pure openlayer in Javascript.

**Comment by jerry1108** [comment]
@Munyvorn : 
So the question seems to be  related to vuejs, not vuelayers, right?
You can just make an ajax call from your API and get the geojson results to assign to geojsonObject variable  (reference to the above example). That's it.

As to how to make an ajax call...
You can use the traditional pure  javascript (XMLHttpRequest()) or jquery or other 3rd party tools to achieve it. Then let the function call to be your methods of your vue instance and call it in the mounted function.

Normally I would use axios.js to get API's results and render them in the map. Which tool is better to get geogson results... I think it's up to you.

**Comment by Munyvorn** [comment]
@jerry1108  that's quite helpful. But to a new programmer like me, it's hard to catch up to what you just said. I'm really looking for some working example code that shows how to use this vuelayer's components to display geojson. I have tried Vue2-leaflet library as well, but the output is not as expected, but with Vuelayer it's even harder for me to get any output.

**Comment by ghettovoice** [comment]
Hello @Munyvorn ,
sorry for delay. If you have geojson encoded features available through the some endpoint, so the simplest solution will be something like this: https://jsfiddle.net/ghettovoice/b07z1dcx/.

But you have some custom API , through which you plan load objects, then, as @jerry1108 suggested, you should load objects by your self. Then you form an array of GeoJSON encoded features and pass it to the `vl-source-vector` component. Demo is here https://jsfiddle.net/ghettovoice/bfhLy1q0/

**Comment by Munyvorn** [comment]
@ghettovoice, Thank you so much for your valuable response. In my case, the backend returns an array of geojson objects. The user will selected one of the geojson object, and my job is to visualize it. 
Each geojson object, there is a feature collections. Based on your API suggestion, I formed an array of all the features of the featureCollection, and pass it to `:features` in `vl-source-vector`.
However by doing so, I still cannot see the visualization of the Geojson selected. 
Could you please guide me a bit more?

**Comment by ghettovoice** [comment]
I missed this requirement. For selection feature you need to use `vl-interaction-select`.
Here is the updated demo https://jsfiddle.net/ghettovoice/bfhLy1q0/

**Comment by Munyvorn** [comment]
@ghettovoice  actually the requirement is like this:
1. User upload a DXF file to the web 
2. The DXF file is read to backend and converted to layers (Geojson files).
3. Backend return all of those Geojson files to frontend.
4. Frontend provides option to select one geojson among all the geojson.
5. User select one geojson name, then it should shows based on the selected geojson.
here is a sample of how it looks: 
![image](https://user-images.githubusercontent.com/40157826/69692893-118ab380-1106-11ea-8cf1-5db206734ef8.png)

The problem is that I still do not know how to visualize the geojosn using `vl-source-vector` correctly. Whether I should access to `geojson_example.features`, or pass the entire geojson? or any other way around?

**Comment by ghettovoice** [comment]
You load GeoJSON layer data from backend, then you should form JS array of geojson features and pass it to the `vl-source-vector` to the `features` property. If you server returns a GeoJSON feature collection then you should pass to the `vl-source-vector` what inside `features` key in the server response.
Actually if you server returns response in form of GeoJSON FeatureCollection, and this endpoint can be accessed from the client by GET request, you can just pass this url to the `url` property of the `vl-source-vector` cmp. https://jsfiddle.net/ghettovoice/b07z1dcx/

**Comment by Munyvorn** [comment]
@ghettovoice, I do not get the geojson file in the form of url, instead it's the json object itself. How do I pass a JSON object into `vl-source-layer`

**Comment by ghettovoice** [comment]
Can you dump an example response?

As I said, in that case all you need is map you server response to the array of GeoJSON objects, like it was in my first example here https://jsfiddle.net/ghettovoice/bfhLy1q0/. Take a look at the `placeFeatures` computed prop, here I map emulated server response to the array of GeoJSON features.

**Comment by Munyvorn** [comment]
@ghettovoice I finally made it with the visualization. Thank you so much for your time and responses. There is one final thing for me to solve, which is the styling of the map. 
Here the zoom button is not shown as a default button, and the height seems to be so short, unless until I zoom the browser itself (no matter how much I adjust the wrapper tag):

<img width="432" alt="new_capture" src="https://user-images.githubusercontent.com/40157826/70598984-b20cc780-1c1e-11ea-948f-e4e353aa011e.PNG">

Could you please help me with this?

**Comment by Munyvorn** [comment]
@ghettovoice, I have gone through ZoomToExtent may meet the requirements. But not sure how to use it with vue. Could you explain how?

**Comment by ghettovoice** [comment]
Here is the demo https://jsfiddle.net/ghettovoice/z3pfkLq2/
You have two ways to pass any custom interaction/control to the map:
- through vl-map properties
- by vl-map `created` event

**Comment by Munyvorn** [comment]
@ghettovoice using vl-map property works very well for my case as following: 

<img width="363" alt="zoom_error" src="https://user-images.githubusercontent.com/40157826/71781986-77bcfd00-3007-11ea-9aaf-f1cc560e6c3c.PNG">

However, another problem occurs. As you can see in the picture, **there is no zoom in and zoom out button available**. How have I missed in the code or what could be the problem that the zoom buttons are missing? 

Regarding my code, I follow exactly as your given fiddle (using only `default-controls` property and use the OL library to get extent and size for activating `zoom-to-extent`. 

Also the default height of my `vl-map` is very small and it is not a proper button, as you can see here: 
<img width="343" alt="zoom_error_2" src="https://user-images.githubusercontent.com/40157826/71782037-03cf2480-3008-11ea-8cc8-4483042d77af.PNG">
So I set the ` style = "height: 400px" ` to get the top-most image output. But If I do so, the **zoom button just disappear**.

Solving this would finally makes this issue tackled. Thank you in advance!

**Comment by ghettovoice** [comment]
Hmm, it would be helpful if dump you component code where you use the `vl-map` component.
It looks like some problem with css. Do you open map in the popup element?

**Comment by Munyvorn** [comment]
@ghettovoice 
here is my vl-map component: 
![image](https://user-images.githubusercontent.com/40157826/72057978-ed73e200-3301-11ea-85bb-727cfa71ec84.png)

Yes I do put it in a popup element. It's a popup dialog.
![image](https://user-images.githubusercontent.com/40157826/72058313-7c80fa00-3302-11ea-8fb0-53de975e78f2.png)

**Comment by ghettovoice** [comment]
Broken map height when it is rendered in the popup is a known issue with any map lib, as I known. To workaround this issue, you can call `this.$refs.map.updateSize()` right after popup element will be visible and have a right height, so the vl-map will fill the whole height of the parent element and re-render canvas frame.

As for missed zoom buttons: can you confirm that you extend default controls collection with additional control instead of overriding it? If so, maybe the map parent HTML element have a height a bit less that map and `overflow: hidden`, so the map root element is cutted.

**Comment by Munyvorn** [comment]
@ghettovoice  The buttons are hidden because as you have mentioned the `overflow: hidden` is set in the following element:
![image](https://user-images.githubusercontent.com/40157826/73432940-589b5c00-4376-11ea-88e8-c2af62baffc9.png)
Here is the block of code in which I already set `style ="overflow: visible"` but still I cannot change the style overflow of that element:
![image](https://user-images.githubusercontent.com/40157826/73433049-8f717200-4376-11ea-947a-06caf305d785.png)

And regarding the `this.$refs.map.updateSize( )`, every time I select a new layer, the extent is zoomed one level higher (image gets bigger).
