### ISSUE TITLE
Unselecting with SHIFT+click after box selection does not work

### ISSUE THREAD

**Issue by spaasis** [ghettovoice/vuelayers#262]
Hi,
When trying to remove a single selection from box-selected features, the feature is instead selected again.

Simple reproduction:
An old fiddle on box selection from #148  (https://jsfiddle.net/ghettovoice/v2s9drx4/) works.

Now, update the vuelayers index.umd.js reference to the newest version https://unpkg.com/vuelayers@0.11.17/lib/index.umd.js and try to unselect features again. With this new version it doesn't work anymore.

**Comment by ghettovoice** [comment]
Hi @spaasis!
Yes, I see the problem. I guess it's related to #258 .
Thanks for report!

**Comment by spaasis** [comment]
Hi @ghettovoice, any idea on how to fix this?

**Comment by ghettovoice** [comment]
Hi @spaasis , sorry for delay.
The fix is ready in v0.11.18. Upgrade please!

**Comment by spaasis** [comment]
@ghettovoice good to hear! I updated the package, after which I get an error from npm:
```
This dependency was not found:

* ol-ext/consts in ./node_modules/vuelayers/lib/ol-ext/geojson.js
To install it, you can run: npm install --save ol-ext/consts```

But I don't think that npm install could even work (and it doesn't, at least when I just tested it)

**Comment by ghettovoice** [comment]
Yeh, my IDE insert incorrect import path.
Upgrade to v0.11.19

**Comment by spaasis** [comment]
@ghettovoice Now it works. Thanks!
