### ISSUE TITLE
vl-interaction-draw promise error

### ISSUE THREAD

**Issue by signmeuptwice** [ghettovoice/vuelayers#263]
I am trying to use the vl-interaction-draw component to achieve [this](https://openlayers.org/en/latest/examples/draw-features.html)

the official [doc](https://vuelayers.github.io/#/docs/component/draw-interaction?id=vl-interaction-draw) is really not helping and I can't find any code example somewhere else

So I tried finding it myself and got so far:

```
import VueLayers from 'vuelayers'
import 'vuelayers/lib/style.css'
import Vue from 'vue'
Vue.use(VueLayers)
```
...

```
<vl-map :load-tiles-while-animating="true" :load-tiles-while-interacting="true"
       data-projection="EPSG:4326" style="height: 400px">
       <vl-view :zoom.sync="zoom"
            :center.sync="center"
            :rotation.sync="rotation"
            @update:center="updateCoordinates"
            @update:zoom="updateZoom"
       ></vl-view>

       <vl-geoloc @update:position="geolocPosition = $event">
         <template slot-scope="geoloc">
         <vl-feature v-if="geoloc.position" id="position-feature">
           <vl-geom-point :coordinates="geoloc.position"></vl-geom-point>
           <vl-style-box>
             <vl-style-icon src="_media/marker.png" :scale="0.4" :anchor="[0.5, 1]"></vl-style-icon>
           </vl-style-box>
         </vl-feature>
         </template>
       </vl-geoloc>

       <vl-layer-tile id="osm">
           <vl-source-osm></vl-source-osm>
       </vl-layer-tile>

       <vl-feature>
          <vl-geom-multi-point :coordinates="[[116.544921,40.451633]]"></vl-geom-multi-point>
          <vl-interaction-draw :source="drawCollection" :type="drawType"></vl-interaction-draw>
       </vl-feature>
</vl-map>

...
data(){
    return{
        drawCollection:"",
        drawType:"Point"
    }
}
```
but I get the following error in the console:

`Unhandled Promise Rejection: TypeError: undefined is not an object (evaluating 'source.getFeatures')`

If I remove the <vl-interaction-draw> component there is no error

```
"dependencies": {
  "vue": "^2.5.22",
  "vuelayers": "^0.11.4"
}
```
codepen [here](https://codepen.io/signmeuptwice/pen/oNgvQKO?editors=1111)

**Comment by ghettovoice** [comment]
Hello @signmeuptwice ,
yeh, I know that docs is weakness. 
Take a look at your updated demo here https://codepen.io/ghettovoice/pen/QWwjxJa

Several notes about the demo:
- vl-interaction-draw / modify and snap always works with some vector source through `source` property. `source` property accepts name of the target vector source in the identity map.
- vector source defined with `ident` property, this will add vector source instance to the identity map, so it will be available for interactions

**Comment by signmeuptwice** [comment]
Please what is the change event to get the drawed data and the prop to display it back ? nothing in the doc ? or can you point me to it ? thank you
