### ISSUE TITLE
Custom Geometry Feature

### ISSUE THREAD

**Issue by SSepton** [ghettovoice/vuelayers#265]
My project requires custom geometries such as ellipses. when i worked in openlayers, i created a new class that extended polygon and i succeeded to add an ellipse geometry to the map, how can i integrate this geometry into vuelayers so i could draw ellipses with vuelayers?

**Comment by ghettovoice** [comment]
Hi @SSepton ,
you already have custom geometry classes written for OpenLayers, right?
So you can try to implement custom geometry components for vuelayers using base geometry mixin from this lib.

```js
import { .geometry } from 'vuelayers/lib/mixin'

export default {
  name: 'Ellipse',
  mixins: [geometry],
  ....
}
```

**Comment by SSepton** [comment]
I have already tried this direction but it had some problems. mainly performence problems... i have opened another issue about them, is there any other way to implement ellipses?

**Comment by ghettovoice** [comment]
Ah, yes, I see. 
VueLayers always works with GeoJSON format as shared data between Vue and OpenLayers.
So you have 2 options here:
- manually insert your features with custom OpenLayers geometries into the source. Here is the example https://jsfiddle.net/ghettovoice/0h9evjfa/
- represent ellipses as polygons like I suggest you in another issue #261
