### ISSUE TITLE
How to create an OSM layer using XYZ source

### ISSUE THREAD

**Issue by categulario** [ghettovoice/vuelayers#267]
Hi @ghettovoice 

I'm writing the docs on using some of the sources, currently working on XYZ and OSM. I tried a very simple example that didn't quite work:

```
<template>
  <vl-map :load-tiles-while-animating="true" :load-tiles-while-interacting="true" style="height: 400px">
      <vl-view :zoom.sync="zoom" :center.sync="center" :rotation.sync="rotation"></vl-view>

      <vl-layer-tile>
        <vl-source-xyz :url="url"></vl-source-xyz>
      </vl-layer-tile>
  </vl-map>
</template>

<script>
  export default {
    data () {
      return { 
        zoom: 2,
        center: [0, 0],
        rotation: 0,
        url: 'https://{a-c}.tile.openstreetmap.org/{z}/{x}/{-y}.png',
      }
    },
  }
</script>
```

Reading the source (both of vuelayers and of openlayers) it seems like this simple example should work out of the box but for some reason it doesn't. In the network pane of my browser I see the tiles being requested but the numbers don't match what I see when using `<vl-source-osm>`:

![Captura de pantalla de 2019-12-12 14-24-33](https://user-images.githubusercontent.com/790756/70746312-39277180-1ceb-11ea-9b18-60bc7035700a.png)

I found this related issues: #70 and #139 but no light on how to fix this.

Thanks

**Comment by categulario** [comment]
Something really weird is that I just tried the exact same thing in one of my projects where I have:

```
    "ol": "^5.3.3",
    "vuelayers": "^0.11.8"
```

and it works... A regression perhaps?

**Comment by ghettovoice** [comment]
I see in the first example there is `-y`. This is wrong for this source layer.
Try remove `-` before the `y` and all should work as expected.
Here is the correct demo: https://jsfiddle.net/ghettovoice/otanrqdb/

**Comment by categulario** [comment]
I actually tried both with and without the `-`. In the screenshot it doesn't have it

**Comment by ghettovoice** [comment]
What is the version of vuelayers and openlayers? 
Take a note that vuelayers v0.11.* requires ol v5.
In the ol v6 they are change internal y axis representation.

**Comment by categulario** [comment]
I was trying to figure that out. Apparently latest. It's the one that the docs use. The code is in #268

**Comment by categulario** [comment]
It worked changing openlayers version to `v5.3.0` in `docs/index.html:86`. Should I submit the changes?

**Comment by ghettovoice** [comment]
See here my note about branches and versions https://github.com/ghettovoice/vuelayers/issues/269#issuecomment-566518504
