### ISSUE TITLE
Should docs use `next` tag instead of `latest`?

### ISSUE THREAD

**Issue by categulario** [ghettovoice/vuelayers#269]
As pointed out in #267 the examples of xyz source don't work out of the box probably because the vuelayers version used in the docs (`latest` tag that points to `11.x`) doesn't match the openlayers version (6.x). The two possible solutions I can think of are:

* use `next` vuelayers version
* downgrade openlayers to 5.x

Also, I think this idea of `next` and `latest` is a little bit confusing. I'm used to `latest` being the actual latest available released version and `master` being like the nightly build but not a tag.

**Comment by ghettovoice** [comment]
I think I forget to route you to the `v0.11.x` branch for docs and other things. For now this branch is 
correspond for `latest` npm tag and this is current stable version.
In this branch you can see that the docs site uses openlayers v5 https://github.com/ghettovoice/vuelayers/blob/v0.11.x/docs/index.html#L86

**Comment by ghettovoice** [comment]
When I complete the upgrade (I need to find some time to do this), the docs will be switched to the openlayers v6

**Comment by categulario** [comment]
Ok. I'll point my pull request to the `v0.11` branch in the meanwhile
