### ISSUE TITLE
Setting overflow for vl-style-text

### ISSUE THREAD

**Issue by fofferhorn** [ghettovoice/vuelayers#274]
I want to set overflow to true for text inside a vl-style-text. How can I do this? 

My code now is:

```html
<vl-feature
  v-if="polygons"
  v-for="(polygon) in polygons"
  :key="polygon.Id"
  :id="polygon.Id"
>
  <vl-geom-polygon
    :coordinates="polygon.GeoJSON.geometry.coordinates"
  />
  <vl-style-box>
    <vl-style-stroke :color="isSelected(polygon, selectedPolygonId) ? #FF7A7A : #000000"/>
    <vl-style-fill :color="isHovered(polygon) ? '#73beed' : '#ffffff'" />
    <vl-style-text :text="polygon.Name" />
  </vl-style-box>
</vl-feature>
```

I've tried to use ```:overflow="true"``` on the ```<vl-style-text>```-tag but it didn't do anything.

**Comment by fofferhorn** [comment]
I've looked more into it, and as far as I can tell ```overflow``` has not been implemented for ```vl-style-text```-elements.

**Comment by ghettovoice** [comment]
Hello @fofferhorn ,
yes, looks like vl-style-text missed `overflow` property. I'll add it soon.
For a while you can define your styles in a more advance way - with style function through `vl-style-func` component. This components is a more advanced replacement for `<vl-style-box>...</vl-style-box>`.
Here is the demo where you can see this component in action https://jsfiddle.net/ghettovoice/rc4u02na/. In the demo I use it as style for the whole layer, but it also can be injected into the vl-feature.

Thanks for response!

**Comment by fofferhorn** [comment]
Thank you for the response @ghettovoice.

I've looked into using the style function instead. However, I could not get the functionality that I wanted. 

The styling of the polygon/feature depends on different properties from my polygon object. However, the style function receives a feature as input. I could not find a way to include properties from each polygon in the feature and thereby pass the properties on to my style function like seen in the example below. 

```javascript
let polygon = {
    'PolygonId': '1234',
    'Name': "Square",
    'Number': 1,
    ...
}

styleFuncFactory () {
    return feature => {
        return [
            new ol.style.Style({
                stroke: new ol.style.Stroke({
                    color: isSelected(feature.PolygonId, selectedPolygonId) ? '#FF7A7A' : '#000000'
                }),
                fill: new ol.style.Fill({
                    color: isHovered(feature.PolygonId) ? '#73BEED' : '#FFFFFF'
                }),
                text: new ol.style.Text({
            	    text: feature.Name + ' ' + feature.Number,
                    overflow: true
                })
            })
        ]
    }
}
```

**Comment by ghettovoice** [comment]
When you add your polygon objects to the vuelayers, you transform them to the GeoJSON objects, so the vuelayers can understand and render them as features. In the style function you get each styling feature as ol/Feature object. So if you pass some additional data as feature properties, then you can get this data from ol/Feature data values.

So if you pass features through `:features` prop like it in this demo https://jsfiddle.net/ghettovoice/rc4u02na/, you can add custom feature properties like this
```
let geojsonObject = {
  'type': 'FeatureCollection',
  'crs': {
    'type': 'name',
    'properties': {
      'name': 'EPSG:3857'
    }
  },
  'features': [
    {
  	'id': 1,
        'type': 'Feature',
        'properties': {
            'field_1': 'value',
            ...
        },
        'geometry': {
           'type': 'Polygon',
           'coordinates': [[[-5e6, 6e6], [-5e6, 8e6], [-3e6, 8e6],
                       [-3e6, 6e6], [-5e6, 6e6]]]
        },
    },
    ...
}
```
Then in the style function you can get the field value like : `const val = feature.get('field_1')`.

If you use `vl-feature` component for vector features, you can pass custom properties through `:properties` prop.

**Comment by ghettovoice** [comment]
Done in v0.11.21
