### ISSUE TITLE
how to add ol-geocoder? 

### ISSUE THREAD

**Issue by addean** [ghettovoice/vuelayers#275]
if i import ol-geocoder it will return `Cannot read property 'control' of undefined`
and `Geocoder is not defined`.
I user geocoder from here [https://github.com/jonataswalker/ol-geocoder].
I'm not using vue-cli, load vuelayers using cdn
(https://github.com/jonataswalker/ol-geocoder)
![image](https://user-images.githubusercontent.com/22883450/71468284-5a668280-2800-11ea-9d29-384f883c5a5c.png)

**Comment by ghettovoice** [comment]
Hello @addean, 
do you find a solution for this issue? 
It looks like you you forget to add openlayers to the page.
