### ISSUE TITLE
Unable to synchronise features on vl-interaction-select in 0.11.20

### ISSUE THREAD

**Issue by panchofrank** [ghettovoice/vuelayers#276]
Is there a regression on feature synchronisation on vl-interaction-select?   I have forked a [fiddle](https://jsfiddle.net/Francoisgaudin/cqnhrmef/) to illustrate the issue.
With version 0.11.20 the button is unable to unselect features.  With 0.11.16 it works fine.

**Comment by ghettovoice** [comment]
Hello @panchofrank!
Yes, you are right. Thanks for report!

**Comment by ghettovoice** [comment]
Upgrade please up to v0.11.21
Here is the demo with this version https://jsfiddle.net/ghettovoice/pm9n6fux/

**Comment by panchofrank** [comment]
Wow - super fast fix.  Thankyou, fix confirmed. :-)
