### ISSUE TITLE
Why is 'normal' font weight always being applied in createTextStyle function?

### ISSUE THREAD

**Issue by become-iron** [ghettovoice/vuelayers#277]
https://github.com/ghettovoice/vuelayers/blob/baa9ed4845ad4cd7ff32cb1120b7b51a9e9e3806/src/ol-ext/style.js#L333

It prevents to set custom font weight, doesn't it?

**Comment by become-iron** [comment]
Also I wonder if font size should always be in pixels

https://github.com/ghettovoice/vuelayers/blob/baa9ed4845ad4cd7ff32cb1120b7b51a9e9e3806/src/ol-ext/style.js#L332

**Comment by ghettovoice** [comment]
Hello @become-iron !
You are right, this place can be improved to allow user to setup this style options.
For a while, if you stack with this, use OpenLayers native style constructors

**Comment by become-iron** [comment]
@ghettovoice Is it possible to protect issues from the stale bot?

**Comment by ghettovoice** [comment]
Yes, thank for reminding me of that

**Comment by ghettovoice** [comment]
Done. 
You can set font weight with `textFontWeight`. And `textFontSize` now can accept strings with sizes defined in units other than `px`.
