### ISSUE TITLE
Cannot use import statement outside a module

### ISSUE THREAD

**Issue by aditya369thalluri** [ghettovoice/vuelayers#281]
I am currently working on Nuxt JS. I installed OpenLayers and trying to import it.  Gives the below error.

"Cannot use import statement outside a module"

Error is coming up only for this package. I am able to import other packages successfully.

 // Code generated from rollup --es but using .js so likely not intended to run as modules
  "main": "./lib/index.js",
  "module": "./lib/index.js",
  // Code generated from rollup --umd, likely intended to run as a script or CommonJS
  "unpkg": "./lib/index.umd.js",

Please support SSR using this code.

Any help would be appreciated.

**Comment by ghettovoice** [comment]
Hello @aditya369thalluri ,
where exactly you see this error? Which file/line? And which file do you import into your app?
