### ISSUE TITLE
Custom marker on click event

### ISSUE THREAD

**Issue by byinff** [ghettovoice/vuelayers#282]
Hi, do you have an example for create a custom marker on click event on the map ?

I used the following example of the webpage

`<vl-map
            :load-tiles-while-animating="true"
            :load-tiles-while-interacting="true"
            data-projection="EPSG:4326"
            style="height: 400px"
            @click="clickInMap"
          >
            <vl-view :zoom.sync="zoom" :center.sync="center" :rotation.sync="rotation"></vl-view>

            <vl-layer-tile>
              <vl-source-osm></vl-source-osm>
            </vl-layer-tile>

            <vl-layer-vector>
              <vl-source-vector :features="features"></vl-source-vector>

              <vl-style-box>
                <vl-style-fill color="white"></vl-style-fill>
                <vl-style-stroke color="red"></vl-style-stroke>
                <vl-style-icon
                  src="http://hotelkokoro.com/wp-content/uploads/2016/11/map-marker-icon-300x300.png"
                  :anchor="[.5, 1]"
                  :scale=".3"
                ></vl-style-icon>
              </vl-style-box>
            </vl-layer-vector>
          </vl-map>`

In function clickInMap i replace the variable features with the coordinates of event click map

`clickInMap(e) {
      this.features = [
        {
          type: "Feature",
          geometry: {
            type: "Point",
            coordinates: [e.coordinate[0], e.coordinate[1]]
          },
          properties: {}
        }
      ];
    },`

But this doesn't work. Do you have any idea for this ?

**Comment by ghettovoice** [comment]
Hello @byinff ,
sorry for the late response. Take a look here https://jsfiddle.net/ghettovoice/uctsj1z4/.
For such simple cases like click marker, geolocation marker you can just drop `vl-feature` directly to `vl-map` tag. Sources and layers are more useful when you work with group of objects
