### ISSUE TITLE
Point not working on vl-source-vector?

### ISSUE THREAD

**Issue by RobbieVerdurme** [ghettovoice/vuelayers#284]
Hi @ghettovoice 

I was hoping you could help me with a problem. i have the library vuelayers installed and want to use the <vl-source-vector> tag for adding points on the map. But i don't see a marker on the map(where i drew the circle)
![vuelayers](https://user-images.githubusercontent.com/25928398/76219703-847fec00-6216-11ea-9020-715fddf3baaa.png)
 i used the this code:

html
`      <vl-layer-vector>
        <vl-source-vector :features.sync="features" />
        
        <vl-style-box>
          <vl-style-fill color="white" />
          <vl-style-stroke color="red" />
        </vl-style-box>
      </vl-layer-vector>`

javascript
```
features: [
{type:"Feature",geometry:{type:'Polygon',coordinates:[[[414688.076662,6630700.090869],[414813.600711,6630641.210585],[414911.205519,6630636.015258],[414967.091753,6630703.136228]]]}},
        {type:"Feature",geometry:{type:'Point',coordinates:[415563.997335,6630907.426425]}}]
```
i do see the polygon as you see but not the point that i added. It also does not work on the site 
https://vuelayers.github.io/#/docs/component/vector-layer

**Comment by ghettovoice** [comment]
Hello @RobbieVerdurme ,
cause you override the default style with `vl-style-box` tag, the point style is reset too. So you should also provide custom styles for point geometries.

```html
...
<!--styling--> 
<vl-style-box> 
  <!-- top level fill/stroke applies only on lines and polygons -->
  <vl-style-fill color="white" /> 
  <vl-style-stroke color="red" /> 
  <!-- points, could be circle or icon -->
  <vl-style-circle>
      <vl-style-fill color="white" /> 
     <vl-style-stroke color="red" /> 
  </vl-style-cirlce>
</vl-style-box>
...
```

**Comment by RobbieVerdurme** [comment]
Hi @ghettovoice 

I can see the point now.
thx for the help
