### ISSUE TITLE
please help me about ol.filter.Crop & ol.filter.Mask

### ISSUE THREAD

**Issue by khjde1207** [ghettovoice/vuelayers#286]
Hello!

https://viglino.github.io/ol-ext/examples/filter/map.filter.crop.html

I want to implement this sample in vuelayers.
No matter how I find it, I can't find any examples of using ol.filter.Crop and ol.filter.Mask.
Could you give me a way how to use it in Vuelayers?
Thanks in advance

**Comment by ghettovoice** [comment]
Hello @khjde1207 ,
I have made almost one-to-one reproduction of filter demo. 
Take a look here https://jsfiddle.net/ghettovoice/vjpgc7ba/

**Comment by khjde1207** [comment]
Thanks !!
