### ISSUE TITLE
vl-interaction-select throwing typerrors

### ISSUE THREAD

**Issue by yyuri** [ghettovoice/vuelayers#287]
Hello, I'm receiving typerros when accessing the selected features of vl-interaction-select

I'm doing the following:

`      <vl-interaction-select :features.sync="selected">

      </vl-interaction-select>
`

Then, I'm watching the selected array to call a function anytime selected changes:

    watch: {
      selected () {
        this.loadFeatureInfo();
      }, deep:true,
    },

The function I'm calling:

      loadFeatureInfo: async function() {
        if (this.selected.length) {
          let id = this.selected[0].properties.id
          console.log(this.selected[0].properties.id);
          let res = await fetch('/focus?id='+this.selected[0].properties.id);
          let json = await res.json();
          if (res.ok != true) {
            this.errors= "Algo ha fallado al cargar /municipis";
          }
          else {
              this.dialog=true;
              this.focuss=json.data;
          }
        }
      },

The properties.id gets logged and the fetch is done, but I'm also getting this error

`TypeError: "t is null"`

Thanks for you contributions, once solved I'll take my time to provide some examples on vl-interaction-select for the documentation :)

**Comment by ghettovoice** [comment]
Hello @yyuri ,
I doubt that the problem is due to selected features access. I think it lies somewhere else.
Can you post the line where you get this error? 
It would be more helpful to see the whole component, what is inside `this.focuss` and how it is used

**Comment by yyuri** [comment]
Solved, certainly it was not related to vuelayers.

Thanks for your work.
