### ISSUE TITLE
Change style when change vl-source-layer

### ISSUE THREAD

**Issue by goof03** [ghettovoice/vuelayers#288]
HI i have something like that :
```html
<vl-layer-tile
  v-for="layer in baseLayers"
  :id="layer.name"
  :key="layer.name"
  :visible="layer.visible"
  @postcompose="test"
>
  <component
    :is="'vl-source-' + layer.name"
    v-bind="layer"
  />
</vl-layer-tile>
<vl-layer-vector
  ref="sensorsLayer"
  update-while-animating
  update-while-interacting
>
  <vl-source-vector :features="DevicesCoordinate" />
  <vl-style-func :factory="styleFuncFactory" />
</vl-layer-vector>
`

How to change vl-source-vector style when i change layer visibility ? When i switch from simple map to satellite view …

Thanks

**Comment by ghettovoice** [comment]
Hi @goof03 ,
there can be applied various approaches to achieve this.
But the most efficient, as I think, you can see here https://jsfiddle.net/ghettovoice/6zdaueb2/.
You just need to refresh layer component by some event, in my case this is base layer change. Cause you already use style function, you only need to build you styles in it that depends on current visible layer.
