### ISSUE TITLE
vl-style-text question

### ISSUE THREAD

**Issue by vvizden** [ghettovoice/vuelayers#292]
Hi,

I try to  add vl-style-fill / vl-style-stroke inside vl-style-text, but the following error appears in the console.

![image](https://user-images.githubusercontent.com/32644183/77764572-d11d5100-7077-11ea-91e1-3344eee2affc.png)

![image](https://user-images.githubusercontent.com/32644183/77764429-987d7780-7077-11ea-9504-420404aa81b4.png)

dependencies:
"vuelayers": "0.11.21",
"core-js-pure": "3.6.4"

Please help me, thanks!

**Comment by ghettovoice** [comment]
Hello @vvizden ,
thanks for bug report. 
I will try to release a patch as soon as possible. 
For a while as a workaround you can switch to use `vl-style-func` and build styles inside factory function.

**Comment by ghettovoice** [comment]
Install last version v0.11.22, pls. It should resolve your issue

**Comment by vvizden** [comment]
Wow，so good! Thank you very much!

**Comment by vvizden** [comment]
All right, it's ok now.Thanks.
