### ISSUE TITLE
xyz == tms?

### ISSUE THREAD

**Issue by wendellwt** [ghettovoice/vuelayers#297]
Thank you for VueLayers!

Does vl-source-xyz (or vl-source-wms) work for Tile Mapping Service (TMS) tiles?

When generating tiles using gdal2tiles.py, it creates an openlayers.html file that contains:
```
             // create TMS Overlay layer
              var tmsoverlay = new OpenLayers.Layer.TMS("TMS Overlay", "",
             {
                 serviceVersion: '.',
                 layername: '.',
                 alpha: true,
                 type: 'png',
                 isBaseLayer: false,
                 getURL: getURL
             });
```
Is that function available in VueLayers?  Are there parameters to vl-source-xyz that make it accept TMS tiles?

Thanks again for this terrific module,
Wendell

**Comment by ghettovoice** [comment]
Hello @wendellwt ,
thanks for response!

What is the actual url for tiles is used? From you example it's not clear what's inside `getURL` function.
I guess you have a directory where `gdal2tiles .py` dump image tiles grouped into directories by XY coords. So for `vl-source-xyz` you need to provide an url template, something like `http://example.com/tiles/{z}/{x}/{-y}.png`. Where `{-y}` is used to define TMS like coord system. https://openlayers.org/en/v5.3.0/apidoc/module-ol_source_XYZ-XYZ.html

**Comment by wendellwt** [comment]
You can see some of my tiles here: https://tiles.ilikecarrots.com/tiles_high_only/openlayers.html (site currently has mixed https/http).  The tiles were generated by gdal2tiles.py (https://gdal.org/programs/gdal2tiles.html)  The very latest version of that will generate xyz tiles, so I can do that if necessary.  The openlayers code it generated, with the OpenLayers.Layer.TMS and getUrl() function, is attached.

Thank you.
[openlyr_sample.zip](https://github.com/ghettovoice/vuelayers/files/4432718/openlyr_sample.zip)

**Comment by ghettovoice** [comment]
I guess you just can load your tiles with something like this:

```html
<template>
<vl-map ...>
  <vl-layer-tile ...>
    <vl-source-xyz :url="url" />
  </vl-layer-tile>
</vl-map>
</template>

<script>
export default {
  data () {
    baseUrl: 'http://example.com/tiles',
    serviceVersion: '...',
    layername: '...',
  },
  computed: {
    url () {
      return [this.baseUrl, this.serviceVersion, this.layername].join('/') + '/{z}/{x}/{-y}.png'
    },
  },
}
</script>
```

**Comment by wendellwt** [comment]
Thank you.  That works fine!

Sorry to have bothered you.  I should have figured that out myself.

Wendell

**Comment by ghettovoice** [comment]
No prob. You are welcome!
