### ISSUE TITLE
CSP `unsafe-eval` minilo.js issue 

### ISSUE THREAD

**Issue by VRuzhentsov** [ghettovoice/vuelayers#299]
We have `get()` method inside  `/src/util/minilo.js`  
it has eval inside, and as we all knew, it is not good
Also Content Security Policy disables that script 😢 

Can i create PR with replacing by https://github.com/lodash/lodash/blob/master/get.js, or it will be overkill?

Or I can also propose solution from this post https://gomakethings.com/how-to-get-the-value-of-an-object-from-a-specific-path-with-vanilla-js/

**Comment by ghettovoice** [comment]
Hello @VRuzhentsov ,
lodash version would be overkill. Actually this is why I  use internal simplified functions.

The second link is following to 404 page.

Anyway if you can propose simple implementation, you are welcome for pull request. Just take a note that it should support paths similar to lodash, i.e. object fields and array elements: `obj.field.slice[2].field`

**Comment by VRuzhentsov** [comment]
Hi @ghettovoice 
Updated link
https://gomakethings.com/how-to-get-the-value-of-an-object-from-a-specific-path-with-vanilla-js/

**Comment by ghettovoice** [comment]
I think this implementation looks suitable

**Comment by VRuzhentsov** [comment]
found, that solution above did not solves deep arrays 
`get(objWithDeepArrays, "geometry.coordinates[0][0][0]")`

but [this one](https://github.com/you-dont-need/You-Dont-Need-Lodash-Underscore#_get) - solves

**Comment by ghettovoice** [comment]
released as v0.11.23
thanks for contrib!
