### ISSUE TITLE
Cannot override default zoom control

### ISSUE THREAD

**Issue by alex3493** [ghettovoice/vuelayers#300]
I'm trying to override default zoom behavior, precisely what I need it to change zoom delta.

I'm using default-controls vl-map property. It works fine for just enable/disable given controls, but I can't find the way to modify control options.

I tried to use plain object with desired zoom options, also tried native Zoom instance with options, imported from OL.

Application runs without errors, but my custom options have no effect. Sure, I'm missing something.

Documentation is not clear. Could you please give me some hints?

**Comment by ghettovoice** [comment]
Hello @alex3493 ,
take a look at this demo https://jsfiddle.net/ghettovoice/x2ufmj3h/.
The object format is actually described on the OpenLayers doc site https://openlayers.org/en/v5.3.0/apidoc/module-ol_control.html

**Comment by alex3493** [comment]
Thank you for the prompt reply.

It works - just checked it setting zoomOptions.delta to 2. However, my intention was to reduce zoom buttons effect, i.e. set delta < 1, e.g. 0.3

With float values < 1 it doesn't work as expected. Any suggestion?

My code:
```
          return {
            // By default all controls are enabled. We have to explicitly
            // set false for the controls we want to hide.
            // zoom: true,
            // attribution: true,
            rotate: false,
            zoom: true,
            zoomOptions: {
              delta: 0.3
            }
          }
```

**Comment by ghettovoice** [comment]
Deltavin zoom control less than 1 is not meaningful.  It just define the step to jump through defined view resolutions. Take a look at this comment https://github.com/openlayers/openlayers/issues/3684#issuecomment-103195457.

If you need to define smaller steps between zoom levels, you need to setup own resolutions. You can make this with `zoom-factor` like here https://jsfiddle.net/ghettovoice/x2ufmj3h/32/. The zoom factor used to determine the resolution constraint. 
Or you can define your own custom `resolutions` array, i.e. actual zoom levels which will be used.
In any case zoom control delta should be equal to `1`, to define how resolutions should be jumped from this `resolutions` array.

**Comment by alex3493** [comment]
Thank you, now it's clear. I will browse docs for how to setup and use custom resolutions array and try this approach. If you have a link to this topic at hand... It would be highly appreciated.
