### ISSUE TITLE
About print export map

### ISSUE THREAD

**Issue by Rih** [ghettovoice/vuelayers#306]
Hello @ghettovoice ,
About version 0.12 is currently available?
I just wonder because I cannot reproduce the openlayers example of export to PDF https://openlayers.org/en/latest/examples/export-pdf.html?q=export
I think it works on openlayers version 6+ and vuelayers 0.11 uses 5+
I've tried many ways to obtain the canvas image with no success, even i'm trying html2canvas and nothing yet :c

**Comment by ghettovoice** [comment]
Hello @Rih ,
v0.12.x currently is not ready yet. Cause current supported version is v5.x you should view at the example https://openlayers.org/en/v5.3.0/examples/export-pdf.html?q=export.
And here is the demo almost reproduce this example https://jsfiddle.net/ghettovoice/zfjtabdv/
