### ISSUE TITLE
 does not render in chrome

### ISSUE THREAD

**Issue by JONDJ** [ghettovoice/vuelayers#309]
It does not render until the container is resized. In firefox if it works. Thanks

**Comment by ghettovoice** [comment]
Hello @JONDJ ,
do the parent element is visible at map render time? 
If not visible, after showing it you need to call `updateSize` method.

**Comment by JONDJ** [comment]
Hi @ghettovoice thanks for you fast reply. 
Yes the parent element is visible. I call updateSize methos on mounted component but the problem continues

`mounted() {
      this.$refs.map.$updateSize
    }`

But in firefox all works fine.

Thanks again

**Comment by JONDJ** [comment]
This is the full component based on your example 
`<template>
  <div>
    <vl-map ref="map" :load-tiles-while-animating="true" :load-tiles-while-interacting="true"
             data-projection="EPSG:4326" style="height: 400px">
      <vl-view :zoom.sync="zoom" :center.sync="center" :rotation.sync="rotation"></vl-view>

      <vl-geoloc @update:position="center = $event">
        <template slot-scope="geoloc">
          <vl-feature v-if="geoloc.position" id="position-feature">
            <vl-geom-point :coordinates="geoloc.position"></vl-geom-point>
            <vl-style-box>
              <vl-style-icon src="img/marker.png" :scale="0.4" :anchor="[0.5, 1]"></vl-style-icon>
            </vl-style-box>
          </vl-feature>
        </template>
      </vl-geoloc>

      <vl-layer-tile id="osm">
        <vl-source-osm></vl-source-osm>
      </vl-layer-tile>
    </vl-map>
    <div style="padding: 20px">
      Zoom: {{ zoom }}<br>
      Center: {{ center }}<br>
      Rotation: {{ rotation }}<br>
      My geolocation: {{ geolocPosition }}
    </div>
  </div>
</template>

<script>
  export default {
    data () {
      return { 
        zoom: 13,
        center: [0, 0],
        rotation: 0,
        geolocPosition: undefined,
      }
    },
    mounted() {
      this.$refs.map.$updateSize
    }
  }
</script>`

**Comment by ghettovoice** [comment]
It's hard to say why experience this issue without any code sample or demo which reproduce it.
I'm using chrome every day, also during development, and don't see any problem with render map in this browser. There can be such issues if at the render time parent element has height = 0, so the map canvas height calculate to 0 too.

Can you post here component where you use `vl-map`?

**Comment by JONDJ** [comment]
Hi @ghettovoice

I`m using the component fo quickstart of your page

https://vuelayers.github.io/#/docs/quickstart


I inspect element and view that canva element has display:none until it is resized

<canvas class="ol-unselectable" style="width: 100%; height: 100%; display: none;"></canvas>

Thanks

**Comment by ghettovoice** [comment]
In the quickstart the `vl-map` has hardcoded height `400px`, by default `vl-map` has height `100%`.
So I guess your parent element has something like `min-height: 100%`, so the child element `height: 100%` actually renders with height = 0px.

Try to setup absolute height for the `vl-map` element.

**Comment by JONDJ** [comment]
Hi @ghettovoice, actually the parent had display:none property I change this and work perfect

Thanks.
