### ISSUE TITLE
Ruby on Rails, gem webpacker, vuelayers problems, bugs.

### ISSUE THREAD

**Issue by nPaul** [ghettovoice/vuelayers#31]
Vuelayers not work correctly with gem webpacker in Ruby on Rails project.
I create simple project demonstration it.
https://github.com/nPaul/webpacker_vuelayers

page http://localhost:3000/map1
work fine in Google Chrome, but not working in Internet Explorer.
 ```
import Vue from 'vue'
import VueLayers from 'vuelayers'
import TpMap from '../map.vue'
import 'vuelayers/lib/style.css'
Vue.use(VueLayers)

import TurbolinksAdapter from 'vue-turbolinks';
document.addEventListener('turbolinks:load', () => {
    var element = document.getElementById("map1")
    if (element != null) {
        const app = new Vue({
            el: '#map1',
            render: h => h(TpMap)
        })
    }
})
```
page http://localhost:3000/map2
does not work on all browsers
```
import Vue from 'vue/dist/vue.esm'
import VueLayers from 'vuelayers'
import TpMap from '../map.vue'
import 'vuelayers/lib/style.css'
Vue.use(VueLayers)

import TurbolinksAdapter from 'vue-turbolinks';
document.addEventListener('turbolinks:load', () => {
    var element = document.getElementById("map2")
    if (element != null) {
        const app = new Vue({
            el: '#map2',
            components: { TpMap  },
            template: '<TpMap />'
        })
    }
})
```
please help me

**Comment by ghettovoice** [comment]
Hi!
The problem is that your app loads two different Vue version () on the same page.
I make pull request to your repo with fix. 
Take a look at `config/webpack/environment.js` file (added `resolve.alias` to load Vue with compiler version) and `app/javascript/packs/map2.js` (just import Vue as normal, webapack take scare about Vue dist file)

**Comment by ghettovoice** [comment]
Can't check whats going wrong in IE right now, I'll test this soon

**Comment by nPaul** [comment]
if use "babel-polyfill" in IE works, but it maybe bad idea.
in documentaion recomends  set params "useBuiltIns" to true, "target" to "ie >= 9" in .babelrc, but this not work with vuelayers
also i try use "transform-runtime" babel plugin, its too not working in IE.

**Comment by ghettovoice** [comment]
Try v0.9.1, it should work without babel-polyfill.
See issue #32

**Comment by nPaul** [comment]
i upgraded to version 0.9.1
without 'babel-polyfills' get errors on IE all versions

[Vue warn]: Injection "$services" not found

```
found in

---> <VlMap>
       <TpMap> at app/javascript/components/tp_map.vue
         <Root>
```

**Comment by ghettovoice** [comment]
This is not a fatal error, only warning. 
I'll fix it soon

**Comment by nPaul** [comment]
if exclude **vuelayers** from main.js, other vue components work fine without error in IE.
if **import 'vuelayers';** than webpack generate code
`var r=n[i]={i,l:!1,exports:{}};` in out package in production mode.
this is code not work in IE.

try use plugin "transform-es2015-shorthand-properties" not help

**Comment by ghettovoice** [comment]
I just tried bundle your repo https://github.com/nPaul/webpacker_vuelayers (run `bin/webpack`) and didn't see short properties in final bundles.
Can you add some clarification how to reproduce?

**Comment by nPaul** [comment]
iam fix it temporary
vuelayers tp_map.vue component move to separately pack "tp_map.js"
and on start line insert 
import 'babel-polyfilll'

in babelrc
set useBuiltIns = false
enable 'transform-runtime'
than all work file in IE10-11,edge
But not work in IE9. all pages with vuejs is empty.

its work if polyfill only import in tp_main.js pack
if move to application.js globally, IE get errors
like "shorthand properties not supported"
`var r=n[i]={i,l:!1,exports:{}};`

**Comment by ghettovoice** [comment]
I'm not an expert in Ruby and Rails, so it would help if you load this changes to your test repo https://github.com/nPaul/webpacker_vuelayers .

**Comment by ghettovoice** [comment]
I dig into `@rails/webpacker` code and found why uglified version contains shortand properties, this is due to UglifyJs plugin configured with `ecma: 8` by default (see https://github.com/rails/webpacker/blob/master/package/environments/production.js#L16)
You can override that in `config/webpack/production.js`:
```js
const environment = require('./environment')
const UglifyJsPlugin = require('uglifyjs-webpack-plugin')

environment.plugins.delete('UglifyJs')
environment.plugins.append('UglifyJs', new UglifyJsPlugin({
    parallel: true,
    cache: true,
    sourceMap: true,
    uglifyOptions: {
      mangle: true,
      compress: {
        warnings: false,
        comparisons: false
      },
      output: {
        ascii_only: true
      }
    }
  }))

module.exports = environment.toWebpackConfig()
```

**Comment by ghettovoice** [comment]
Close due to inactivity
