### ISSUE TITLE
clear() is not a function on WMSsource

### ISSUE THREAD

**Issue by yyuri** [ghettovoice/vuelayers#313]
I've a layer declared as follow:

```html
       <vl-layer-tile :z-index="10" :visible="isvisible">
         <vl-source-wms
           url="http://localhost/geoserver/mosquits/wms?"
           ref="WMSpendentse"
           :ext-params="{ TILED: true, 'INFO_FORMAT': 'application/json'}"
           server-type="geoserver"
           layers="mylayer:vista_areas_de_prospeccio"
           projection="EPSG:3857"
           version="1.3.0"
           :strategy-factory="loadingStrategyFactory"
           >
         </vl-source-wms>
       </vl-layer-tile>
```

At some point I'm drawing some features that will be added to this same layer, so I need to clear the cache and refresh this tiles in order to be able to see the newly added features.

So, I checked the [docs](https://openlayers.org/en/latest/apidoc/module-ol_source_TileWMS-TileWMS.html#refresh) and thought that calling clear and refresh would do:
```js
this.$refs.WMSpendentse.clear();
this.$refs.WMSpendentse.refresh();
```

 - refresh() is visibly working
 - but clear() is not, this is what I see on the console:

> Uncaught (in promise) TypeError: this.$refs.WMSpendentse.clear is not a function

**Comment by ghettovoice** [comment]
Hello @yyuri ,
wms source doesn't contain `clear` method, in OpenLayers and VueLayers.
Calling `refresh` should be enough to trigger reload of current layer extent

**Comment by yyuri** [comment]
Refresh() does not seem to be enough. Although you can see the layer refreshing you will only be able to see the new feature if you zoom in or out. If you go back to the initial zoom state it disappears, it is not there.
It looks like you are still seeing the cached tile, and if you reload the page the cache disappears and you'll see the added feature on any zoom level.

**WmsSource** is `/source/tilewms` on [OpenLayers](https://openlayers.org/en/latest/apidoc/module-ol_source_TileWMS-TileWMS.html) ?

If so, it appears to have clear() as an inherited method.

**Comment by ghettovoice** [comment]
Yes, `vl-source-wms` uses OpenLayers `ol/source/TileWMS` under the hood, but from v5.3.x https://github.com/openlayers/openlayers/blob/v5.3.x/src/ol/source/Tile.js#L293. In OpenLayers v5.3.x TileWMS hasn't `clear` method, but tileCache clear is called inside `refresh` method.

Take a look at the simple demo https://jsfiddle.net/ghettovoice/35bwtrma/. If you open console on Network tab, you can see, that on every `Reload` button click , tiles are reloading from the wms service.

Maybe you have some backend cache too? If so, you can try to avoid it by adding some GET param with unique value, each time you need to reload tiles.

**Comment by yyuri** [comment]
It does not look to be due to backend cache, I'm using geoserver, and it is disabled.

The refresh is not working as intended. I can set up a button as you did on the fiddle an click as many times, the layer will get refreshed but the cache does not get flushed.

The only improvement I've achieved is to set cache to 0, so now if I zoom in or out and return to the initial zoom state the new features does appear, which it does not happen if the cache is set by default. This confirms that the cache is not really cleared by refresh().

I've tried to getParams() and updateParams() way with some timestamp, but both functions are returning the same:

Uncaught (in promise) TypeError: this.$refs.WMSpendentse.updateparams is not a function

Sorry for be such a pain in the ass.

**Comment by ghettovoice** [comment]
In the current version not all methods are exported (this will be in upcoming next major release).
For a while any missed method you can call directly on openlayers object, for sources try: `this.$refs.WMSpendentse.$source.updateParams(...)`

**Comment by yyuri** [comment]
This worked out, many thanks!
