### ISSUE TITLE
 can't create a tileGrid with extent and resolutions

### ISSUE THREAD

**Issue by Juato2** [ghettovoice/vuelayers#316]
Hi, thanks for your excellent work.

My problem is the following. On my map I use a particular projection "EPSG: 25830" I have no problem with this. The problem I have when I use the <vl-source-wms> component, since the tileGrid object that is created internally does not use my "resolutions" matrix and this is fundamental since my map server is in Geoserver and uses GeoWebCache but always results in "geowebcache-cache-result: MISS". The case that does work for me in OpenLayers would be:

```javascript
const map = new Map({
    target: 'map',
    layers: [
        new TileLayer({
            title: "My Map",
            source: new TileWMS({
                url: "https://myserver/geoserver/wms",
                tileGrid: new TileGrid({
                    extent: extent,
                    resolutions: resolutions,  // <-- I need this
                }),
                params: {
                    LAYERS: "mylayer",
                    TILED: true
                }
            })
        })
    ],
    view: new View({
        projection: 'EPSG:25830',
        center: center,
        zoom: zoom,
        resolutions: resolutions,
    })
});
```

**Comment by ghettovoice** [comment]
Hello @Juato2 ,
unfortunately there is no easy way to provide your own tile grid in the current version. 
The only possibility I see: you need to make your own WMS source component and override tile grid factory in it. There is nothing hard, but additional component need. You can extend `vl-source-wms` to achieve this.

```html
<script>
  import { WmsSource } from 'vuelayers'
  import TileGrid from 'ol/tilegrid/TileGrid'

  export default {
    name: 'wms-source',
    extends: WmsSource,
    props: {
      resolutions: {
        type: Array,
        required: true,
      },
      extent: {
        type: Array,
        required: true,
      },
    },
    methods: {
      /**
       * Overrides tile grid factory https://github.com/ghettovoice/vuelayers/blob/v0.11.x/src/mixin/tile-source.js#L109 
       */
      createTileGrid () {
        return new TileGrid({
          extent: this.extent,
          resolutions: this.resolutions,
        })
      },
    },
  }
</script>
```

**Comment by ghettovoice** [comment]
From the v0.12.x it will be more easy to override this factory
