### ISSUE TITLE
How to authenticate a source vector tile?

### ISSUE THREAD

**Issue by seasick-pete** [ghettovoice/vuelayers#317]
Hi Vladimir,

Really great work on this :)

I've been trying to authenticate a vector tile layer which works when I turn authentication off on the backend, so I know the process overall works.

Would I need to extend the existing vl-source-vector-tile components' TileLoadFunction' for this or can this be handled in the template expression?

I've tried these various failed options , I think I am missing something.
```
<vl-source-vector-tile :url="working_url_when_no_auth_required" :token="<my-auth-token>"></vl-source-vector-tile>
<vl-source-vector-tile :url="working_url_when_no_auth_required" :authKey="<my-auth-token>></vl-source-vector-tile>
```

Again, thanks for a great project

**Comment by ghettovoice** [comment]
Hello @seasick-pete ,
I guess you use authentication with custom HTTP headers, right?
 So I think you can just  provide your custom tileLoadFunction `<vl-source-vector-tile :tile-load-function="myLoadFunc" ... />`.  Here is an example of such function https://openlayers.org/en/v5.3.0/apidoc/module-ol_source_VectorTile-VectorTile.html.

**Comment by seasick-pete** [comment]
Thanks very much for getting back to me, I see now how to apply the custom load function. Thank you Vladimir

**Comment by ghettovoice** [comment]
You are welcome
