### ISSUE TITLE
Large Bundle Size

### ISSUE THREAD

**Issue by ghansham** [ghettovoice/vuelayers#319]
I am using only three components namely map, tilelayer, wmssource. Still in the webpackbundle analyzer I am seeing all files getting packed with the build.
I am not using webpack.config.js.
I am using vuelayers 0.11.22.

Kindly help

**Comment by ghettovoice** [comment]
Hi @ghansham ,
I'm not check this for while, it was tree shakable some time ago.

I have just tried fresh install with vue-cli and can confirm that webpack don't eliminate dead code again. Currently i can't say what's going on, it just mark unused exports, but not remove them. This is always hard to debug why tree shaking broken again. For a while you can import components directly from `vuelayers/lib/....`. 

BTW Strictly speaking webpack's tree shaking is kind of bullshit for me, very unstable

**Comment by ghettovoice** [comment]
Found the reason vuejs/rollup-plugin-vue#344. 
Need to upgrade vue build tools vuejs/vue-component-compiler#96

**Comment by ghansham** [comment]
I tried to update vue-template-compiler. Following is my package.json. I am just starter in vue. So not very sure what you meant by upgrading vue build tools. Do I need to update some other package.



{
  "name": "test_vue",
  "version": "0.1.0",
  "private": true,
  "scripts": {
    "serve": "vue-cli-service serve",
    "build": "vue-cli-service build",
    "lint": "vue-cli-service lint",
    "generate-icons": "vsvg -s ./svg-icons -t ./src/compiled-icons"
  },
  "dependencies": {
    "axios": "^0.19.2",
    "core-js": "^3.6.4",
    "hammerjs": "^2.0.8",
    "moment-timezone": "^0.5.28",
    "node-fetch": "^2.6.0",
    "ol": "^6.3.1",
    "stylus-loader": "^3.0.2",
    "swiper": "^5.3.8",
    "vue": "^2.6.11",
    "vue-awesome-swiper": "^4.1.1",
    "vue-draggable-resizable": "^2.1.2",
    "vue-moment": "^4.1.0",
    "vue-svgicon": "^3.2.6",
    "vue-swipeable-bottom-sheet": "0.0.5",
    "vuedraggable": "^2.23.2",
    "vuelayers": "^0.11.22",
    "vuetify": "^2.2.28",
    "vuex": "^3.2.0",
    "xmldom": "^0.3.0",
    "xpath": "0.0.27"
  },
  "devDependencies": {
    "@vue/cli-plugin-babel": "~4.3.0",
    "@vue/cli-plugin-eslint": "~4.3.0",
    "@vue/cli-service": "~4.3.0",
    "babel-eslint": "^10.1.0",
    "eslint": "^6.7.2",
    "eslint-plugin-vue": "^6.2.2",
    "node-sass": "^4.13.1",
    "sass": "^1.26.3",
    "sass-loader": "^8.0.2",
    "stylus": "^0.54.7",
    "vue-cli-plugin-vuetify": "~2.0.5",
    "vue-template-compiler": "^2.6.11",
    "vuetify-loader": "^1.4.3"
  },
  "eslintConfig": {
    "root": true,
    "env": {
      "node": true
    },
    "extends": [
      "plugin:vue/essential",
      "eslint:recommended"
    ],
    "parserOptions": {
      "parser": "babel-eslint"
    },
    "rules": {}
  },
  "browserslist": [
    "> 1%",
    "last 2 versions",
    "not dead"
  ]
}


regards
Ghansham

**Comment by ghettovoice** [comment]
No, I need to rebuild vuelayers with updated vue compile tools, so the vuelayers components will have such annotations needed by webpack

**Comment by ghansham** [comment]
Okay. Then I will pick latest update vue layers from npm repo may be tomorrow or later..

**Comment by ghettovoice** [comment]
Yes, for a while you can directly import components that you need like :
```js
import Map from 'vuelayers/lib/map'
import TileLayer from 'vuelayers/lib/tile-layer'
....
```

**Comment by ghansham** [comment]
Yeah.. as of now I am doing that only...
