### ISSUE TITLE
Is it possible to set .svg icon fill & stroke colors

### ISSUE THREAD

**Issue by dan-an** [ghettovoice/vuelayers#320]
Hello @ghettovoice !

I wanted to use custom icon for map marker, but I can't set it's color.

My template:
```
<vl-feature v-if="searchPopupShow" id="marker">
                <vl-geom-point :coordinates="searchPopupPosition"></vl-geom-point>

                <vl-style-func :factory="styleMarker"></vl-style-func>
</vl-feature>
```

Style factory function:
```
private styleMarker(): any {
            return function __styleFunc(feature: API.Feature): any {

                const style = createStyle({
                    imageSrc: marker,
                    strokeColor: "#fff",
                    fillColor: "#000",
                });

                return [style];
            };
        }
```

`marker` in `imageSrc` is imported before, so default icon is rendering.

Thank you for great library)

**Comment by ghettovoice** [comment]
Hi @dan-an ,
if this is svg, why not just change colors inside this svg markup with xpath selectors?
This lib (and openlayers too) doesn't provide any functions to change what is inside your marker. 
In your example, fillColor, strokeColor will be used to render polygons and lines with defined colors.

**Comment by sjmallon** [comment]
I came a across this issue some time back, and found the basis of the solution in this [SO answer](https://stackoverflow.com/questions/43058070/openlayers-color-an-svg-icon).  Hence if you set the `fill` to white in your SVG, you can use `imageColor` as an option to `createStyle` to change the color in the style function.

**Comment by dan-an** [comment]
@ghettovoice i just thought those properties could affect passed svg.

@sjmallon thank you for solution, it worked!)
