### ISSUE TITLE
listen to features added in the vector layer

### ISSUE THREAD

**Issue by ghansham** [ghettovoice/vuelayers#321]
I am unable to listen to the features added into the vector layer when I click. Geometry passed is point. There are a couple of events in the mixin/feature-container.js. But at vector-source, I am unable to listen to these points.

**Comment by ghettovoice** [comment]
Hello @ghansham ,
I don't know your actual use case, but take a look at this demo https://jsfiddle.net/ghettovoice/qcrjzdwn/.
If you open console, you should see that add/remove event handlers are triggered.

**Comment by ghansham** [comment]
I want to keep only one feature at a time remove all the old features. Right now I am watching the featuresArray passed to the vector layer and removing them. But that is a very ugly way. I am right now able to listen to the add events. But dont know what is the elegant way of doing that.

**Comment by ghettovoice** [comment]
The vue ideomatic way would be to change array that is passed to `vl-source-vector`, if you need only one feature, you can use `this.features.splice(0, 1, newFeature)` to replace fist feature. Then `vl-source-vector` should synchronize map view with this prop array

**Comment by ghansham** [comment]
Yes I am doing splice in the watch for the features array. Is there a better place other than watch. I thought if I listen to add:feature event the feature length will reflect number if features but it is one less than that. So it didnt serve the purpose. Right now watching features array and limiting it to latest added feature.

**Comment by ghettovoice** [comment]
Watcher actually is same as event listener, expect that it triggers for any change of property it bound to. 
Another option would be to use computed property, something like this:

```js
<template>
  ...
  <vl-source-vector :features.sync="singleFeatureArr" />
  ...
</template>

<script>
export default {
  data () {
    return {
      features: [],
    }
  },
  computed: {
    singleFeatureArr: {
      get () {
        return this.features
      },
      set (features) {
        this.features = features.slice(0, 1)
      },
    },
  },
}
</script>
```

**Comment by ghansham** [comment]
Added a v-if to vl-source-vector to control whether user can add features by clicking or not. After first on-off-on, it loses track of feature sync array. Although features are getting added but I am getting feature array as undefined. This issue has started coming from 0.11.26 onwards. In 0.11.25, it is working well. I am not using 0.12 branch as of now. It will take me sometime to migrate to 0.12.

**Comment by ghettovoice** [comment]
@ghansham can you make a demo?

I have made myself with latest v0.11.28 https://jsfiddle.net/ghettovoice/qa8p913o/17/ and can't reproduce your issue.
Probably there is something else interfere with vl-source-vector synchronization.

**Comment by ghansham** [comment]
I will send you a demo code

**Comment by ghansham** [comment]
Use vl-interaction-draw. I  am trying to make one demo.
But could not
https://jsfiddle.net/ghanshamsangar/a3qLgurw/23/

**Comment by ghettovoice** [comment]
> We should gradually switch to 0.12

Yes, when it will be fully ready. But even in v0.12.x disabling through visibility or active is recommended, as I said, it avoids multiple recreation of openlayers instances, Vue components, that is obviously is more efficient.

**Comment by ghettovoice** [comment]
@ghansham I see. 
v0.11.x have known sync issues in such cases. 

To workaround I suggest to replace v-if with `:visible="enabled"` and `:active="enabled"`.  Same effect but less objects recreations.

```html
<vl-layer-vector id="probe-vector" :visible="enabled">
  <vl-source-vector
    ident="draw-target"
    :features.sync="features"
  ></vl-source-vector>
</vl-layer-vector>

<vl-interaction-draw
  :active="enabled"
  source="draw-target"
  type="point"
/>
```

**Comment by ghansham** [comment]
Thanks. So you mean.  We should gradually switch to 0.12 :-)

**Comment by ghansham** [comment]
Thanks. It worked. Too good..
