### ISSUE TITLE
Select newly drawn feature when drawend event fires

### ISSUE THREAD

**Issue by bejohu** [ghettovoice/vuelayers#322]
The method I tried is for selecting newly drawn features is this: `vl-interaction-draw` component fires `drawend` event, `mode` is set to `draw`.  To select the feature (`event.feature`) the call to `select` method of `vl-select-interaction` is delayed via `$nextTick`.

When using `vl-interaction-select` slot with `vl-style-box` the new feature disappears or custom styles are not applied: https://jsfiddle.net/nvaxt8z6/2/

Without custom styles in `vl-interaction-select` it appears to work just fine: https://jsfiddle.net/nvaxt8z6/3/

Also, the new feature appears not to have been added to synched `features` prop when `$nextTick` executes callback: https://jsfiddle.net/nvaxt8z6/4/

**Comment by ghettovoice** [comment]
Hi @bejohu ,
yep, I see here unsync problem. 
Thanks for response!

**Comment by ghettovoice** [comment]
Fixed. Here is your demo with latest version https://jsfiddle.net/ghettovoice/nacy6wfe/
