### ISSUE TITLE
About cache wms

### ISSUE THREAD

**Issue by Rih** [ghettovoice/vuelayers#323]
Hi @ghettovoice ,
I have a question. is there a way to cache image assets in image-wms loaded by vl-source component?

This is because, there are some layers with huge amount of "tiles" as png files to be loaded and its getting slow the render process inside the map. Actually it requests several hits to geoserver, changing the bbox params, perhaps can I change that way to load?
Thank you

**Comment by ghettovoice** [comment]
Hello @Rih ,
wms source and almost every source already cache loaded extents by default and don't reload them on zoom. 
To reduce requests number you can try to double tile size. And the best option is enable tile caching on the mapserver side, for example with pre-seeding of wms layers and switch to vl-source-xyz components.

**Comment by Rih** [comment]
Thank you @ghettovoice , I'll give a try to your suggestion
