### ISSUE TITLE
 Modification after polygon selection?

### ISSUE THREAD

**Issue by kireevRoman** [ghettovoice/vuelayers#326]
Hi! If there are a lot of polygons on the map. then how can I do it so that when using vl-interaction-modify, only the selected polygon can be changed. Like in this example https://openlayers.org/en/latest/examples/modify-features.html. Help please.

**Comment by ghettovoice** [comment]
Hello @kireevRoman ,
yes you can. 
Just provide vl-interaction-modify with source pointed to vl-interaction-select.
Here is a demo https://jsfiddle.net/ghettovoice/mhL08qya/

**Comment by kireevRoman** [comment]
Thanks! You helped me a lot
