### ISSUE TITLE
vuelayers/lib/ol-ext on 0.12.x version

### ISSUE THREAD

**Issue by empereira** [ghettovoice/vuelayers#336]
Hello @ghettovoice ,

In that version you no longer have the ol-ext options?

I upgraded to this version and it gave error in the import:

```import { findPointOnSurface } from 'vuelayers/lib/ol-ext';```

**Comment by ghettovoice** [comment]
Hello @empereira ,
I don't yet describe changes for v0.12.x.
There is a changes in package layout. Now you can import all stuff from `vuelayers/dist/...` (https://unpkg.com/browse/vuelayers@0.12.0-rc.0/dist/)

**Comment by empereira** [comment]
Nice!!! Thanks for the feedback @ghettovoice !!!
