### ISSUE TITLE
How to get current view extent ?

### ISSUE THREAD

**Issue by signmeuptwice** [ghettovoice/vuelayers#337]
I would like to get the current `vl-view` extent but not sure how to do it or if it is possible; can't find anything in the docs.

That would be great so I can create boundaries for my SQL request.

**Comment by ghettovoice** [comment]
Hello @signmeuptwice ,
bind a ref to the vl-view and then you can get extent with `this.$refs.view.$view.getExtent`. But take a note that extent will be in view projection (usually EPSG:3857).

If you need  view extent to load vector data only inside visible map area, there is more easy way to achieve this.

```html
<template>
  <vl-source-vector : strategy-factory="loadingStrategy" />
</template>

<script>
import {.bbox } from 'ol/loadingstrategy'

export default {
  methods: {
    loadingStrategy () {
      return bbox // loads current view extent
    }
  }
}
</script>
```

**Comment by signmeuptwice** [comment]
Hi @ghettovoice, thank you for the quick reply

I tried `this.$refs.myRef.$view.getExtent` but I get undefined
I also tried `this.$refs.myRef.$view.getExtent()` but it returns `not a function`

then I tried `this.$refs.myRef.$view.projection_.extent_` but the values are never updated so Im thinking there is an update issue.. ?

I also tried `{.bbox}` but had to change it to `{bbox}` then changed your code to `<vl-source-vector :strategy-factory="loadingStrategy" />` for it to compile then console logging `bbox` does not give me anything

I don't think the bbox thing is the right solution. What I am looking to get is just the coordinates of the four corners of the current view and it to be updated after zoom, move, etc...
So I need to get the extent and convert it to coordinates ?

**Comment by ghettovoice** [comment]
Take look here https://jsfiddle.net/ghettovoice/nLmq5vux/

**Comment by signmeuptwice** [comment]
Thank you so much !!

No time right now but I’ll take a look at it in the next days and let you know.

Would be great to see this as a native feature in a future update :)

Best regards,
Edouard

**Comment by signmeuptwice** [comment]
Hi,

Thanks for the help.

In order to make it work I had to copy locally and import the entire ol.js file which is 650kb ! So pretty big for a single function on the homepage :(( weback is also complaining about size.

Ideally I would need to just import the function and looking at the ol code in node modules it looks like the functions are exported however trying to import the function (import transformExtent from '../../../js/ol/ol.js’) gives VL-VIEW errors:

[Error] [Vue warn]: Error in v-on handler: "TypeError: _js_ol_ol_js__WEBPACK_IMPORTED_MODULE_4___default() is not a function. (In '_js_ol_ol_js__WEBPACK_IMPORTED_MODULE_4___default()(olView.calculateExtent(), 'EPSG:3857', 'EPSG:4326')', '_js_ol_ol_js__WEBPACK_IMPORTED_MODULE_4___default()' is an instance of Object)"

found in

---> <VlView> at view.vue
       <VlMap> at map.vue
         <LatestEventsComponent> at src/vue/component/home/latest-events.vue
           <HomeComponent> at src/vue/component/home/home.vue
             <Root>
	warn (vue-d9bd3e30d8903d038bd3.js:12193)
	logError (vue-d9bd3e30d8903d038bd3.js:13456)
	globalHandleError (vue-d9bd3e30d8903d038bd3.js:13451)
	handleError (vue-d9bd3e30d8903d038bd3.js:13411)
	invokeWithErrorHandling (vue-d9bd3e30d8903d038bd3.js:13434)
	invokeWithErrorHandling (vue-d9bd3e30d8903d038bd3.js:13426)
	(anonymous function) (vue-d9bd3e30d8903d038bd3.js:15455)
	(anonymous function) (18-d9bd3e30d8903d038bd3.js:31455)
	promiseReactionJob
[Error] TypeError: _js_ol_ol_js__WEBPACK_IMPORTED_MODULE_4___default() is not a function. (In '_js_ol_ol_js__WEBPACK_IMPORTED_MODULE_4___default()(olView.calculateExtent(), 'EPSG:3857', 'EPSG:4326')', '_js_ol_ol_js__WEBPACK_IMPORTED_MODULE_4___default()' is an instance of Object) — latest-events.vue:296
	logError (vue-d9bd3e30d8903d038bd3.js:13460)
	globalHandleError (vue-d9bd3e30d8903d038bd3.js:13451)
	handleError (vue-d9bd3e30d8903d038bd3.js:13411)
	invokeWithErrorHandling (vue-d9bd3e30d8903d038bd3.js:13434)
	invokeWithErrorHandling (vue-d9bd3e30d8903d038bd3.js:13426)
	(anonymous function) (vue-d9bd3e30d8903d038bd3.js:15455)
	(anonymous function) (18-d9bd3e30d8903d038bd3.js:31455)
	promiseReactionJob
[Error] [Vue warn]: Error in callback for watcher "zoom": "TypeError: _js_ol_ol_js__WEBPACK_IMPORTED_MODULE_4___default() is not a function. (In '_js_ol_ol_js__WEBPACK_IMPORTED_MODULE_4___default()(olView.calculateExtent(), 'EPSG:3857', 'EPSG:4326')', '_js_ol_ol_js__WEBPACK_IMPORTED_MODULE_4___default()' is an instance of Object)"

found in

---> <LatestEventsComponent> at src/vue/component/home/latest-events.vue
       <HomeComponent> at src/vue/component/home/home.vue
         <Root>
	warn (vue-d9bd3e30d8903d038bd3.js:12193)
	logError (vue-d9bd3e30d8903d038bd3.js:13456)
	globalHandleError (vue-d9bd3e30d8903d038bd3.js:13451)
	handleError (vue-d9bd3e30d8903d038bd3.js:13411)
	run (vue-d9bd3e30d8903d038bd3.js:16137)
	flushSchedulerQueue (vue-d9bd3e30d8903d038bd3.js:15877)
	(anonymous function) (vue-d9bd3e30d8903d038bd3.js:13552)
	flushCallbacks (vue-d9bd3e30d8903d038bd3.js:13478)
	promiseReactionJob
[Error] TypeError: _js_ol_ol_js__WEBPACK_IMPORTED_MODULE_4___default() is not a function. (In '_js_ol_ol_js__WEBPACK_IMPORTED_MODULE_4___default()(olView.calculateExtent(), 'EPSG:3857', 'EPSG:4326')', '_js_ol_ol_js__WEBPACK_IMPORTED_MODULE_4___default()' is an instance of Object) — latest-events.vue:296
	logError (vue-d9bd3e30d8903d038bd3.js:13460)
	globalHandleError (vue-d9bd3e30d8903d038bd3.js:13451)
	handleError (vue-d9bd3e30d8903d038bd3.js:13411)
	run (vue-d9bd3e30d8903d038bd3.js:16137)
	flushSchedulerQueue (vue-d9bd3e30d8903d038bd3.js:15877)
	(anonymous function) (vue-d9bd3e30d8903d038bd3.js:13552)
	flushCallbacks (vue-d9bd3e30d8903d038bd3.js:13478)
	promiseReactionJob
[Error] [Vue warn]: Error in callback for watcher "center": "TypeError: _js_ol_ol_js__WEBPACK_IMPORTED_MODULE_4___default() is not a function. (In '_js_ol_ol_js__WEBPACK_IMPORTED_MODULE_4___default()(olView.calculateExtent(), 'EPSG:3857', 'EPSG:4326')', '_js_ol_ol_js__WEBPACK_IMPORTED_MODULE_4___default()' is an instance of Object)"

found in

---> <LatestEventsComponent> at src/vue/component/home/latest-events.vue
       <HomeComponent> at src/vue/component/home/home.vue
         <Root>
	warn (vue-d9bd3e30d8903d038bd3.js:12193)
	logError (vue-d9bd3e30d8903d038bd3.js:13456)
	globalHandleError (vue-d9bd3e30d8903d038bd3.js:13451)
	handleError (vue-d9bd3e30d8903d038bd3.js:13411)
	run (vue-d9bd3e30d8903d038bd3.js:16137)
	flushSchedulerQueue (vue-d9bd3e30d8903d038bd3.js:15877)
	(anonymous function) (vue-d9bd3e30d8903d038bd3.js:13552)
	flushCallbacks (vue-d9bd3e30d8903d038bd3.js:13478)
	promiseReactionJob
[Error] TypeError: _js_ol_ol_js__WEBPACK_IMPORTED_MODULE_4___default() is not a function. (In '_js_ol_ol_js__WEBPACK_IMPORTED_MODULE_4___default()(olView.calculateExtent(), 'EPSG:3857', 'EPSG:4326')', '_js_ol_ol_js__WEBPACK_IMPORTED_MODULE_4___default()' is an instance of Object) — latest-events.vue:296
	logError (vue-d9bd3e30d8903d038bd3.js:13460)
	globalHandleError (vue-d9bd3e30d8903d038bd3.js:13451)
	handleError (vue-d9bd3e30d8903d038bd3.js:13411)
	run (vue-d9bd3e30d8903d038bd3.js:16137)
	flushSchedulerQueue (vue-d9bd3e30d8903d038bd3.js:15877)
	(anonymous function) (vue-d9bd3e30d8903d038bd3.js:13552)
	flushCallbacks (vue-d9bd3e30d8903d038bd3.js:13478)
	promiseReactionJob
[Error] [Vue warn]: Error in callback for watcher "coordinates": "TypeError: _js_ol_ol_js__WEBPACK_IMPORTED_MODULE_4___default() is not a function. (In '_js_ol_ol_js__WEBPACK_IMPORTED_MODULE_4___default()(olView.calculateExtent(), 'EPSG:3857', 'EPSG:4326')', '_js_ol_ol_js__WEBPACK_IMPORTED_MODULE_4___default()' is an instance of Object)"

found in

---> <LatestEventsComponent> at src/vue/component/home/latest-events.vue
       <HomeComponent> at src/vue/component/home/home.vue
         <Root>
	warn (vue-d9bd3e30d8903d038bd3.js:12193)
	logError (vue-d9bd3e30d8903d038bd3.js:13456)
	globalHandleError (vue-d9bd3e30d8903d038bd3.js:13451)
	handleError (vue-d9bd3e30d8903d038bd3.js:13411)
	run (vue-d9bd3e30d8903d038bd3.js:16137)
	flushSchedulerQueue (vue-d9bd3e30d8903d038bd3.js:15877)
	(anonymous function) (vue-d9bd3e30d8903d038bd3.js:13552)
	flushCallbacks (vue-d9bd3e30d8903d038bd3.js:13478)
	promiseReactionJob
[Error] TypeError: _js_ol_ol_js__WEBPACK_IMPORTED_MODULE_4___default() is not a function. (In '_js_ol_ol_js__WEBPACK_IMPORTED_MODULE_4___default()(olView.calculateExtent(), 'EPSG:3857', 'EPSG:4326')', '_js_ol_ol_js__WEBPACK_IMPORTED_MODULE_4___default()' is an instance of Object) — latest-events.vue:296
	logError (vue-d9bd3e30d8903d038bd3.js:13460)
	globalHandleError (vue-d9bd3e30d8903d038bd3.js:13451)
	handleError (vue-d9bd3e30d8903d038bd3.js:13411)
	run (vue-d9bd3e30d8903d038bd3.js:16137)
	flushSchedulerQueue (vue-d9bd3e30d8903d038bd3.js:15877)
	(anonymous function) (vue-d9bd3e30d8903d038bd3.js:13552)
	flushCallbacks (vue-d9bd3e30d8903d038bd3.js:13478)
	promiseReactionJob

**Comment by ghettovoice** [comment]
You should be able to import it like this: 

```js
import { transformExtent } from 'ol/proj'
```

**Comment by signmeuptwice** [comment]
Yes that works; damn I was so close… just the {} missing. Thanks for that.

Sorry to be a pain, hopefully you could help me on this too,

On the same map I am using this view extend; I am using this extent to display events in the area.

However the location of the event moves as I zoom; It is never on the right position unless zoomed maximum. Can you have a look ?

Here is my code:

https://gist.github.com/signmeuptwice/5480c8a6d298c33a502cd531b09bfb23

**Comment by ghettovoice** [comment]
Hmm, I don't see any errors in your code. I see that you use vl-overlay, if `d.longitude, d.latitude` are correct coordinates, then it's top left corner(default positioning) should point exactly to this coordinate, regardless of view zoom,  center, any other things.

Can you catch screen video with this issue?

**Comment by signmeuptwice** [comment]
Can’t take videos but here are some screenshots:

**Comment by signmeuptwice** [comment]
If I move the map the points are fixed

They move when I zoom more closer to their real location

**Comment by ghettovoice** [comment]
> Can’t take videos but here are some screenshots:

Don't see any screenshots...

**Comment by signmeuptwice** [comment]
Really ?? 

And now ?

**Comment by ghettovoice** [comment]
<img width="958" alt="Снимок экрана 2020-09-02 в 18 43 20" src="https://user-images.githubusercontent.com/4323000/92005459-2e66ae00-ed4c-11ea-9c35-c594a25737a1.png">

**Comment by ghettovoice** [comment]
You can send them to the ghettovoice@gmail.com

**Comment by signmeuptwice** [comment]
Sent to your email

**Comment by ghettovoice** [comment]
If I'm correctly understand, you reload data on each zoom.
Do you confirm that this 2 features from screenshots have same coordinates on each reload?

**Comment by signmeuptwice** [comment]
Yes, as the gist shows every time something changes, I have a timeout that triggers a data reload.

I double checked and yes same coordinates

**Comment by ghettovoice** [comment]
Frankly speaking I'm not fully understand from screenshots where is vl-overlay on them. 
Also screenshots showing two points, but I see in the gist that vl-geom-line-string used with vl-feature.
So what is actually green circles on the map?

**Comment by signmeuptwice** [comment]
Green circles are events locations on the map 

The overlay has this position where d is an event
:position="[d.longitude, d.latitude]"

**Comment by ghettovoice** [comment]
If I'm correctly understand your use case: you need to show some additional data by clicking on the event feature.
So propose more easier way to achieve this https://jsfiddle.net/ghettovoice/mu59o2yj/

**Comment by signmeuptwice** [comment]
No

my problem is that the dots are not displayed at the correct coordinates.

You see they move to different location when I zoom

**Comment by ghettovoice** [comment]
I guess that green dots are spans inside vl-overlay. I'm not see any vector feature styles in your example.
And how this span positioned inside vl-overlay out of the scope of the VueLayers.

Anyway using vl-overlay in this way looks for me a bit unusual use of vl-overlay. So I show you in the demo how to achieve same functionality. 
To show event dots you only need vector layer and source, to which you pass an array of loaded event features (encoded in GeoJSON format). To catch the event select and react on this you can use vl-interaction-select that can sync selected features to some data property. Then just use Vue wather, prepare data, show vl-overlay as event popup, or show additional layer with event lines (vl-feature vl-geom-line-string in your gist).
Take a look at this demo https://jsfiddle.net/ghettovoice/mu59o2yj/ (updated with additional event lines layer)

**Comment by signmeuptwice** [comment]
Thanks, ill have a look,

It is not possible to send you video, your server refuses files too big

My video is 5.9M; that is not big...

**Comment by ghettovoice** [comment]
> It is not possible to send you video, your server refuses files too big

This is gmail. Maybe it have some restrictions on this. 
Do you have google drive? Can you share though it?

**Comment by signmeuptwice** [comment]
That’s ok it went through now

**Comment by ghettovoice** [comment]
Try to temporary replace <vl-overlay>...</vl-overlay> in your code with this.

```html
<vl-feature
  v-if="uid"
  v-for="(d, index) in data"
  :id="'data-'+uid+index"
  :key="'data-'+uid+index"
>
  <vl-geom-point :coordinates="[d.longitude, d.latitude]" />
</vl-feature>
```

You should see this two points in the correct place on any zoom

**Comment by signmeuptwice** [comment]
Sorry but replace … ?

**Comment by signmeuptwice** [comment]
Sorry I got it

Thanks a million; it seems to work !!!
 :))))

**Comment by ghettovoice** [comment]
Anyway I strongly recommend to not use vl-feature for multiple features, because due to how Vue works with components (they always have some element in the real DOM) they have a performance issues.
Also vl-feature not inside vl-source-vector are appended to the internal default map overlay (that is always shown on top of any other normal layers), so they can't be selectable with vl-interaction-select for example. The basic use case for vl-feature not in the vl-source-vector is show some single marker, for example user location, search result pin and so on. 
To show some set of features, it is recommended to use separate vl-layer-vector/vl-source-vector like in the demo.

**Comment by signmeuptwice** [comment]
Thank you

I will look at implementing your example.

**Comment by signmeuptwice** [comment]
I implemented vectors as you said.
It works great.

Thanks for all your help :)

When the site is up I let you know
