### ISSUE TITLE
choropleth

### ISSUE THREAD

**Issue by empereira** [ghettovoice/vuelayers#340]
hi,

Would the vuelayers have a choropleth or just through the pure openlayers js?

**Comment by ghettovoice** [comment]
Hello @empereira ,
choropleth is just a special styling of vector features.
So just you need to write a custom style function, this is possible with vuelayers and very similar to openlayers.

Here is another example that can show you how to set style function https://jsfiddle.net/ghettovoice/9yx5Lfj1/
