### ISSUE TITLE
windmap

### ISSUE THREAD

**Issue by ghansham** [ghettovoice/vuelayers#343]
Do we have an example of windmap using vue layers?
http://esri.github.io/wind-js/

regards
Ghansham

**Comment by ghettovoice** [comment]
Hello @ghansham ,
I have found integration of wind-js as a layer for openlayers https://github.com/sakitam-fdd/wind-layer
And here is a demo with VueLayers https://jsfiddle.net/ghettovoice/2hmdpuLv/.

You can also build wind-layer component based on layer mixins from vuelayers package, so it can be used as a template tag.

**Comment by ghansham** [comment]
Thanks a ton. I will give it a try.
