### ISSUE TITLE
vector tile sources in latest version for ol6

### ISSUE THREAD

**Issue by aliciahogue** [ghettovoice/vuelayers#346]
Previously, I would just pass the url to vl-source-vector-tile in the format below and all worked great, but cant seem to get anything to display in latest version.  No request is made, no error is thrown, etc.. Am I missing something basic?  The layer and source show up in vue dev tools.

"/mvt/vi_bounds/marine_regions-625/{z}/{x}/{y}"

**Comment by aliciahogue** [comment]
to follow up, if I call the setUrl function on the source once created, then all works as intended

**Comment by ghettovoice** [comment]
@aliciahogue thanks for report!
It seems as bug, I'll try to fix it soon.
