### ISSUE TITLE
listening to changes in ol-view

### ISSUE THREAD

**Issue by ghansham** [ghettovoice/vuelayers#347]
I am trying to listen to the changes in view within map. Unable to do that. As per the openlayers documentation, it fires following events:

Fires:
change (module:ol/events/Event~BaseEvent) - Generic change event. Triggered when the revision counter is increased.
change:center (module:ol/Object.ObjectEvent)
change:resolution (module:ol/Object.ObjectEvent)
change:rotation (module:ol/Object.ObjectEvent)
error (module:ol/events/Event~BaseEvent) - Generic error event. Triggered when an error occurs.
propertychange (module:ol/Object.ObjectEvent) - Triggered when a property is changed.

https://openlayers.org/en/latest/apidoc/module-ol_View-View.html

regards
Ghansham

**Comment by ghettovoice** [comment]
Hello @ghansham ,
`change:*` events usually have an watchable property in VueLayers.
So you can use std Vue API to react on `center`, `zoom`, `resolution`, .. changes.

```html
<template>
  <vl-view :center.sync="center" :resolution.sync="resolution" :rotation.sync="rotation" />
</template>

<script>
export default {
  data () {
    return {
      center: [0, 0],
      resolution: 123123123,
      rotation: 0,
    }
  },
  watch: {
    center (val, prev) {
      // react on change
    },
    resolution (val, prev) {
      // react on change
    },
    rotation (val, prev) {
      // react on change
    },
  },
}
</script>
```

If you want you can replace `.sync` modifier with event binding

```html
<vl-view @update:center="val => {}" @update:resolution="val => {}" ... />
```

https://vuejs.org/v2/guide/components-custom-events.html#sync-Modifier

**Comment by ghansham** [comment]
Thanks Sir. I will attempt method approach. I am sure it will work
