### ISSUE TITLE
How to set color and style of a geom-point?

### ISSUE THREAD

**Issue by littlefinger42** [ghettovoice/vuelayers#35]
```
            <vl-feature v-if="geoloc.position" id="geoloc-feature">
              <vl-geom-point class="hello" :coordinates="geoloc.position"></vl-geom-point>
              <vl-style-box>
                <vl-style-stroke :color="colour" :width="3"></vl-style-stroke>
                <vl-style-fill :color="colour"></vl-style-fill>
              </vl-style-box>
            </vl-feature>
```

colour is a string #ff0000
What am i doing wrong? The icon has disapeared from my map when i apply the stylebox.
Looks good following the documentation and example..

**Comment by ghettovoice** [comment]
Hi! You should wrap `vl-style-stroke` and `vl-style-fill` into `vl-style-circle` (or `vl-style-icon`) component to style point geometries like in OpenLayers.

**Comment by littlefinger42** [comment]
'<vl-feature v-if="geoloc.position" id="geoloc-feature">
              <vl-geom-point class="hello" :coordinates="geoloc.position"></vl-geom-point>
              <vl-style-box>
                <vl-style-circle>
                  <vl-style-stroke :color="colour"></vl-style-stroke>
                </vl-style-circle>
              </vl-style-box>
            </vl-feature>'

Great! Thanks a bunch.
