### ISSUE TITLE
vuelayers 0.12 on Android iOS interactive does not work

### ISSUE THREAD

**Issue by Informateur** [ghettovoice/vuelayers#351]
I have successfully migrated from version 0.11 using PC browsers. On Android iOS, the map is loaded with all geojson data, the zoom + - buttons work. Does not react to finger input in any way. Can you tell me how to fix this?
Only Android Chrome works. Other browsers don't. Doesn't work anywhere on iOS.

**Comment by ghettovoice** [comment]
Hello @Informateur ,
check this issue from OpenLayers https://github.com/openlayers/openlayers/issues/11366.
