### ISSUE TITLE
Two icon merge is possible

### ISSUE THREAD

**Issue by ramazanulucay** [ghettovoice/vuelayers#352]
Hi,

I want to use two icon for each point. Is it possible? 

Thanks.

**Comment by ghettovoice** [comment]
Hello @ramazanulucay ,
yes, sure.

There are several ways to achieve this:

- if those points inside single layer -> use style function to dynamically style based on some feature properties (id, any other custom properties) 
  There is an old example https://jsfiddle.net/ghettovoice/m3j0zydr/. It shows how to color svg icons based on some feature property with `vl-style-func` component.

- if those points in a separate layers -> just define style for each layer with corresponding
```html
<vl-layer-vector id="one">
  <vl-source-vector :features="layerOneFeatures" />
  <vl-style-box>
    <vl-style-icon :src="//exmaple.com/marker1.png"></vl-style-icon>
  </vl-style-box>
</vl-layer-vector>

<vl-layer-vector id="two">
  <vl-source-vector :features="layerTwoFeatures" />
  <vl-style-box>
    <vl-style-icon :src="//exmaple.com/marker2.png"></vl-style-icon>
  </vl-style-box>
</vl-layer-vector>
```

**Comment by ramazanulucay** [comment]
Thank you @ghettovoice
