### ISSUE TITLE
Using different projections in 0.12.x

### ISSUE THREAD

**Issue by Soren-Knudsen** [ghettovoice/vuelayers#356]
I'm having some trouble upgrading my current solution with `0.11.x` to `0.12.x`.  My working solution with `0.11.x` is depicted below together with my first try on upgrading to `0.12.x`.

**Version 0.11.x**
```javascript
<vl-map ref="map" projection="EPSG:25832">
  <vl-view
    ref="view"
    projection="EPSG:25832"
    :zoom.sync="zoom"
    :extent="extent"
    :center.sync="center"
    :resolutions="resolutions"
    :enable-rotation="false"
  ></vl-view>
  <vl-layer-tile :z-index="0">
    <vl-source-wmts
      projection="EPSG:25832"
      :url="url"
      :resolutions="resolutions"
      :matrix-ids="matrixIds"
      :style-name="styleName"
      :layer-name="layerName"
      :matrix-set="matrixSet"
    ></vl-source-wmts>
  </vl-layer-tile>
  <vl-layer-vector  z-index="1">
    <vl-source-vector :features="features" projection="EPSG:4326"></vl-source-vector>
  </vl-layer-vector>
</vl-map>
```

After some fiddling, I added the `data-projection="EPSG:25832"` and `tile-grid-factory` _(because the matrix ids are strings)_ which made the background layer work but I still can get my vector layer to render? It seems to be ignoring the `projection` on `vl-layer-vector` when converting the `GeoJson` objects to `Features`?

**Version 0.12.0-rc.4**
```javascript
<vl-map data-projection="EPSG:25832">
    <vl-view
    :projection="EPSG:25832"
    :zoom.sync="zoom"
    :extent="extent"
    :center.sync="center"
    :resolutions="resolutions"
    :enable-rotation="false"
    ></vl-view>
    <vl-layer-tile :z-index="0">
    <vl-source-wmts
        :projection="EPSG:25832"
        :url="url"
        :style-name="styleName"
        :layer-name="layerName"
        :tile-grid-factory="tileGridFactory"
        :matrix-set="matrixSet"
    ></vl-source-wmts>
    </vl-layer-tile>
    <vl-layer-vector :z-index="1">
      <vl-source-vector :features="features" projection="EPSG:4326"></vl-source-vector>
    </vl-layer-vector>
</vl-map>
```

**Comment by ghettovoice** [comment]
Hello @Soren-Knudsen ,
thanks for response. 
I found that there is incorrect data projection resolving in source components.

Wait a bit, I will publish a patched version

**Comment by Soren-Knudsen** [comment]
@ghettovoice: Awesome, thanks for a quick reply 👍

**Comment by ghettovoice** [comment]
@Soren-Knudsen  upgrade please

**Comment by Soren-Knudsen** [comment]
@ghettovoice: The fix works! 👍 

I stumbled upon another issue with either the `z-index` or when the rendering is triggered. The `features` are not rendered when the map first loads. If I manually clear the `features` list and add the items again after the map is mounted the features renders as expected.  

```javascript
<vl-layer-vector :z-index="1">
    <vl-source-vector :features="features" projection="EPSG:4326"></vl-source-vector>
</vl-layer-vector>
```

**Comment by ghettovoice** [comment]
I don't see any problems with this in my local setup.
Maybe you forget to register EPSG:25832 projection with proj4.
Can you show full code?

**Comment by ghettovoice** [comment]
> I will create an example

Yes, it would be helpful. 
I tried through data property and through computed. Actually there is no difference between them for vl-source-vector component.

**Comment by Soren-Knudsen** [comment]
Hi @ghettovoice 

I looked into the issue. When the vector layer first renders, the `currentFeaturesViewProj` uses a wrong projection. If I after the map is rendered, triggers a change (The `features` property above) `currentFeaturesViewProj` is recalculated with the correct projection. That is why the features are not a shown on the map.

**Comment by ghettovoice** [comment]
Ok, let me check

**Comment by ghettovoice** [comment]
Do you sure that features in the correct projection at the start?
 They should be in the resolved data projection, you can check `resolvedDataProjection` of the `vl-source-vector`. In your case it should be `EPSG:4326`.

I'm still not see any problems with this. I have made simple demo with different projections on components https://jsfiddle.net/ghettovoice/8upykq9g/. Maybe I missed something meaningful in your use case...

**Comment by Soren-Knudsen** [comment]
@ghettovoice, I tried to recreate the issue in jsfiddle - Please have a look https://jsfiddle.net/75fyx10a/1/ . If e.g. wrap the code in the `created` hook with a `timeout` the data gets rendered.

**Comment by ghettovoice** [comment]
Thanks, now I got it. 
Publishing fixed release...

**Comment by Soren-Knudsen** [comment]
@ghettovoice Awesome! The demo works!  I tried it on the actual solution where I get one step closer 🙌 The solution renders the map and afterward throws an exception and the map is blank. The exception below.

![image](https://user-images.githubusercontent.com/25668704/95368882-fddbdc00-08d6-11eb-8f77-5bce1e01699d.png)

**Comment by ghettovoice** [comment]
This is interesting... I didn't saw any problems with this.

Post me your code pls. Especially the place where "The solution renders the map after bumping"
