### ISSUE TITLE
textFontSize, textFontWeight not being applied in v12

### ISSUE THREAD

**Issue by aliciahogue** [ghettovoice/vuelayers#365]
The properties are listed, but the style.js is missing the portion that handles it otherwise.

-- from v11 which is missing in v12
 
  let fontSize = '10px'
  if (vlStyle.textFontSize) {
    fontSize = isNumber(vlStyle.textFontSize) ? vlStyle.textFontSize + 'px' : vlStyle.textFontSize
  }
  let fontName = vlStyle.textFont || 'sans-serif'
  const font = [vlStyle.textFontWeight, fontSize, fontName].filter(x => !!x).join(' ')

**Comment by ghettovoice** [comment]
Hi @aliciahogue ,
yes, in v0.12 all this separate options was merged into single `textFont` like in OpenLayers `font` option for `ol/style/Text`. https://openlayers.org/en/latest/apidoc/module-ol_style_Text-Text.html

So just you need font description string yourself as you need like in CSS. 
https://developer.mozilla.org/en-US/docs/Web/API/CanvasRenderingContext2D/font
https://developer.mozilla.org/en-US/docs/Web/CSS/font

**Comment by webcdh** [comment]
你好，我发现你们的地图重新渲染有问题，你们可以测试一下  重新渲染地图和只画一个图形（圆形，多边形等）
