### ISSUE TITLE
Map  Bug 

### ISSUE THREAD

**Issue by webcdh** [ghettovoice/vuelayers#366]
refresh()
Returns: {Promise<void>}
Updates map size and re-renders map.

render()
Returns: {Promise<void>}
Request a map rendering (at the next animation frame).

These two functional modules seem to be imperfect, and there is no change before and after use. Using native openlayers will work

**Comment by ghettovoice** [comment]
Hello @webcdh ,
do you have code sample? And which vuelayers version?

Actually `render` is a wrapper around `ol/Map#render()` method. And `refresh` a wrapper around `render` + `updateSize` methods. So it is a bit strange that it is not work while native openlayers call works.
