### ISSUE TITLE
imageloaderror event on vl-source-tile-wms

### ISSUE THREAD

**Issue by aliciahogue** [ghettovoice/vuelayers#371]
Is this expected to fire  on vl-source-tile-wms?

@imageloaderror="handleError"  

the event only seems to fire when I subscribe to it manually from the ol $source

** I did try @update:imageloaderror and @change:imageloaderror  as well.

**Comment by ghettovoice** [comment]
vl-source-tile-wms fires tile related events:

- `tileloadstart`
- `tileloadend`
- `tileloaderror`

`imageloaderror` is fired by image source like vl-source-image-wms, vl-source-image-static and so on.
Image source fires those events:

- `imageloadstart`
- `imageloadend`
- `imageloaderror`

This is true for vuelayers v0.12.x. Those events are similar to OpenLayers events

**Comment by aliciahogue** [comment]
oh my.. hahaha.  When I referenced it manaually I was using tileloaderror

this.$refs.mapSource.$source.once('tileloaderror', this.handleError);

but on the component must have been trying to use imageloaderror.   Thank you!!!
