### ISSUE TITLE
Any plans to support vue3

### ISSUE THREAD

**Issue by yuanqiangxie** [ghettovoice/vuelayers#377]
This is an awesome package. do you have a plan to support vue3?

**Comment by ghettovoice** [comment]
Hello @yuanqiangxie ,
yes I have such plans.
But for now I don't much time even to just try run vuelayers with vue 3.

**Comment by alci63** [comment]
Would be great...

**Comment by MelihAltintas** [comment]
i have been using vuelayers for a long time. Since I was very impressed, I made a very similar one for vue3, you can use it. https://github.com/MelihAltintas/vue3-openlayers

**Comment by MelihAltintas** [comment]
@alci63 @yuanqiangxie  https://vue3openlayers.netlify.app/   https://github.com/MelihAltintas/vue3-openlayers
