### ISSUE TITLE
点击例子里的按妞点击没反应

### ISSUE THREAD

**Issue by wincentytg** [ghettovoice/vuelayers#38]
vue.runtime.esm.js?35e2:587 [Vue warn]: Property or method "polygonCoords" is not defined on the instance but referenced during render. Make sure that this property is reactive, either in the data option, or for class-based components, by initializing the property. See: https://vuejs.org/v2/guide/reactivity.html#Declaring-Reactive-Properties.

**Comment by wincentytg** [comment]
有没有基本例子的demo啊？

**Comment by ghettovoice** [comment]
Hi, @wincentytg !
Can explain what you trying to do in English, please
As I can see you have problem with data property definition ,but can't understand how it is related with VueLayers lib

**Comment by ghettovoice** [comment]
Close due to inactivity
