### ISSUE TITLE
issue with label placement in feature

### ISSUE THREAD

**Issue by ghansham** [ghettovoice/vuelayers#381]
Dear Sir

I am trying to draw concentric circles. And I want to place their labels on the circle boundary.
I am trying to  use placement="line" property mentioned in:

https://openlayers.org/en/latest/examples/vector-labels.html
My template section in the .vue file is as follows.

<vl-feature v-for="rc in radii_captions" :key="rc.caption" :id="rc.caption">
        <vl-geom-circle :radius="rc.radius" :coordinates="[center[0], center[1]]" />
        <vl-style-box>
            <vl-style-stroke color="#423e9e" :width="2"></vl-style-stroke>
            <vl-style-fill :color="[0, 0, 0, 0]"></vl-style-fill>
            <vl-style-text placement="line" :text="rc.caption"> </vl-style-text>
        </vl-style-box>
    </vl-feature>

It  is giving some exception:
Uncaught TypeError: ends is undefined
    drawText TextReplay.js:171
    renderCircleGeometry vector.js:84
    renderFeatureInternal vector.js:138
    renderFeature vector.js:115
    renderFeature$1 VectorLayer.js:400
    render VectorLayer.js:351
    prepareFrame VectorLayer.js:368
    renderFrame Map.js:157
    renderFrame_ PluggableMap.js:1226
    animationDelay_ PluggableMap.js:189

Digging deep I found that when placement gets updated, it is updating font. 
I am using 0.11.25.

regards
Ghansham

**Comment by ghansham** [comment]
I am trying this with 0.11.28 but unsuccessful.

<vl-feature v-for="rc in radii_captions" :key="rc.caption" :id="rc.caption">
        <vl-geom-circle :radius="rc.radius" :coordinates="[center[0], center[1]]" />
        <vl-style-box>
            <vl-style-stroke color="#423e9e" :width="2"></vl-style-stroke>
            <vl-style-fill :color="[0, 0, 0, 0]"></vl-style-fill>
            <vl-style-text text="qwerty" placement="line"></vl-style-text>
        </vl-style-box>
    </vl-feature>
And I want different captions for different circles

**Comment by ghettovoice** [comment]
Because `vl-geom-circle` create `ol/geom/Circle` geometry instance which not work with text line placement.
You should use `vl-geom-polygon` and make a circular polygon from circle center and radius. For geojson geometries you can use great gis lib `turf`, there is a helper `circle` that can make circular polygons http://turfjs.org/docs/#circle.

As for dynamic captions, just bind you caption data to the `:text` input proerty:

```html
<vl-feature v-for="rc in radii_captions" :key="rc.caption" :id="rc.caption">
        <vl-geom-polygon :coordinates="makeCircleCoords(rc.center, rc.radius)" />
        <vl-style-box>
            <vl-style-stroke color="#423e9e" :width="2"></vl-style-stroke>
            <vl-style-fill :color="[0, 0, 0, 0]"></vl-style-fill>
            <vl-style-text :text="rc.caption" placement="line"></vl-style-text>
        </vl-style-box>
    </vl-feature>

<script>
import makeCircle from '@turf/circle'

export default {
  methods: {
    makeCircleCoords (center, radiusKm) {
      const feature = makeCircle(center, radius, { units: 'kilometers' })
     return feature.geometry.coordinates
    },
  },
}
</script>
```

**Comment by ghansham** [comment]
I must appreciate that you gave a solution. This is bad at ol end. They
should have supported simple geometries.
