### ISSUE TITLE
rc14 toggle declutter on layer removes style on layer

### ISSUE THREAD

**Issue by aliciahogue** [ghettovoice/vuelayers#383]
`   <vl-layer-vector-image
      :declutter="cfg.declutter"
      ref="labelLayer"
      :min-zoom="7"
      v-bind="pointsLayer"
      @mounted="setContextMenu"
      :id="`${value.id}-labels`"
      :update-while-interacting="true">
      <vl-source-vector ref="labelSource"></vl-source-vector>
      <vl-style-func ref="labelStyle" :func="vesselLabelStyle"></vl-style-func>
    </vl-layer-vector-image>`

if I add a watcher with this code, things work correctly

`mapVm.$map.once('rendercomplete', e => {
          this.$refs.labelStyle.scheduleRemount();
        });

        mapVm.$map.renderSync();`

Initial declutterd labels
![initial-view](https://user-images.githubusercontent.com/4161629/98450993-29412900-2118-11eb-9776-492b326bf915.jpg)

after toggle declutter off
![toggle-declutter-off](https://user-images.githubusercontent.com/4161629/98450995-31996400-2118-11eb-9dfd-b527a2e3c4a2.jpg)

**Comment by ghettovoice** [comment]
Hello @aliciahogue ,
thanks for report!

Can you try to temporarily switch to the `dev` tag and try with it?
```
npm install vuelayers@dev
```

**Comment by ghettovoice** [comment]
Also change in vl-style-func component props: `:func` is renamed to the `:function`
