### ISSUE TITLE
TypeError in loaderFactory

### ISSUE THREAD

**Issue by sh-aix** [ghettovoice/vuelayers#386]
Hey there,

I am using a loader function in a vector source for loading Features. It works once but then I usually receive this error:
Uncaught (in promise) TypeError: loader is not a function

I am defining it the following way 
`layer.source.loaderFactory = function (extent, resolution, projection) {...}`

and register it in the vector source component with 
`:loader-factory="layer.source.loaderFactory"`

In my understanding, the function should be executed if the extent changes. The strategyFactory is set to loadingBBox.

Am I missing something here?

**Comment by ghettovoice** [comment]
Hello @sh-aix ,
which version of VueLayers do you using?

I can't reproduce this with v0.11.x https://jsfiddle.net/ghettovoice/qa8p913o/122/
Can you provide a demo or full code sample?

**Comment by sh-aix** [comment]
Ah now it works. I changed the loader factory to:
`layer.source.loaderFactory = function loader() {
        return (extent, resolution, projection) =>  {...}}`

Thanks!
