### ISSUE TITLE
The property `pixel` of pointermove event doesn't exist

### ISSUE THREAD

**Issue by vvizden** [ghettovoice/vuelayers#387]
Hi,

I try to get the pixel when the pointermove event is fired, but it doesn't exist.

Please check out my [demo](https://codepen.io/vviz/pen/mdEaZgb).

**Comment by ghettovoice** [comment]
Hello @vvizden ,
ol's team change signature of the MapBrowser events. 
It is now defined with pixel/coordinate as js getter and not catched by spread operator in my listener.

Thanks for report!

**Comment by ghettovoice** [comment]
Try install from `dev` tag for some time.
`npm install vuelayers@dev`

**Comment by ghettovoice** [comment]
Try install from `dev` tag for some time.
`npm install vuelayers@dev`

**Comment by vvizden** [comment]
I'll use `pixel_` for now, and waiting for your stable version.

Thank you!
