### ISSUE TITLE
Bing source?

### ISSUE THREAD

**Issue by fnoop** [ghettovoice/vuelayers#39]
Would it be possible to add support for bing source?
http://openlayers.org/en/latest/examples/bing-maps.html?q=bing

**Comment by ghettovoice** [comment]
Hi, @fnoop!
Yes, it's possible. I plan the next release on this week and can include bing source

**Comment by fnoop** [comment]
Great, thanks for such a great library!
I've had some problems getting started, mostly due to lack of documentation.  Where is the best place to discuss this and see if I can help out a bit?

**Comment by ghettovoice** [comment]
Yes, currently documentation is poor. With the next release I also will publish the new documentation based on [docsify](https://docsify.js.org/), this make it easy to describe all components.
There is an issue about documentation #34.

**Comment by ghettovoice** [comment]
[vl-source-bing-maps](https://vuelayers.github.io/#/component/bing-maps-source) now available, try with [0.10.1](https://github.com/ghettovoice/vuelayers/releases/tag/v0.10.1) version.
Now close this, re-open if you have questions.

**Comment by fnoop** [comment]
Great!  But I think the usage section in the docs is incomplete?
https://github.com/ghettovoice/vuelayers/blob/master/docs/component/bing-maps-source.md
The online doc site is not working, perhaps you're still refreshing it for the new release?

**Comment by fnoop** [comment]
Yes working now, and the usage doc is great now it's viewed through docsify.  When viewed in github markdown, it's missing the component use.
Thanks :)
