### ISSUE TITLE
CanceledError: VlOverlay ol object lifecycle canceled

### ISSUE THREAD

**Issue by vvizden** [ghettovoice/vuelayers#390]
Hi,

i want to pop up something on the feature by hover,

but when using the `v-if` on the `vl-overlay`, and the pointer moves back and forth quickly, the CanceledError appeared.

```
Uncaught (in promise) CanceledError: VlOverlay.1568c449-6b5e-464d-b969-88e1198bbfb3 ol object lifecycle canceled
```

Replace `v-if` with `v-show`, it is ok.

[Demo](https://codepen.io/vviz/pen/mdEaZgb) is here.But something seems wrong with `codepen`, because it doesn't work with the `vl-overlay`.

**Comment by ghettovoice** [comment]
Hello @vvizden ,
thanks for report!

This issue should be resolved in v0.12.0-rc.15. Try to reinstall with `npm install vuelayers@next`
