### ISSUE TITLE
Attribute-based styling of features

### ISSUE THREAD

**Issue by sh-aix** [ghettovoice/vuelayers#392]
Hey there,

is it possible to do an attribute-based styling, e.g. based on a property of the feature?

I am using a vl-style-text and like to adjust the text according to the feature:

`"vl-style-text": {
              "text": "3A",
              "font": "15px FontAwesome",
              "fill": {
                "color": "#2355af"
              },
              "stroke": {
                "color": "white"
              }
            }`

Thanks,
Stefan

**Comment by ghettovoice** [comment]
Hello @sh-aix ,
you should use vl-style-func component for dynamic styling. 
There is an example https://jsfiddle.net/ghettovoice/wxf43djb/
