### ISSUE TITLE
Error in data projection

### ISSUE THREAD

**Issue by syanguo** [ghettovoice/vuelayers#395]
Hi, I fetch the last update of Current 0.12 version, finding the features are disappear in the vl-feature, vl-layer-vector vl-interaction-draw when the data-projection added in the vl-map.

**Comment by ghettovoice** [comment]
Hello @syanguo ,
can you provide example?

Usually you don't need vl-feature drawing features, because newly drawn features automatically synchronized to the target source. So I need to look at your use case to understand what's wrong with this.

**Comment by syanguo** [comment]
Now it's ok when you update the  features-container.js , Thank you !
