### ISSUE TITLE
When I draw feature drawnFeatures array doesn't change

### ISSUE THREAD

**Issue by Nikitoring** [ghettovoice/vuelayers#396]
Example of my code https://codesandbox.io/s/drawendvuelayers-cflg9?file=/src/App.vue
emit `drawend` doesn't change drawFeaturesFrom array.
When I don't use composition-api, emit `drawend` changes array if there are more than one drawn features

**Comment by ghettovoice** [comment]
Hello @Nikitoring ,
something wrong with your demo 
<img width="1110" alt="Снимок экрана 2020-12-07 в 12 18 57" src="https://user-images.githubusercontent.com/4323000/101333465-b39bba80-3887-11eb-8539-2f67a8d12a15.png">

In my demo I don't see any problems with synchroniation between drawend and drawn features array.
https://jsfiddle.net/ghettovoice/Ln9qr135/110/

Can you fix your demo?

**Comment by Nikitoring** [comment]
Hello, @ghettovoice I fixed my demo https://codesandbox.io/s/drawendvuelayers-cflg9?file=/src/components/Map.vue 
It works if my drawend function looks like:
```
    const endDraw = ({ json }) => {
      console.log("new feature", json);
      console.log("drawn features", drawFeaturesFrom);
    };
```
![Screenshot_2020-12-07 CodeSandbox](https://user-images.githubusercontent.com/50715463/101350534-29138500-38a0-11eb-9e40-4697c9d9fe41.png)

Thanks a lot

**Comment by Nikitoring** [comment]
It works when drawn features is more one

**Comment by ghettovoice** [comment]
@Nikitoring 

This part is for v0.12.x.

```
({ json }) => {
      console.log("new feature", json);
      console.log("drawn features", drawFeaturesFrom);
    };
```

But as I understand you are using v0.11.x. And there was a bug, thanks for report! 
Upgrade to the v0.11.29
