### ISSUE TITLE
Global data projection doesn't work for maps

### ISSUE THREAD

**Issue by fnoop** [ghettovoice/vuelayers#40]
Docs here: https://github.com/ghettovoice/vuelayers/blob/master/docs/quickstart.md#global-data-projection
say that this should set data projection:
```
Vue.use(VueLayers, {
  dataProjection: 'EPSG:4326'
})
```

However, this doesn't work for this use:
```
vl-map(ref="map" :load-tiles-while-animating="true" :load-tiles-while-interacting="true", :controls="{attribution: false, zoom: true}")
    vl-view(v-if="xy.length > 0" :zoom="15" :center="[long,lat]" :rotation="0")
```
But this does work:
```
vl-map(data-projection="EPSG:4326" ref="map" :load-tiles-while-animating="true" :load-tiles-while-interacting="true", :controls="{attribution: false, zoom: true}")
    vl-view(v-if="xy.length > 0" :zoom="15" :center="xy" :rotation="0")
```

**Comment by ghettovoice** [comment]
You can find all OpenLayers related helpers at vuelayers/lib/ol-ext directory (ES6 versions at vuelayers/lib/_esm/ol-ext dir). If I export all helpers to `this.$vuelayers` then all of them would blow your final bundle even if not used. As long as I could not think of anything better than to publish them separately and let the end user bundle do the his work.
Issue with dataProjection probably a bug, I'll look at this soon.
Thanks!

**Comment by ghettovoice** [comment]
v0.10.2 should resolve issue with not working `dataProjection`

**Comment by fnoop** [comment]
Yes that works fine now, thanks :)

How do I access the vuelayers/lib/_esm/ol-ext components from <script>?

**Comment by ghettovoice** [comment]
In UMD version you can find it at `VueLayers.olExt` path. 
I'll describe this in documentation later.

**Comment by fnoop** [comment]
Actually sorry 0.10.3 isn't working for me, I still have to add `data-projection="EPSG:4326"` to vl-map component.

**Comment by ghettovoice** [comment]
Hmm, I can't reproduce the bug. Can you add some example which will clarify the use case?

**Comment by ghettovoice** [comment]
Try with v0.10.4, it should resolve the issue

**Comment by fnoop** [comment]
Unfortunately not, for me.  Here is my component with the problem:
http://www.maverick.one/web/maverick/#/planner
Here is the source:
https://github.com/goodrobots/maverick-web/blob/master/src/components/modules/planner/Planner2d.vue
If you look in the vue devtools for this component, it shows everything as EPSG_3857 even though I've specified the global projection in the script section:
```
Vue.use(VueLayers, {
  dataProjection: 'EPSG:4326'
})
```
Am I doing something stupid? (I do a lot of that)

**Comment by ghettovoice** [comment]
Now I see where is the problem.
You have another page with VueLayers initialization https://github.com/goodrobots/maverick-web/blob/master/src/components/modules/cockpit/CockpitMap.vue#L37
Then in the route index file https://github.com/goodrobots/maverick-web/blob/master/src/router/index.js
you import CockpitModule and PlannerModule with different VueLayers initialization, but only the first, from CockpitModule is actually initialize VueLayers.

**Comment by fnoop** [comment]
Aaah.  Yes, thankyou!  Is there a better way of declaring VueLayers then, or setting the dataProjection default eg. in main.js?

**Comment by ghettovoice** [comment]
Yes, this is a bug. I'll fix it

**Comment by ghettovoice** [comment]
Sorry for such long resolving, I'm a little confused myself with data projection resolving and applying.
Please try with v0.10.5

**Comment by fnoop** [comment]
Yes, working perfectly with 0.10.5.  Thanks very much!
