### ISSUE TITLE
interaction-translate

### ISSUE THREAD

**Issue by Shookk69** [ghettovoice/vuelayers#401]
Hi ! 
Tell me plz how use  vl-interaction-translate ?

 "vuelayers": "^0.12.0-rc.19.1",

**Comment by ghettovoice** [comment]
Hello @Shookk69 ,
look at this demo https://jsfiddle.net/ghettovoice/wzms32nb/13/

**Comment by Shookk69** [comment]
Thanks for the answer @ghettovoice, 
but https://jsfiddle.net/ghettovoice/wzms32nb/13/ use vl-interaction-**select**, 
I asked about vl-interaction-**translate** ) ( https://openlayers.org/en/latest/apidoc/module-ol_interaction_Translate.html )

**Comment by ghettovoice** [comment]
Sorry, I missed this.
This is updated example https://jsfiddle.net/ghettovoice/wzms32nb/17/.

For the  draw, translate, modify interactions you need to provide some source `ident`. This is usually `vl-source-vector` for the draw interaction and `vl-interaction-select` for the translate, modify.

**Comment by Shookk69** [comment]
Thank you so much
