### ISSUE TITLE
WebGL

### ISSUE THREAD

**Issue by Shookk69** [ghettovoice/vuelayers#410]
Hi @ghettovoice ,
is there a possibility of using   **WebGLPointsLayer** ?

**Comment by ghettovoice** [comment]
Hello @Shookk69 ,
currently no.   
It's for now not stable API and I can't include it.  
But if you need you can wrap `ol/layer/WebGLPoints` yourself with the help of vuelayers basic layer mixins.
Openlayers v6 is supported by Vuelayers v0.12 that you can install with `npm install vuelayers@next`. 
Mixins inside `vuelayers/dist/mixins/...` folder.
