### ISSUE TITLE
default-controls set to false still shows zoom controls

### ISSUE THREAD

**Issue by kalyncoose** [ghettovoice/vuelayers#415]
Hello and thank you so much for this Vue library for OpenLayers @ghettovoice ! I am refactoring a Leaflet (Vue2-leaflet) project into VueLayers and have had an easy time so far.

My issue is with the `default-controls` or `controls` parameter for the `vl-map` component. I combed through the existing issues and documentation first before posting. It appears that the parameter, when set to `false`, does not remove the default zoom control that appears in the upper-left corner of the map. See my component:
```
<vl-map :load-tiles-while-animating="true" :load-tiles-while-interacting="true" :default-controls="false"
            data-projection="EPSG:3857" style="height:100vh;" @click="handleClick($event.coordinate)">
```
Screenshot (I have a custom search bar, but you can see the zoom control is the blue peaking out behind it):

![screenshot](https://i.ibb.co/gt5kfxh/Screen-Shot-2021-03-16-at-8-47-57-PM.png)

[Here](https://vuelayers.github.io/#/docs/component/map?id=controls) is the documentation page for the parameter. It used to be called `default-controls` but now is `controls`. I tried both parameters and no luck, the zoom controls keep appearing. I am using this version in my `package.json`: `"vuelayers": "^0.11.31",`

Should I try accessing the olMap instance and manually setting the controls to false? If so, could you please provide some example code of how to access the underlying map and its controls, thanks!

**Comment by ghettovoice** [comment]
@kalyncoose thanks for report! Should work as expected in v0.11.32

**Comment by scil** [comment]
in v0.12.3,  attribute `default-controls` works well,  but  `controls` not.

**Comment by ghettovoice** [comment]
@scil  `default-controls` in v0.12 it is renamed `controls` from v0.11
