### ISSUE TITLE
Can't resolve 'rx-ext'

### ISSUE THREAD

**Issue by menesty** [ghettovoice/vuelayers#424]
I have configure like described on https://vuelayers.github.io/#/docs/quickstart
npm install vuelayers

installed version "vuelayers": "^0.11.33",

in create file in folder plugins/vuelayers.js
import Vue from 'vue'
import VueLayers from 'vuelayers'
import 'vuelayers/lib/style.css'

Vue.use(VueLayers);

than include plugin in main.js
import "@/plugins/vuelayers.js";

Copy example  from https://vuelayers.github.io/#/docs/component/vector-layer

When open page with example got
./node_modules/vuelayers/lib/vector-tile-source/index.js
Module not found: Error: Can't resolve 'rx-ext' in 'projectPath/node_modules/vuelayers/lib/vector-tile-source'

How to solve a problem ?

**Comment by srabiller** [comment]
Same issue here

**Comment by menesty** [comment]
> Same issue here with vuelayers
> 
> ERROR Failed to compile with 1 error 01:48:59
> 
> This dependency was not found:
> 
> * rx-ext in ./node_modules/vuelayers/lib/vector-tile-source/index.js
> 
> To install it, you can run: npm install --save rx-ext

 npm install --save rx-ext
npm ERR! code E404
npm ERR! 404 Not Found - GET https://registry.npmjs.org/rx-ext - Not found
npm ERR! 404 
npm ERR! 404  'rx-ext@*' is not in the npm registry.
npm ERR! 404 You should bug the author to publish it (or use the name yourself!)

**Comment by ghettovoice** [comment]
Sorry, looks like a broken build or typo in some of the imports. I'm going to rebuild new release...

**Comment by ghettovoice** [comment]
rdy

**Comment by srabiller** [comment]
Thanks @ghettovoice, it did the trick !
