### ISSUE TITLE
Color manipulation

### ISSUE THREAD

**Issue by StefanNemeth** [ghettovoice/vuelayers#425]
Hey, I'd like to apply a grayscale filter to my map. Is there a recommended way to approach this with VueLayers?

Thanks in advance :)

**Comment by ghettovoice** [comment]
Hello @StefanNemeth ,
you can use great addition for openlayers called ol-ext http://viglino.github.io/ol-ext/. They provide tons of additional components.

Regarding your case: take a look at this demo https://jsfiddle.net/ghettovoice/qa8p913o/248/. It is fast adaption of original ol-ext demo for colorizer component http://viglino.github.io/ol-ext/examples/filter/map.filter.colorize.html?lon=2.219234&lat=50.593699&z=8
