### ISSUE TITLE
TopoJson is not rendered on map

### ISSUE THREAD

**Issue by li-shasha** [ghettovoice/vuelayers#426]
currently topojson data is not rendered on map even with component vl-source-vector :format-factory property and :overlap=false

wasser.json is a topology json data.

```
<vl-source-vector :url="/maps/wasser.json" :format-factory="createTopoJsonFmt" :overlaps="false"></vl-source-vector>

...

import {TopoJSON} from 'ol/format';
...
methods: {
  createTopoJsonFmt(){
    return new TopoJSON({})
  }
}
```
can you help to check it please?  you can see the topojson with mapshapper or whatever you like.
[sandbox example](https://codesandbox.io/s/vigilant-noyce-ipj60?file=/src/App.vue)

**Comment by ghettovoice** [comment]
Hi @li-shasha ,
the topojson file not work even with openlayers https://jsfiddle.net/ghettovoice/sdx98e2f/42/. 
If you check in the console created features, you will see that some of coordinates have Nan value. Usually this due to incorrect projection.

**Comment by li-shasha** [comment]
thank you very much!
just as what you said, topojson rendered after i add dataProjection property.

**Comment by li-shasha** [comment]
vuelayers work with topojson. It just need proper data projection
