### ISSUE TITLE
ol.getUid is not a function error

### ISSUE THREAD

**Issue by yasinarga** [ghettovoice/vuelayers#427]
Hello , I develop small project in HTML files.
I import modules from CDN. 
When I add `<vl-feature>` it gives this error.
What can be problem?

OpenLayer version 6.5.0
VueLayer version 11.35

Thank you.

![image](https://user-images.githubusercontent.com/30650132/114744843-c99a1a00-9d56-11eb-89aa-1bfd1e4394f5.png)

![image](https://user-images.githubusercontent.com/30650132/114745688-95732900-9d57-11eb-9308-b73f403c1b0a.png)

![image](https://user-images.githubusercontent.com/30650132/114746176-1cc09c80-9d58-11eb-9aa2-892672978074.png)

**Comment by ghettovoice** [comment]
Hello @yasinarga ,
with vuelayers@^0.11 you should use openlayers v5. Change ol path to https://cdn.jsdelivr.net/gh/openlayers/openlayers.github.io@master/en/v5.3.0/build/ol.js and all should work as expected.
