### ISSUE TITLE
Mouse position

### ISSUE THREAD

**Issue by jaganacbozji** [ghettovoice/vuelayers#432]
I have the example from openlayers but is there some custom control in vuelayers to do the same?
i would like to console log mouse position in vue.

import 'ol/ol.css';
import Map from 'ol/Map';
import MousePosition from 'ol/control/MousePosition';
import OSM from 'ol/source/OSM';
import TileLayer from 'ol/layer/Tile';
import View from 'ol/View';
import {createStringXY} from 'ol/coordinate';
import {defaults as defaultControls} from 'ol/control';

var mousePositionControl = new MousePosition({
  coordinateFormat: createStringXY(4),
  projection: 'EPSG:4326',
  // comment the following two lines to have the mouse position
  // be placed within the map.
  className: 'custom-mouse-position',
  target: document.getElementById('mouse-position'),
  undefinedHTML: '&nbsp;',
});

var map = new Map({
  controls: defaultControls().extend([mousePositionControl]),
  layers: [
    new TileLayer({
      source: new OSM(),
    }) ],
  target: 'map',
  view: new View({
    center: [0, 0],
    zoom: 2,
  }),
});

var projectionSelect = document.getElementById('projection');
projectionSelect.addEventListener('change', function (event) {
  mousePositionControl.setProjection(event.target.value);
});

var precisionInput = document.getElementById('precision');
precisionInput.addEventListener('change', function (event) {
  var format = createStringXY(event.target.valueAsNumber);
  mousePositionControl.setCoordinateFormat(format);
});
index.html
<!DOCTYPE html>
<html lang="en">
  <head>
    <meta charset="UTF-8">
    <title>Mouse Position</title>
    
    <script src="https://unpkg.com/elm-pep"></script>
    <style>
      .map {
        width: 100%;
        height:400px;
      }
    </style>
  </head>
  <body>
    <div id="map" class="map"></div>
    <div id="mouse-position"></div>
    <form>
      <label for="projection">Projection </label>
      <select id="projection">
        <option value="EPSG:4326">EPSG:4326</option>
        <option value="EPSG:3857">EPSG:3857</option>
      </select>
      <label for="precision">Precision</label>
      <input id="precision" type="number" min="0" max="12" value="4"/>
    </form>
    <script src="main.js"></script>
  </body>
</html>

**Comment by ghettovoice** [comment]
Hello @jaganacbozji ,
currently controls is not covered by vuelayers api. But they can be added in runtime in the map event handlers.
There is a demo https://jsfiddle.net/ghettovoice/qa8p913o/285/

**Comment by jaganacbozji** [comment]
ty comarade

**Comment by jaganacbozji** [comment]
i found similar solution:
//  inside template i added @pointermove


<template>
  <vl-map
    id="infokarta"
    ref="map"
    :load-tiles-while-animating="true"
    :load-tiles-while-interacting="true"
    style="height: 100vh"
    @click="handleClick($event.coordinate)"
    @created="clickAndDrag"
    @pointermove="pointerMove"
  >

.....
 import { ScaleLine } from 'ol/control'


mounted () {
    // dodan scaleline (scalebar) !!! prije export default treba importat openLayers komponentu, te dodat sljedeće:
    // stil se mijenja u _map.scss i mora koristiti !important tag da bi radilo
    // get vl-map by ref="map" and await ol.Map creation
    this.$refs.map.$createPromise.then(() => {
      this.$refs.map.$map.addControl(new ScaleLine())
    })
  },


//and finally stored mouse position in the store::

methods: {
    pointerMove (event) {
      this.$store.commit('mapInfo/mousePosition', event.coordinate)
      // pass event object, bound to mouse move with updat
    },

works like a charm :D
