### ISSUE TITLE
Is it possible to use maptiler with vuelayers? 

### ISSUE THREAD

**Issue by alcadeana** [ghettovoice/vuelayers#433]
If yes how can I use it?  I tried to make a custom map in https://cloud.maptiler.com/maps/ but the URL doesn't work with vl-source-xyz.

**Comment by ghettovoice** [comment]
Hello @alcadeana ,
which type of custom map do you create? Vector tiles or raster tiles?
vl-layer-tile/vl-source-xyz is for raster tiles (world map with the help of [ol-mapbox-style](https://github.com/openlayers/ol-mapbox-style) https://jsfiddle.net/ghettovoice/qa8p913o/294/)
vl-layer-vector-tile/vl-source-vector-tile is for vector tiles. (https://jsfiddle.net/ghettovoice/qa8p913o/289/)
