### ISSUE TITLE
About OverviewMap

### ISSUE THREAD

**Issue by Rih** [ghettovoice/vuelayers#436]
Hi @ghettovoice , 
I've testing v0.11.35 and it had a few bugs that delayed the maps render when the browser downloaded the image requested already.
I saw v0.12.x probably solved this issue but it affect the Overview map. It throws an AssertionError
![Captura de Pantalla 2021-05-31 a la(s) 12 23 51](https://user-images.githubusercontent.com/2819055/120220672-1fddf200-c20b-11eb-948c-af41089a10fa.png)
error #1 The view center is not defined.

So PreviewMap is not displayed
![Captura de Pantalla 2021-05-31 a la(s) 12 24 37](https://user-images.githubusercontent.com/2819055/120220723-308e6800-c20b-11eb-9d6c-47a0271e83a2.png)

any hint ? 
any suggested date to v0.12 look the sunlight :)? 
Thank you all

**Comment by ghettovoice** [comment]
Hello @Rih ,
try with v0.12.0-rc.26. It should resolve this issue.
https://jsfiddle.net/ghettovoice/Ln9qr135/139/

Thanks for report!

**Comment by Rih** [comment]
thank you @ghettovoice I works like charm !
