### ISSUE TITLE
Circle draw does not correspond to real word scale

### ISSUE THREAD

**Issue by Nikitoring** [ghettovoice/vuelayers#438]
[#192](https://github.com/ghettovoice/vuelayers/issues/192)
Solution in this issue doesn't work for me 
I need to use circle in my project.
My solution https://codesandbox.io/s/objective-rgb-xfqln?file=/src/components/Map.vue
Do you have another solution or this functional is in new release? I use version 0.11.35

**Comment by ghettovoice** [comment]
Hello @Nikitoring ,
if you wan't use circlular polygon then yes, this is the only good solution to adjust small circle radius on the  map in EPSG:3857. As far the cirlce center from  the equator the more diff you will get, but ol.circle.Circle doesn't consider this, it just appends radius as an offset.
