### ISSUE TITLE
Implement right click/context menus

### ISSUE THREAD

**Issue by giesberge** [ghettovoice/vuelayers#439]
So i'm trying to implement right-click/custom context menus in this but I can't seem to get it to work. I can get normal click to work and the event to trigger if I use "native" but other than that it doesn't seem to work.

**Comment by ghettovoice** [comment]
Hello @giesberge ,
there is a 3rd party custom control for OpenLayers that implements Map context menu. https://github.com/jonataswalker/ol-contextmenu

And there is a demo how to connect with vuelayers https://jsfiddle.net/ghettovoice/qa8p913o/352/
