### ISSUE TITLE
public fiddles mistake

### ISSUE THREAD

**Issue by wendellwt** [ghettovoice/vuelayers#442]
Help!  Did I edit one of your jsfiddles?  I'm sorry!
The first example on your `jsfiddle.net` page, https://jsfiddle.net/ghettovoice/shm1dfeg/1/ looks like mine.  How did I do that?
I created my own account on jsfiddle.net earlier this week.  I must have done something wrong, because it looks like I edited one of your examples (or added one of my tests to your page).

Sorry about that.

**Comment by ghettovoice** [comment]
@wendellwt no, it's my fork from you fiddle from #441.
When you open somebody fiddle and start changing it, it will be automatically forked to your account.
So don't worry 😄

**Comment by wendellwt** [comment]
Whew!  That's good to know.  Thank you.

**Comment by wendellwt** [comment]
Oh, and in a discord channel [Amelia ](https://wattenberger.com/blog/d3-interactive-charts) resolved by D3 + OL issue.  At least I have the map zoom/pan working, but not the D3 interaction (yet).  The `pointer-events:none` had to be at the correct level:
```
.ol-overlay-container {
  pointer-events: none;
}
```
As in shown in my [map-2-amelia](https://jsfiddle.net/wendellwt/ebd21x3a/2/)
