### ISSUE TITLE
custom map projection demo

### ISSUE THREAD

**Issue by ghansham** [ghettovoice/vuelayers#447]
R/Sir

import proj4 from "proj4";
//import { get as getProjection } from "ol/proj";
import { register as registerProjection } from "ol/proj/proj4";

proj4.defs(
      "EPSG:997106",
      "+proj=geos +sweep=x +lon_0=82.5 +h=35786023 +x_0=0 +y_0=0 +datum=wgs84 +ellps=wgs84 +units=m +no_defs"
    );
    registerProjection(proj4);

This code is not working in vuelayers application.

openlayers example is given below:
https://openlayers.org/en/latest/examples/reprojection.html

regards
Ghansham

**Comment by 0xMDIV** [comment]
import {register} from "ol/proj/proj4"; works fine for me, i have nearly the the same code as you ^^
