### ISSUE TITLE
How to use a different map (basemap) style 

### ISSUE THREAD

**Issue by slaetthult** [ghettovoice/vuelayers#448]
How can i use a different map style (basemap)? The default is too colorful. I need a more simple looking grey map like this:

![Bildschirmfoto 2021-09-22 um 15 03 01](https://user-images.githubusercontent.com/22275417/134348523-9c24e949-5336-4d6f-96ad-8a33130a61ad.png)

**Comment by ghettovoice** [comment]
Hello @slaetthult ,
you can use `vl-source-xyz` with `vl-layer-tile` to load and show any tiled layer on the map.

```html
<vl-map >
  <vl-layer-tile>
    <vl-source-xyz :url="https://{a-c}.tile.openstreetmap.org/{z}/{x}/{y}.png" />
  </vl-layer-tile>
</vl-map>
```
