### ISSUE TITLE
How to open a popup

### ISSUE THREAD

**Issue by slaetthult** [ghettovoice/vuelayers#449]
How can I open a Popup-box, when I click on a marker?

**Comment by ghettovoice** [comment]
Hello @slaetthult ,
take a look at this demo https://jsfiddle.net/ghettovoice/yh9zxskf/.

What you need:
1. vl-layer-vector/vl-source-vector - vector source and layer to load and show vector features.
2. vl-interaction-select - provides vector feature selection 
3. vl-overlay - any html container bound to some coordinate.

So in the simplest case you only need to bind vl-overlay to select features from vl-interaction-select, like it is done in the demo above.

**Comment by fernanduandrade** [comment]
i'm really new, but it didnt work with polygon

**Comment by ghettovoice** [comment]
No prob 👌
What type of the layer do you use? Show me your component source

**Comment by ghettovoice** [comment]
> I made it work
ok.

You should know feature geometry type in the select feature handler. 
With geojson-encoded feature: `featureGeoJSON.geometry.type`.
With openlayers `ol/Feature`: `feature.getGeometry().getType()`.

**Comment by fernanduandrade** [comment]
thanks!! that helps a lot

**Comment by iboates** [comment]
@ghettovoice How can I get the information from the GeoJSON feature in the popup? All I can get is the feature in the context of VueLayers, I need the properties of the feature as it appears in the source GeoJSON

**Comment by ghettovoice** [comment]
@iboates take a look here, it is updated demo https://jsfiddle.net/ghettovoice/yh9zxskf/31/

**Comment by iboates** [comment]
@ghettovoice Ok I realize now that what I have to do is to open a dialog box with the feature's GeoJSON properties, not a popup in the map. Is the `<vl-interaction-select>` really the best way to go about this?

I can make a dialog with a boolean `v-model` variable, but the way you have it in the fiddle, you use a template slot, so how can I get it to activate the `v-dialog`?

**Comment by ghettovoice** [comment]
vl-interaction-select just implements select/unselect vector feature function. 
It can also synchronize selected features through the `features` prop: `:features.sync="selectedFeatures"`.
Or you can listen `select`, `unselect` events on it to trigger something for each feature. 
So using of it's slot is not required.

**Comment by iboates** [comment]
@ghettovoice thanks, that clears it up
