### ISSUE TITLE
layer switcher

### ISSUE THREAD

**Issue by wendellwt** [ghettovoice/vuelayers#454]
Is it possible to use [OpenLayers LayerSwitcher](https://github.com/walkermatt/ol-layerswitcher) in vuelayers? 

Would it be something like this?
```
<vl-overlay ref="ovly_ref">
   <vl-layer-vector ref="layer_ref">
       ....
   </vl-layer-vector>
</vl-overlay>
```
And define the switcher as:
```
var layerSwitcher = new LayerSwitcher();
map.addControl(layerSwitcher);
```
And then somehow insert the references to that layer into ol-layerswitcher:
```
  overlayGroup.getLayers().push(
    new Layer({
       title: 'My Layer',
       source: this.$refs.layer_ref }) )
```
Where should the group be defined?  Does vuelayers automatically generate this?

Is the vl-overlay ref `ovly_ref` inserted into the group instead of the vl-layer-vector ref `layer_ref`?

Thank you

**Comment by ghettovoice** [comment]
Hello @wendellwt ,
vl-overlay component is for another purposes. It appends div container and bind it to some coordinate. So it not needed here.

As for LayerSwitcher usage: it expects custom layer fields that vuelayers doesn't support, but you can append them in the `created` event handler for each layer that should be in the switcher panel. 
Here is example https://jsfiddle.net/ghettovoice/qa8p913o/401/

**Comment by wendellwt** [comment]
Perfect!  That works great!

Thank you again @ghettovoice !
