### ISSUE TITLE
ol-ext legend

### ISSUE THREAD

**Issue by npltr62** [ghettovoice/vuelayers#455]
hello,
how to integrate legend from [ol-ext](https://viglino.github.io/ol-ext/examples/legend/map.control.legend.html). Unfortunately i didn't find any example to help me.

**Comment by ghettovoice** [comment]
Hello @npltr62 ,
there is a demo https://jsfiddle.net/ghettovoice/qa8p913o/453/

**Comment by npltr62** [comment]
thank's for your help
