### ISSUE TITLE
infinity update features

### ISSUE THREAD

**Issue by malkovDanik** [ghettovoice/vuelayers#457]
**Vesion "vuelayers": "0.12.0-rc.26",**
When I use `<vl-style-icon
          :src="resources/img.svg"
          :scale="1.5"
      ></vl-style-icon>` for features then `<vl-source-vector/>` called  `update:features ` all time.
![img](https://user-images.githubusercontent.com/11462916/141659616-b18c4753-bff5-4269-a18a-7d5b60c6dfef.png)

**Comment by ghettovoice** [comment]
Hello @malkovDanik ,
I can't reproduce your issue on my setup.
Can you provide simple demo?

**Comment by malkovDanik** [comment]
Гайзенбаг! Осталось только картинка, если воспроизведу закину. Также отметили, что очень сильно начинает тормозить если включен Vue DevTools... возможно это как-то связано.

**Comment by malkovDanik** [comment]
Есть также предложения по поводу #251. В 6.9.0 есть возможность затыкать переопределение стиля interaction select передав ему в options.style = null | false. Предлагаю дать такую возможность и здесь. На текущий момент значение передается в зависимости от this.getStyleTarget(),getStyle() или _style контейнера style-container.js. Я смог его переопределить только через хук таким макаром:

` <template>
    <vl-interaction-select
        :layers="['layerId']"
        :hit-tolerance="10"
        :toggleCondition="() => true"
        ref="interaction"
    >
        <template slot-scope="selectScope">
            
            <vl-overlay
                v-for="feature in selectScope.features"
                :key="feature.id"
                :id="feature.id"
                :position="feature.geometry.coordinates"
            >
                <p class="content">
                    Always opened overlay for Feature ID
                    <strong>{{ feature.id }}</strong>
                </p>
            </vl-overlay>
        </template>
    </vl-interaction-select>
</template>
<script lang="ts">
export default {
    name: 'interaction-select',
    mounted() {
      // eslint-disable-next-line no-debugger
        debugger;
        **this.$refs.interaction._style = false;**
    },
};
</script> `
В таком случаем стиль при клике переопределяться не будет. Возможно есть метода по проще, но за 5ч мне хватило ума только таким образом :)

**Comment by ghettovoice** [comment]
VueDevTools может тормозить когда включена вкладка События. OpenLayers и соответсвенно VueLayers тригеррит очень много событий, особенно при смещении/зуме карты.

Насчёт отключения дефолтного стиля через null/false - согласен. Я как то упустил этот момент, надо добавить

**Comment by malkovDanik** [comment]
Благодарю!
