### ISSUE TITLE
WMTS Source matrixIds validation checks for Number instead of String

### ISSUE THREAD

**Issue by lol2x** [ghettovoice/vuelayers#458]
Validation for WMTS Source [prop matrixIds](https://github.com/ghettovoice/vuelayers/blob/86d3af0f2e5b05e808097421e40ba7f906470835/src/components/wmts-source/source.vue#L59 ) is looking for number instead of string (as in [OpenLayers ](https://github.com/openlayers/openlayers/blob/f86bad745967fa075fffcafadeb0e81cbab27eba/src/ol/tilegrid/WMTS.js#L26))

**Comment by ghettovoice** [comment]
@lol2x you are definitely right. I have missed this.
Thanks for report!
