### ISSUE TITLE
URL token replacement

### ISSUE THREAD

**Issue by elwoodhouse** [ghettovoice/vuelayers#46]
G'Day Vladimir,

Thanks for the quick fix on the demo app yesterday. Today I've been try to add a Mapbox layer to the demo app but for some reason I can't get the layers source properties to parse into the url that gets generated to request the tiles.

This is what I have added to the demo app:
<img width="515" alt="0" src="https://user-images.githubusercontent.com/38488541/38973596-045e9ce8-43ea-11e8-9f2e-6089674cf4df.PNG">
and in the vue dev tools the properties come through to the browser:
<img width="622" alt="1" src="https://user-images.githubusercontent.com/38488541/38973619-1d81e040-43ea-11e8-9f3c-a3fb355e68c3.png">
but the urlTmpl doesn't seem to replace the tokens so the url request isn't correct:
<img width="654" alt="2" src="https://user-images.githubusercontent.com/38488541/38973685-753a51aa-43ea-11e8-84a0-f7f46c5cb631.png">

If I manually replace the tokens in postman I do get the correct tile returned. Is this another quick fix?

Thanks,
Leon.

**Comment by ghettovoice** [comment]
Hi, @elwoodhouse!
As a quick fix you can switch to vl-soruce-xyz component and set url with already replaced urlTokens.
```
<vl-source-xyz url="https://{a-c}.tiles.mapbox.com/v4/mapbox.light/{z}{x}/{y}.png?access_token=you access token"></vl-source-xyz>
```
This is what actually vl-source-mapbox doing, but probably doing wrong.

**Comment by ghettovoice** [comment]
Please, upgrade to the last version v0.10.6, that should resolve this issue.
Re-open if it doesn't help
