### ISSUE TITLE
Feature properties is undefined 

### ISSUE THREAD

**Issue by malkovDanik** [ghettovoice/vuelayers#463]
Hello, Vladimir!
I created demo [https://jsfiddle.net/DanikJsFiddle/0a2qsh5g/67/](https://jsfiddle.net/DanikJsFiddle/0a2qsh5g/67/) with my problem.

I create `<vl-interaction-select>.` I use ` <template slot-scope="selectScope">` into `<vl-interaction-select>` to create overlay popup. Further, feature properties are changed by method's overlay . Now, I want to see modified props in deselect method of interaction, but they equals `undefined`.

**Comment by ghettovoice** [comment]
Hello @malkovDanik ,
first of all you can't change feature properties inside v-for of select scope, and actually it isn't supposed. JSON features here are just a dump of internal openlayers objects. So they are read-only.

You can make any changes in select/unselect event handlers. 
However take a note how I have made it in a new demo https://jsfiddle.net/ghettovoice/xaofqhdc/9/. 
Event object contains several fields:
- `feature` - instance of ol/Feature
- `json` - json read-only representation of the ol/Feature.
So you can change the state of the feature via openlayers setters, then they will be dumped into the json representation.
