### ISSUE TITLE
Updating features

### ISSUE THREAD

**Issue by alg3rd** [ghettovoice/vuelayers#47]
Thank you for library! Awesome job. 

My situation:
I have a cluster of points with real-time updates(via EventSource). Points have different styling depends on properties.
How I can update existing features' properties and refresh them?

**Comment by ghettovoice** [comment]
Hi, @alg3rd,
thank yo for your response!
I made an example, take a look https://jsfiddle.net/ghettovoice/azn6q6qL/52/
Notes: 
- features updating made through Vue reactive property on vl-source-vector
- for clustering point layer I use vl-source-cluster, that accepts distance in pixel 
- for dynamically style features the best choice is vl-style-func component that accepts a factory that creates actual style function (see https://openlayers.org/en/latest/apidoc/ol.html#.StyleFunction)

**Comment by alg3rd** [comment]
After your example I realized that feature Id must be different from properties.id because comparator making diff on feature id. 
Thank you.

**Comment by panchofrank** [comment]
Hello,

I'm trying to update the latitude and longitude of features but the changes seem to be ignored.  I wanted to look at the fiddle mentioned above but it doesn't seem available anymore.  Are there any other examples of features that move?

**Comment by ghettovoice** [comment]
Hi @panchofrank !

Watcher for `features` property in the current stable version doesn't triggers for deep changes inside
features objects. Only changes in the `features` array are taking into account. 

So to trigger feature re-render you should replace old feature object with the new one with another coordinates. For this you can use `push`/`splice` array methods that are wrapped with the Vue reactiveness

```js
let idx = this.features.findIndex(f => f.id === featureId)
if (idx === -1) {
  this.features.push({ type: 'Feature', id: ..., coordinates: [....] })
} else {
  this.features.splice(idx, 1, { 
     ...this.features[idx],
    coordinates: [ /* ...new coordinates */ ]
  })
}
```

**Comment by ghettovoice** [comment]
Also you  can try to install `vuelayers@next` where watcher for `features` prop now is deep and resolved
several other well known issues.

Thanks!
