### ISSUE TITLE
className on layer

### ISSUE THREAD

**Issue by Isitar** [ghettovoice/vuelayers#478]
It would be nice to have a className option for the layers.

i cannot find a way to add a grayscale filter to one layer with the current implementation

doc for className: 

https://openlayers.org/en/latest/apidoc/module-ol_layer_Layer-Layer.html

**Comment by ghettovoice** [comment]
Hello @Isitar ,
which version of VueLayers do you use? Is is v0.11 or v0.12.
I'm asking because v0.11 is based on openlayers v5 and there is no `className` option on layer classes.
It was added in the openlayers v6, that is used by VueLayers v0.12. And here each `vl-layer-*` has `className` prop.

**Comment by Isitar** [comment]
Thanks for the hint, i was using v0.11. i switched to v0.12 and it's working now.
