### ISSUE TITLE
Projection issue with map height

### ISSUE THREAD

**Issue by bobrosset** [ghettovoice/vuelayers#48]
I'm not sure if I'm the only one with this error, but using this projection `EPSG:4326` causes my map to render sort of squashed. If I remove that projection, the map looks fine, but the points are, of course, in another places. Any clue anyone?

**Comment by ghettovoice** [comment]
Hi, @bobrosset!
Seems like you use `projection`  property on `vl-view` component, this property is responsible for internal map view projection, that by default is `EPSG:3857`.   
If you want to rendred map in EPSG:3857, but work with coordinates data in EPSG:4326
there is another option called [`data-projection`](https://vuelayers.github.io/#/quickstart?id=global-data-projection). In short: remove projection from vl-view component and add data-projection=EPSG:4326 to vl-map

**Comment by bobrosset** [comment]
@ghettovoice, I updated to test if the newer versions works with that projection. And it does.

Not this is my problem:

`import { findPointOnSurface } from 'vuelayers/lib/_esm/ol-ext'` leads to an import export issue.

On the previous version, I was using:
`import { core as vlCore } from 'vuelayers';`

And using it like: `pointOnSurface: vlCore.geomHelper.pointOnSurface,`

But that's not working anymore. Any help would be appreciated man. Thanks!

**Comment by ghettovoice** [comment]
You already figured out how to migrate to the new version, while I wrote the answer :thumbsup:

>  leads to an import export issue.

What kind of issue you talking about?
Here is example of usage helpers with the last version https://github.com/ghettovoice/vuelayers-demo/blob/master/src/App.vue

**Comment by bobrosset** [comment]
The error I'm getting is:
```
export * from './collection';
^
ParseError: 'import' and 'export' may appear only with 'sourceType: module'
```

Now, I think this issue is related to some `vueify`, `babelify`, `something-in-between`. But I cannot figure out what's wrong. Nor why it only happens with this package. And yes, I was using that example.

Last but not least, I saw you added a new documentation. I like the change you made!

**Comment by ghettovoice** [comment]
What options you use for babel? Presets?
Try to change import path to `vuelayers/lib/ol-ext`. I'm not an expert with babelify, may be it doesn't use "module" field from package.json and loads CommonJs version.

**Comment by ghettovoice** [comment]
Or may be you should add `vuelayers` path to babel configuration, usually node_modules folder is excluded for babel transpiling

**Comment by bobrosset** [comment]
Using `vuelayers/lib/ol-ext` did the trick. It's a different html structure now. But that's a minor. Wooooo! Thanks man.

**Comment by ghettovoice** [comment]
Nice! 
And thank you for response. I'm working on the new documentation to cover all available components.
Re-open if you will have questions.

**Comment by bobrosset** [comment]
I see... `vl-overlay` overwrite the class. Not a big deal. Changed the css to `.ol-overlay-container` instead. Thanks mate. Have a great week. Amazing job.
