### ISSUE TITLE
loading features

### ISSUE THREAD

**Issue by npltr62** [ghettovoice/vuelayers#480]
hello  when i switched to v0.12 this code below not working. 
`                <vl-layer-vector :z-index=0>
                    <vl-source-vector ref="dept_Source" :url="dept_url"/>
                    <vl-style>
                        <vl-style-fill color="#cacee6"></vl-style-fill>
                        <vl-style-stroke :width=0.5 color="grey"></vl-style-stroke>
                    </vl-style>
                </vl-layer-vector>
        data() {
            return {
         dept_url: null
          }
          },
        mounted () {
                this.isLoading = true;
                setTimeout(() => {
                    this.dept_url = process.env.VUE_APP_GEOSERV + "geoserver/fd/ows?service=WFS&version=1.0.0&request=GetFeature&typeName=fdp49%3Adept_49&outputFormat=application%2Fjson"
                    this.isLoading = false;
                }, 2000);
        },
`
in latest version, a url validator was added cf [doc](https://github.com/ghettovoice/vuelayers/blob/v0.12.0/src/mixins/vector-source.js#L25). Should i use loader property?

**Comment by ghettovoice** [comment]
Hello @npltr62 ,
I have forgot to add source refresh on `url`, `loader` prop changes.
I'll fix this ASAP.
Thanks for report!
