### ISSUE TITLE
Map flashes with custom view resolutions

### ISSUE THREAD

**Issue by marena** [ghettovoice/vuelayers#485]
Hi,

I'm using custom resolutions in view (same as base layers). The map flashes as you zoom and drag.
https://codesandbox.io/s/vuelayers-isv-map-v378bm?file=/src/App.vue
If you remove resolutions from view it works fine (but map tiles is not sharp)

Any idea whether this problem is a vuelayers/openalyers/map settings?

Thanks for answer

**Comment by ghettovoice** [comment]
Hello @marena ,
I found that is flashes when zoom has `.sync` modifier.
Seems that some synchronization bug. I will try to fix it soon.
Thanks for report!

**Comment by marena** [comment]
Thanks for answer

I found also center.sync do same errors
