### ISSUE TITLE
vl-interaction-draw and vl-interaction-select interferering each other

### ISSUE THREAD

**Issue by niklashaa** [ghettovoice/vuelayers#486]
Hi,

I have an issue where a LineString gets styled differently on every second mouse click while being drawn.
It seems to happen when vl-interaction-draw and vl-interaction-select are included at the same time even when they both reference different vector sources.
The issue can be reproduced in this [JSFiddle](https://jsfiddle.net/jworh8t7/18/) by drawing a new Linestring with multiple edges.
How can I avoid the drawn feature being added to the features of vl-interaction-select without excluding the component?

**Comment by ghettovoice** [comment]
Hello @niklashaa ,
to avoid triggering of select interaction, add `:stop-click="true"` to the vl-interaction-draw. This should prevent click event bubbling
