### ISSUE TITLE
vl-interaction-select

### ISSUE THREAD

**Issue by fernanduandrade** [ghettovoice/vuelayers#487]
Hello, I have a question. How can I prevent the vl-interaction-select from selecting the blue feature? I'm only displaying the information about the pink features but also I can select the blue feature which it doesn't contain any infomation.
![image](https://user-images.githubusercontent.com/58053397/159166177-869e659b-f2fe-4a3b-9868-7c3557768357.png)

**Comment by marena** [comment]
I'm using `filter` prop. For example:

```
<vl-interaction-select :features.sync="selectedFeatures" :filter="filter">
```

```
methods: {
        filter(vector) {
            return vector?.get('id') === 'blueone';
        },
},
```

**Comment by fernanduandrade** [comment]
Really appreciate!! It worked very well
