### ISSUE TITLE
vl-style-icon not updating

### ISSUE THREAD

**Issue by infokartasplit** [ghettovoice/vuelayers#488]
Example code that works only becouse :key prop    
```
<vl-source-vector :features.sync="feature">
      <vl-style v-if="type === 'Point'">
        <vl-style-icon :key="rotation" src="/mapillary_view.png" :scale=".15" :rotation="rotation" />
      </vl-style>
    </vl-source-vector>
...............
computed: {
    rotation () {
      return this.bearing * 3.1415926 / 180
    }
}
```
when :rotation changes it doesnt automatically update my vector feature when not using :key="rotation" prop
i tried :rotation.sync and it doesnt work
i could also probably make it work by using vl-style-func...
it worked in older version... latest doesnt work propertly.  
Is this intended ?
Please update documentation to newest version

**Comment by ghettovoice** [comment]
Hello @infokartasplit ,
yep, I see that it is broken. I will try to fix it ASAP.
Thanks for report!
