### ISSUE TITLE
Rendering issue with mapbox vector layers

### ISSUE THREAD

**Issue by dmcd** [ghettovoice/vuelayers#49]
Hi @ghettovoice,

I'm seeing some interesting results rendering mapbox vector layers. The edges are a little blurry and there are gaps in the tiles (faint white lines).

Without vuelayers:
<img width="684" alt="screen shot 2018-05-04 at 17 06 52" src="https://user-images.githubusercontent.com/4025574/39616202-9f2d51e0-4fbd-11e8-9e5f-ef2d627e1593.png">

With vuelayers:
<img width="719" alt="screen shot 2018-05-04 at 17 07 49" src="https://user-images.githubusercontent.com/4025574/39616224-b6c4c9be-4fbd-11e8-88e4-89afc7228fc6.png">

Do you know what might be causing this?

**Comment by ghettovoice** [comment]
Hi @dmcd,
this may be caused by reprojection threshold or tile pixel ratio, there are a lot of issue in openlayers repository about it. It's hard to understand clearly what is actually the reason.
Can you provide an example source code that you use in screenshots above to see actual options used?

**Comment by dmcd** [comment]
Sure, sorry should have included this above.

Without vuelayers:
```javascript
var layer =  new ol.layer.VectorTile({
  source: new ol.source.VectorTile({
    format: new ol.format.MVT(),
    url: 'http://localhost:8080/geoserver/gwc/service/wmts?REQUEST=GetTile&SERVICE=WMTS&VERSION=1.0.0&LAYER=myvic:suburb_cultural_diversity&STYLE=&TILEMATRIX=EPSG:900913:{z}&TILEMATRIXSET=EPSG:900913&FORMAT=application/x-protobuf;type=mapbox-vector&TILECOL={x}&TILEROW={y}'
  })
})

var view = new ol.View({
  center: [16137931, -4457491],
  zoom: 7,
});

var mapElement = document.getElementById('map');
var map = new ol.Map({
  target: mapElement,
  loadTilesWhileAnimating: true,
  view: view
});

fetch('http://localhost:8080/geoserver/rest/styles/suburb_culture_diversity.MBStyle').then(function (response) {
  response.json().then(function (glStyle) {
    olms.applyStyle(layer, glStyle, 'suburb_culture_diversity').then(function() {
      map.addLayer(layer)
    })
  })
})
```
With vuelayers:
```javascript
onMapCreated () {
  var layer = new VectorTileLayer({
    renderMode: 'vector',
    source: new VectorTileSource({
      format: new MVT(),
      url: 'http://localhost:8080/geoserver/gwc/service/wmts?REQUEST=GetTile&SERVICE=WMTS&VERSION=1.0.0&LAYER=myvic:suburb_cultural_diversity&STYLE=&TILEMATRIX=EPSG:900913:{z}&TILEMATRIXSET=EPSG:900913&FORMAT=application/x-protobuf;type=mapbox-vector&TILECOL={x}&TILEROW={y}',
    }),
  })

  let map = this.$refs.map.$map
  fetch('http://localhost:8080/geoserver/rest/styles/suburb_culture_diversity.MBStyle').then(function (response) {
    response.json().then(function (glStyle) {
      applyStyle(layer, glStyle, 'suburb_culture_diversity').then(function () {
        map.addLayer(layer)
      })
    })
  })
},
```

**Comment by ghettovoice** [comment]
Try to add `:pixel-ratio="window.devicePixelRatio"` to `vl-map` tag in your Vue related code.
I suspect that vuelayers wrapped map and openlayers map gets different `pixelRatio` value and this causes some threshold error.

**Comment by dmcd** [comment]
Thanks!
That fixed the fuzziness. I had to put it in a function like so: 
```javascript
<vl-map class="map" ref="map" :pixel-ratio="getDevicePixelRatio()" :load-tiles-while-animating="true" :load-tiles-while-interacting="true"
@created="onMapCreated">
  <vl-view ref="view" :center.sync="center" :zoom.sync="zoom" :rotation.sync="rotation">
  </vl-view>
</vl-map>
...
getDevicePixelRatio () {
  return window.devicePixelRatio
},
```
I'm still getting the faint white lines, just doing some googling for that now.

**Comment by dmcd** [comment]
Ok, removing `renderMode: 'vector'` from the VectorTileLayer fixed the white lines.

**Comment by ghettovoice** [comment]
It's nice, but I don't understand why it's working for you because `renderMode: 'vector'` is used by default :)

**Comment by dmcd** [comment]
Looks like the default renderMode in openlayers 4.6.5 is now "hybrid". Not sure if that was a recent change?
https://openlayers.org/en/latest/apidoc/ol.layer.VectorTile.html
