### ISSUE TITLE
Vuelayers support ECW format?

### ISSUE THREAD

**Issue by Donchurru** [ghettovoice/vuelayers#492]
Hello and Thank you for VueLayers!

I need to display an ecw image on vuelayers and i don´t know how to do it.

I don't know if there is any option to make it easy.

Thanks!

**Comment by ghettovoice** [comment]
Hello @Donchurru ,
I'm not very familiar with ecw format, so it is just my assumption.
To load ecw image into the web you need to setup WMS service with any mapserver (probably GeoServer supports it, but I'm not sure) that can work with this type of geodata images. Then you can load this data into the VueLayers (and OpenLayers too) using WMS source (vl-layer-tile + vl-source-tile-wms).

**Comment by Donchurru** [comment]
Thanks, but I would need to upload the file from offline, Like an image.
I don't know if you can suggest me the best way to do it.

Thanks

**Comment by ghettovoice** [comment]
Yep, I understand. 
I'm just talking that ECW usually need some mapserver that can serve it for the web, split for tiles if it is big and so on. 
So I doubt that exists some js lib for the web that can directly show data from ECW, at least simple googling shows nothing.

Another option I have found here https://groups.google.com/g/leaflet-js/c/AxANUKRSVBs (last comment)
You can try with QGIS gdal2tiles tool, it can prepare for you tiles directory that then can be easily shown with any popular web map lib.
