### ISSUE TITLE
 I'm using vuelayers in my application currently I created a button that selects all my points on the map so far everything is perfect, now when all the points are selected and I try to select just one clicking it gives an error

### ISSUE THREAD

**Issue by TavinhoFIux** [ghettovoice/vuelayers#497]
I'm using vuelayers in my application currently I created a button that selects all my points on the map so far everything is perfect, now when all the points are selected and I try to select just one clicking it gives an Error in nextTick: "NotFoundError: Failed to execute 'insertBefore' on 'Node': The node before which the new node is to be inserted is not a child of this node

**Comment by ghettovoice** [comment]
Hello @TavinhoFIux ,
I'm trying to reproduce this basing on your description https://jsfiddle.net/ghettovoice/Ln9qr135/333/.
But don't see any errors, so I think the possible error somewhere else. 
Can you you provide some demo app or source code? Especially how do you render features on the map, select them and so on.
