### ISSUE TITLE
Global data projection vs view projection option

### ISSUE THREAD

**Issue by flyfishMT** [ghettovoice/vuelayers#50]
If I am working with EPSG:4326 data, what is the benefit of using the global dataProjection or map data-projection binding over setting the projection option of the View to EPSG:4326?  Thank you.

**Comment by ghettovoice** [comment]
Hi, @flyfishMT,
there is no benefit, if you use EPSG:4326 as view projection all coordinate data will be in EPSG:4326 too.
Data projection is used only for convenience when view and data in different projections (view EPSG:3857 but geographic data usually in EPSG:4326 ).

**Comment by flyfishMT** [comment]
Ok that makes sense thank you.
