### ISSUE TITLE
VectorTile Layer flashes on zoom with zoom.sync modifier

### ISSUE THREAD

**Issue by lol2x** [ghettovoice/vuelayers#503]
I believe it may be similar to #485

VlLayerVectorTile flashes when zoom have .sync modifier note: I'm using custom projection
I'm actually unable to create reproduction of the error right now (lack of public .mvt tiles layers)
However I've recorded the problem
Zoom without sync:
[![Zoom without sync](http://img.youtube.com/vi/KVPW9P-5eCY/0.jpg)](https://youtu.be/KVPW9P-5eCY "Zoom without sync")
Zoom with sync:
[![Zoom with sync](http://img.youtube.com/vi/glm7y09VXGA/0.jpg)](https://youtu.be/glm7y09VXGA "Zoom with sync")
Zoom with sync and background openlayers (not flashing):
[![Zoom with sync and background](http://img.youtube.com/vi/Qj_ZB7NeMnQ/0.jpg)](https://youtu.be/Qj_ZB7NeMnQ "Zoom with sync and background")

**Comment by ghettovoice** [comment]
Hello @lol2x ,
thanks for report!
I will try to review this issue ASAP

**Comment by lol2x** [comment]
same thing happening for center.sync

**Comment by ghettovoice** [comment]
Hello @lol2x , 
I'm debugging this issue... and having troubles with reproduction with public vector tiles data.
Can you provide me with a piece of code where you configure map, view and vector tile layer/source?
