### ISSUE TITLE
Layer component doesn't watches for extent change

### ISSUE THREAD

**Issue by become-iron** [ghettovoice/vuelayers#51]
I believe it should be in watch section of layer mixin:

```
extent (value) {
  if (this.$layer) {
    this.$layer.setExtent(value)
  }
}
```

**Comment by ghettovoice** [comment]
Hi, @become-iron ,
you are right, it should be here.

**Comment by ghettovoice** [comment]
Hi! Please try v0.10.8, it should resolve the issue.
Thank you for conversation!

**Comment by become-iron** [comment]
Yeah, thank you. I think it works properly
