### ISSUE TITLE
Attribution is always collapsed by default

### ISSUE THREAD

**Issue by iboates** [ghettovoice/vuelayers#514]
I have an attribution text but it is always collapsed by default. [In vanilla OL you would have to create an Attribution object and set its `collapsible` paramater to false](https://openlayers.org/en/latest/examples/attributions.html). Can you do this in VueLayers?

![image](https://user-images.githubusercontent.com/13814358/186113091-32e74124-8ea0-4ac2-873f-8c683293e598.png)

**Comment by ghettovoice** [comment]
Hello @iboates ,
vl-map has a prop `default-controls` though which you can configure initial set of map controls.
The value can be an object or a collection of controls (by default it is true - use default set of controls), you can find description of this object here https://openlayers.org/en/v6.15.1/apidoc/module-ol_control.html#.defaults.

So, for your case, to only reconfigure Attributions control you can set something like this:
```html
<VlMap :default-controls="{attributionOptions: {collapsed: false, collapsible: true}}">...</VlMap>
```
