### ISSUE TITLE
Projections failing in v12.x

### ISSUE THREAD

**Issue by bmcalees** [ghettovoice/vuelayers#515]
I'm just getting around to updating to v12.x and getting the following warning/errors:

![image](https://user-images.githubusercontent.com/7414766/188996340-0e60da4a-5b1a-43b8-b040-4150ad285459.png)

I'm assuming the warnings are tied to the errors but not sure.

Previously, we passed the 'projection name' to the vl-map and vl-view components and this seemed to work fine. Has this changed?

Here is an example of the projection I'm trying to use. Previously it was added via the 'addProj' import from VueLayers but this has been changed to use OL now.

`import { addProjection as addProj, get as getProj } from 'ol/proj';`
`import Projection from 'ol/proj/Projection';`
`const projection = new Projection({
        code: this.projectionName,
        units: 'pixels',
        extent: this.extent,
      });`
`addProj(projection);`

Lastly, here is how the projection is being sent to VueLayers:

![image](https://user-images.githubusercontent.com/7414766/188997053-cb268fc1-619b-4fe4-8656-1ac628009af2.png)

**Comment by ghettovoice** [comment]
Hello @bmcalees ,
very often after upgrade to v0.12 you may have now 2 versions of `ol` package inside `node_modules`, v5 used with vuelayers v0.11 and v6 installed with vuelayers v0.12. Probably because you manually installed `ol@v4` before and have it's amoung your app dependencies. Try to drop any `ol` package and re-install vuelayers v0.12.

**Comment by bmcalees** [comment]
Hi @ghettovoice,

I triple checked and only one version of `ol` in `node_modules`. I've also deleted `node_modules` and re-installed.

The error seems to be coming from the inability to find the source projection. Notice in the image below that `destination = CYTO-241607821` but `destinationProjection = null`.

![image](https://user-images.githubusercontent.com/7414766/189397597-f686d2d8-e69e-4999-a25a-9e4e916623cb.png)

In my original question I show how the projection is being created and added. Any idea why this isn't working?

**Comment by bmcalees** [comment]
Found my issue. I was adding my projection to my local instance of `ol` and not the `VueLayers` instance. 

In the prior version of `VueLayers` these `ol` functions were exposed like so:

`import { addProj, createProj, getProj } from 'vuelayers/lib/ol-ext';
`

The solution was to change it to this:

`import { addProjection as addProj } from 'vuelayers/node_modules/ol/proj';`
