### ISSUE TITLE
Label Vector Fonts don't' have the right rendering [BUG]

### ISSUE THREAD

**Issue by silassantos21** [ghettovoice/vuelayers#517]
**Label text founded in style-func has weird break fonts**
When i try to load my map with dynamic text in each vector, the font texts are appearing like a weird writing.
In each loading, the weird font appears in randomly vectors

<img width="599" alt="gitHubIssues1" src="https://user-images.githubusercontent.com/32674845/189415759-576fffc0-d715-4db9-919d-2a19223f8e01.PNG">

<img width="585" alt="gitHubIssues2" src="https://user-images.githubusercontent.com/32674845/189415788-0af74c9b-caad-4ddd-a68a-c9601a6f0147.PNG">

Can i fix this using the style-func or would be other way?

**Expected behavior**
The dynamic vectors text comes with the normal config style and font

**Comment by ghettovoice** [comment]
Hello @silassantos21 ,
interesting picture, I'm not sure what can be a reason .
Can you provide a code sample how do you define style for this vector layer? 
I'll try to reproduce/debug

**Comment by silassantos21** [comment]
I can't reply in a codesanbox, but i can show the code snippet configuration:

I configure the vector style and coordenates using vl-style-func:

```
<vl-layer-vector id="draw-pane">
    <vl-source-vector ident="draw-target" ref="source" :features="drawnFeaturesFilter"></vl-source-vector>
    <vl-style-func :factory="styleFuncFactory" />
  </vl-layer-vector>
```  
  Inside the styleFuncFactory, i have this configuration
  
```
  styleFuncFactory () {
      // eslint-disable-next-line no-unused-vars
      return (feature, resolution) => {
        let textDesk = feature.values_.deskName
        var deskMarker = new Style({
          image: new Icon({
            src: require('../assets/svg/location_on-24px.svg'),
            imgSize: [ 30, 30 ]
          }),
        })
          deskMarker['text_'] = new Text({
            text: textDesk,
            offsetY: 20,
            offsetx: -15,
            padding: [3, 3, 3, 3],
            backgroundFill: new Fill({color: 'white'}),
            backgroundStroke: new Stroke({ color: '#e1e1e1'}),
          })
        let styles = [ deskMarker ]
        return styles
      }
    },
```

OBS: Style, Icon, Text, Fill and Stroke are imported by ol

```
import Icon from 'ol/style/icon'
import Style from 'ol/style/style'
import Fill from 'ol/style/fill';
import Stroke from 'ol/style/stroke';
import Text from 'ol/style/text';
```

**Comment by ghettovoice** [comment]
Hello @silassantos21 ,
frankly speaking I'm not sure what's going on. Maybe it is something with text or font... However default font is `10px sans-serif`, most common value.
Here https://codesandbox.io/s/vuelayers-v0-12-dynamic-labels-0u8344 I have made a simple demo with dynamic text labels. Do you see any rendering issues?
