### ISSUE TITLE
When using vl-geom-line-string or vl-geom-multi-line-string the map tiles arent loaded correcty anymore.

### ISSUE THREAD

**Issue by basbroens** [ghettovoice/vuelayers#521]
When using vl-geom-line-string or vl-geom-multi-line-string the map tiles arent loaded correcty anymore.

Is there a way to fix this?

my code:

`  <vl-map ref="map" :update-while-animating="true" :update-while-interacting="true" :max-tiles-loading="100" :default-interactions="{doubleClickZoom:false}" @dblclick="newMarkerOpen($event)" data-projection="EPSG:4326">

                        <vl-view :zoom.sync="mapZoom" :center.sync="mapCenter"></vl-view>
                        <vl-layer-tile  id="osm">
                            <vl-source-osm></vl-source-osm>
                        </vl-layer-tile>

                            <vl-feature v-if="item.history && item.history.length" v-for="(item,key) in history">
                                <vl-geom-multi-line-string :id="'line'+key"  :coordinates="item.history" />
                                <vl-style>
                                    <vl-style-stroke line-join="bevel" :line-dash="[10, 10]" :width="4" :color="getColor(item.name)" />
                                </vl-style>
                            </vl-feature>
</vl-map>`

![Capture](https://user-images.githubusercontent.com/24257007/192720609-8de1144b-88ce-435f-ae00-5af806869f5c.JPG)

**Comment by ghettovoice** [comment]
Hello @basbroens ,
which version of vuelayers do you use? 
With v0.12 I don't see any problems using line string geometries. 
Do you sure it is not some network problems?
