### ISSUE TITLE
unmount maps

### ISSUE THREAD

**Issue by fernanduandrade** [ghettovoice/vuelayers#525]
Hello! What's the best practice for umountings the maps?

**Comment by ghettovoice** [comment]
Hello @fernanduandrade ,
unmounting is done by Vue automatically via `beforeDestroy` hook.
But if you need to make it programmatically, you can use 
```js
mapCmp.$destroy() - std Vue method to unmount and destroy component
mapCmp.unmount() - vuelayers method to unmount only ol/Map object.
```

**Comment by fernanduandrade** [comment]
thankyou u'r the best. I'm not used to use the beforeDestroy hook, that helps a lot
