### ISSUE TITLE
Demos not working in Webpack install

### ISSUE THREAD

**Issue by chgad** [ghettovoice/vuelayers#526]
Hello,

I'm using a webpack config for my project and added the libraray like so

    import Vue from 'vue'
    import App from './App.vue'
    import vuetify from './plugins/vuetify'
    import VueLayers from 'vuelayers'
    import 'vuelayers/dist/vuelayers.css' // needs css-loader

    Vue.use(VueLayers)
    Vue.config.productionTip = false

    new Vue({
      vuetify,
      render: h => h(App)
    }).$mount('#app')

And to test/try-out the library's features I copied both the [geo-map](https://vuelayers.github.io/#/docs/component/geoloc?id=usage) and the [xkcd](https://vuelayers.github.io/#/docs/component/image-layer?id=usage) demos to my root App.vue component.

This is the result

![Screenshot from 2022-11-29 21-01-43](https://user-images.githubusercontent.com/21121667/204636038-670b4949-ccc3-4a8e-aa3f-08604c2610fe.png)

It seems like everything but the actual maps is working.

Am I missing a loader config or some other dependency? Is my webpack install incorrect or missing something?

Thanks in adnvance.

**Comment by ghettovoice** [comment]
Hello @chgad ,
you are right, it seems that map components are loaded but images from OSM layer is missing.
Do you see some errors in browser console, nodejs console ? 
and  also do you see requests on browser network tab to openstreet map tiles? something like this https://a.tile.openstreetmap.org/2/1/2.png

**Comment by chgad** [comment]
Okok... i don't know why but it seems like i didn't pay attention to the Errors in the console.

I had errors showing "sourceProjection is null" which was caused by an `ol@v7` install. Downgrading to `ol@v6` fixed everything.

Now the XKCD Demo works. But the geo-map demo is still not showing the map. Now without any Error messages and no requests fetching map tiles.

I tried copying [this](https://vuelayers.github.io/#/docs/component/map) map demo and it works just fine (BUG: Implementing [this](https://vuelayers.github.io/#/docs/component/map) map and the XKCD demo alongside each other seems to work as long as you do not scroll the normal map. As soon as you drag or scroll the map, the XKCD map disappears.)


In addition to that matter: It would be great to add a "you need to install ol manually" statement to the docs.

**Comment by ghettovoice** [comment]
> I tried copying [this](https://vuelayers.github.io/#/docs/component/map) map demo and it works just fine (BUG: Implementing [this](https://vuelayers.github.io/#/docs/component/map) map and the XKCD demo alongside each other seems to work as long as you do not scroll the normal map. As soon as you drag or scroll the map, the XKCD map disappears.)

XKCD example uses custom non-geographic projection. So, if you share it's view with another map in EPSG projection, after dragging normal geo map, XKCD map just moves somewhere far away of image. You can check coordinates, view extents of both maps in Vue dev.

> In addition to that matter: It would be great to add a "you need to install ol manually" statement to the docs.

`ol@6` is among vuelayers dependencies, so if you didn't manually install `ol` package before vuelayers, npm should install vuelayers and all it's dependencies with correct versions. Current stable vuelayers based on `ol@6`.

> Now the XKCD Demo works. But the geo-map demo is still not showing the map. Now without any Error messages and no requests fetching map tiles.

Thats interesting, OSM layer works on one map and don't work on another. What do you see in Vue devtool's components tree? Do you see `<VlLayerTile> -> <VlSourceOsm>` nodes in the `<VlMap>` node?

**Comment by chgad** [comment]
> XKCD example uses custom non-geographic projection. So, if you share it's view with another map in EPSG projection, after dragging normal geo map, XKCD map just moves somewhere far away of image. You can check coordinates, view extents of both maps in Vue dev.

So in general all maps rendered are moved simultaneously ?

> Thats interesting, OSM layer works on one map and don't work on another. What do you see in Vue devtool's components tree? Do you see <VlLayerTile> -> <VlSourceOsm> nodes in the <VlMap> node?

This is what the VueDevTool shows me:

![Screenshot from 2022-12-06 14-47-42](https://user-images.githubusercontent.com/21121667/205929609-9cb0457e-7dc8-4916-a1d4-c8af928e1942.png)


As i inspected both of the maps i recognized that the geo-map has an additional `data-projection="EPSG:4326"` prop set.

Removing this prop, the map gets render just like the others. Is this maybe a deprecated or fault projection?
