### ISSUE TITLE
WIN BUILD ERROR 

### ISSUE THREAD

**Issue by xdengpao** [ghettovoice/vuelayers#53]
when i install vuelayers with "npm run build" on windows
the wrong out:
![image](https://user-images.githubusercontent.com/32158950/40412219-3fc970a2-5ea5-11e8-94d5-1469cf2de788.png)

**Comment by xdengpao** [comment]
is it not builded on Windows?

**Comment by ghettovoice** [comment]
Hi @xdengpao !
No, I build it only on Linux, didn't try Windows setup. As I can see from screenshot I use `rm` linux utility in the `clean` command. You can try to run `npm run rollup` command to avoid `clean` call.
Thank you!

**Comment by xdengpao** [comment]
@ghettovoice Thank You！

**Comment by ghettovoice** [comment]
Ok, I close this. If have another questions open new one.
Thanks!
