### ISSUE TITLE
Using filters for tile layers

### ISSUE THREAD

**Issue by sparrow92** [ghettovoice/vuelayers#533]
vl-layer-tile has no events. Is it posible to do something like this in VueLayers?

```
    osm.on('prerender', (event) => {
       if (event.context) {
         const context = event.context;
         context.filter = 'invert(90%) contrast(60%)';
         context.globalCompositeOperation = 'source-over';
      }
    })
```

I have no idea how to do the trick.

**Comment by ghettovoice** [comment]
Hello @sparrow92 ,
yes, you subscribe on `prerender`/`postrender` events on vl-layer-tile component. The event object is same as in OpenLayers.
