### ISSUE TITLE
Support for Openlayers 7

### ISSUE THREAD

**Issue by scadergit** [ghettovoice/vuelayers#534]
If I could contribute to resolving braking changes, are you open to creating 0.13 that supports OL 7?

**Comment by ghettovoice** [comment]
Hello @scadergit,
yes, no prob.

**Comment by scadergit** [comment]
I'm ready to start picking away at OL7 breaking changes, will you create the 0.13 alpha so I can fork?

**Comment by ghettovoice** [comment]
Nice!
I have made ol7-dev, you can fork and push here.
