### ISSUE TITLE
forEachFeatureAtPixel layerFilter not excute in right way

### ISSUE THREAD

**Issue by erDuo10** [ghettovoice/vuelayers#537]
![image](https://github.com/ghettovoice/vuelayers/assets/10446440/d262e83c-5765-4fa5-8271-a08b2d3a597d)

    onMapPointerMove(e) {
      let hitFeature = this.$refs.map.$map.forEachFeatureAtPixel(
        e.pixel,
        this.handleDemanderFeatureClick,
        { layerFilter: function(layer) {
            const id = layer.get("id");
            return id != undefined && id.startsWith('wells-status');
          }
        }
      )

      console.error('onMapPointerMove hitFeature:', hitFeature);
    },
     handleDemanderFeatureClick(feature, layer ){
       console.error('handleDemanderFeatureClick feature:', feature);
       console.error('handleDemanderFeatureClick layer:', layer);

       return feature;
     },

as the code show, layerFilter do not implement filter use, the filter code could not trigger the callbak method handleDemanderFeatureClick.

after delete the filter,  the onMapPointerMove trigger many a time

**Comment by ghettovoice** [comment]
Hello @erDuo10 ,

You should check layer id is correct, and is it "managed"(not added as overlay) layer, is it vector layer and etc. 
There is extended documentation https://openlayers.org/en/v6.15.1/apidoc/module-ol_Map-Map.html#forEachFeatureAtPixel, when call though `this.$refs.map.$map.forEachFeatureAtPixel`.
There is also a demo https://jsfiddle.net/ghettovoice/Ln9qr135/460/

**Comment by erDuo10** [comment]
Thank you! That helps a lot.
