### ISSUE TITLE
 VueLayers with OpenLayers version 4.x

### ISSUE THREAD

**Issue by TioWidow** [ghettovoice/vuelayers#54]
Hello, On the compatibility of VueLayers with OpenLayer version 4.x, are there any plans to perform this compatibility?

Thank you for the attention and the fantastic project.

**Comment by ghettovoice** [comment]
Hi, @TioWidow ,
what kind of compatability do you mean?
I'm using vuelayers in several projects with ol v4 and don't have any problems

**Comment by TioWidow** [comment]
Thanks for the quick response, I probably had a misunderstanding about the version of openlayers that was compatible then.

We are still in the phase of evaluating the components to be used, the possibility of using VueLayers is great and for the time being I only had good impressions

Sorry for the embarrassment,

**Comment by ghettovoice** [comment]
No problem man. If you have questions , I'm ready to help. 
Currently the documentation is pure, I don't have much time to write it. But I'm trying to answer as fast as possible

**Comment by ghettovoice** [comment]
Close this. Re-open or add new one if you have question
