### ISSUE TITLE
question: what do you think about using vuex to drive openlayers?

### ISSUE THREAD

**Issue by guidorice** [ghettovoice/vuelayers#55]
First off, `vuelayers` looks very useful! I cannot wait to use it to build some cool GIS apps. Thanks so much for creating this library!

I am pretty new to Vue.js so this is a general question. Did you ever consider using `vuex` https://vuex.vuejs.org/ to implement vuelayers? 

In some Js frameworks, there is a formal way of communicating with 3rd party libraries which have side effects and generate events. e.g. Elm's ports, or Cycle.js's drivers. Along these lines, I was  thinking `vuex` would be the best way to integrate with a 3rd party library like openlayers into Vue.js. I have been tinkering around with ways to do it, with mixed results, not knowing best practices for `vuex` usage, and dynamic module registration in particular.

But I see that `vuex` is not used anywhere in `vuelayers`. What do you think about the pros and cons of your component oriented approach vs. a `vuex` flux-pattern approach? I see you have implemented a good part of the openlayers api already, so it certainly appears to be working well.

Just a question :) thanks again

**Comment by ghettovoice** [comment]
Hi @guidorice!
I think that requirement to use vuex with vuelayers may be an overkill, I'm trying to make vuelayers tiny as possible. Also vuex is not the one state solution for Vue, there are several other implementations https://github.com/vuejs/awesome-vue#state-management, it would be hard to support at least two of them.
So I think that state management lib like vuex should be an opt in of the end user application. This is not so hard to connect several libs with vuex in application code where you know usage context.
Thank you

**Comment by guidorice** [comment]
@ghettovoice thanks for sharing your rational and design. Makes sense! I look forward to contributing to `vuelayers`, should any enhancements or issues come up in future.

**Comment by ghettovoice** [comment]
Ok, thank you! :+1:
