### ISSUE TITLE
Colour maps and props

### ISSUE THREAD

**Issue by Fer17** [ghettovoice/vuelayers#57]
First of all, great job! A wonderful implementation of OpenLayers library with VueJs.

Is there any way to give colour to a set of specific countries in your vl-source-vector (url) example?

For instance: <vl-source-vector url="https://openlayers.org/en/latest/examples/data/geojson/countries.geojson" :country="FRA" : colour="red"></vl-source-vector>

As a general question, is there a "props" passingthrough -or whatever method-  in order to call primitive OL functions?

Thank you in advance.

**Comment by ghettovoice** [comment]
Hi @Fer17 ,
thank you!
Yes, there is vl-style-func component (https://github.com/ghettovoice/vuelayers/blob/master/src/component/style-func/style.vue) that helps to dynamically style any vl-vector-layer, but currently there is no documentation for it. Check this example:

```html
<template>
  <vl-map ...>
    ...
    <vl-layer-vector>
      <vl-source-vector ...></vl-source-vector>

     <vl-style-func :factory="styleFuncFactory"></vl-style-func>
   </vl-layer-vector>
  </vl-map>
</template>

<script>
export default {
  methods: {
    styleFuncFactory () {
      // here you can pre-create non-dynamic styles

      return function __styleFunc (feature) {
         // do what you need to dynamically create array of ol.style.Style objects
        // from feature( ol.Feature) properties
      }
    },
  },
}
</script>
```
[This](styleFuncFactory) and [this](https://github.com/ghettovoice/vuelayers-demo/blob/master/src/App.vue#L305) are another examples of style function factory.

**Comment by ghettovoice** [comment]
Close this due to inactivity
