### ISSUE TITLE
How to use some features ?

### ISSUE THREAD

**Issue by rSammy** [ghettovoice/vuelayers#59]
Hello.

There is no docs for all of the categories.

I'd like to know how to use vuelayers to setup polygons from geojson.
How to use the select feature ?

Thank you

**Comment by ghettovoice** [comment]
Hi @rSammy , you are right, currently the doc is pure.
You can find usage example of vl-interaction-select with styling and popup in demo app https://github.com/ghettovoice/vuelayers-demo/blob/master/src/App.vue. 

Also you can find example of loading vector features from simple array, remote url and etc.
In short: 
- if you load features yourself, or already have an collection of GeoJSON features, so you can use `features` property on `vl-source-vector` component that accepts array of GeoJSON features. example from demo https://github.com/ghettovoice/vuelayers-demo/blob/master/src/App.vue#L497. `staticFeatures` passed to `vl-source-vector` like that `<vl-source-vector :features="staticFeatures"></vl-source-vector>`
- if you want to load features from a remote geo service (WFS or another custom API) you can use `url` property or `loader-factory` properties. If you provide `url` property then default xhr loader will be used (example from demo with `url` as string https://github.com/ghettovoice/vuelayers-demo/blob/master/src/App.vue#L525, and `url` as function https://github.com/ghettovoice/vuelayers-demo/blob/master/src/App.vue#L627). If you need to load features from some custom API you should use `loader-factory` - this is function that returns [ol.FeatureLoader function](http://openlayers.org/en/latest/apidoc/ol.html#.FeatureLoader)

Mostly the behavior of components is close to behavior of OpenLayers components on which VueLayers is based.

**Comment by rSammy** [comment]
Thank you,

Indeed I searched through some demo code.
I still can't load my local geojson, so I ended up using url mode.

**Comment by ghettovoice** [comment]
Can you provide your code? May be I can help

**Comment by rSammy** [comment]
```
<template>
    <vl-map :load-tiles-while-animating="true" :load-tiles-while-interacting="true" style="height: 400px">
        <vl-view :zoom.sync="zoom" :center.sync="center" :rotation.sync="rotation"></vl-view>

        <vl-layer-tile id="osm">
            <vl-source-osm></vl-source-osm>
        </vl-layer-tile>


        <component v-for="layer in layers" :is="layer.cmp" v-if="layer.visible" :key="layer.id" v-bind="layer">
            <!-- add vl-source-* -->
            <component :is="layer.source.cmp" v-bind="layer.source">
                <!-- add static features to vl-source-vector if provided -->
                <vl-feature v-if="layer.source.staticFeatures && layer.source.staticFeatures.length"
                            v-for="feature in layer.source.staticFeatures" :key="feature.id"
                            :id="feature.id" :properties="feature.properties">
                    <component :is="geometryTypeToCmpName(feature.geometry.type)" v-bind="feature.geometry"></component>
                </vl-feature>

                <!-- add inner source if provided (like vl-source-vector inside vl-source-cluster) -->
                <component v-if="layer.source.source" :is="layer.source.source.cmp" v-bind="layer.source.source">
                    <!-- add static features to vl-source-vector if provided -->
                    <vl-feature v-if="layer.source.source.staticFeatures && layer.source.source.staticFeatures.length"
                                v-for="feature in layer.source.source.staticFeatures" :key="feature.id"
                                :id="feature.id" :properties="feature.properties">
                        <component :is="geometryTypeToCmpName(feature.geometry.type)" v-bind="feature.geometry"></component>
                    </vl-feature>
                </component>
            </component>
            <!--// vl-source-* -->

            <!-- add style components if provided -->
            <!-- create vl-style-box or vl-style-func -->
            <component v-if="layer.style" v-for="(style, i) in layer.style" :key="i" :is="style.cmp" v-bind="style">
                <!-- create inner style components: vl-style-circle, vl-style-icon, vl-style-fill, vl-style-stroke & etc -->
                <component v-if="style.styles" v-for="(st, cmp) in style.styles" :key="cmp" :is="cmp" v-bind="st">
                    <!-- vl-style-fill, vl-style-stroke if provided -->
                    <vl-style-fill v-if="st.fill" v-bind="st.fill"></vl-style-fill>
                    <vl-style-stroke v-if="st.stroke" v-bind="st.stroke"></vl-style-stroke>
                </component>
            </component>
            <!--// style -->
        </component>
            <!--// vl-source-* -->

    </vl-map>
</template>

<script>
    import store from '../../store';
    import Vue from 'vue'
    import VueLayers from 'vuelayers'
    import 'vuelayers/lib/style.css' // needs css-loader
    import domainsJson from './domains.json'
    import { kebabCase, range, random, camelCase } from 'lodash'

    Vue.use(VueLayers)

    export default {
        props: [],
        store,
        computed : {

        },
        data() {
            return {
                zoom: 2,
                center: [0, 0],
                rotation: 0,
                geolocPosition: undefined,
                layers: [
                    // Countries vector layer
                    // loads GeoJSON data from remote server
                    {
                        id: 'domains',
                        title: 'Domains',
                        cmp: 'vl-layer-vector',
                        visible: true,
                        source: {
                            cmp: 'vl-source-vector',
                            staticFeatures: domainsJson.features,
                        },
                    },
                ]
            }
        },
        methods: {
            geometryTypeToCmpName (type) {
                return 'vl-geom-' + kebabCase(type)
            },
        },
        components: {
            VueLayers
        },
        mounted() {
            console.log(domainsJson.features);
        }
    }
</script>

```

**Comment by rSammy** [comment]
By the way, how to set boundaries ? 

I don't want the map to exceed some coordinates

**Comment by ghettovoice** [comment]
> By the way, how to set boundaries ?
You can use [`extent`](https://vuelayers.github.io/#/component/view?id=extent) on the `vl-view` component.
This will restricts the map center to only be inside defined rectangle

**Comment by rSammy** [comment]
Is this interaction supported ?

```
// select interaction working on "pointermove"
var selectPointerMove = new ol.interaction.Select({
    condition: ol.events.condition.pointerMove
});
```

**Comment by rSammy** [comment]
My bad I didn't notice the extent property. 
I'm using ESPG 4326, does it work the same way as 3857 ?

**Comment by ghettovoice** [comment]
> does it work the same way as 3857 ?

Yes

If you plan to use EPSG:4326 everywhere so the best option is to define `data-projection="EPSG:4326"` on vl-map component to switch all components to that projection when working with plain GeoJSON or coordinates data (internally vl-view will continue with EPSG:3857 projection).

**Comment by rSammy** [comment]
Indeed it did the trick, the same goes for local geojson loading.

May I know if pointer move interaction is supported ?  You may have skipped the question 😃

**Comment by rSammy** [comment]
What is the callback for select interaction ?

I'd like to bind it to some method

**Comment by ghettovoice** [comment]
> May I know if pointer move interaction is supported ? 

Are you mean draw point interaction? Or something else? Drawing is supported by vl-interaction-draw and vl-interaction-modify components

> What is the callback for select interaction ?

vl-interaction-select fires `select`/`unselect` events - that mostly low level OpenLayers events, you get `{feature: ol.Feature, mapBrowserEvent: ol.MapBrowserEvent }` as argument. Or `update:features` - this is the top-level Vue event that synchronizes state of the `feature` property

**Comment by rSammy** [comment]
By pointer move, I mean when the mouse hover some polygons. I used it in default open layer.

-----------------------------------------------------

In fact I'd like to get the properties of the selected area from my geojson file

-----------------------------------------------------

I can't get extent to work properly

**Comment by rSammy** [comment]
I found with vue-devtools which events were fired with values.

**Comment by rSammy** [comment]
But I still can't get the value when the pointer hovers some polygons. 

![image](https://user-images.githubusercontent.com/30237980/41363038-ee02c02c-6f00-11e8-80fa-b01565ac3ee8.png)

**Comment by ghettovoice** [comment]
You should use `forEachAtCoordinate` on the map component in `pointermove` handler.
```html
<template>
  <vl-map ref="map" @pointermove="onPointerMove" ...></vl-map>
</template>

<script>
export default {
   methods: {
      onPointerMove ({ pixel }) {
          let feature = this.$refs.map.forEachFeatureAtPixel(pixel, ....)
          // then find your geojson feature by id in your data     
      },
   },
}
</script>
```
