### ISSUE TITLE
Add support of GetFeatureInfo request

### ISSUE THREAD

**Issue by ghettovoice** [ghettovoice/vuelayers#6]
Add methods to send request GetFeatureInfo in WMS source

**Comment by JeremyGerard** [comment]
Hi,

Do you have erase this functionnality with the commit : 0b958e256063f6fe7a8a20eea573f38464532b32 ?

**Comment by ghettovoice** [comment]
Hi, 
I don't, just move it to wmsSource mixin.
Is it missing?

**Comment by JeremyGerard** [comment]
Oh yes you right ! 
Thanks

**Comment by JeremyGerard** [comment]
But i have an error...
 error  in ./node_modules/vuelayers/src/util/minilo.js

Module parse failed: Unexpected token (14:20)
You may need an appropriate loader to handle this file type.

I m beginner in vuejs. Do you know what's my issue ?

**Comment by ghettovoice** [comment]
Are you import components from vuelayers `src` folder?

**Comment by JeremyGerard** [comment]
i do that : 
<script>
    import getFeatureInfoUrl from '../../node_modules/vuelayers/src/mixin/wms-source.js'
export default {

**Comment by JeremyGerard** [comment]
and in my main.js : 
import VueLayers from 'vuelayers'
Vue.use(VueLayers)

**Comment by ghettovoice** [comment]
You need only this
```
import VueLayers from 'vuelayers'
Vue.use(VueLayers)

```

Method getFeetureInfoUrl is part of `vl-source-wms` and `vl-source-image-wms` components.

Anyway if you want use mixins, or helpers from vuelayers, you should import them from `vuelayers/lib/....`. **lib** folder contains compiled source code

**Comment by ghettovoice** [comment]
In vuelayers v0.10.x under **lib** all components compiled for CommonJs environment. If you are using webpack so you can use ES modules  import/export that under **lib/_esm** folder.

In the next v0.11 version commonjs support will be dropped, all compiled code will be under **lib** folder

**Comment by JeremyGerard** [comment]
I think that because actually i have this error : 
TypeError: _node_modules_vuelayers_lib_mixin_wms_source__WEBPACK_IMPORTED_MODULE_0___default(...) is not a function

**Comment by ghettovoice** [comment]
I wrote not quite well about **src** folder. You can use any module from here but cause there is a source code you should compile it yourself.

 **lib** folder contains ready to use compiled modules.

**Comment by ghettovoice** [comment]
> _node_modules_vuelayers_lib_mixin_wms_source__WEBPACK_IMPORTED_MODULE_0___default(...) is not a function

wms-source.js default export is a plain object.

```
import wmsSource from 'vuelayers/lib/mixin/wms-source'

wmsSource.methods.getFeatureInfoUrl 
```

**Comment by JeremyGerard** [comment]
Right.
with your method i have this : 
Error: component has "$view" property

I must add resolution and projection

**Comment by ghettovoice** [comment]
Because wmsSource is an mixin, it should be used to build a vue component. This component inherits all methods from wmsSource.

What are you trying to make? Is it a custom wms source?

**Comment by JeremyGerard** [comment]
is it make reference to vl-view ?

**Comment by JeremyGerard** [comment]
i have a map with wms data. I try to catch my wms source tile informations

**Comment by JeremyGerard** [comment]
Yes it is

**Comment by JeremyGerard** [comment]
thanks for your help. 
I give you some news when i succes

**Comment by ghettovoice** [comment]
Are you render wms layers with vl-source-wns component? If so all you need is add ref attribute for each vl-source-wms tags, then use getFeatureInfoUrl method of the component instance.
```html
<template>
  <vl-map @click="mapClicked">
    <vl-layer-tile>
      <vl-source-wms ref="mySource" ...></vl-source-wms>
    </vl-layer-tile>
  </vl-map>
</template>

<script>
export default { 
  ...
  methods: {
    mapClicked (evt) {
      console.log(this.$refs.mySource.getFeatureInfoUrl(evt.coordinate))
    },
  }
}
</script>
```

**Comment by ghettovoice** [comment]
I'm writting from phone, so sorry if there is some errors in example

**Comment by JeremyGerard** [comment]
Again i have a reference issu : 
this.$source.getFeatureInfoUrl is not a function

**Comment by JeremyGerard** [comment]
I have try : <vl-source-wms v-bind:ref="mySource"
but that s not better

**Comment by JeremyGerard** [comment]
I don't have acces to  :  
this.$source.getFeatureInfoUrl is not a function

**Comment by ghettovoice** [comment]
Show me <script> sectipn please

**Comment by JeremyGerard** [comment]
```
<script>
  import wmsSource from 'vuelayers/lib/mixin/wms-source'
export default {
  name: 'Map',
  props: {
    msg: String
  },
  data () {
      return {
         ...
      }
  },
  methods: {
      mapClicked (evt) {
          console.log(this.$refs.mySource.getFeatureInfoUrl(evt.coordinate))
      },
  }
}
</script>
```

**Comment by ghettovoice** [comment]
Hmm. Very strange, this.$refs shouldn't be undefined, it's Vue feature. Probably some kind of syntax error or typo.

Currently I can't see where is the problem, I need to deploy test app with your code to reproduce it.

**Comment by JeremyGerard** [comment]
I will work on it too.
Thanks

**Comment by JeremyGerard** [comment]
The reference seems to work weel.
I made a test with the createSource () function. It s working but getFeatureInfoUrl is not in the class.
Thats why i think a can't call it

**Comment by JeremyGerard** [comment]
This error come from : wms-source.js
97:return this.$source.getFeatureInfoUrl(coordinate, resolution, projection, _extends({}, this.cleanExtParams, params));

**Comment by ghettovoice** [comment]
I found that there was a typo in method name. try to update vuelayers: `npm install vuelayers@latest`.
There is example https://jsfiddle.net/ghettovoice/m2x7dqv3/17/

**Comment by JeremyGerard** [comment]
Great !
I have an other issu : 
```
tilegrid.js?97ab:383 Uncaught TypeError: Cannot read property '0' of undefined
    at _ol_tilegrid_TileGrid_.getTileCoordForCoordAndResolution (tilegrid.js?97ab:383)
    at _ol_source_TileWMS_.getGetFeatureInfoUrl (tilewms.js?bcb4:120)
    at VueComponent.getFeatureInfoUrl (wms-source.js?1c1c:94)
    at VueComponent.mapClicked (Map.vue?108f:44)
    at invoker (vue.runtime.esm.js?2b0e:2023)
    at HTMLDivElement.fn._withTask.fn._withTask (vue.runtime.esm.js?2b0e:1822)
```
I think my callback is an array

**Comment by ghettovoice** [comment]
Show me `mapClicked` handler please

**Comment by JeremyGerard** [comment]
I fix it. I have a result : 
`http://localhost:8080/geoserver/gwc/service/wms?SERVICE=WMS&VERSION=1.2.0&REQUEST=GetFeatureInfo&FORMAT=image%2Fpng&TRANSPARENT=true&QUERY_LAYERS=FranceCadastre%3Aparcelles&TILED=true&LAYERS=FranceCadastre%3Aparcelles&X=17&Y=144&WIDTH=256&HEIGHT=256&SRS=EPSG%3A3857&BBOX=-190786.82259979844%2C6119854.232624352%2C-185894.85278954715%2C6124746.202434603```

**Comment by JeremyGerard** [comment]
Some params are missing but i have my request !
You rock

**Comment by ghettovoice** [comment]
> I fix it. 

Nice!

> Some params are missing

which params?

**Comment by JeremyGerard** [comment]
"info_format" for now the 4th params of getgetfeatureinfoUrl

**Comment by JeremyGerard** [comment]
I add it like that :
` :ext-params="{ TILED: true, 'INFO_FORMAT': 'text/html'}"`

It s perfect !

**Comment by ghettovoice** [comment]
You should provide it trough 4th method argument or with `ext-params` property

**Comment by JeremyGerard** [comment]
Thanks for your singleness
