### ISSUE TITLE
createStyle({..}) textOffsetX and textOffsetY properties not working

### ISSUE THREAD

**Issue by bwip** [ghettovoice/vuelayers#60]
I created the following style within a style function:

```.js
          style = createStyle({
            imageRadius: 20,
            imageStrokeColor: "black",
            textFillColor: "black",
            textStrokeColor: "white",
            textStrokeWidth: 3,
            text: "test",
            textFont: "10pt sans-serif",
            textOffsetX: 10,
            textOffsetY: 10
          });
```

Do I use it the right way or may this be a minor bug?

![2018-06-14 15_00_07-analysis tool](https://user-images.githubusercontent.com/31283100/41413559-c0ca6810-6fe3-11e8-8f5d-c27f0e0d110a.png)
![2018-06-14 14_59_32-analysis tool](https://user-images.githubusercontent.com/31283100/41413560-c0ef9ca2-6fe3-11e8-9f4e-c9851ae904ab.png)

**Comment by ghettovoice** [comment]
Hi @bwip, 
you are right, looks like a bug. I need to investigate this

**Comment by ghettovoice** [comment]
v0.10.11 should resolve issue.
Thank you!

**Comment by bwip** [comment]
Thank you for fixing! Can confirm that it works in your test app. 

I updated me package.json entry to v0.10.11. But, still got the older version in the lib directory. 

Than I tried to manually build the component; checked out the source inside my app's node_modules directory, ran npm install and build. All went well. 

When I start my dev server, the following error appears:

```
ERROR  Failed to compile with 1 errors

This relative module was not found:

* ./builder in ./node_modules/vuelayers/lib/_esm/cluster-source/index.js
````

Any suggestions what the problem could be?

**Comment by ghettovoice** [comment]
Seems like npm installs cached version from package-lock.json, try to run `npm install vuelayers@latest`. This should force reinstallation

**Comment by bwip** [comment]
It still seems to use the old code:

![2018-06-15 18_14_37-c__windows_system32_cmd exe](https://user-images.githubusercontent.com/31283100/41478817-5e9579aa-70c9-11e8-8673-888b0185d8bf.png)

![2018-06-15 18_22_05-analysis tool](https://user-images.githubusercontent.com/31283100/41478821-60cd9d1a-70c9-11e8-8525-290b26ab50e4.png)

![2018-06-15 18_43_00-ol-ext](https://user-images.githubusercontent.com/31283100/41479612-0bf2b890-70cc-11e8-9d2f-f6941fb0a503.png)

Also tried to clear the browser cache (Chrome "Empty cache and hard reload")

Not sure how npm works in detail. Where does the lib gets build and fetched from?

**Comment by ghettovoice** [comment]
Looks like I forget to rebuild lib code, sorry for that.
I'll make the new release

**Comment by ghettovoice** [comment]
Now it should be ok https://unpkg.com/vuelayers@0.10.12/lib/ol-ext/style.js

**Comment by bwip** [comment]
Thank you. Great component. Works like a charm!

**Comment by ghettovoice** [comment]
It's nice, thank you!
