### ISSUE TITLE
Keep map in canvas

### ISSUE THREAD

**Issue by Hugo-Contreras** [ghettovoice/vuelayers#61]
How can I keep the map in the canvas when zooming out and/or click and drag the map. I want to prevent the user to reach the white zone that we see in the illustration below.

![map_ok](https://user-images.githubusercontent.com/8998258/41484152-b32e895e-70a9-11e8-9c68-906ee2047996.png)
![map_ko](https://user-images.githubusercontent.com/8998258/41484153-b33df074-70a9-11e8-95f3-85ab108181d0.png)

**Comment by ghettovoice** [comment]
You can try to play with `extent` property on the `vl-view` component, it restricts center of the map to provided rectangle.
World extent in EPSG:3857 projection : `[-20026376.39, -20048966.10, 20026376.39, 20048966.10]`
So you can try divide Y coordinate by 2 for example, like `[-20026376.39, -10024483.05, 20026376.39, 10024483.05]`

**Comment by ghettovoice** [comment]
Close this due to inactivity
