### ISSUE TITLE
Update map size

### ISSUE THREAD

**Issue by rSammy** [ghettovoice/vuelayers#62]
Hello,

How do you update map size after resizing browser ?

I know, we could do map.updateSize from openlayer.

Thank you.

**Comment by ghettovoice** [comment]
Hello @rSammy,
I usually made an throttled resize handler in which call to `updateSize` method. To simplify this a bit iwhen use with vuelayers you can use `updateSize` on the `vl-map` component instance.

**Comment by rSammy** [comment]
Okay I saw it on the docs but I didn't know how to trigger it.
