### ISSUE TITLE
Is the demo broken ?

### ISSUE THREAD

**Issue by tsanyqudsi** [ghettovoice/vuelayers#63]
I can't see the demo or the documentation, is it just me or something is wrong.

**Comment by ghettovoice** [comment]
Hi @tsanyqudsi,
I don't see any problems with site or demo.

**Comment by tsanyqudsi** [comment]
![untitled](https://user-images.githubusercontent.com/1050880/41620719-c88a2180-7434-11e8-958c-1a27358e034d.png)

Is it because of my end or yours ?

**Comment by ghettovoice** [comment]
Looks like it can be an old cache or something else. Neither the site nor in the public demo there are no such files. 
https://github.com/VueLayers/demo/tree/master/static/js
https://github.com/VueLayers/vuelayers.github.io

Where you take this screenshot?

**Comment by tsanyqudsi** [comment]
https://vuelayers.github.io/

nevermind... it's the cache.. -_-
