### ISSUE TITLE
openlayers warning

### ISSUE THREAD

**Issue by fnoop** [ghettovoice/vuelayers#65]
```
warning vuelayers > openlayers@4.6.5: Please use the ol package instead
warning vuelayers > openlayers > nomnom@1.8.1: Package no longer supported. Contact support@npmjs.com for more info.
warning vuelayers > openlayers > closure-util > nomnom@1.8.1: Package no longer supported. Contact support@npmjs.com for more info.
warning vuelayers > openlayers > closure-util > socket.io > engine.io > uws@9.14.0: stop using this version
```

**Comment by ghettovoice** [comment]
Hi @fnoop!
While `openlayers` package isn't fully deprecated, VueLayers need to suppprts both version of the OpenLayers: ES5 that lives in `openlayers` and ES6 from `ol` version. 
Some people still may use the old openlayers or node, or old bundler that doesn' suppport ES6 modules.
Thank you!

**Comment by fnoop** [comment]
Hi!  No problem just thought I'd raise it to track, warnings trigger my OCD ;)

**Comment by ghettovoice** [comment]
My mistake, I didn't notice that the new openlayers v5 already is ready.
So I think vuelayers can be released as the new major version with support of openlayers v5

**Comment by fnoop** [comment]
Yes, works great, thanks :)
