### ISSUE TITLE
Upgrade to ol v5

### ISSUE THREAD

**Issue by ghettovoice** [ghettovoice/vuelayers#66]
Upgrade vuelayers to add support of openlayers v5
Related issue #65

**Comment by caesar** [comment]
Any news on this? OpenLayers 5.2 is the current version now.

**Comment by ghettovoice** [comment]
In progress. While I do not have enough free time to finish it

**Comment by ghettovoice** [comment]
v0.11.0-rc.1 that is based on OpenLayers 5 is ready
```
npm install vuelayers@next
```

**Comment by ghettovoice** [comment]
v0.11.0 based on ol 5 is ready
