### ISSUE TITLE
I cant use CDN Option

### ISSUE THREAD

**Issue by akinba** [ghettovoice/vuelayers#67]
Hi, 
I try to use CDN option from Documentation but i cant pass warning.

> [Vue warn]: Unknown custom element: vl-map 
> [Vue warn]: Unknown custom element: vl-layer-tile ... 

Below my html , how can i register vuelayers as component

```
<body>
  <div id="app">
  <vl-map :load-tiles-while-animating="true" :load-tiles-while-interacting="true" style="height: 400px">
      <vl-view :zoom.sync="zoom" :center.sync="center" :rotation.sync="rotation"></vl-view>

      <vl-layer-tile id="osm">
          <vl-source-osm></vl-source-osm>
      </vl-layer-tile>
  </vl-map>
  </div>
 
<!-- include Vue -->
<script src="https://unpkg.com/vue/dist/vue.js"></script>
<!-- include OpenLayers -->
<script src="https://unpkg.com/openlayers/dist/ol.js"></script>
<!-- include UMD VueLayers build -->
<link rel="stylesheet" href="https://unpkg.com/vuelayers/lib/style.css">
<script src="https://unpkg.com/vuelayers/lib/index.umd.js"></script>
  <script>

    new Vue({
       el: '#app' ,
       data: {
        zoom: 6,
        center: [40,28],
        rotation:0
       }
    });
  </script>
</body>
```

**Comment by ghettovoice** [comment]
Hi @akinba ,
you should manually register VueLayers before vm initialization: `Vue.use(VueLayers)`.

**Comment by akinba** [comment]
i missed it, thx a lot

**Comment by bobrosset** [comment]
@ghettovoice, I tried this approach since I'm deploying to Heroku and if I use it with npm, it uses a lot of memory and I cannot deploy (I can manually build offline, that works). Registering `Vue.use(VueLayers)` leads to `TypeError: Cannot read property 'prototype' of undefined"`. Any clue what I might be missing?

**Comment by bobrosset** [comment]
I added these 3:
```
    <script src="https://unpkg.com/openlayers/dist/ol.js"></script>
    <link rel="stylesheet" href="https://unpkg.com/vuelayers/lib/style.css">
    <script src="https://unpkg.com/vuelayers/lib/index.umd.js"></script>
```

I recently move this project to the standard `vue init webpack`. And I think it's loaded since there's a difference between using `Vue.use(VueLayers)` or not (Different errors).

**Comment by bobrosset** [comment]
@ghettovoice, I went down the easy way and remove uglyfy from webpack. All good now. And no need to use CDN. Happy weekend mate.

**Comment by ghettovoice** [comment]
Nice! Just a note https://unpkg.com/openlayers/dist/ol.js this line now loads openlayers v5 that doesn't currently supported. You should load it like this https://unpkg.com/openlayers@v4.6.5/dist/ol.js"
