### ISSUE TITLE
how to render icons with the 'vl-style-func' component

### ISSUE THREAD

**Issue by zhouLion** [ghettovoice/vuelayers#69]
Could you provide a little doc about these style components
thanks

**Comment by ghettovoice** [comment]
Hi @zhouLion,
sure, I know currently the documentation is pure. I'll back to it when l'll have a bit more free time.
vl-style-func accepts `factory` for the OpenLayers style function, so here you can just use OpenLayers API to build array of styles. 
To add icons you should use ol.style.Icon class https://openlayers.org/en/v4.6.5/apidoc/ol.style.Icon.html.
Take a look here http://openlayers.org/en/v4.6.5/examples/icon.html?q=Icon. With the style function you just need to return array of styles.
Example of vl-style-func and style function factory you can see in this issue #68

**Comment by zhouLion** [comment]
ok!
Thank you for your help. I got it.

**Comment by ghettovoice** [comment]
Close this due to inactivity
