### ISSUE TITLE
Click event on map, layer and feature

### ISSUE THREAD

**Issue by ghettovoice** [ghettovoice/vuelayers#7]
- [x] Emit click event in map component.
- [ ] Emit click on layer component.
- [ ] Emit click on feautre component
- [x] Add `forEachFeatureAtPixel`, `forEachFeatureAtCoordinate`, `forEachLayerAtPixel` helper methods to map component, should return feautre in GeoJSOn format.

**Comment by ajotka** [comment]
Hi! 
Is it possible to add click listener on feature component? 
I saw the way with pointmove method, but I think, the better idea is to connect somehow feature component with basic vue click event.

What do you think?

**Comment by ghettovoice** [comment]
Hi @ajotka ,
I didn't implement because this can drastically kill performance with big vector layers. So the more efficient way is to listen `click` event on the map and then find feature by event pixel or coordinate.
