### ISSUE TITLE
IE11  SCRIPT1002: Syntax Error

### ISSUE THREAD

**Issue by ChristianBielak** [ghettovoice/vuelayers#71]
I try to use VueLayers with IE11. Despite using babbel-polyfill I get the error SCRIPT1002: Syntax Error

my babelrc file look like

`{
  "presets": [
    ["env", {
      "modules": false
    }],
    "stage-2"
  ],
  "plugins": ["transform-runtime"],
  "env": {
    "production": {
      "presets": ["minify"]
    },
    "test": {
      "presets": ["env", "stage-2"],
      "plugins": ["transform-es2015-modules-commonjs", "dynamic-import-node"]
    }
  }
}`

Thanks for help :)

**Comment by ghettovoice** [comment]
Hi @ChristianBielak ,
what version of vuelayers are you using? And provide please error stack trace and webpack config.

**Comment by ChristianBielak** [comment]
Hi thanks for the quick answer.

I'm using Version 0.10.12. At the moment i don't have access to the Webpack, but it Looks quite normal. I also added entry: ['babel-polyfill', './resources/assets/js/app.js'], to the Webpack file

**Comment by ghettovoice** [comment]
I need somehow to reproduce the issue, so webpack config would help. Also I ask you about it because there was issue with webpack config generated by ruby on rails webpacker module (#31 ).
What about error stack trace? Or at least the line on which the error occures

**Comment by ChristianBielak** [comment]
I'm sorry i dont have access to the code right now. 

Here is a screenshot where the error occures.

![screen shot 2018-07-30 at 10 27 35](https://user-images.githubusercontent.com/17922533/43386259-67574158-93e3-11e8-859a-aadd11c68eaa.png)

**Comment by ghettovoice** [comment]
Ok, I see that in final build there is `=>` operator, that doesn't supported by IE. And as I think this code imported from rxjs package, that is used by VueLayers. Maybe you should provide babel with target browsers (https://babeljs.io/docs/en/next/babel-preset-env.html#targetsbrowsers ) with something like this: `> 1%, last 2 versions`

**Comment by ChristianBielak** [comment]
Thanks for your help :) i'll try i later.

**Comment by ChristianBielak** [comment]
Still an Error :/ just moved to an other line 
<img width="1488" alt="screen shot 2018-07-30 at 21 37 41" src="https://user-images.githubusercontent.com/17922533/43419381-02c89c74-9441-11e8-8fa9-7fa0b4392421.png">

**Comment by ChristianBielak** [comment]
Thats the Webpack config file

`var path = require('path');
var webpack = require('webpack');
var polyfill = require("./node_modules/babel-polyfill");
const {VueLoaderPlugin} = require('./node_modules/vue-loader/lib');

module.exports = {
    entry: ['babel-polyfill', './wp-content/themes/twentyseventeen/assets/js/vessel.js'],
    mode: "production",
    output: {
        path: path.resolve(__dirname, "./wp-content/plugins/vessel_tracker/assets/js"),
        filename: "vessel_out.js"
    },
    module: {
        rules: [
            {
                test: /\.js$/,
                exclude: /(node_modules)/,
                use: {
                    loader: 'babel-loader',
                    options: {
                        presets: [
                            ['env', {
                                "targets": {
                                    "browserslist": ["> 1%", "last 2 versions"]
                                }
                            }]
                        ]
                    }
                }
            },
            {
                test: /\.vue$/,
                loader: 'vue-loader',
            },
            {
                test: /\.css$/,
                oneOf: [
                    // this applies to <style module>
                    {
                        resourceQuery: /module/,
                        use: [
                            'vue-style-loader',
                            {
                                loader: 'css-loader',
                                options: {
                                    modules: true,
                                    localIdentName: '[local]_[hash:base64:8]'
                                }
                            }
                        ]
                    },
                    // this applies to <style> or <style scoped>
                    {
                        use: [
                            'vue-style-loader',
                            'css-loader'
                        ]
                    }
                ]
            },
            // exmaple configration for <style lang="scss">
            {
                test: /\.scss$/,
                use: [
                    'vue-style-loader',
                    'css-loader',
                    {
                        loader: 'sass-loader',
                        // global data for all components
                        // this can be read from a scss file
                        options: {
                            data: '$color: red;'
                        }
                    }
                ]
            }
        ],
    },
    resolve: {
        alias: {
            'vue': 'vue/dist/vue.js',
            'vue-loader': 'vue-loader/lib'
        }
    },
    plugins: [
        new VueLoaderPlugin()
    ]
};`

**Comment by ghettovoice** [comment]
Config look ok except one note: in the env option there should be `targets: { browsers: ... }` instead of `browserslist`. Key `browserslist` can be used in the package.json file to provide singe browsers config for different frontend tools

**Comment by ChristianBielak** [comment]
I tried it with both :D my last try was with browserlist thats why browserlist is still there

**Comment by ghettovoice** [comment]
Ok, seems like I found where the problem lies.
Try with [v0.10.13](https://github.com/ghettovoice/vuelayers/releases/tag/v0.10.13)

**Comment by ChristianBielak** [comment]
Perfect this fixed the issue :) thank you very much :)
