### ISSUE TITLE
What is the proper way to track whether a layer or any other component is initialized?

### ISSUE THREAD

**Issue by become-iron** [ghettovoice/vuelayers#73]
I want to do certain actions exactly after inner object `$layer` of layer component (`vl-layer-vector`, for example) was created. But I can't understand in which moment I should do it. `$nextTick` doesn't always help. Also I could not find documentation for proper events.
The same story with `vl-feature`. I can't get its geometry.
Maybe it's not really problem of vuelayers, but I would be grateful for any help.

**Comment by ghettovoice** [comment]
Hi @become-iron ,
each vl-* component has two fields (https://github.com/ghettovoice/vuelayers/blob/master/src/mixin/ol-cmp.js#L192): 
- `$createPromise`  - will be resolved when internal OpenLayers is read
- `$mountPromise`  - will be resolved when internal OpenLayers instance appended to it's parent instance  
Example:
```html
<template>
  <vl-map ref="map">
    <vl-layer-vector ref="layer">...</vl-layer-vector>
  </vl-map>
</template>

export default {
  mounted () {
    this.$refs.layer.$mountPromise.then(() => {
       this.$refs.layer.$layer - ol.layer.Vector instance   
    })
  },
}
```

Also there are 2 events (currently doesn't described in docs) as a more convenient way to know when promises above are resolved:
- `created`
- `mounted`

```html
<template>
  <vl-map ref="map">
    <vl-layer-vector ref="layer" @mounted="onLayerMounted">...</vl-layer-vector>
  </vl-map>
</template>

export default {
  methods: {
    onLayerMounted (layerCmp) {
        layerCmp.$layer - ol.layer.Vector instance   
    },
  },
}
```

**Comment by become-iron** [comment]
Thank you for a quick and helpful answer

But that won't help always. For example, there is a `vl-feature` component that has some geometry.

```vue
<vl-feature ref="myFeature">
  <component :is="myFeature.component" 
             v-bind="myFeature.geometry"></component>
</vl-feature>
```
Initially I can listen `mounted` to wait the moment when a component is ready. But if I change type of geometry component or only geometry of that component then ```this.$myFeature.getGeometry()``` will return the old geometry data. I want do it this way to get processed geometry object and not to do it manually

And if are there `created` and `mounted` hooks then maybe there should be others as well?

**Comment by ghettovoice** [comment]
In your example you should bind `created`/`mounted` hooks to the `vl-geom-*` component because it has own life cycle. Unfortunately VueLayers doesn't has some special hooks for child component mounting. 

> And if are there created and mounted hooks then maybe there should be others as well?

Agree, in `vl-feature` (https://github.com/ghettovoice/vuelayers/blob/master/src/component/feature/feature.vue#L292) component should be `update:geometry` event like in OpenLayers.

As a workaround you can get fresh geometry `mounted` and `update:coordinates` on the `vl-geom-*` component,. I made a tiny example https://jsfiddle.net/ghettovoice/jomfdp3q/17/

**Comment by become-iron** [comment]
It helped. Thank you a lot
