### ISSUE TITLE
Add Proj4 support

### ISSUE THREAD

**Issue by stomppah** [ghettovoice/vuelayers#77]

**Comment by ghettovoice** [comment]
Hi @stomppah ,
what kind of support do you mean?

In fact VueLayers supports using projections from proj4 like it does OpenLayers .
Take a look at this simple example https://jsfiddle.net/ghettovoice/b3t5s4ku/44/

**Comment by stomppah** [comment]
Hi @ghettovoice ,

apologies, this can be closed now, I'm still very new to GIS
