### ISSUE TITLE
Update/remove Vue 2.3.0 peer dependency?

### ISSUE THREAD

**Issue by arjanski** [ghettovoice/vuelayers#79]
Hello there,

First of all thank you for your work and bringing OpenLayers to Vue.

I am trying to use v. 0.10.13 in a Vue 2.9.6 project. I don't know if it's due to my UI framework, but my code breaks due to the Vue 2.3.0 peer dependency.

Is there a way to update this to a current version, or even remove it?

Cheers

**Comment by ghettovoice** [comment]
Hello @arjanski ,
What is the actual error you got? 
Also I don't find information about Vue 2.9.6. The actual Vue version  is 2.5.17 that should be ok.
