### ISSUE TITLE
How to re center v map ?

### ISSUE THREAD

**Issue by rSammy** [ghettovoice/vuelayers#81]
With the positioning problem,

I need to recenter the map when I'm done. After that, I screenshot the area with html2canvas.

But first I need to know how to re center map please 👍

**Comment by ghettovoice** [comment]
You can bind data property to vl-view `center` property with `.sync` modifier (https://github.com/ghettovoice/vuelayers-demo/blob/master/src/App.vue#L8), then just change data property value like `center = [0, 0]`.

**Comment by rSammy** [comment]
Thank you it works.
