### ISSUE TITLE
How to style OpenMapTiles

### ISSUE THREAD

**Issue by koehn** [ghettovoice/vuelayers#82]
I'm able to create an unstyled vector map with OpenMapTiles, but I cannot figure out how to apply a [style](https://openmaptiles.org/styles/) ("OSM Bright") to it. Can you help me out?

**Comment by ghettovoice** [comment]
Hi @koehn ,
as I know there is no such tools in OpenLayers (and obviously in VueLayers) to easily integrate MapBox style format.

As from official OpenLayers example (http://openlayers.org/en/v4.6.5/examples/mapbox-vector-tiles-advanced.html) you can load OSM Bright JSON (https://github.com/openmaptiles/osm-bright-gl-style/blob/master/style.json), parse it and build styles in the custom style function.  
Then you can bind your style function to the layer through `vl-style-func` component. 
See examples here https://github.com/ghettovoice/vuelayers/issues/68#issuecomment-403598573 and 
https://github.com/ghettovoice/vuelayers-demo/blob/master/src/App.vue#L264.

**Comment by koehn** [comment]
OK thanks. It looks like [this is a tool](https://openmaptiles.org/docs/website/openlayers/) that can do the conversion; I just needed to know where it goes, and it sounds like the `vl-style-func` is the place. Thanks!

**Comment by ghettovoice** [comment]
Yes, vl-style-func what you need for complex styling.
