### ISSUE TITLE
How to apply an image to top corner of the v map ?

### ISSUE THREAD

**Issue by rSammy** [ghettovoice/vuelayers#85]
Hello !

I'd like to put some static image/div/html element here
![image](https://user-images.githubusercontent.com/30237980/46614083-f06e9a00-cae2-11e8-8131-0c710d340f55.png)

Is that possible ? I want it to always be visible on the map

**Comment by bobrosset** [comment]
Simple as adding a div with `position: absolute` `top: 0.5em` `right: 0.5em`.

**Comment by rSammy** [comment]
Lmao I didn't think about it, indeed, there is no need to use vuelayers to show some div. 

Haha 🤣

**Comment by ghettovoice** [comment]
Hello!
Just put your div with `position: absolute` inside the `vl-map` tag.
