### ISSUE TITLE
Icon marker doesn't  appear

### ISSUE THREAD

**Issue by kodami** [ghettovoice/vuelayers#86]
Problem appears on development build.
I was trying to reproduce example with geolocation locally, but marker icon doesn't appear.

I found problem with generating icon path.
These paths doesn't work:
`./assets/marker.png` [like in official VueLayers _demo_]
`_media/marker.png` [like in VueLayers _documentation_]

Icon only appears if I add img tag with path `./assets/marker.png` somewhere outside vl-map,
copy its generated path and paste to vl-style-icon as absolute path `http://localhost:8080/img/flag.b9225040.png`

Official VueLayers demo on website and example in documentation works without problem.
Please help.

Vuelayers v0.10.13
Vue v3.0.4
Yarn v1.9.4
Node v10.10.0

**Comment by ghettovoice** [comment]
Hi @kodami !
Can you show me your vue-loader config? If you are using the latest version the config should have:
```js
// webpack config
....
module:
  rules: [
    {
        test: /\.vue$/,
        loader: 'vue-loader',
        options: {
          transformAssetUrls: {
            video: ['src', 'poster'],
            source: 'src',
            img: 'src',
            image: 'xlink:href',
            'vl-style-icon': 'src', // this allow vue-loader to transform path in the `src` attribute to `require`
          },
        },
    },
  ],
...
```
In the previous versions of the vue-loader there was `transformToRequire` option

**Comment by kodami** [comment]
Hi @ghettovoice, thanks for replay!
I was using Vue-CLI to create project. No errors in console, map works so I thought it doesn't need additional configuration. I'm using the latest vue-loader version.

**Comment by kodami** [comment]
Thank you so much!
I've create `vue.config.js` than added your options using code from Vue-CLI documentation:
[Modifying options of a loader](https://cli.vuejs.org/guide/webpack.html#modifying-options-of-a-loader)

**Comment by ghettovoice** [comment]
That's good! :+1:

**Comment by haloboy777** [comment]
> Thank you so much!
> I've create `vue.config.js` than added your options using code from Vue-CLI documentation:
> [Modifying options of a loader](https://cli.vuejs.org/guide/webpack.html#modifying-options-of-a-loader)

Hey Can you provide your vue.config.js file in its eternity? I'm not able to make a configuration file.

**Comment by avpavp** [comment]
Hi,

I seem to be experiencing the exact same issue.  I'm using a style function, creating an Icon, and it works with the src set to and http://... address, but shows nothing when I use a relative url, './assets/imge.png', for example.  So it sounds exactly like the problem described above, but I can't get it to work when I modify my vue.config.js as above.

The vue.config.js is in the root, same level as package.json.

I don't see any relevant errors in the console?

Any other ideas or suggestions as to how to debug this or track down the issue?

using vue 2.6.10

Thanks!
