### ISSUE TITLE
olExt is undefined

### ISSUE THREAD

**Issue by NeoMarine** [ghettovoice/vuelayers#90]
Running into some issues attempting to get an image-based map working.

I've used your code example [here](https://vuelayers.github.io/#/component/image-layer). I've made a couple of adjustments as it seemed invalid:
- changed "</vl-layer-tile>" to "</vl-layer-image>"
- changed "<vl-layer-image id="xkcd">" to "<vl-layer-image id="xkcd-image">"
- added lines "import VueLayers from 'vuelayers';" and "Vue.use(VueLayers);" at top of <script> as error VueLayers is not defined error occurs in the template.

However, an error is thrown everytime at this stage:
let customProj = VueLayers.olExt.createProj({
... olExt is undefined.

I am unsure how to get this working.

**Comment by ghettovoice** [comment]
Hi @NeoMarine,
example you mentioned uses UMD build for quick browser usage, it includes all modules and obviously not the best for production. 

As I understand your are using ES6 version of VueLayers, so `olExt` helpers should be imported explicitly:

```js
import { createProj, addProj } from 'vuelayers/lib/_esm/ol-ext'
```

Mostly functions from the `ol-ext` sub-package are just wrappers around original OpenLayers functions,
so you could make same things with OpenLayers API:

```js
// openlayers v5
import { addProjection, createProjection } from 'ol/proj'

let myProj = createProjection({
    code: 'xkcd-image',
    units: 'pixels',
    extent,
})
addProjection(myProj)

// openlayers v4
import proj from 'ol/proj'

let myProj = proj.createProjection(({
    code: 'xkcd-image',
    units: 'pixels',
    extent,
})
proj.addProjection(myProj)
```

The documentation isn't so clear here, I need to update it.

**Comment by NeoMarine** [comment]
Thank you!

**Comment by hecent** [comment]
I tried using the OpenLayers API solution, but I seem to be having an issue with the getCode() function:
```vue
<script>
import { addProjection, createProjection } from 'ol/proj'

  let size = [1024, 968]
  let extent = [0, 0, ...size]

  let customProj = createProjection({
    code: 'xkcd-image',
    units: 'pixels',
    extent,
  })
  
  addProjection(customProj)

  export default {
    data () {
      return { 
        zoom: 2,
        maxZoom: 8,
        center: [size[0] / 2, size[1] / 2],
        rotation: 0,
        projection: customProj.getCode(),
        imgUrl: 'https://imgs.xkcd.com/comics/online_communities.png',
        imgCopyright: '© <a href="http://xkcd.com/license.html">xkcd</a>',
        imgSize: size,
        imgExtent: extent,
      }
    },
  }
</script>
```

```
Uncaught TypeError: projection.getCode is not a function
    at addProjection (proj.js:153:22)
```

**Comment by ghettovoice** [comment]
Hello @hecent ,
seems that `createProjection` shouldn't be use with latest OpenLayers v6.x, because it actually creates nothing.
There is a valid example:

```js
import { addProjection, Projection } from 'ol/proj'

const size = [1024, 968]
const extent = [0, 0, ...size]
const customProj = new Projection({
  code: 'xkcd-image',
  units: 'pixels',
  extent,
})
addProjection(customProj)
```
