### ISSUE TITLE
IE Problem Injection $services not found

### ISSUE THREAD

**Issue by ChristianBielak** [ghettovoice/vuelayers#91]
Hi, 

on IE i get the warn Injection $services not found in VlStyleFill, VlStyleStroke, VlStyleCircle and VlStyleBox.

I tried diffrent versions of your package. I also use babel-polyfill and the correct presets.

Thanks for help :)

**Comment by ghettovoice** [comment]
Hi @ChristianBielak ,
can you provide the template of your component?   
This warning shouldn't be fatal for your app.  
There was several same issues and I thought that it was fixed.

**Comment by ghettovoice** [comment]
downloading vm with ie 11 :zzz:

**Comment by ChristianBielak** [comment]
http://mwsp-dev.ultrabold.de/lokale-stadterneuerung

Here you can check out the map :)

**Comment by ghettovoice** [comment]
> Here you can check out the map :)

Greate! Thank you. I'll check it tonight, I already have several assumptions about the reason of the warning

**Comment by ChristianBielak** [comment]
No, thank you :)

**Comment by ChristianBielak** [comment]
Should i try to reinstall the package?

**Comment by ghettovoice** [comment]
Not yet published. Maybe tonight I'll have free time to complete package release, last resort tomorrow morning

**Comment by ChristianBielak** [comment]
Nice :) thanks for your great support

**Comment by ghettovoice** [comment]
it's ready: `npm i vuelayers@latest`

**Comment by ChristianBielak** [comment]
nice :) it works
