### ISSUE TITLE
Is the component of ImageWMS source missing?

### ISSUE THREAD

**Issue by become-iron** [ghettovoice/vuelayers#92]
I needed this component, but I wasn't able to find it

**Comment by ghettovoice** [comment]
Hi @become-iron ,
you are right, vuelayers currently doesn't support ImageWMS. It is on my todo list and definitely should be included to the next release

**Comment by ghettovoice** [comment]
Meanwhile you can try to implement it yourself, take a look at the very similar components : [vl-source-image-static](https://github.com/ghettovoice/vuelayers/blob/master/src/component/image-static-source/source.vue) and [vl-source-wms](https://github.com/ghettovoice/vuelayers/blob/master/src/component/wms-source/source.vue).  
To help you there is [imageSource mixin](https://github.com/ghettovoice/vuelayers/blob/master/src/mixin/image-source.js) that is used in vl-source-image-static and actually is an prototype for single image sources

**Comment by ghettovoice** [comment]
`vl-source-image-wms` is introduced in v0.10.18

**Comment by become-iron** [comment]
Thank you very much
