### ISSUE TITLE
Cannot use the "fit" method of sub component "vl-view"

### ISSUE THREAD

**Issue by haies** [ghettovoice/vuelayers#93]
I need to set the current map to a certain extent, and set constrain resolution false.
So, When I run **this.$refs.mapView.fit(extent, options)**,and I got the following warn:
[Vue warn]: Error in callback for watcher "extent": "Error: component has "$view" property"
Chrome@69, Vuelayers@0.10.18
``` html
<template>
  <div id="mapContainer">
    <vl-map v-bind="mapOptions">
      <vl-view ref='mapView' v-bind="mapViewOptions" :zoom.sync="zoom" :center.sync="center" :rotation.sync="rotation"/>
      <ol-wmts-layer-cn v-bind="cnOpt"/>
      <ol-wmts-layer-cn v-bind="cnAnOpt"/>
    </vl-map>
  </div>
</template>
const watch = {
  extent: function(extent) {
    if (extent.length !== 4) return
    const options ={
      constrainResolution: false,
      padding: [5, 0, 5, 0],
      duration: undefined,
      easing: Easing.inAndOut
    }
    this.$refs.mapView.fit(extent, options)
  }
}
```

**Comment by ghettovoice** [comment]
Hi @haies !
This error means that underlying openlayers instance is not ready yet. Each vuelayers component has one or more underlying openlayers component that is created asynchronously To know when it is occurred there are two instance promises: `$createPromise` and `$mountPromise`.
To avoid this you should call `fit` method after `$createPromise` or `$mountPromise` is resolved

```js
this.$refs.mapView.$createPromise.then(() => this.$refs.mapView.fit(extent, options))
```

**Comment by haies** [comment]
Hi @ghettovoice !
Thanks a lot, it works !!!
