### ISSUE TITLE
Drop out not needed enums

### ISSUE THREAD

**Issue by ghettovoice** [ghettovoice/vuelayers#94]
OpenLayers 5 now uses ES modules and there is no need to copy/past its standard enum types.
So vuelayers's copies can be replaced with usage of the openlayers modules

**Comment by categulario** [comment]
with some guidance I could be able to do this. Do you have a file I can look at to get started?

**Comment by ghettovoice** [comment]
Hello @categulario !
It is tough question because dropping of this enums means breaking UMD version. OpenLayers UMD and ES builds are slightly different in what you can use, so to support vuelayers UMD build I was forced to copy/paste some types, functions and etc. from OpenLayers.

From the other hand, vuelayers UMD build already now intended only for development/testing purpose. So I can just include all the openlayers stuff into the vuelayers UMD bundle. With ES modules there isn't any problems with that cause you just import what you need from OpenLayers.

This replacements of the OpenLayers types are composed into `ol-ext` package and used everywhere in other components, exactly enums in the `ol-ext/consts.js` (https://github.com/ghettovoice/vuelayers/blob/master/src/ol-ext/consts.js#L44). This enums is a start point from which I plan remove all of this replacements and leave only really useful helpers in the `ol-ext` package.

**Comment by ghettovoice** [comment]
resolved in upcoming v0.12
