### ISSUE TITLE
Stamen source?

### ISSUE THREAD

**Issue by echocompany** [ghettovoice/vuelayers#99]
How to use Stamen source?

**Comment by ghettovoice** [comment]
Hi @echocompany ,
you can use `vl-source-xyz` component [Usage Example](https://jsfiddle.net/ghettovoice/9d4163sk/5/).

`vl-source-xyz` is a generic component for simple tiled layers. Also oyu can use [`xyzSource` mixin from VueLayers](https://unpkg.com/vuelayers@0.10.18/lib/_esm/mixin/xyz-source.js) to make your own source implementation.
